SET TERM ^ ;

CREATE OR ALTER
    PROCEDURE
        ABITUR_QUEUE_UPD_NO_SIGN
        (
            id_ab        INTEGER,
            status_queue SMALLINT,
            photo        BLOB SUB_TYPE 0 SEGMENT SIZE 80
        )
AS
BEGIN
    UPDATE
        ABITUR_QUEUE
    SET
        STATUS_QUEUE = :status_queue,
        PHOTO        = :photo
    WHERE
        ID_AB = :id_ab;
END^

SET TERM ; ^

/* Following GRANT statements are generated automatically */

GRANT
    SELECT,
    UPDATE
ON
    ABITUR_QUEUE
TO
    PROCEDURE
        ABITUR_QUEUE_UPD_NO_SIGN;

/* Existing privileges on this procedure */

GRANT EXECUTE ON PROCEDURE ABITUR_QUEUE_UPD_NO_SIGN TO ABITUR1;
GRANT EXECUTE ON PROCEDURE ABITUR_QUEUE_UPD_NO_SIGN TO ABITUR2;
GRANT EXECUTE ON PROCEDURE ABITUR_QUEUE_UPD_NO_SIGN TO ABITUR3;
GRANT EXECUTE ON PROCEDURE ABITUR_QUEUE_UPD_NO_SIGN TO ABITUR4;
GRANT EXECUTE ON PROCEDURE ABITUR_QUEUE_UPD_NO_SIGN TO ABITURA;
GRANT EXECUTE ON PROCEDURE ABITUR_QUEUE_UPD_NO_SIGN TO ALENA_2109;
GRANT EXECUTE ON PROCEDURE ABITUR_QUEUE_UPD_NO_SIGN TO ALEXANDER_GONCHAROV;
GRANT EXECUTE ON PROCEDURE ABITUR_QUEUE_UPD_NO_SIGN TO ALINA_E;
GRANT EXECUTE ON PROCEDURE ABITUR_QUEUE_UPD_NO_SIGN TO ANNA;
GRANT EXECUTE ON PROCEDURE ABITUR_QUEUE_UPD_NO_SIGN TO ASPIRANTURA;
GRANT EXECUTE ON PROCEDURE ABITUR_QUEUE_UPD_NO_SIGN TO ASU;
GRANT EXECUTE ON PROCEDURE ABITUR_QUEUE_UPD_NO_SIGN TO ASU1;
GRANT EXECUTE ON PROCEDURE ABITUR_QUEUE_UPD_NO_SIGN TO ASU2;
GRANT EXECUTE ON PROCEDURE ABITUR_QUEUE_UPD_NO_SIGN TO ASU3;
GRANT EXECUTE ON PROCEDURE ABITUR_QUEUE_UPD_NO_SIGN TO ASU4;
GRANT EXECUTE ON PROCEDURE ABITUR_QUEUE_UPD_NO_SIGN TO BAKS68878;
GRANT EXECUTE ON PROCEDURE ABITUR_QUEUE_UPD_NO_SIGN TO DEV;
GRANT EXECUTE ON PROCEDURE ABITUR_QUEUE_UPD_NO_SIGN TO DEVELOPER;
GRANT EXECUTE ON PROCEDURE ABITUR_QUEUE_UPD_NO_SIGN TO DEVELOPER2;
GRANT EXECUTE ON PROCEDURE ABITUR_QUEUE_UPD_NO_SIGN TO DOBROVOLSKAYA;
GRANT EXECUTE ON PROCEDURE ABITUR_QUEUE_UPD_NO_SIGN TO DVORETSKAYA_K;
GRANT EXECUTE ON PROCEDURE ABITUR_QUEUE_UPD_NO_SIGN TO GONCHAROV434_2;
GRANT EXECUTE ON PROCEDURE ABITUR_QUEUE_UPD_NO_SIGN TO GUNICH_OKSANA;
GRANT EXECUTE ON PROCEDURE ABITUR_QUEUE_UPD_NO_SIGN TO HOSTEL_PK1;
GRANT EXECUTE ON PROCEDURE ABITUR_QUEUE_UPD_NO_SIGN TO HOSTEL_PK2;
GRANT EXECUTE ON PROCEDURE ABITUR_QUEUE_UPD_NO_SIGN TO IMSIT_Z;
GRANT EXECUTE ON PROCEDURE ABITUR_QUEUE_UPD_NO_SIGN TO IT1;
GRANT EXECUTE ON PROCEDURE ABITUR_QUEUE_UPD_NO_SIGN TO IT2;
GRANT EXECUTE ON PROCEDURE ABITUR_QUEUE_UPD_NO_SIGN TO IT3;
GRANT EXECUTE ON PROCEDURE ABITUR_QUEUE_UPD_NO_SIGN TO IT5;
GRANT EXECUTE ON PROCEDURE ABITUR_QUEUE_UPD_NO_SIGN TO IT7;
GRANT EXECUTE ON PROCEDURE ABITUR_QUEUE_UPD_NO_SIGN TO IT_8;
GRANT EXECUTE ON PROCEDURE ABITUR_QUEUE_UPD_NO_SIGN TO IT_Z;
GRANT EXECUTE ON PROCEDURE ABITUR_QUEUE_UPD_NO_SIGN TO IVANOVA_A;
GRANT EXECUTE ON PROCEDURE ABITUR_QUEUE_UPD_NO_SIGN TO JKMUF2507;
GRANT EXECUTE ON PROCEDURE ABITUR_QUEUE_UPD_NO_SIGN TO KANDRUKEVICH_M;
GRANT EXECUTE ON PROCEDURE ABITUR_QUEUE_UPD_NO_SIGN TO KAND_M;
GRANT EXECUTE ON PROCEDURE ABITUR_QUEUE_UPD_NO_SIGN TO KRISTINA;
GRANT EXECUTE ON PROCEDURE ABITUR_QUEUE_UPD_NO_SIGN TO LAVRENOVA_V;
GRANT EXECUTE ON PROCEDURE ABITUR_QUEUE_UPD_NO_SIGN TO LENAUSOVA;
GRANT EXECUTE ON PROCEDURE ABITUR_QUEUE_UPD_NO_SIGN TO LTRFYFN2019;
GRANT EXECUTE ON PROCEDURE ABITUR_QUEUE_UPD_NO_SIGN TO MAGISTR;
GRANT EXECUTE ON PROCEDURE ABITUR_QUEUE_UPD_NO_SIGN TO MARINA;
GRANT EXECUTE ON PROCEDURE ABITUR_QUEUE_UPD_NO_SIGN TO MATUSEVICH;
GRANT EXECUTE ON PROCEDURE ABITUR_QUEUE_UPD_NO_SIGN TO MVS1;
GRANT EXECUTE ON PROCEDURE ABITUR_QUEUE_UPD_NO_SIGN TO MVS2;
GRANT EXECUTE ON PROCEDURE ABITUR_QUEUE_UPD_NO_SIGN TO MVS3;
GRANT EXECUTE ON PROCEDURE ABITUR_QUEUE_UPD_NO_SIGN TO MVS4;
GRANT EXECUTE ON PROCEDURE ABITUR_QUEUE_UPD_NO_SIGN TO MVS_D;
GRANT EXECUTE ON PROCEDURE ABITUR_QUEUE_UPD_NO_SIGN TO MVS_Z;
GRANT EXECUTE ON PROCEDURE ABITUR_QUEUE_UPD_NO_SIGN TO MVS_Z_L;
GRANT EXECUTE ON PROCEDURE ABITUR_QUEUE_UPD_NO_SIGN TO M_2;
GRANT EXECUTE ON PROCEDURE ABITUR_QUEUE_UPD_NO_SIGN TO OFKIT1;
GRANT EXECUTE ON PROCEDURE ABITUR_QUEUE_UPD_NO_SIGN TO OFKIT2;
GRANT EXECUTE ON PROCEDURE ABITUR_QUEUE_UPD_NO_SIGN TO OFKIT3;
GRANT EXECUTE ON PROCEDURE ABITUR_QUEUE_UPD_NO_SIGN TO OFKIT4;
GRANT EXECUTE ON PROCEDURE ABITUR_QUEUE_UPD_NO_SIGN TO OFKIT_A;
GRANT EXECUTE ON PROCEDURE ABITUR_QUEUE_UPD_NO_SIGN TO OFKIT_D;
GRANT EXECUTE ON PROCEDURE ABITUR_QUEUE_UPD_NO_SIGN TO OFKIT_M;
GRANT EXECUTE ON PROCEDURE ABITUR_QUEUE_UPD_NO_SIGN TO OFKIT_N;
GRANT EXECUTE ON PROCEDURE ABITUR_QUEUE_UPD_NO_SIGN TO OKSANA;
GRANT EXECUTE ON PROCEDURE ABITUR_QUEUE_UPD_NO_SIGN TO OK_STUD_1;
GRANT EXECUTE ON PROCEDURE ABITUR_QUEUE_UPD_NO_SIGN TO PK;
GRANT EXECUTE ON PROCEDURE ABITUR_QUEUE_UPD_NO_SIGN TO PK_IT;
GRANT EXECUTE ON PROCEDURE ABITUR_QUEUE_UPD_NO_SIGN TO PK_IT1;
GRANT EXECUTE ON PROCEDURE ABITUR_QUEUE_UPD_NO_SIGN TO PK_IT2;
GRANT EXECUTE ON PROCEDURE ABITUR_QUEUE_UPD_NO_SIGN TO PK_IT3;
GRANT EXECUTE ON PROCEDURE ABITUR_QUEUE_UPD_NO_SIGN TO PK_IT4;
GRANT EXECUTE ON PROCEDURE ABITUR_QUEUE_UPD_NO_SIGN TO PK_IT5;
GRANT EXECUTE ON PROCEDURE ABITUR_QUEUE_UPD_NO_SIGN TO PK_MSTIG1;
GRANT EXECUTE ON PROCEDURE ABITUR_QUEUE_UPD_NO_SIGN TO PK_MSTIG2;
GRANT EXECUTE ON PROCEDURE ABITUR_QUEUE_UPD_NO_SIGN TO PK_MSTIG3;
GRANT EXECUTE ON PROCEDURE ABITUR_QUEUE_UPD_NO_SIGN TO PK_MSTIG4;
GRANT EXECUTE ON PROCEDURE ABITUR_QUEUE_UPD_NO_SIGN TO PK_MSTIGP1;
GRANT EXECUTE ON PROCEDURE ABITUR_QUEUE_UPD_NO_SIGN TO PK_MSTIGP2;
GRANT EXECUTE ON PROCEDURE ABITUR_QUEUE_UPD_NO_SIGN TO PK_MSTIG_1;
GRANT EXECUTE ON PROCEDURE ABITUR_QUEUE_UPD_NO_SIGN TO PK_MSTIG_2;
GRANT EXECUTE ON PROCEDURE ABITUR_QUEUE_UPD_NO_SIGN TO PK_MSTIG_3;
GRANT EXECUTE ON PROCEDURE ABITUR_QUEUE_UPD_NO_SIGN TO PK_MSTIG_4;
GRANT EXECUTE ON PROCEDURE ABITUR_QUEUE_UPD_NO_SIGN TO PK_MSTIG_P1;
GRANT EXECUTE ON PROCEDURE ABITUR_QUEUE_UPD_NO_SIGN TO PK_MSTIG_P2;
GRANT EXECUTE ON PROCEDURE ABITUR_QUEUE_UPD_NO_SIGN TO PK_MVS;
GRANT EXECUTE ON PROCEDURE ABITUR_QUEUE_UPD_NO_SIGN TO PK_MVS1;
GRANT EXECUTE ON PROCEDURE ABITUR_QUEUE_UPD_NO_SIGN TO PK_MVS2;
GRANT EXECUTE ON PROCEDURE ABITUR_QUEUE_UPD_NO_SIGN TO PK_MVS3;
GRANT EXECUTE ON PROCEDURE ABITUR_QUEUE_UPD_NO_SIGN TO PK_MVS4;
GRANT EXECUTE ON PROCEDURE ABITUR_QUEUE_UPD_NO_SIGN TO PK_MVS5;
GRANT EXECUTE ON PROCEDURE ABITUR_QUEUE_UPD_NO_SIGN TO PK_MVSP1;
GRANT EXECUTE ON PROCEDURE ABITUR_QUEUE_UPD_NO_SIGN TO PK_MVSP2;
GRANT EXECUTE ON PROCEDURE ABITUR_QUEUE_UPD_NO_SIGN TO PK_MVS_1;
GRANT EXECUTE ON PROCEDURE ABITUR_QUEUE_UPD_NO_SIGN TO PK_MVS_2;
GRANT EXECUTE ON PROCEDURE ABITUR_QUEUE_UPD_NO_SIGN TO PK_MVS_3;
GRANT EXECUTE ON PROCEDURE ABITUR_QUEUE_UPD_NO_SIGN TO PK_MVS_4;
GRANT EXECUTE ON PROCEDURE ABITUR_QUEUE_UPD_NO_SIGN TO PK_MVS_P1;
GRANT EXECUTE ON PROCEDURE ABITUR_QUEUE_UPD_NO_SIGN TO PK_MVS_P2;
GRANT EXECUTE ON PROCEDURE ABITUR_QUEUE_UPD_NO_SIGN TO PK_OFKIT;
GRANT EXECUTE ON PROCEDURE ABITUR_QUEUE_UPD_NO_SIGN TO PK_OFKIT1;
GRANT EXECUTE ON PROCEDURE ABITUR_QUEUE_UPD_NO_SIGN TO PK_OFKIT2;
GRANT EXECUTE ON PROCEDURE ABITUR_QUEUE_UPD_NO_SIGN TO PK_OFKIT3;
GRANT EXECUTE ON PROCEDURE ABITUR_QUEUE_UPD_NO_SIGN TO PK_OFKIT4;
GRANT EXECUTE ON PROCEDURE ABITUR_QUEUE_UPD_NO_SIGN TO PK_OFKIT5;
GRANT EXECUTE ON PROCEDURE ABITUR_QUEUE_UPD_NO_SIGN TO PK_OFKITP1;
GRANT EXECUTE ON PROCEDURE ABITUR_QUEUE_UPD_NO_SIGN TO PK_OFKITP2;
GRANT EXECUTE ON PROCEDURE ABITUR_QUEUE_UPD_NO_SIGN TO PK_OFK_1;
GRANT EXECUTE ON PROCEDURE ABITUR_QUEUE_UPD_NO_SIGN TO PK_OFK_2;
GRANT EXECUTE ON PROCEDURE ABITUR_QUEUE_UPD_NO_SIGN TO PK_OFK_3;
GRANT EXECUTE ON PROCEDURE ABITUR_QUEUE_UPD_NO_SIGN TO PK_OFK_4;
GRANT EXECUTE ON PROCEDURE ABITUR_QUEUE_UPD_NO_SIGN TO PK_OFK_P1;
GRANT EXECUTE ON PROCEDURE ABITUR_QUEUE_UPD_NO_SIGN TO PK_OFK_P2;
GRANT EXECUTE ON PROCEDURE ABITUR_QUEUE_UPD_NO_SIGN TO PK_OTV1;
GRANT EXECUTE ON PROCEDURE ABITUR_QUEUE_UPD_NO_SIGN TO PK_OTV2;
GRANT EXECUTE ON PROCEDURE ABITUR_QUEUE_UPD_NO_SIGN TO PK_OTV3;
GRANT EXECUTE ON PROCEDURE ABITUR_QUEUE_UPD_NO_SIGN TO PK_OTV4;
GRANT EXECUTE ON PROCEDURE ABITUR_QUEUE_UPD_NO_SIGN TO PK_SIIE;
GRANT EXECUTE ON PROCEDURE ABITUR_QUEUE_UPD_NO_SIGN TO PK_SIIE1;
GRANT EXECUTE ON PROCEDURE ABITUR_QUEUE_UPD_NO_SIGN TO PK_SIIE2;
GRANT EXECUTE ON PROCEDURE ABITUR_QUEUE_UPD_NO_SIGN TO PK_SIIE3;
GRANT EXECUTE ON PROCEDURE ABITUR_QUEUE_UPD_NO_SIGN TO PK_SIIE4;
GRANT EXECUTE ON PROCEDURE ABITUR_QUEUE_UPD_NO_SIGN TO PK_SIIE5;
GRANT EXECUTE ON PROCEDURE ABITUR_QUEUE_UPD_NO_SIGN TO PK_SIIEP1;
GRANT EXECUTE ON PROCEDURE ABITUR_QUEUE_UPD_NO_SIGN TO PK_SIIEP2;
GRANT EXECUTE ON PROCEDURE ABITUR_QUEUE_UPD_NO_SIGN TO PK_SIIEP3;
GRANT EXECUTE ON PROCEDURE ABITUR_QUEUE_UPD_NO_SIGN TO PK_SIIE_1;
GRANT EXECUTE ON PROCEDURE ABITUR_QUEUE_UPD_NO_SIGN TO PK_SIIE_2;
GRANT EXECUTE ON PROCEDURE ABITUR_QUEUE_UPD_NO_SIGN TO PK_SIIE_3;
GRANT EXECUTE ON PROCEDURE ABITUR_QUEUE_UPD_NO_SIGN TO PK_SIIE_4;
GRANT EXECUTE ON PROCEDURE ABITUR_QUEUE_UPD_NO_SIGN TO PK_SIIE_P1;
GRANT EXECUTE ON PROCEDURE ABITUR_QUEUE_UPD_NO_SIGN TO PK_SIIE_P2;
GRANT EXECUTE ON PROCEDURE ABITUR_QUEUE_UPD_NO_SIGN TO PLANIDA_E;
GRANT EXECUTE ON PROCEDURE ABITUR_QUEUE_UPD_NO_SIGN TO PUBLIC;
GRANT EXECUTE ON PROCEDURE ABITUR_QUEUE_UPD_NO_SIGN TO SADIK;
GRANT EXECUTE ON PROCEDURE ABITUR_QUEUE_UPD_NO_SIGN TO SEL_COM;
GRANT EXECUTE ON PROCEDURE ABITUR_QUEUE_UPD_NO_SIGN TO SETUN1998;
GRANT EXECUTE ON PROCEDURE ABITUR_QUEUE_UPD_NO_SIGN TO SHMAENKOVA_M;
GRANT EXECUTE ON PROCEDURE ABITUR_QUEUE_UPD_NO_SIGN TO SHPAKEVICH_P;
GRANT EXECUTE ON PROCEDURE ABITUR_QUEUE_UPD_NO_SIGN TO SIIE1;
GRANT EXECUTE ON PROCEDURE ABITUR_QUEUE_UPD_NO_SIGN TO SIIE1234;
GRANT EXECUTE ON PROCEDURE ABITUR_QUEUE_UPD_NO_SIGN TO SIIE2;
GRANT EXECUTE ON PROCEDURE ABITUR_QUEUE_UPD_NO_SIGN TO SIIE3;
GRANT EXECUTE ON PROCEDURE ABITUR_QUEUE_UPD_NO_SIGN TO SIIE4;
GRANT EXECUTE ON PROCEDURE ABITUR_QUEUE_UPD_NO_SIGN TO SIIE_Z1;
GRANT EXECUTE ON PROCEDURE ABITUR_QUEUE_UPD_NO_SIGN TO STUD_KADR1;
GRANT EXECUTE ON PROCEDURE ABITUR_QUEUE_UPD_NO_SIGN TO STUD_KADR4;
GRANT EXECUTE ON PROCEDURE ABITUR_QUEUE_UPD_NO_SIGN TO SVETA;
GRANT EXECUTE ON PROCEDURE ABITUR_QUEUE_UPD_NO_SIGN TO SYSDBA;
GRANT EXECUTE ON PROCEDURE ABITUR_QUEUE_UPD_NO_SIGN TO UO_LAB;
GRANT EXECUTE ON PROCEDURE ABITUR_QUEUE_UPD_NO_SIGN TO UO_N;
GRANT EXECUTE ON PROCEDURE ABITUR_QUEUE_UPD_NO_SIGN TO UO_Z;
GRANT EXECUTE ON PROCEDURE ABITUR_QUEUE_UPD_NO_SIGN TO VIEWER_MOB;
GRANT EXECUTE ON PROCEDURE ABITUR_QUEUE_UPD_NO_SIGN TO VNUK;
GRANT EXECUTE ON PROCEDURE ABITUR_QUEUE_UPD_NO_SIGN TO VOROBEI75;
GRANT EXECUTE ON PROCEDURE ABITUR_QUEUE_UPD_NO_SIGN TO YAUHENI_HATSURA;