SET TERM ^ ;

CREATE OR ALTER
    PROCEDURE
        ABITUR_FROM_QUEUE
        (
            status_queue SMALLINT,
            time_queue   DATE,
            n_specializ  SMALLINT,
            n_spec       SMALLINT,
            vid_edu      SMALLINT,
            category_ab  SMALLINT,
            category_edu SMALLINT,
            term_edu     SMALLINT,
            price        SMALLINT,
            konkurs      SMALLINT,
            id_ab        SMALLINT,
            category_if  SMALLINT
        )
AS
BEGIN
    UPDATE
        ABITUR_QUEUE
    SET
        STATUS_QUEUE = :status_queue,
        TIME_QUEUE   = :time_queue,
        N_SPECIALIZ  = :n_specializ,
        N_SPEC       = :n_spec,
        VID_EDU      = :vid_edu,
        CATEGORY_AB  = :category_ab,
        CATEGORY_IF  = :category_if,
        CATEGORY_EDU = :category_edu,
        TERM_EDU     = :term_edu,
        PRICE        = :price,
        KONKURS      = :konkurs
    WHERE
        ID_AB = :id_ab;
END^

SET TERM ; ^

/* Following GRANT statements are generated automatically */

GRANT
    SELECT,
    UPDATE
ON
    ABITUR_QUEUE
TO
    PROCEDURE
        ABITUR_FROM_QUEUE;

/* Existing privileges on this procedure */

GRANT EXECUTE ON PROCEDURE ABITUR_FROM_QUEUE TO ABITUR1;
GRANT EXECUTE ON PROCEDURE ABITUR_FROM_QUEUE TO ABITUR2;
GRANT EXECUTE ON PROCEDURE ABITUR_FROM_QUEUE TO ABITUR3;
GRANT EXECUTE ON PROCEDURE ABITUR_FROM_QUEUE TO ABITUR4;
GRANT EXECUTE ON PROCEDURE ABITUR_FROM_QUEUE TO ABITURA;
GRANT EXECUTE ON PROCEDURE ABITUR_FROM_QUEUE TO ALEXANDER_GONCHAROV;
GRANT EXECUTE ON PROCEDURE ABITUR_FROM_QUEUE TO ASU;
GRANT EXECUTE ON PROCEDURE ABITUR_FROM_QUEUE TO ASU1;
GRANT EXECUTE ON PROCEDURE ABITUR_FROM_QUEUE TO ASU2;
GRANT EXECUTE ON PROCEDURE ABITUR_FROM_QUEUE TO ASU3;
GRANT EXECUTE ON PROCEDURE ABITUR_FROM_QUEUE TO ASU4;
GRANT EXECUTE ON PROCEDURE ABITUR_FROM_QUEUE TO DEVELOPER;
GRANT EXECUTE ON PROCEDURE ABITUR_FROM_QUEUE TO IVANOVA_A;
GRANT EXECUTE ON PROCEDURE ABITUR_FROM_QUEUE TO OKSANA;
GRANT EXECUTE ON PROCEDURE ABITUR_FROM_QUEUE TO PK;
GRANT EXECUTE ON PROCEDURE ABITUR_FROM_QUEUE TO PK_IT;
GRANT EXECUTE ON PROCEDURE ABITUR_FROM_QUEUE TO PK_IT1;
GRANT EXECUTE ON PROCEDURE ABITUR_FROM_QUEUE TO PK_IT2;
GRANT EXECUTE ON PROCEDURE ABITUR_FROM_QUEUE TO PK_IT3;
GRANT EXECUTE ON PROCEDURE ABITUR_FROM_QUEUE TO PK_IT4;
GRANT EXECUTE ON PROCEDURE ABITUR_FROM_QUEUE TO PK_IT5;
GRANT EXECUTE ON PROCEDURE ABITUR_FROM_QUEUE TO PK_MSTIG1;
GRANT EXECUTE ON PROCEDURE ABITUR_FROM_QUEUE TO PK_MSTIG2;
GRANT EXECUTE ON PROCEDURE ABITUR_FROM_QUEUE TO PK_MSTIG3;
GRANT EXECUTE ON PROCEDURE ABITUR_FROM_QUEUE TO PK_MSTIG4;
GRANT EXECUTE ON PROCEDURE ABITUR_FROM_QUEUE TO PK_MSTIGP1;
GRANT EXECUTE ON PROCEDURE ABITUR_FROM_QUEUE TO PK_MSTIGP2;
GRANT EXECUTE ON PROCEDURE ABITUR_FROM_QUEUE TO PK_MSTIG_1;
GRANT EXECUTE ON PROCEDURE ABITUR_FROM_QUEUE TO PK_MSTIG_2;
GRANT EXECUTE ON PROCEDURE ABITUR_FROM_QUEUE TO PK_MSTIG_3;
GRANT EXECUTE ON PROCEDURE ABITUR_FROM_QUEUE TO PK_MSTIG_4;
GRANT EXECUTE ON PROCEDURE ABITUR_FROM_QUEUE TO PK_MSTIG_P1;
GRANT EXECUTE ON PROCEDURE ABITUR_FROM_QUEUE TO PK_MSTIG_P2;
GRANT EXECUTE ON PROCEDURE ABITUR_FROM_QUEUE TO PK_MVS;
GRANT EXECUTE ON PROCEDURE ABITUR_FROM_QUEUE TO PK_MVS1;
GRANT EXECUTE ON PROCEDURE ABITUR_FROM_QUEUE TO PK_MVS2;
GRANT EXECUTE ON PROCEDURE ABITUR_FROM_QUEUE TO PK_MVS3;
GRANT EXECUTE ON PROCEDURE ABITUR_FROM_QUEUE TO PK_MVS4;
GRANT EXECUTE ON PROCEDURE ABITUR_FROM_QUEUE TO PK_MVS5;
GRANT EXECUTE ON PROCEDURE ABITUR_FROM_QUEUE TO PK_MVSP1;
GRANT EXECUTE ON PROCEDURE ABITUR_FROM_QUEUE TO PK_MVSP2;
GRANT EXECUTE ON PROCEDURE ABITUR_FROM_QUEUE TO PK_MVS_1;
GRANT EXECUTE ON PROCEDURE ABITUR_FROM_QUEUE TO PK_MVS_2;
GRANT EXECUTE ON PROCEDURE ABITUR_FROM_QUEUE TO PK_MVS_3;
GRANT EXECUTE ON PROCEDURE ABITUR_FROM_QUEUE TO PK_MVS_4;
GRANT EXECUTE ON PROCEDURE ABITUR_FROM_QUEUE TO PK_MVS_P1;
GRANT EXECUTE ON PROCEDURE ABITUR_FROM_QUEUE TO PK_MVS_P2;
GRANT EXECUTE ON PROCEDURE ABITUR_FROM_QUEUE TO PK_OFKIT;
GRANT EXECUTE ON PROCEDURE ABITUR_FROM_QUEUE TO PK_OFKIT1;
GRANT EXECUTE ON PROCEDURE ABITUR_FROM_QUEUE TO PK_OFKIT2;
GRANT EXECUTE ON PROCEDURE ABITUR_FROM_QUEUE TO PK_OFKIT3;
GRANT EXECUTE ON PROCEDURE ABITUR_FROM_QUEUE TO PK_OFKIT4;
GRANT EXECUTE ON PROCEDURE ABITUR_FROM_QUEUE TO PK_OFKIT5;
GRANT EXECUTE ON PROCEDURE ABITUR_FROM_QUEUE TO PK_OFKITP1;
GRANT EXECUTE ON PROCEDURE ABITUR_FROM_QUEUE TO PK_OFKITP2;
GRANT EXECUTE ON PROCEDURE ABITUR_FROM_QUEUE TO PK_OFK_1;
GRANT EXECUTE ON PROCEDURE ABITUR_FROM_QUEUE TO PK_OFK_2;
GRANT EXECUTE ON PROCEDURE ABITUR_FROM_QUEUE TO PK_OFK_3;
GRANT EXECUTE ON PROCEDURE ABITUR_FROM_QUEUE TO PK_OFK_4;
GRANT EXECUTE ON PROCEDURE ABITUR_FROM_QUEUE TO PK_OFK_P1;
GRANT EXECUTE ON PROCEDURE ABITUR_FROM_QUEUE TO PK_OFK_P2;
GRANT EXECUTE ON PROCEDURE ABITUR_FROM_QUEUE TO PK_OTV1;
GRANT EXECUTE ON PROCEDURE ABITUR_FROM_QUEUE TO PK_OTV2;
GRANT EXECUTE ON PROCEDURE ABITUR_FROM_QUEUE TO PK_OTV3;
GRANT EXECUTE ON PROCEDURE ABITUR_FROM_QUEUE TO PK_OTV4;
GRANT EXECUTE ON PROCEDURE ABITUR_FROM_QUEUE TO PK_SIIE;
GRANT EXECUTE ON PROCEDURE ABITUR_FROM_QUEUE TO PK_SIIE1;
GRANT EXECUTE ON PROCEDURE ABITUR_FROM_QUEUE TO PK_SIIE2;
GRANT EXECUTE ON PROCEDURE ABITUR_FROM_QUEUE TO PK_SIIE3;
GRANT EXECUTE ON PROCEDURE ABITUR_FROM_QUEUE TO PK_SIIE4;
GRANT EXECUTE ON PROCEDURE ABITUR_FROM_QUEUE TO PK_SIIE5;
GRANT EXECUTE ON PROCEDURE ABITUR_FROM_QUEUE TO PK_SIIEP1;
GRANT EXECUTE ON PROCEDURE ABITUR_FROM_QUEUE TO PK_SIIEP2;
GRANT EXECUTE ON PROCEDURE ABITUR_FROM_QUEUE TO PK_SIIEP3;
GRANT EXECUTE ON PROCEDURE ABITUR_FROM_QUEUE TO PK_SIIE_1;
GRANT EXECUTE ON PROCEDURE ABITUR_FROM_QUEUE TO PK_SIIE_2;
GRANT EXECUTE ON PROCEDURE ABITUR_FROM_QUEUE TO PK_SIIE_3;
GRANT EXECUTE ON PROCEDURE ABITUR_FROM_QUEUE TO PK_SIIE_4;
GRANT EXECUTE ON PROCEDURE ABITUR_FROM_QUEUE TO PK_SIIE_P1;
GRANT EXECUTE ON PROCEDURE ABITUR_FROM_QUEUE TO PK_SIIE_P2;
GRANT EXECUTE ON PROCEDURE ABITUR_FROM_QUEUE TO SYSDBA;