SET TERM ^ ;

CREATE OR ALTER
    PROCEDURE
        ABITUR_QUEUE_DEL
        (
            id_ab INTEGER
        )
AS
BEGIN
    DELETE FROM
        ABITUR_QUEUE
    WHERE
        abitur_queue.ID_AB = :id_ab;
END ^

SET TERM ; ^

/* Following GRANT statements are generated automatically */

GRANT
    SELECT,
    DELETE
ON
    ABITUR_QUEUE
TO
    PROCEDURE
        ABITUR_QUEUE_DEL;

/* Existing privileges on this procedure */

GRANT EXECUTE ON PROCEDURE ABITUR_QUEUE_DEL TO ABITUR1;
GRANT EXECUTE ON PROCEDURE ABITUR_QUEUE_DEL TO ABITUR2;
GRANT EXECUTE ON PROCEDURE ABITUR_QUEUE_DEL TO ABITUR3;
GRANT EXECUTE ON PROCEDURE ABITUR_QUEUE_DEL TO ABITUR4;
GRANT EXECUTE ON PROCEDURE ABITUR_QUEUE_DEL TO ABITURA;
GRANT EXECUTE ON PROCEDURE ABITUR_QUEUE_DEL TO ALEXANDER_GONCHAROV;
GRANT EXECUTE ON PROCEDURE ABITUR_QUEUE_DEL TO DEVELOPER;
GRANT EXECUTE ON PROCEDURE ABITUR_QUEUE_DEL TO IVANOVA_A;
GRANT EXECUTE ON PROCEDURE ABITUR_QUEUE_DEL TO OKSANA;
GRANT EXECUTE ON PROCEDURE ABITUR_QUEUE_DEL TO PK_MSTIG1;
GRANT EXECUTE ON PROCEDURE ABITUR_QUEUE_DEL TO PK_MSTIG2;
GRANT EXECUTE ON PROCEDURE ABITUR_QUEUE_DEL TO PK_MSTIG3;
GRANT EXECUTE ON PROCEDURE ABITUR_QUEUE_DEL TO PK_MSTIG4;
GRANT EXECUTE ON PROCEDURE ABITUR_QUEUE_DEL TO PK_MSTIGP1;
GRANT EXECUTE ON PROCEDURE ABITUR_QUEUE_DEL TO PK_MSTIGP2;
GRANT EXECUTE ON PROCEDURE ABITUR_QUEUE_DEL TO PK_MSTIG_1;
GRANT EXECUTE ON PROCEDURE ABITUR_QUEUE_DEL TO PK_MSTIG_2;
GRANT EXECUTE ON PROCEDURE ABITUR_QUEUE_DEL TO PK_MSTIG_3;
GRANT EXECUTE ON PROCEDURE ABITUR_QUEUE_DEL TO PK_MSTIG_4;
GRANT EXECUTE ON PROCEDURE ABITUR_QUEUE_DEL TO PK_MSTIG_P1;
GRANT EXECUTE ON PROCEDURE ABITUR_QUEUE_DEL TO PK_MSTIG_P2;
GRANT EXECUTE ON PROCEDURE ABITUR_QUEUE_DEL TO PK_MVSP1;
GRANT EXECUTE ON PROCEDURE ABITUR_QUEUE_DEL TO PK_MVSP2;
GRANT EXECUTE ON PROCEDURE ABITUR_QUEUE_DEL TO PK_MVS_1;
GRANT EXECUTE ON PROCEDURE ABITUR_QUEUE_DEL TO PK_MVS_2;
GRANT EXECUTE ON PROCEDURE ABITUR_QUEUE_DEL TO PK_MVS_3;
GRANT EXECUTE ON PROCEDURE ABITUR_QUEUE_DEL TO PK_MVS_4;
GRANT EXECUTE ON PROCEDURE ABITUR_QUEUE_DEL TO PK_MVS_P1;
GRANT EXECUTE ON PROCEDURE ABITUR_QUEUE_DEL TO PK_MVS_P2;
GRANT EXECUTE ON PROCEDURE ABITUR_QUEUE_DEL TO PK_OFKIT1;
GRANT EXECUTE ON PROCEDURE ABITUR_QUEUE_DEL TO PK_OFKITP1;
GRANT EXECUTE ON PROCEDURE ABITUR_QUEUE_DEL TO PK_OFKITP2;
GRANT EXECUTE ON PROCEDURE ABITUR_QUEUE_DEL TO PK_OFK_1;
GRANT EXECUTE ON PROCEDURE ABITUR_QUEUE_DEL TO PK_OFK_2;
GRANT EXECUTE ON PROCEDURE ABITUR_QUEUE_DEL TO PK_OFK_3;
GRANT EXECUTE ON PROCEDURE ABITUR_QUEUE_DEL TO PK_OFK_4;
GRANT EXECUTE ON PROCEDURE ABITUR_QUEUE_DEL TO PK_OFK_P1;
GRANT EXECUTE ON PROCEDURE ABITUR_QUEUE_DEL TO PK_OFK_P2;
GRANT EXECUTE ON PROCEDURE ABITUR_QUEUE_DEL TO PK_OTV1;
GRANT EXECUTE ON PROCEDURE ABITUR_QUEUE_DEL TO PK_OTV2;
GRANT EXECUTE ON PROCEDURE ABITUR_QUEUE_DEL TO PK_OTV3;
GRANT EXECUTE ON PROCEDURE ABITUR_QUEUE_DEL TO PK_OTV4;
GRANT EXECUTE ON PROCEDURE ABITUR_QUEUE_DEL TO PK_SIIEP1;
GRANT EXECUTE ON PROCEDURE ABITUR_QUEUE_DEL TO PK_SIIEP2;
GRANT EXECUTE ON PROCEDURE ABITUR_QUEUE_DEL TO PK_SIIEP3;
GRANT EXECUTE ON PROCEDURE ABITUR_QUEUE_DEL TO PK_SIIE_1;
GRANT EXECUTE ON PROCEDURE ABITUR_QUEUE_DEL TO PK_SIIE_2;
GRANT EXECUTE ON PROCEDURE ABITUR_QUEUE_DEL TO PK_SIIE_3;
GRANT EXECUTE ON PROCEDURE ABITUR_QUEUE_DEL TO PK_SIIE_4;
GRANT EXECUTE ON PROCEDURE ABITUR_QUEUE_DEL TO PK_SIIE_P1;
GRANT EXECUTE ON PROCEDURE ABITUR_QUEUE_DEL TO PK_SIIE_P2;
GRANT EXECUTE ON PROCEDURE ABITUR_QUEUE_DEL TO SYSDBA;