SET TERM ^ ;

CREATE OR ALTER
    PROCEDURE
        ABITURA_STATUS_UP
AS
    DECLARE
        VARIABLE n_ab INTEGER;
BEGIN
    FOR
        SELECT
            abitura.ID_AB_QUEUE
        FROM
            ABITURA
        WHERE
            abitura.STATUS = 5
        INTO
            :n_ab
    DO
        BEGIN
            UPDATE
                ABITUR_QUEUE
            SET
                abitur_queue.STATUS_QUEUE = 1105
            WHERE
                abitur_queue.ID_AB = :n_ab;
        END
    SUSPEND;
END

SET TERM ; ^


/* Following GRANT statements are generated automatically */

GRANT
    SELECT
ON
    ABITURA
TO
    PROCEDURE
        ABITURA_STATUS_UP;

GRANT
    SELECT,
    UPDATE
ON
    ABITUR_QUEUE
TO
    PROCEDURE
        ABITURA_STATUS_UP;

/* Existing privileges on this procedure */

GRANT EXECUTE ON PROCEDURE ABITURA_STATUS_UP TO ABITUR1;
GRANT EXECUTE ON PROCEDURE ABITURA_STATUS_UP TO ABITUR2;
GRANT EXECUTE ON PROCEDURE ABITURA_STATUS_UP TO ABITUR3;
GRANT EXECUTE ON PROCEDURE ABITURA_STATUS_UP TO ABITUR4;
GRANT EXECUTE ON PROCEDURE ABITURA_STATUS_UP TO ABITURA;
GRANT EXECUTE ON PROCEDURE ABITURA_STATUS_UP TO ALEXANDER_GONCHAROV;
GRANT EXECUTE ON PROCEDURE ABITURA_STATUS_UP TO IVANOVA_A;
GRANT EXECUTE ON PROCEDURE ABITURA_STATUS_UP TO OKSANA;
GRANT EXECUTE ON PROCEDURE ABITURA_STATUS_UP TO PK_MSTIG1;
GRANT EXECUTE ON PROCEDURE ABITURA_STATUS_UP TO PK_MSTIG2;
GRANT EXECUTE ON PROCEDURE ABITURA_STATUS_UP TO PK_MSTIG3;
GRANT EXECUTE ON PROCEDURE ABITURA_STATUS_UP TO PK_MSTIG4;
GRANT EXECUTE ON PROCEDURE ABITURA_STATUS_UP TO PK_MSTIGP1;
GRANT EXECUTE ON PROCEDURE ABITURA_STATUS_UP TO PK_MSTIGP2;
GRANT EXECUTE ON PROCEDURE ABITURA_STATUS_UP TO PK_MSTIG_1;
GRANT EXECUTE ON PROCEDURE ABITURA_STATUS_UP TO PK_MSTIG_2;
GRANT EXECUTE ON PROCEDURE ABITURA_STATUS_UP TO PK_MSTIG_3;
GRANT EXECUTE ON PROCEDURE ABITURA_STATUS_UP TO PK_MSTIG_4;
GRANT EXECUTE ON PROCEDURE ABITURA_STATUS_UP TO PK_MSTIG_P1;
GRANT EXECUTE ON PROCEDURE ABITURA_STATUS_UP TO PK_MSTIG_P2;
GRANT EXECUTE ON PROCEDURE ABITURA_STATUS_UP TO PK_MVSP1;
GRANT EXECUTE ON PROCEDURE ABITURA_STATUS_UP TO PK_MVSP2;
GRANT EXECUTE ON PROCEDURE ABITURA_STATUS_UP TO PK_MVS_1;
GRANT EXECUTE ON PROCEDURE ABITURA_STATUS_UP TO PK_MVS_2;
GRANT EXECUTE ON PROCEDURE ABITURA_STATUS_UP TO PK_MVS_3;
GRANT EXECUTE ON PROCEDURE ABITURA_STATUS_UP TO PK_MVS_4;
GRANT EXECUTE ON PROCEDURE ABITURA_STATUS_UP TO PK_MVS_P1;
GRANT EXECUTE ON PROCEDURE ABITURA_STATUS_UP TO PK_MVS_P2;
GRANT EXECUTE ON PROCEDURE ABITURA_STATUS_UP TO PK_OFKIT1;
GRANT EXECUTE ON PROCEDURE ABITURA_STATUS_UP TO PK_OFKITP1;
GRANT EXECUTE ON PROCEDURE ABITURA_STATUS_UP TO PK_OFKITP2;
GRANT EXECUTE ON PROCEDURE ABITURA_STATUS_UP TO PK_OFK_1;
GRANT EXECUTE ON PROCEDURE ABITURA_STATUS_UP TO PK_OFK_2;
GRANT EXECUTE ON PROCEDURE ABITURA_STATUS_UP TO PK_OFK_3;
GRANT EXECUTE ON PROCEDURE ABITURA_STATUS_UP TO PK_OFK_4;
GRANT EXECUTE ON PROCEDURE ABITURA_STATUS_UP TO PK_OFK_P1;
GRANT EXECUTE ON PROCEDURE ABITURA_STATUS_UP TO PK_OFK_P2;
GRANT EXECUTE ON PROCEDURE ABITURA_STATUS_UP TO PK_OTV1;
GRANT EXECUTE ON PROCEDURE ABITURA_STATUS_UP TO PK_OTV2;
GRANT EXECUTE ON PROCEDURE ABITURA_STATUS_UP TO PK_OTV3;
GRANT EXECUTE ON PROCEDURE ABITURA_STATUS_UP TO PK_OTV4;
GRANT EXECUTE ON PROCEDURE ABITURA_STATUS_UP TO PK_SIIEP1;
GRANT EXECUTE ON PROCEDURE ABITURA_STATUS_UP TO PK_SIIEP2;
GRANT EXECUTE ON PROCEDURE ABITURA_STATUS_UP TO PK_SIIEP3;
GRANT EXECUTE ON PROCEDURE ABITURA_STATUS_UP TO PK_SIIE_1;
GRANT EXECUTE ON PROCEDURE ABITURA_STATUS_UP TO PK_SIIE_2;
GRANT EXECUTE ON PROCEDURE ABITURA_STATUS_UP TO PK_SIIE_3;
GRANT EXECUTE ON PROCEDURE ABITURA_STATUS_UP TO PK_SIIE_4;
GRANT EXECUTE ON PROCEDURE ABITURA_STATUS_UP TO PK_SIIE_P1;
GRANT EXECUTE ON PROCEDURE ABITURA_STATUS_UP TO PK_SIIE_P2;
GRANT EXECUTE ON PROCEDURE ABITURA_STATUS_UP TO SYSDBA;