SET TERM ^ ;

CREATE OR ALTER
    PROCEDURE
        ALL_MAS_KONKURS
        (
            in_sp_all_m      SMALLINT,
            in_vid_edu_all_m SMALLINT
        )
    RETURNS
        (
            out_n_ab_all_m INTEGER
        )
AS
BEGIN
    FOR
        SELECT
            a.NOMER_AB
        FROM
            ABITURA a 
        WHERE
                (a.N_SPECIALIZ =      :in_sp_all_m)
            AND (a.STATUS      =      0)
            AND (a.VID_EDU     =      :in_vid_edu_all_m)
            AND (a.KONKURS     NOT IN (3))
        INTO
            :out_n_ab_all_m
    DO
    SUSPEND;
END^

SET TERM ; ^

/* Following GRANT statements are generated automatically */

GRANT
    SELECT
ON
    ABITURA
TO
    PROCEDURE
        ALL_MAS_KONKURS;

/* Existing privileges on this procedure */

GRANT EXECUTE ON PROCEDURE ALL_MAS_KONKURS TO ABITUR1;
GRANT EXECUTE ON PROCEDURE ALL_MAS_KONKURS TO ABITUR2;
GRANT EXECUTE ON PROCEDURE ALL_MAS_KONKURS TO ABITUR3;
GRANT EXECUTE ON PROCEDURE ALL_MAS_KONKURS TO ABITUR4;
GRANT EXECUTE ON PROCEDURE ALL_MAS_KONKURS TO ABITURA;
GRANT EXECUTE ON PROCEDURE ALL_MAS_KONKURS TO ALEXANDER_GONCHAROV;
GRANT EXECUTE ON PROCEDURE ALL_MAS_KONKURS TO ASU;
GRANT EXECUTE ON PROCEDURE ALL_MAS_KONKURS TO ASU1;
GRANT EXECUTE ON PROCEDURE ALL_MAS_KONKURS TO ASU2;
GRANT EXECUTE ON PROCEDURE ALL_MAS_KONKURS TO ASU3;
GRANT EXECUTE ON PROCEDURE ALL_MAS_KONKURS TO ASU4;
GRANT EXECUTE ON PROCEDURE ALL_MAS_KONKURS TO DEVELOPER;
GRANT EXECUTE ON PROCEDURE ALL_MAS_KONKURS TO DEVELOPER2;
GRANT EXECUTE ON PROCEDURE ALL_MAS_KONKURS TO IT1;
GRANT EXECUTE ON PROCEDURE ALL_MAS_KONKURS TO IT2;
GRANT EXECUTE ON PROCEDURE ALL_MAS_KONKURS TO IT3;
GRANT EXECUTE ON PROCEDURE ALL_MAS_KONKURS TO IVANOVA_A;
GRANT EXECUTE ON PROCEDURE ALL_MAS_KONKURS TO MVS1;
GRANT EXECUTE ON PROCEDURE ALL_MAS_KONKURS TO MVS2;
GRANT EXECUTE ON PROCEDURE ALL_MAS_KONKURS TO MVS3;
GRANT EXECUTE ON PROCEDURE ALL_MAS_KONKURS TO MVS4;
GRANT EXECUTE ON PROCEDURE ALL_MAS_KONKURS TO OFKIT1;
GRANT EXECUTE ON PROCEDURE ALL_MAS_KONKURS TO OFKIT2;
GRANT EXECUTE ON PROCEDURE ALL_MAS_KONKURS TO OFKIT3;
GRANT EXECUTE ON PROCEDURE ALL_MAS_KONKURS TO OFKIT4;
GRANT EXECUTE ON PROCEDURE ALL_MAS_KONKURS TO OKSANA;
GRANT EXECUTE ON PROCEDURE ALL_MAS_KONKURS TO PK;
GRANT EXECUTE ON PROCEDURE ALL_MAS_KONKURS TO PK_IT;
GRANT EXECUTE ON PROCEDURE ALL_MAS_KONKURS TO PK_IT1;
GRANT EXECUTE ON PROCEDURE ALL_MAS_KONKURS TO PK_IT2;
GRANT EXECUTE ON PROCEDURE ALL_MAS_KONKURS TO PK_IT3;
GRANT EXECUTE ON PROCEDURE ALL_MAS_KONKURS TO PK_IT4;
GRANT EXECUTE ON PROCEDURE ALL_MAS_KONKURS TO PK_IT5;
GRANT EXECUTE ON PROCEDURE ALL_MAS_KONKURS TO PK_MSTIG1;
GRANT EXECUTE ON PROCEDURE ALL_MAS_KONKURS TO PK_MSTIG2;
GRANT EXECUTE ON PROCEDURE ALL_MAS_KONKURS TO PK_MSTIG3;
GRANT EXECUTE ON PROCEDURE ALL_MAS_KONKURS TO PK_MSTIG4;
GRANT EXECUTE ON PROCEDURE ALL_MAS_KONKURS TO PK_MSTIGP1;
GRANT EXECUTE ON PROCEDURE ALL_MAS_KONKURS TO PK_MSTIGP2;
GRANT EXECUTE ON PROCEDURE ALL_MAS_KONKURS TO PK_MSTIG_1;
GRANT EXECUTE ON PROCEDURE ALL_MAS_KONKURS TO PK_MSTIG_2;
GRANT EXECUTE ON PROCEDURE ALL_MAS_KONKURS TO PK_MSTIG_3;
GRANT EXECUTE ON PROCEDURE ALL_MAS_KONKURS TO PK_MSTIG_4;
GRANT EXECUTE ON PROCEDURE ALL_MAS_KONKURS TO PK_MSTIG_P1;
GRANT EXECUTE ON PROCEDURE ALL_MAS_KONKURS TO PK_MSTIG_P2;
GRANT EXECUTE ON PROCEDURE ALL_MAS_KONKURS TO PK_MVS;
GRANT EXECUTE ON PROCEDURE ALL_MAS_KONKURS TO PK_MVS1;
GRANT EXECUTE ON PROCEDURE ALL_MAS_KONKURS TO PK_MVS2;
GRANT EXECUTE ON PROCEDURE ALL_MAS_KONKURS TO PK_MVS3;
GRANT EXECUTE ON PROCEDURE ALL_MAS_KONKURS TO PK_MVS4;
GRANT EXECUTE ON PROCEDURE ALL_MAS_KONKURS TO PK_MVS5;
GRANT EXECUTE ON PROCEDURE ALL_MAS_KONKURS TO PK_MVSP1;
GRANT EXECUTE ON PROCEDURE ALL_MAS_KONKURS TO PK_MVSP2;
GRANT EXECUTE ON PROCEDURE ALL_MAS_KONKURS TO PK_MVS_1;
GRANT EXECUTE ON PROCEDURE ALL_MAS_KONKURS TO PK_MVS_2;
GRANT EXECUTE ON PROCEDURE ALL_MAS_KONKURS TO PK_MVS_3;
GRANT EXECUTE ON PROCEDURE ALL_MAS_KONKURS TO PK_MVS_4;
GRANT EXECUTE ON PROCEDURE ALL_MAS_KONKURS TO PK_MVS_P1;
GRANT EXECUTE ON PROCEDURE ALL_MAS_KONKURS TO PK_MVS_P2;
GRANT EXECUTE ON PROCEDURE ALL_MAS_KONKURS TO PK_OFKIT;
GRANT EXECUTE ON PROCEDURE ALL_MAS_KONKURS TO PK_OFKIT1;
GRANT EXECUTE ON PROCEDURE ALL_MAS_KONKURS TO PK_OFKIT2;
GRANT EXECUTE ON PROCEDURE ALL_MAS_KONKURS TO PK_OFKIT3;
GRANT EXECUTE ON PROCEDURE ALL_MAS_KONKURS TO PK_OFKIT4;
GRANT EXECUTE ON PROCEDURE ALL_MAS_KONKURS TO PK_OFKIT5;
GRANT EXECUTE ON PROCEDURE ALL_MAS_KONKURS TO PK_OFKITP1;
GRANT EXECUTE ON PROCEDURE ALL_MAS_KONKURS TO PK_OFKITP2;
GRANT EXECUTE ON PROCEDURE ALL_MAS_KONKURS TO PK_OFK_1;
GRANT EXECUTE ON PROCEDURE ALL_MAS_KONKURS TO PK_OFK_2;
GRANT EXECUTE ON PROCEDURE ALL_MAS_KONKURS TO PK_OFK_3;
GRANT EXECUTE ON PROCEDURE ALL_MAS_KONKURS TO PK_OFK_4;
GRANT EXECUTE ON PROCEDURE ALL_MAS_KONKURS TO PK_OFK_P1;
GRANT EXECUTE ON PROCEDURE ALL_MAS_KONKURS TO PK_OFK_P2;
GRANT EXECUTE ON PROCEDURE ALL_MAS_KONKURS TO PK_OTV1;
GRANT EXECUTE ON PROCEDURE ALL_MAS_KONKURS TO PK_OTV2;
GRANT EXECUTE ON PROCEDURE ALL_MAS_KONKURS TO PK_OTV3;
GRANT EXECUTE ON PROCEDURE ALL_MAS_KONKURS TO PK_OTV4;
GRANT EXECUTE ON PROCEDURE ALL_MAS_KONKURS TO PK_SIIE;
GRANT EXECUTE ON PROCEDURE ALL_MAS_KONKURS TO PK_SIIE1;
GRANT EXECUTE ON PROCEDURE ALL_MAS_KONKURS TO PK_SIIE2;
GRANT EXECUTE ON PROCEDURE ALL_MAS_KONKURS TO PK_SIIE3;
GRANT EXECUTE ON PROCEDURE ALL_MAS_KONKURS TO PK_SIIE4;
GRANT EXECUTE ON PROCEDURE ALL_MAS_KONKURS TO PK_SIIE5;
GRANT EXECUTE ON PROCEDURE ALL_MAS_KONKURS TO PK_SIIEP1;
GRANT EXECUTE ON PROCEDURE ALL_MAS_KONKURS TO PK_SIIEP2;
GRANT EXECUTE ON PROCEDURE ALL_MAS_KONKURS TO PK_SIIEP3;
GRANT EXECUTE ON PROCEDURE ALL_MAS_KONKURS TO PK_SIIE_1;
GRANT EXECUTE ON PROCEDURE ALL_MAS_KONKURS TO PK_SIIE_2;
GRANT EXECUTE ON PROCEDURE ALL_MAS_KONKURS TO PK_SIIE_3;
GRANT EXECUTE ON PROCEDURE ALL_MAS_KONKURS TO PK_SIIE_4;
GRANT EXECUTE ON PROCEDURE ALL_MAS_KONKURS TO PK_SIIE_P1;
GRANT EXECUTE ON PROCEDURE ALL_MAS_KONKURS TO PK_SIIE_P2;
GRANT EXECUTE ON PROCEDURE ALL_MAS_KONKURS TO SIIE1;
GRANT EXECUTE ON PROCEDURE ALL_MAS_KONKURS TO SIIE2;
GRANT EXECUTE ON PROCEDURE ALL_MAS_KONKURS TO SIIE3;
GRANT EXECUTE ON PROCEDURE ALL_MAS_KONKURS TO SIIE4;
GRANT EXECUTE ON PROCEDURE ALL_MAS_KONKURS TO SYSDBA;
GRANT EXECUTE ON PROCEDURE ALL_MAS_KONKURS TO UO_LAB;
GRANT EXECUTE ON PROCEDURE ALL_MAS_KONKURS TO UO_N;
GRANT EXECUTE ON PROCEDURE ALL_MAS_KONKURS TO UO_Z;