SET TERM ^ ;

CREATE OR ALTER
    PROCEDURE
        CONTROL_EXERC_IU
        (
            id_control_exerc INTEGER,
            n_fac            SMALLINT,
            n_specializ      SMALLINT,
            pol              CHAR (1),
            num_exerc_grp    SMALLINT,
            id_exerc         SMALLINT
        )
AS
BEGIN
    IF (  EXISTS
          (
              SELECT
                  ID_CONTROL_EXERC
              FROM
                  CONTROL_EXERC
              WHERE
                  (ID_CONTROL_EXERC = :id_control_exerc)
          )
       )
    THEN
        UPDATE
            CONTROL_EXERC
        SET
            N_FAC         = :n_fac,
            N_SPECIALIZ   = :n_specializ,
            POL           = :pol,
            NUM_EXERC_GRP = :num_exerc_grp,
            ID_EXERC      = :id_exerc
        WHERE
            ID_CONTROL_EXERC = :id_control_exerc;
    ELSE
        INSERT INTO
            CONTROL_EXERC
            (
                ID_CONTROL_EXERC,
                N_FAC,
                N_SPECIALIZ,
                POL,
                NUM_EXERC_GRP,
                ID_EXERC
            )
        VALUES
            (
                :id_control_exerc,
                :n_fac,
                :n_specializ,
                :pol,
                :num_exerc_grp,
                :id_exerc
            );
END^

SET TERM ; ^

/* Following GRANT statements are generated automatically */

GRANT
    SELECT,
    INSERT,
    UPDATE
ON
    CONTROL_EXERC
TO
    PROCEDURE
        CONTROL_EXERC_IU;

/* Existing privileges on this procedure */

GRANT EXECUTE ON PROCEDURE CONTROL_EXERC_IU TO PROCEDURE CONTROL_EXERC_IU;
GRANT EXECUTE ON PROCEDURE CONTROL_EXERC_IU TO ABITUR1;
GRANT EXECUTE ON PROCEDURE CONTROL_EXERC_IU TO ABITUR2;
GRANT EXECUTE ON PROCEDURE CONTROL_EXERC_IU TO ABITUR3;
GRANT EXECUTE ON PROCEDURE CONTROL_EXERC_IU TO ABITUR4;
GRANT EXECUTE ON PROCEDURE CONTROL_EXERC_IU TO ABITURA;
GRANT EXECUTE ON PROCEDURE CONTROL_EXERC_IU TO ALEXANDER_GONCHAROV;
GRANT EXECUTE ON PROCEDURE CONTROL_EXERC_IU TO ASU;
GRANT EXECUTE ON PROCEDURE CONTROL_EXERC_IU TO ASU1;
GRANT EXECUTE ON PROCEDURE CONTROL_EXERC_IU TO ASU2;
GRANT EXECUTE ON PROCEDURE CONTROL_EXERC_IU TO ASU3;
GRANT EXECUTE ON PROCEDURE CONTROL_EXERC_IU TO ASU4;
GRANT EXECUTE ON PROCEDURE CONTROL_EXERC_IU TO DEVELOPER;
GRANT EXECUTE ON PROCEDURE CONTROL_EXERC_IU TO IVANOVA_A;
GRANT EXECUTE ON PROCEDURE CONTROL_EXERC_IU TO OKSANA;
GRANT EXECUTE ON PROCEDURE CONTROL_EXERC_IU TO PK;
GRANT EXECUTE ON PROCEDURE CONTROL_EXERC_IU TO PK_IT;
GRANT EXECUTE ON PROCEDURE CONTROL_EXERC_IU TO PK_IT1;
GRANT EXECUTE ON PROCEDURE CONTROL_EXERC_IU TO PK_IT2;
GRANT EXECUTE ON PROCEDURE CONTROL_EXERC_IU TO PK_IT3;
GRANT EXECUTE ON PROCEDURE CONTROL_EXERC_IU TO PK_IT4;
GRANT EXECUTE ON PROCEDURE CONTROL_EXERC_IU TO PK_IT5;
GRANT EXECUTE ON PROCEDURE CONTROL_EXERC_IU TO PK_MSTIG1;
GRANT EXECUTE ON PROCEDURE CONTROL_EXERC_IU TO PK_MSTIG2;
GRANT EXECUTE ON PROCEDURE CONTROL_EXERC_IU TO PK_MSTIG3;
GRANT EXECUTE ON PROCEDURE CONTROL_EXERC_IU TO PK_MSTIG4;
GRANT EXECUTE ON PROCEDURE CONTROL_EXERC_IU TO PK_MSTIGP1;
GRANT EXECUTE ON PROCEDURE CONTROL_EXERC_IU TO PK_MSTIGP2;
GRANT EXECUTE ON PROCEDURE CONTROL_EXERC_IU TO PK_MSTIG_1;
GRANT EXECUTE ON PROCEDURE CONTROL_EXERC_IU TO PK_MSTIG_2;
GRANT EXECUTE ON PROCEDURE CONTROL_EXERC_IU TO PK_MSTIG_3;
GRANT EXECUTE ON PROCEDURE CONTROL_EXERC_IU TO PK_MSTIG_4;
GRANT EXECUTE ON PROCEDURE CONTROL_EXERC_IU TO PK_MSTIG_P1;
GRANT EXECUTE ON PROCEDURE CONTROL_EXERC_IU TO PK_MSTIG_P2;
GRANT EXECUTE ON PROCEDURE CONTROL_EXERC_IU TO PK_MVS;
GRANT EXECUTE ON PROCEDURE CONTROL_EXERC_IU TO PK_MVS1;
GRANT EXECUTE ON PROCEDURE CONTROL_EXERC_IU TO PK_MVS2;
GRANT EXECUTE ON PROCEDURE CONTROL_EXERC_IU TO PK_MVS3;
GRANT EXECUTE ON PROCEDURE CONTROL_EXERC_IU TO PK_MVS4;
GRANT EXECUTE ON PROCEDURE CONTROL_EXERC_IU TO PK_MVS5;
GRANT EXECUTE ON PROCEDURE CONTROL_EXERC_IU TO PK_MVSP1;
GRANT EXECUTE ON PROCEDURE CONTROL_EXERC_IU TO PK_MVSP2;
GRANT EXECUTE ON PROCEDURE CONTROL_EXERC_IU TO PK_MVS_1;
GRANT EXECUTE ON PROCEDURE CONTROL_EXERC_IU TO PK_MVS_2;
GRANT EXECUTE ON PROCEDURE CONTROL_EXERC_IU TO PK_MVS_3;
GRANT EXECUTE ON PROCEDURE CONTROL_EXERC_IU TO PK_MVS_4;
GRANT EXECUTE ON PROCEDURE CONTROL_EXERC_IU TO PK_MVS_P1;
GRANT EXECUTE ON PROCEDURE CONTROL_EXERC_IU TO PK_MVS_P2;
GRANT EXECUTE ON PROCEDURE CONTROL_EXERC_IU TO PK_OFKIT;
GRANT EXECUTE ON PROCEDURE CONTROL_EXERC_IU TO PK_OFKIT1;
GRANT EXECUTE ON PROCEDURE CONTROL_EXERC_IU TO PK_OFKIT2;
GRANT EXECUTE ON PROCEDURE CONTROL_EXERC_IU TO PK_OFKIT3;
GRANT EXECUTE ON PROCEDURE CONTROL_EXERC_IU TO PK_OFKIT4;
GRANT EXECUTE ON PROCEDURE CONTROL_EXERC_IU TO PK_OFKIT5;
GRANT EXECUTE ON PROCEDURE CONTROL_EXERC_IU TO PK_OFKITP1;
GRANT EXECUTE ON PROCEDURE CONTROL_EXERC_IU TO PK_OFKITP2;
GRANT EXECUTE ON PROCEDURE CONTROL_EXERC_IU TO PK_OFK_1;
GRANT EXECUTE ON PROCEDURE CONTROL_EXERC_IU TO PK_OFK_2;
GRANT EXECUTE ON PROCEDURE CONTROL_EXERC_IU TO PK_OFK_3;
GRANT EXECUTE ON PROCEDURE CONTROL_EXERC_IU TO PK_OFK_4;
GRANT EXECUTE ON PROCEDURE CONTROL_EXERC_IU TO PK_OFK_P1;
GRANT EXECUTE ON PROCEDURE CONTROL_EXERC_IU TO PK_OFK_P2;
GRANT EXECUTE ON PROCEDURE CONTROL_EXERC_IU TO PK_OTV1;
GRANT EXECUTE ON PROCEDURE CONTROL_EXERC_IU TO PK_OTV2;
GRANT EXECUTE ON PROCEDURE CONTROL_EXERC_IU TO PK_OTV3;
GRANT EXECUTE ON PROCEDURE CONTROL_EXERC_IU TO PK_OTV4;
GRANT EXECUTE ON PROCEDURE CONTROL_EXERC_IU TO PK_SIIE;
GRANT EXECUTE ON PROCEDURE CONTROL_EXERC_IU TO PK_SIIE1;
GRANT EXECUTE ON PROCEDURE CONTROL_EXERC_IU TO PK_SIIE2;
GRANT EXECUTE ON PROCEDURE CONTROL_EXERC_IU TO PK_SIIE3;
GRANT EXECUTE ON PROCEDURE CONTROL_EXERC_IU TO PK_SIIE4;
GRANT EXECUTE ON PROCEDURE CONTROL_EXERC_IU TO PK_SIIE5;
GRANT EXECUTE ON PROCEDURE CONTROL_EXERC_IU TO PK_SIIEP1;
GRANT EXECUTE ON PROCEDURE CONTROL_EXERC_IU TO PK_SIIEP2;
GRANT EXECUTE ON PROCEDURE CONTROL_EXERC_IU TO PK_SIIEP3;
GRANT EXECUTE ON PROCEDURE CONTROL_EXERC_IU TO PK_SIIE_1;
GRANT EXECUTE ON PROCEDURE CONTROL_EXERC_IU TO PK_SIIE_2;
GRANT EXECUTE ON PROCEDURE CONTROL_EXERC_IU TO PK_SIIE_3;
GRANT EXECUTE ON PROCEDURE CONTROL_EXERC_IU TO PK_SIIE_4;
GRANT EXECUTE ON PROCEDURE CONTROL_EXERC_IU TO PK_SIIE_P1;
GRANT EXECUTE ON PROCEDURE CONTROL_EXERC_IU TO PK_SIIE_P2;
GRANT EXECUTE ON PROCEDURE CONTROL_EXERC_IU TO SYSDBA;