SET TERM ^ ;

CREATE OR ALTER
    PROCEDURE
        GIAZ021
        (
            vid_edu SMALLINT,
            date_in DATE
        )
    RETURNS
        (
            s_all INTEGER,  /* number of all students minus next two position */
            s_16  INTEGER,  /* 1-е место на чемпионате РБ */
            s_17  INTEGER   /* Лаўрэат спецыяльнага фонду Прэзiдэнта РБ */
        )
AS
    DECLARE
        VARIABLE n_ab     INTEGER;
    DECLARE
        VARIABLE sel_priv SMALLINT;
    DECLARE
        VARIABLE dat_priv SMALLINT;
    DECLARE
        VARIABLE nom_1    INTEGER;
BEGIN
    s_all = 0;
    s_17  = 0;
    s_16  = 0;
    nom_1 = 0;
    
    FOR
        SELECT
            abitura.NOMER_AB,       /* abiturient ID */
            privileg_log.SEL_PRIV,  /* Переключатель привелегий (значения от 1 до 19) (возможно, данные из PRIVILEG.N_WITHOUT_TESTS)*/
            privileg_log.DAT_PRIV   /* Значение переключателя привилегии */
        FROM
            ABITURA,
            PRIVILEG_LOG,
            ABITUR_LOGBOOK
        WHERE
                abitura.VID_EDU         =      :vid_edu
            AND abitura.STATUS          IS NOT NULL
            AND abitura.KONKURS         =      1
            AND abitura.CATEGORY_IF     =      0
            AND privileg_log.ID_LOG     =      abitur_logbook.ID_LOG
            AND privileg_log.N_PRIV     =      0                    /* select only T_PRIVILEGE.N_WITHOUT_TESTS */
            AND abitur_logbook.NOMER_AB =      abitura.NOMER_AB
            AND abitur_logbook.DATE_IN  <      :date_in
            AND (     (abitur_logbook.DATE_OUT >  :date_in)
                  OR  (abitur_logbook.DATE_OUT IS NULL)
                )
            AND (     (abitura.TERM_EDU        != 4)
                  AND (abitura.TERM_EDU        != 5)
                )
            
        ORDER BY
            abitura.NOMER_AB
        INTO
            :n_ab,
            :sel_priv,
            :dat_priv
    DO
        BEGIN
            IF (nom_1 <> n_ab)
            THEN
                BEGIN
                    s_all = s_all + 1;
                    
                    IF (sel_priv = 16)          /* Лаўрэат спецыяльнага фонду Прэзiдэнта РБ */
                    THEN
                        BEGIN
                            s_17  = s_17  + 1;
                            s_all = s_all - 1;
                        END
                    
                    IF (sel_priv = 15)          /* 1-е место на чемпионате РБ */
                    THEN
                        BEGIN
                            s_16  = s_16 + 1;
                            s_all = s_all - 1;
                        END
                END
            nom_1 = n_ab;
         END
    SUSPEND;
END^

SET TERM ; ^

/* Following GRANT statements are generated automatically */

GRANT
    SELECT
ON
    ABITURA
TO
    PROCEDURE
        GIAZ021;


GRANT
    SELECT
ON
    PRIVILEG_LOG
TO
    PROCEDURE
        GIAZ021;


GRANT
    SELECT
ON
    ABITUR_LOGBOOK
TO
    PROCEDURE
        GIAZ021;

/* Existing privileges on this procedure */

GRANT EXECUTE ON PROCEDURE GIAZ021 TO ABITUR1;
GRANT EXECUTE ON PROCEDURE GIAZ021 TO ABITUR2;
GRANT EXECUTE ON PROCEDURE GIAZ021 TO ABITUR3;
GRANT EXECUTE ON PROCEDURE GIAZ021 TO ABITUR4;
GRANT EXECUTE ON PROCEDURE GIAZ021 TO ABITURA;
GRANT EXECUTE ON PROCEDURE GIAZ021 TO ALEXANDER_GONCHAROV;
GRANT EXECUTE ON PROCEDURE GIAZ021 TO ASU;
GRANT EXECUTE ON PROCEDURE GIAZ021 TO ASU1;
GRANT EXECUTE ON PROCEDURE GIAZ021 TO ASU2;
GRANT EXECUTE ON PROCEDURE GIAZ021 TO ASU3;
GRANT EXECUTE ON PROCEDURE GIAZ021 TO ASU4;
GRANT EXECUTE ON PROCEDURE GIAZ021 TO DEVELOPER;
GRANT EXECUTE ON PROCEDURE GIAZ021 TO IVANOVA_A;
GRANT EXECUTE ON PROCEDURE GIAZ021 TO OKSANA;
GRANT EXECUTE ON PROCEDURE GIAZ021 TO PK;
GRANT EXECUTE ON PROCEDURE GIAZ021 TO PK_IT;
GRANT EXECUTE ON PROCEDURE GIAZ021 TO PK_IT1;
GRANT EXECUTE ON PROCEDURE GIAZ021 TO PK_IT2;
GRANT EXECUTE ON PROCEDURE GIAZ021 TO PK_IT3;
GRANT EXECUTE ON PROCEDURE GIAZ021 TO PK_IT4;
GRANT EXECUTE ON PROCEDURE GIAZ021 TO PK_IT5;
GRANT EXECUTE ON PROCEDURE GIAZ021 TO PK_MSTIG1;
GRANT EXECUTE ON PROCEDURE GIAZ021 TO PK_MSTIG2;
GRANT EXECUTE ON PROCEDURE GIAZ021 TO PK_MSTIG3;
GRANT EXECUTE ON PROCEDURE GIAZ021 TO PK_MSTIG4;
GRANT EXECUTE ON PROCEDURE GIAZ021 TO PK_MSTIGP1;
GRANT EXECUTE ON PROCEDURE GIAZ021 TO PK_MSTIGP2;
GRANT EXECUTE ON PROCEDURE GIAZ021 TO PK_MSTIG_1;
GRANT EXECUTE ON PROCEDURE GIAZ021 TO PK_MSTIG_2;
GRANT EXECUTE ON PROCEDURE GIAZ021 TO PK_MSTIG_3;
GRANT EXECUTE ON PROCEDURE GIAZ021 TO PK_MSTIG_4;
GRANT EXECUTE ON PROCEDURE GIAZ021 TO PK_MSTIG_P1;
GRANT EXECUTE ON PROCEDURE GIAZ021 TO PK_MSTIG_P2;
GRANT EXECUTE ON PROCEDURE GIAZ021 TO PK_MVS;
GRANT EXECUTE ON PROCEDURE GIAZ021 TO PK_MVS1;
GRANT EXECUTE ON PROCEDURE GIAZ021 TO PK_MVS2;
GRANT EXECUTE ON PROCEDURE GIAZ021 TO PK_MVS3;
GRANT EXECUTE ON PROCEDURE GIAZ021 TO PK_MVS4;
GRANT EXECUTE ON PROCEDURE GIAZ021 TO PK_MVS5;
GRANT EXECUTE ON PROCEDURE GIAZ021 TO PK_MVSP1;
GRANT EXECUTE ON PROCEDURE GIAZ021 TO PK_MVSP2;
GRANT EXECUTE ON PROCEDURE GIAZ021 TO PK_MVS_1;
GRANT EXECUTE ON PROCEDURE GIAZ021 TO PK_MVS_2;
GRANT EXECUTE ON PROCEDURE GIAZ021 TO PK_MVS_3;
GRANT EXECUTE ON PROCEDURE GIAZ021 TO PK_MVS_4;
GRANT EXECUTE ON PROCEDURE GIAZ021 TO PK_MVS_P1;
GRANT EXECUTE ON PROCEDURE GIAZ021 TO PK_MVS_P2;
GRANT EXECUTE ON PROCEDURE GIAZ021 TO PK_OFKIT;
GRANT EXECUTE ON PROCEDURE GIAZ021 TO PK_OFKIT1;
GRANT EXECUTE ON PROCEDURE GIAZ021 TO PK_OFKIT2;
GRANT EXECUTE ON PROCEDURE GIAZ021 TO PK_OFKIT3;
GRANT EXECUTE ON PROCEDURE GIAZ021 TO PK_OFKIT4;
GRANT EXECUTE ON PROCEDURE GIAZ021 TO PK_OFKIT5;
GRANT EXECUTE ON PROCEDURE GIAZ021 TO PK_OFKITP1;
GRANT EXECUTE ON PROCEDURE GIAZ021 TO PK_OFKITP2;
GRANT EXECUTE ON PROCEDURE GIAZ021 TO PK_OFK_1;
GRANT EXECUTE ON PROCEDURE GIAZ021 TO PK_OFK_2;
GRANT EXECUTE ON PROCEDURE GIAZ021 TO PK_OFK_3;
GRANT EXECUTE ON PROCEDURE GIAZ021 TO PK_OFK_4;
GRANT EXECUTE ON PROCEDURE GIAZ021 TO PK_OFK_P1;
GRANT EXECUTE ON PROCEDURE GIAZ021 TO PK_OFK_P2;
GRANT EXECUTE ON PROCEDURE GIAZ021 TO PK_OTV1;
GRANT EXECUTE ON PROCEDURE GIAZ021 TO PK_OTV2;
GRANT EXECUTE ON PROCEDURE GIAZ021 TO PK_OTV3;
GRANT EXECUTE ON PROCEDURE GIAZ021 TO PK_OTV4;
GRANT EXECUTE ON PROCEDURE GIAZ021 TO PK_SIIE;
GRANT EXECUTE ON PROCEDURE GIAZ021 TO PK_SIIE1;
GRANT EXECUTE ON PROCEDURE GIAZ021 TO PK_SIIE2;
GRANT EXECUTE ON PROCEDURE GIAZ021 TO PK_SIIE3;
GRANT EXECUTE ON PROCEDURE GIAZ021 TO PK_SIIE4;
GRANT EXECUTE ON PROCEDURE GIAZ021 TO PK_SIIE5;
GRANT EXECUTE ON PROCEDURE GIAZ021 TO PK_SIIEP1;
GRANT EXECUTE ON PROCEDURE GIAZ021 TO PK_SIIEP2;
GRANT EXECUTE ON PROCEDURE GIAZ021 TO PK_SIIEP3;
GRANT EXECUTE ON PROCEDURE GIAZ021 TO PK_SIIE_1;
GRANT EXECUTE ON PROCEDURE GIAZ021 TO PK_SIIE_2;
GRANT EXECUTE ON PROCEDURE GIAZ021 TO PK_SIIE_3;
GRANT EXECUTE ON PROCEDURE GIAZ021 TO PK_SIIE_4;
GRANT EXECUTE ON PROCEDURE GIAZ021 TO PK_SIIE_P1;
GRANT EXECUTE ON PROCEDURE GIAZ021 TO PK_SIIE_P2;
GRANT EXECUTE ON PROCEDURE GIAZ021 TO SYSDBA;