SET TERM ^ ;

CREATE OR ALTER
    PROCEDURE
        GIAZ022
        (
            vid_edu SMALLINT,
            date_in DATE
        )
    RETURNS
        (
            s_all   INTEGER,
            s_21    INTEGER,
            s_27    INTEGER,
            s_22_26 INTEGER
        )
AS
    DECLARE
        VARIABLE n_ab     INTEGER;
    DECLARE
        VARIABLE n_priv   SMALLINT;
    DECLARE
        VARIABLE sel_priv SMALLINT;
    DECLARE
        VARIABLE dat_priv SMALLINT;
    DECLARE
        VARIABLE n_a1     INTEGER;
BEGIN
    S_ALL   = 0;
    S_21    = 0;
    S_27    = 0;
    S_22_26 = 0;
    N_A1    = 0;

    FOR
        SELECT
            abitura.NOMER_AB,
            privileg_log.N_PRIV,
            privileg_log.SEL_PRIV,
            privileg_log.DAT_PRIV
        FROM
            ABITURA,
            PRIVILEG_LOG,
            ABITUR_LOGBOOK
        WHERE
                abitura.VID_EDU         =      :vid_edu
            AND abitura.STATUS          IS NOT NULL
            AND abitura.KONKURS         =      2
            AND abitura.CATEGORY_IF     =      0
            AND privileg_log.ID_LOG     =      abitur_logbook.ID_LOG
            AND privileg_log.N_PRIV     =      1            /* select "out of competition" in T_PRIVILEGE.N_OUT_TEST */
            AND abitur_logbook.NOMER_AB =      abitura.NOMER_AB
            AND abitur_logbook.DATE_IN  <      :date_in
            AND (    (abitur_logbook.DATE_OUT >  :date_in)
                 OR  (abitur_logbook.DATE_OUT IS NULL)
                )
            AND (    (abitura.TERM_EDU        != 4)
                 AND (abitura.TERM_EDU        != 5)
                )
        ORDER BY
            abitura.NOMER_AB
        INTO
            :n_ab,
            :n_priv,
            :sel_priv,
            :dat_priv
    DO
        BEGIN
            IF (n_a1 <> n_ab)
            THEN
                BEGIN
                    s_all = s_all + 1;                              /* number of out of competition students */
                    
                    IF (sel_priv = 0) THEN s_21    = s_21    + 1;   /* don't have a null ??? */
                    IF (sel_priv = 6) THEN s_27    = s_27    + 1;   /* Выпускник УОР (2021г., бюджет) */
                    IF (sel_priv = 1) THEN s_22_26 = s_22_26 + 1;   /* Дети-сироты */
                    IF (sel_priv = 2) THEN s_22_26 = s_22_26 + 1;   /* Чемпионат РБ 2020 */
                    IF (sel_priv = 3) THEN s_22_26 = s_22_26 + 1;   /* Чемпионат РБ 2021 */
                    IF (sel_priv = 4) THEN s_22_26 = s_22_26 + 1;   /* 1-е место 2020 */
                    IF (sel_priv = 5) THEN s_22_26 = s_22_26 + 1;   /* 1-е место 2021 */
                END
            n_a1 = n_ab;
        END
    SUSPEND;
END^

SET TERM ; ^

/* Following GRANT statements are generated automatically */

GRANT
    SELECT
ON
    ABITURA
TO
    PROCEDURE
        GIAZ022;


GRANT
    SELECT
ON
    PRIVILEG_LOG
TO
    PROCEDURE
        GIAZ022;


GRANT
    SELECT
ON
    ABITUR_LOGBOOK
TO
    PROCEDURE
        GIAZ022;

/* Existing privileges on this procedure */

GRANT EXECUTE ON PROCEDURE GIAZ022 TO ABITUR1;
GRANT EXECUTE ON PROCEDURE GIAZ022 TO ABITUR2;
GRANT EXECUTE ON PROCEDURE GIAZ022 TO ABITUR3;
GRANT EXECUTE ON PROCEDURE GIAZ022 TO ABITUR4;
GRANT EXECUTE ON PROCEDURE GIAZ022 TO ABITURA;
GRANT EXECUTE ON PROCEDURE GIAZ022 TO ALEXANDER_GONCHAROV;
GRANT EXECUTE ON PROCEDURE GIAZ022 TO ASU;
GRANT EXECUTE ON PROCEDURE GIAZ022 TO ASU1;
GRANT EXECUTE ON PROCEDURE GIAZ022 TO ASU2;
GRANT EXECUTE ON PROCEDURE GIAZ022 TO ASU3;
GRANT EXECUTE ON PROCEDURE GIAZ022 TO ASU4;
GRANT EXECUTE ON PROCEDURE GIAZ022 TO DEVELOPER;
GRANT EXECUTE ON PROCEDURE GIAZ022 TO IVANOVA_A;
GRANT EXECUTE ON PROCEDURE GIAZ022 TO OKSANA;
GRANT EXECUTE ON PROCEDURE GIAZ022 TO PK;
GRANT EXECUTE ON PROCEDURE GIAZ022 TO PK_IT;
GRANT EXECUTE ON PROCEDURE GIAZ022 TO PK_IT1;
GRANT EXECUTE ON PROCEDURE GIAZ022 TO PK_IT2;
GRANT EXECUTE ON PROCEDURE GIAZ022 TO PK_IT3;
GRANT EXECUTE ON PROCEDURE GIAZ022 TO PK_IT4;
GRANT EXECUTE ON PROCEDURE GIAZ022 TO PK_IT5;
GRANT EXECUTE ON PROCEDURE GIAZ022 TO PK_MSTIG1;
GRANT EXECUTE ON PROCEDURE GIAZ022 TO PK_MSTIG2;
GRANT EXECUTE ON PROCEDURE GIAZ022 TO PK_MSTIG3;
GRANT EXECUTE ON PROCEDURE GIAZ022 TO PK_MSTIG4;
GRANT EXECUTE ON PROCEDURE GIAZ022 TO PK_MSTIGP1;
GRANT EXECUTE ON PROCEDURE GIAZ022 TO PK_MSTIGP2;
GRANT EXECUTE ON PROCEDURE GIAZ022 TO PK_MSTIG_1;
GRANT EXECUTE ON PROCEDURE GIAZ022 TO PK_MSTIG_2;
GRANT EXECUTE ON PROCEDURE GIAZ022 TO PK_MSTIG_3;
GRANT EXECUTE ON PROCEDURE GIAZ022 TO PK_MSTIG_4;
GRANT EXECUTE ON PROCEDURE GIAZ022 TO PK_MSTIG_P1;
GRANT EXECUTE ON PROCEDURE GIAZ022 TO PK_MSTIG_P2;
GRANT EXECUTE ON PROCEDURE GIAZ022 TO PK_MVS;
GRANT EXECUTE ON PROCEDURE GIAZ022 TO PK_MVS1;
GRANT EXECUTE ON PROCEDURE GIAZ022 TO PK_MVS2;
GRANT EXECUTE ON PROCEDURE GIAZ022 TO PK_MVS3;
GRANT EXECUTE ON PROCEDURE GIAZ022 TO PK_MVS4;
GRANT EXECUTE ON PROCEDURE GIAZ022 TO PK_MVS5;
GRANT EXECUTE ON PROCEDURE GIAZ022 TO PK_MVSP1;
GRANT EXECUTE ON PROCEDURE GIAZ022 TO PK_MVSP2;
GRANT EXECUTE ON PROCEDURE GIAZ022 TO PK_MVS_1;
GRANT EXECUTE ON PROCEDURE GIAZ022 TO PK_MVS_2;
GRANT EXECUTE ON PROCEDURE GIAZ022 TO PK_MVS_3;
GRANT EXECUTE ON PROCEDURE GIAZ022 TO PK_MVS_4;
GRANT EXECUTE ON PROCEDURE GIAZ022 TO PK_MVS_P1;
GRANT EXECUTE ON PROCEDURE GIAZ022 TO PK_MVS_P2;
GRANT EXECUTE ON PROCEDURE GIAZ022 TO PK_OFKIT;
GRANT EXECUTE ON PROCEDURE GIAZ022 TO PK_OFKIT1;
GRANT EXECUTE ON PROCEDURE GIAZ022 TO PK_OFKIT2;
GRANT EXECUTE ON PROCEDURE GIAZ022 TO PK_OFKIT3;
GRANT EXECUTE ON PROCEDURE GIAZ022 TO PK_OFKIT4;
GRANT EXECUTE ON PROCEDURE GIAZ022 TO PK_OFKIT5;
GRANT EXECUTE ON PROCEDURE GIAZ022 TO PK_OFKITP1;
GRANT EXECUTE ON PROCEDURE GIAZ022 TO PK_OFKITP2;
GRANT EXECUTE ON PROCEDURE GIAZ022 TO PK_OFK_1;
GRANT EXECUTE ON PROCEDURE GIAZ022 TO PK_OFK_2;
GRANT EXECUTE ON PROCEDURE GIAZ022 TO PK_OFK_3;
GRANT EXECUTE ON PROCEDURE GIAZ022 TO PK_OFK_4;
GRANT EXECUTE ON PROCEDURE GIAZ022 TO PK_OFK_P1;
GRANT EXECUTE ON PROCEDURE GIAZ022 TO PK_OFK_P2;
GRANT EXECUTE ON PROCEDURE GIAZ022 TO PK_OTV1;
GRANT EXECUTE ON PROCEDURE GIAZ022 TO PK_OTV2;
GRANT EXECUTE ON PROCEDURE GIAZ022 TO PK_OTV3;
GRANT EXECUTE ON PROCEDURE GIAZ022 TO PK_OTV4;
GRANT EXECUTE ON PROCEDURE GIAZ022 TO PK_SIIE;
GRANT EXECUTE ON PROCEDURE GIAZ022 TO PK_SIIE1;
GRANT EXECUTE ON PROCEDURE GIAZ022 TO PK_SIIE2;
GRANT EXECUTE ON PROCEDURE GIAZ022 TO PK_SIIE3;
GRANT EXECUTE ON PROCEDURE GIAZ022 TO PK_SIIE4;
GRANT EXECUTE ON PROCEDURE GIAZ022 TO PK_SIIE5;
GRANT EXECUTE ON PROCEDURE GIAZ022 TO PK_SIIEP1;
GRANT EXECUTE ON PROCEDURE GIAZ022 TO PK_SIIEP2;
GRANT EXECUTE ON PROCEDURE GIAZ022 TO PK_SIIEP3;
GRANT EXECUTE ON PROCEDURE GIAZ022 TO PK_SIIE_1;
GRANT EXECUTE ON PROCEDURE GIAZ022 TO PK_SIIE_2;
GRANT EXECUTE ON PROCEDURE GIAZ022 TO PK_SIIE_3;
GRANT EXECUTE ON PROCEDURE GIAZ022 TO PK_SIIE_4;
GRANT EXECUTE ON PROCEDURE GIAZ022 TO PK_SIIE_P1;
GRANT EXECUTE ON PROCEDURE GIAZ022 TO PK_SIIE_P2;
GRANT EXECUTE ON PROCEDURE GIAZ022 TO SYSDBA;