SET TERM ^ ;

CREATE OR ALTER
    PROCEDURE   
        KONKURS
        (
            in_sp      smallint,
            in_vid_edu smallint,
            in_konk    smallint,
            in_price   smallint
        )
    RETURNS
        (
            out_nomer_ab integer,
            out_sum_ball double precision,
            out_f        varchar (30),
            out_n        varchar (30),
            out_o        varchar (30),
            out_n_delo   smallint,
            out_date_r   date,
            out_pol      char (1),
            out_name_e_m varchar (50),
            out_name_e_s varchar (50),
            out_when_e_m smallint,
            out_when_e_s smallint,
            out_stag     double precision,
            out_stag_sp  double precision,
            out_sport    varchar (50),
            out_mid_b    double precision,
            out_address  varchar (100),
            out_copy_at  smallint,
            out_v_k      varchar (5),
            out_priv     varchar (50),
            out_without  varchar (5),
            out_region   integer,
            out_centre   integer,
            out_fio      varchar (90),
            out_n_ck     smallint
        )
AS
BEGIN
    FOR
        SELECT
            a.NOMER_AB,
            a.SUM_BALL,
            a.FAM,
            a.NAME,
            a.OTCH,
            a.NOM_DELA,
            a.DATE_R,
            a.POL,
            a.NAME_EDU_MIDDLE,
            a.NAME_EDU_SPEC,
            a.WHEN_EDU_MIDDLE,
            a.WHEN_EDU_SPEC,
            a.STAG,
            a.STAG_SPEC,
            c.SPORT_CATEGORY,
            a.MIDDLE_BALL,
            a.ADDRESS_BEFORE,
            a.COPY_AT,
            a.V_K,
            a.PRIV,
            a.WITHOUT,
            a.N_REGION,
            a.N_CENTRE,
            IIF ( a.OTCH IS NULL,
                    a.FAM || ' ' || a.NAME,
                    a.FAM || ' ' || a.NAME || ' ' || a.OTCH
                ) FIO,
            a.N_CK
        FROM
                ABITURA  a
            LEFT JOIN
                CATEGORY c
            ON
                a.N_SPORT_CATEGORY = c.N_SPORT_CATEGORY
        WHERE
                a.N_SPECIALIZ = :IN_SP
            AND a.VID_EDU     = :IN_VID_EDU
            AND a.KONKURS     = :in_konk
            and a.price       = :IN_PRICE
            AND a.STATUS      = 0
        ORDER BY
            a.WITHOUT,
            a.V_K,
            a.SUM_BALL    DESC,
            a.PRIV,
            a.MIDDLE_BALL DESC
        INTO
            :out_nomer_ab,
            :out_sum_ball,
            :out_f,
            :out_n,
            :out_o,
            :out_n_delo,
            :out_date_r,
            :out_pol,
            :out_name_e_m,
            :out_name_e_s,
            :out_when_e_m,
            :out_when_e_s,
            :out_stag,
            :out_stag_sp,
            :out_sport,
            :out_mid_b,
            :out_address,
            :out_copy_at,
            :out_v_k,
            :out_priv,
            :out_without,
            :out_region,
            :out_centre,
            :out_fio,
            :out_n_ck
    DO
    SUSPEND;
END^

SET TERM ; ^

/* Following GRANT statements are generated automatically */

GRANT
    SELECT
ON
    ABITURA
TO
    PROCEDURE
        KONKURS;


GRANT
    SELECT
ON
    CATEGORY
TO
    PROCEDURE
        KONKURS;

/* Existing privileges on this procedure */

GRANT EXECUTE ON PROCEDURE KONKURS TO ABITUR1;
GRANT EXECUTE ON PROCEDURE KONKURS TO ABITUR2;
GRANT EXECUTE ON PROCEDURE KONKURS TO ABITUR3;
GRANT EXECUTE ON PROCEDURE KONKURS TO ABITUR4;
GRANT EXECUTE ON PROCEDURE KONKURS TO ABITURA;
GRANT EXECUTE ON PROCEDURE KONKURS TO ALEXANDER_GONCHAROV;
GRANT EXECUTE ON PROCEDURE KONKURS TO ASU;
GRANT EXECUTE ON PROCEDURE KONKURS TO ASU1;
GRANT EXECUTE ON PROCEDURE KONKURS TO ASU2;
GRANT EXECUTE ON PROCEDURE KONKURS TO ASU3;
GRANT EXECUTE ON PROCEDURE KONKURS TO ASU4;
GRANT EXECUTE ON PROCEDURE KONKURS TO DEVELOPER;
GRANT EXECUTE ON PROCEDURE KONKURS TO DEVELOPER2;
GRANT EXECUTE ON PROCEDURE KONKURS TO IT1;
GRANT EXECUTE ON PROCEDURE KONKURS TO IT2;
GRANT EXECUTE ON PROCEDURE KONKURS TO IT3;
GRANT EXECUTE ON PROCEDURE KONKURS TO IVANOVA_A;
GRANT EXECUTE ON PROCEDURE KONKURS TO MVS1;
GRANT EXECUTE ON PROCEDURE KONKURS TO MVS2;
GRANT EXECUTE ON PROCEDURE KONKURS TO MVS3;
GRANT EXECUTE ON PROCEDURE KONKURS TO MVS4;
GRANT EXECUTE ON PROCEDURE KONKURS TO OFKIT1;
GRANT EXECUTE ON PROCEDURE KONKURS TO OFKIT2;
GRANT EXECUTE ON PROCEDURE KONKURS TO OFKIT3;
GRANT EXECUTE ON PROCEDURE KONKURS TO OFKIT4;
GRANT EXECUTE ON PROCEDURE KONKURS TO OKSANA;
GRANT EXECUTE ON PROCEDURE KONKURS TO PK;
GRANT EXECUTE ON PROCEDURE KONKURS TO PK_IT;
GRANT EXECUTE ON PROCEDURE KONKURS TO PK_IT1;
GRANT EXECUTE ON PROCEDURE KONKURS TO PK_IT2;
GRANT EXECUTE ON PROCEDURE KONKURS TO PK_IT3;
GRANT EXECUTE ON PROCEDURE KONKURS TO PK_IT4;
GRANT EXECUTE ON PROCEDURE KONKURS TO PK_IT5;
GRANT EXECUTE ON PROCEDURE KONKURS TO PK_MSTIG1;
GRANT EXECUTE ON PROCEDURE KONKURS TO PK_MSTIG2;
GRANT EXECUTE ON PROCEDURE KONKURS TO PK_MSTIG3;
GRANT EXECUTE ON PROCEDURE KONKURS TO PK_MSTIG4;
GRANT EXECUTE ON PROCEDURE KONKURS TO PK_MSTIGP1;
GRANT EXECUTE ON PROCEDURE KONKURS TO PK_MSTIGP2;
GRANT EXECUTE ON PROCEDURE KONKURS TO PK_MSTIG_1;
GRANT EXECUTE ON PROCEDURE KONKURS TO PK_MSTIG_2;
GRANT EXECUTE ON PROCEDURE KONKURS TO PK_MSTIG_3;
GRANT EXECUTE ON PROCEDURE KONKURS TO PK_MSTIG_4;
GRANT EXECUTE ON PROCEDURE KONKURS TO PK_MSTIG_P1;
GRANT EXECUTE ON PROCEDURE KONKURS TO PK_MSTIG_P2;
GRANT EXECUTE ON PROCEDURE KONKURS TO PK_MVS;
GRANT EXECUTE ON PROCEDURE KONKURS TO PK_MVS1;
GRANT EXECUTE ON PROCEDURE KONKURS TO PK_MVS2;
GRANT EXECUTE ON PROCEDURE KONKURS TO PK_MVS3;
GRANT EXECUTE ON PROCEDURE KONKURS TO PK_MVS4;
GRANT EXECUTE ON PROCEDURE KONKURS TO PK_MVS5;
GRANT EXECUTE ON PROCEDURE KONKURS TO PK_MVSP1;
GRANT EXECUTE ON PROCEDURE KONKURS TO PK_MVSP2;
GRANT EXECUTE ON PROCEDURE KONKURS TO PK_MVS_1;
GRANT EXECUTE ON PROCEDURE KONKURS TO PK_MVS_2;
GRANT EXECUTE ON PROCEDURE KONKURS TO PK_MVS_3;
GRANT EXECUTE ON PROCEDURE KONKURS TO PK_MVS_4;
GRANT EXECUTE ON PROCEDURE KONKURS TO PK_MVS_P1;
GRANT EXECUTE ON PROCEDURE KONKURS TO PK_MVS_P2;
GRANT EXECUTE ON PROCEDURE KONKURS TO PK_OFKIT;
GRANT EXECUTE ON PROCEDURE KONKURS TO PK_OFKIT1;
GRANT EXECUTE ON PROCEDURE KONKURS TO PK_OFKIT2;
GRANT EXECUTE ON PROCEDURE KONKURS TO PK_OFKIT3;
GRANT EXECUTE ON PROCEDURE KONKURS TO PK_OFKIT4;
GRANT EXECUTE ON PROCEDURE KONKURS TO PK_OFKIT5;
GRANT EXECUTE ON PROCEDURE KONKURS TO PK_OFKITP1;
GRANT EXECUTE ON PROCEDURE KONKURS TO PK_OFKITP2;
GRANT EXECUTE ON PROCEDURE KONKURS TO PK_OFK_1;
GRANT EXECUTE ON PROCEDURE KONKURS TO PK_OFK_2;
GRANT EXECUTE ON PROCEDURE KONKURS TO PK_OFK_3;
GRANT EXECUTE ON PROCEDURE KONKURS TO PK_OFK_4;
GRANT EXECUTE ON PROCEDURE KONKURS TO PK_OFK_P1;
GRANT EXECUTE ON PROCEDURE KONKURS TO PK_OFK_P2;
GRANT EXECUTE ON PROCEDURE KONKURS TO PK_OTV1;
GRANT EXECUTE ON PROCEDURE KONKURS TO PK_OTV2;
GRANT EXECUTE ON PROCEDURE KONKURS TO PK_OTV3;
GRANT EXECUTE ON PROCEDURE KONKURS TO PK_OTV4;
GRANT EXECUTE ON PROCEDURE KONKURS TO PK_SIIE;
GRANT EXECUTE ON PROCEDURE KONKURS TO PK_SIIE1;
GRANT EXECUTE ON PROCEDURE KONKURS TO PK_SIIE2;
GRANT EXECUTE ON PROCEDURE KONKURS TO PK_SIIE3;
GRANT EXECUTE ON PROCEDURE KONKURS TO PK_SIIE4;
GRANT EXECUTE ON PROCEDURE KONKURS TO PK_SIIE5;
GRANT EXECUTE ON PROCEDURE KONKURS TO PK_SIIEP1;
GRANT EXECUTE ON PROCEDURE KONKURS TO PK_SIIEP2;
GRANT EXECUTE ON PROCEDURE KONKURS TO PK_SIIEP3;
GRANT EXECUTE ON PROCEDURE KONKURS TO PK_SIIE_1;
GRANT EXECUTE ON PROCEDURE KONKURS TO PK_SIIE_2;
GRANT EXECUTE ON PROCEDURE KONKURS TO PK_SIIE_3;
GRANT EXECUTE ON PROCEDURE KONKURS TO PK_SIIE_4;
GRANT EXECUTE ON PROCEDURE KONKURS TO PK_SIIE_P1;
GRANT EXECUTE ON PROCEDURE KONKURS TO PK_SIIE_P2;
GRANT EXECUTE ON PROCEDURE KONKURS TO SIIE1;
GRANT EXECUTE ON PROCEDURE KONKURS TO SIIE2;
GRANT EXECUTE ON PROCEDURE KONKURS TO SIIE3;
GRANT EXECUTE ON PROCEDURE KONKURS TO SIIE4;
GRANT EXECUTE ON PROCEDURE KONKURS TO SYSDBA;
GRANT EXECUTE ON PROCEDURE KONKURS TO UO_LAB;
GRANT EXECUTE ON PROCEDURE KONKURS TO UO_N;
GRANT EXECUTE ON PROCEDURE KONKURS TO UO_Z;