CREATE SEQUENCE
    ABITURA_NOMER_AB
START
    WITH            0
    INCREMENT BY    1;

ALTER SEQUENCE
    ABITURA_NOMER_AB
RESTART
    WITH 1517;

/* Old syntax is:
CREATE GENERATOR ABITURA_NOMER_AB;
SET GENERATOR ABITURA_NOMER_AB TO 1517;
*/

/* Existing privileges on this sequence */

GRANT USAGE ON SEQUENCE ABITURA_NOMER_AB TO ABITUR1;
GRANT USAGE ON SEQUENCE ABITURA_NOMER_AB TO ABITUR2;
GRANT USAGE ON SEQUENCE ABITURA_NOMER_AB TO ABITUR3;
GRANT USAGE ON SEQUENCE ABITURA_NOMER_AB TO ABITUR4;
GRANT USAGE ON SEQUENCE ABITURA_NOMER_AB TO ABITURA;
GRANT USAGE ON SEQUENCE ABITURA_NOMER_AB TO ALEXANDER_GONCHAROV;
GRANT USAGE ON SEQUENCE ABITURA_NOMER_AB TO IVANOVA_A;
GRANT USAGE ON SEQUENCE ABITURA_NOMER_AB TO OKSANA;
GRANT USAGE ON SEQUENCE ABITURA_NOMER_AB TO PK_MSTIG1;
GRANT USAGE ON SEQUENCE ABITURA_NOMER_AB TO PK_MSTIG2;
GRANT USAGE ON SEQUENCE ABITURA_NOMER_AB TO PK_MSTIG3;
GRANT USAGE ON SEQUENCE ABITURA_NOMER_AB TO PK_MSTIG4;
GRANT USAGE ON SEQUENCE ABITURA_NOMER_AB TO PK_MSTIGP1;
GRANT USAGE ON SEQUENCE ABITURA_NOMER_AB TO PK_MSTIGP2;
GRANT USAGE ON SEQUENCE ABITURA_NOMER_AB TO PK_MSTIG_1;
GRANT USAGE ON SEQUENCE ABITURA_NOMER_AB TO PK_MSTIG_2;
GRANT USAGE ON SEQUENCE ABITURA_NOMER_AB TO PK_MSTIG_3;
GRANT USAGE ON SEQUENCE ABITURA_NOMER_AB TO PK_MSTIG_4;
GRANT USAGE ON SEQUENCE ABITURA_NOMER_AB TO PK_MSTIG_P1;
GRANT USAGE ON SEQUENCE ABITURA_NOMER_AB TO PK_MSTIG_P2;
GRANT USAGE ON SEQUENCE ABITURA_NOMER_AB TO PK_MVSP1;
GRANT USAGE ON SEQUENCE ABITURA_NOMER_AB TO PK_MVSP2;
GRANT USAGE ON SEQUENCE ABITURA_NOMER_AB TO PK_MVS_1;
GRANT USAGE ON SEQUENCE ABITURA_NOMER_AB TO PK_MVS_2;
GRANT USAGE ON SEQUENCE ABITURA_NOMER_AB TO PK_MVS_3;
GRANT USAGE ON SEQUENCE ABITURA_NOMER_AB TO PK_MVS_4;
GRANT USAGE ON SEQUENCE ABITURA_NOMER_AB TO PK_MVS_P1;
GRANT USAGE ON SEQUENCE ABITURA_NOMER_AB TO PK_MVS_P2;
GRANT USAGE ON SEQUENCE ABITURA_NOMER_AB TO PK_OFKIT1;
GRANT USAGE ON SEQUENCE ABITURA_NOMER_AB TO PK_OFKITP1;
GRANT USAGE ON SEQUENCE ABITURA_NOMER_AB TO PK_OFKITP2;
GRANT USAGE ON SEQUENCE ABITURA_NOMER_AB TO PK_OFK_1;
GRANT USAGE ON SEQUENCE ABITURA_NOMER_AB TO PK_OFK_2;
GRANT USAGE ON SEQUENCE ABITURA_NOMER_AB TO PK_OFK_3;
GRANT USAGE ON SEQUENCE ABITURA_NOMER_AB TO PK_OFK_4;
GRANT USAGE ON SEQUENCE ABITURA_NOMER_AB TO PK_OFK_P1;
GRANT USAGE ON SEQUENCE ABITURA_NOMER_AB TO PK_OFK_P2;
GRANT USAGE ON SEQUENCE ABITURA_NOMER_AB TO PK_OTV1;
GRANT USAGE ON SEQUENCE ABITURA_NOMER_AB TO PK_OTV2;
GRANT USAGE ON SEQUENCE ABITURA_NOMER_AB TO PK_OTV3;
GRANT USAGE ON SEQUENCE ABITURA_NOMER_AB TO PK_OTV4;
GRANT USAGE ON SEQUENCE ABITURA_NOMER_AB TO PK_SIIEP1;
GRANT USAGE ON SEQUENCE ABITURA_NOMER_AB TO PK_SIIEP2;
GRANT USAGE ON SEQUENCE ABITURA_NOMER_AB TO PK_SIIEP3;
GRANT USAGE ON SEQUENCE ABITURA_NOMER_AB TO PK_SIIE_1;
GRANT USAGE ON SEQUENCE ABITURA_NOMER_AB TO PK_SIIE_2;
GRANT USAGE ON SEQUENCE ABITURA_NOMER_AB TO PK_SIIE_3;
GRANT USAGE ON SEQUENCE ABITURA_NOMER_AB TO PK_SIIE_4;
GRANT USAGE ON SEQUENCE ABITURA_NOMER_AB TO PK_SIIE_P1;
GRANT USAGE ON SEQUENCE ABITURA_NOMER_AB TO PK_SIIE_P2;
GRANT USAGE ON SEQUENCE ABITURA_NOMER_AB TO PUBLIC;
GRANT USAGE ON SEQUENCE ABITURA_NOMER_AB TO SYSDBA WITH GRANT OPTION;