CREATE SEQUENCE
    CATEGORY_N_SPORT_CATEGORY
START
    WITH            0
    INCREMENT BY    1;

ALTER SEQUENCE
    CATEGORY_N_SPORT_CATEGORY
RESTART
    WITH 12;

/* Old syntax is:
CREATE GENERATOR CATEGORY_N_SPORT_CATEGORY;
SET GENERATOR CATEGORY_N_SPORT_CATEGORY TO 12;
*/

/* Existing privileges on this sequence */

GRANT USAGE ON SEQUENCE CATEGORY_N_SPORT_CATEGORY TO ABITUR1;
GRANT USAGE ON SEQUENCE CATEGORY_N_SPORT_CATEGORY TO ABITUR2;
GRANT USAGE ON SEQUENCE CATEGORY_N_SPORT_CATEGORY TO ABITUR3;
GRANT USAGE ON SEQUENCE CATEGORY_N_SPORT_CATEGORY TO ABITUR4;
GRANT USAGE ON SEQUENCE CATEGORY_N_SPORT_CATEGORY TO ABITURA;
GRANT USAGE ON SEQUENCE CATEGORY_N_SPORT_CATEGORY TO ALEXANDER_GONCHAROV;
GRANT USAGE ON SEQUENCE CATEGORY_N_SPORT_CATEGORY TO IVANOVA_A;
GRANT USAGE ON SEQUENCE CATEGORY_N_SPORT_CATEGORY TO OKSANA;
GRANT USAGE ON SEQUENCE CATEGORY_N_SPORT_CATEGORY TO PK_MSTIG1;
GRANT USAGE ON SEQUENCE CATEGORY_N_SPORT_CATEGORY TO PK_MSTIG2;
GRANT USAGE ON SEQUENCE CATEGORY_N_SPORT_CATEGORY TO PK_MSTIG3;
GRANT USAGE ON SEQUENCE CATEGORY_N_SPORT_CATEGORY TO PK_MSTIG4;
GRANT USAGE ON SEQUENCE CATEGORY_N_SPORT_CATEGORY TO PK_MSTIGP1;
GRANT USAGE ON SEQUENCE CATEGORY_N_SPORT_CATEGORY TO PK_MSTIGP2;
GRANT USAGE ON SEQUENCE CATEGORY_N_SPORT_CATEGORY TO PK_MSTIG_1;
GRANT USAGE ON SEQUENCE CATEGORY_N_SPORT_CATEGORY TO PK_MSTIG_2;
GRANT USAGE ON SEQUENCE CATEGORY_N_SPORT_CATEGORY TO PK_MSTIG_3;
GRANT USAGE ON SEQUENCE CATEGORY_N_SPORT_CATEGORY TO PK_MSTIG_4;
GRANT USAGE ON SEQUENCE CATEGORY_N_SPORT_CATEGORY TO PK_MSTIG_P1;
GRANT USAGE ON SEQUENCE CATEGORY_N_SPORT_CATEGORY TO PK_MSTIG_P2;
GRANT USAGE ON SEQUENCE CATEGORY_N_SPORT_CATEGORY TO PK_MVSP1;
GRANT USAGE ON SEQUENCE CATEGORY_N_SPORT_CATEGORY TO PK_MVSP2;
GRANT USAGE ON SEQUENCE CATEGORY_N_SPORT_CATEGORY TO PK_MVS_1;
GRANT USAGE ON SEQUENCE CATEGORY_N_SPORT_CATEGORY TO PK_MVS_2;
GRANT USAGE ON SEQUENCE CATEGORY_N_SPORT_CATEGORY TO PK_MVS_3;
GRANT USAGE ON SEQUENCE CATEGORY_N_SPORT_CATEGORY TO PK_MVS_4;
GRANT USAGE ON SEQUENCE CATEGORY_N_SPORT_CATEGORY TO PK_MVS_P1;
GRANT USAGE ON SEQUENCE CATEGORY_N_SPORT_CATEGORY TO PK_MVS_P2;
GRANT USAGE ON SEQUENCE CATEGORY_N_SPORT_CATEGORY TO PK_OFKIT1;
GRANT USAGE ON SEQUENCE CATEGORY_N_SPORT_CATEGORY TO PK_OFKITP1;
GRANT USAGE ON SEQUENCE CATEGORY_N_SPORT_CATEGORY TO PK_OFKITP2;
GRANT USAGE ON SEQUENCE CATEGORY_N_SPORT_CATEGORY TO PK_OFK_1;
GRANT USAGE ON SEQUENCE CATEGORY_N_SPORT_CATEGORY TO PK_OFK_2;
GRANT USAGE ON SEQUENCE CATEGORY_N_SPORT_CATEGORY TO PK_OFK_3;
GRANT USAGE ON SEQUENCE CATEGORY_N_SPORT_CATEGORY TO PK_OFK_4;
GRANT USAGE ON SEQUENCE CATEGORY_N_SPORT_CATEGORY TO PK_OFK_P1;
GRANT USAGE ON SEQUENCE CATEGORY_N_SPORT_CATEGORY TO PK_OFK_P2;
GRANT USAGE ON SEQUENCE CATEGORY_N_SPORT_CATEGORY TO PK_OTV1;
GRANT USAGE ON SEQUENCE CATEGORY_N_SPORT_CATEGORY TO PK_OTV2;
GRANT USAGE ON SEQUENCE CATEGORY_N_SPORT_CATEGORY TO PK_OTV3;
GRANT USAGE ON SEQUENCE CATEGORY_N_SPORT_CATEGORY TO PK_OTV4;
GRANT USAGE ON SEQUENCE CATEGORY_N_SPORT_CATEGORY TO PK_SIIEP1;
GRANT USAGE ON SEQUENCE CATEGORY_N_SPORT_CATEGORY TO PK_SIIEP2;
GRANT USAGE ON SEQUENCE CATEGORY_N_SPORT_CATEGORY TO PK_SIIEP3;
GRANT USAGE ON SEQUENCE CATEGORY_N_SPORT_CATEGORY TO PK_SIIE_1;
GRANT USAGE ON SEQUENCE CATEGORY_N_SPORT_CATEGORY TO PK_SIIE_2;
GRANT USAGE ON SEQUENCE CATEGORY_N_SPORT_CATEGORY TO PK_SIIE_3;
GRANT USAGE ON SEQUENCE CATEGORY_N_SPORT_CATEGORY TO PK_SIIE_4;
GRANT USAGE ON SEQUENCE CATEGORY_N_SPORT_CATEGORY TO PK_SIIE_P1;
GRANT USAGE ON SEQUENCE CATEGORY_N_SPORT_CATEGORY TO PK_SIIE_P2;
GRANT USAGE ON SEQUENCE CATEGORY_N_SPORT_CATEGORY TO PUBLIC;
GRANT USAGE ON SEQUENCE CATEGORY_N_SPORT_CATEGORY TO SYSDBA WITH GRANT OPTION;