CREATE SEQUENCE
    PREDMET_N_PREDMET
START
    WITH            0
    INCREMENT BY    1;

ALTER SEQUENCE
    PREDMET_N_PREDMET
RESTART
    WITH 19;

/* Old syntax is:
CREATE GENERATOR
    PREDMET_N_PREDMET;
SET
    GENERATOR
        PREDMET_N_PREDMET TO 19;
*/

/* Existing privileges on this sequence */

GRANT USAGE ON SEQUENCE PREDMET_N_PREDMET TO ABITUR1;
GRANT USAGE ON SEQUENCE PREDMET_N_PREDMET TO ABITUR2;
GRANT USAGE ON SEQUENCE PREDMET_N_PREDMET TO ABITUR3;
GRANT USAGE ON SEQUENCE PREDMET_N_PREDMET TO ABITUR4;
GRANT USAGE ON SEQUENCE PREDMET_N_PREDMET TO ABITURA;
GRANT USAGE ON SEQUENCE PREDMET_N_PREDMET TO ALEXANDER_GONCHAROV;
GRANT USAGE ON SEQUENCE PREDMET_N_PREDMET TO IVANOVA_A;
GRANT USAGE ON SEQUENCE PREDMET_N_PREDMET TO OKSANA;
GRANT USAGE ON SEQUENCE PREDMET_N_PREDMET TO PK_MSTIG1;
GRANT USAGE ON SEQUENCE PREDMET_N_PREDMET TO PK_MSTIG2;
GRANT USAGE ON SEQUENCE PREDMET_N_PREDMET TO PK_MSTIG3;
GRANT USAGE ON SEQUENCE PREDMET_N_PREDMET TO PK_MSTIG4;
GRANT USAGE ON SEQUENCE PREDMET_N_PREDMET TO PK_MSTIGP1;
GRANT USAGE ON SEQUENCE PREDMET_N_PREDMET TO PK_MSTIGP2;
GRANT USAGE ON SEQUENCE PREDMET_N_PREDMET TO PK_MSTIG_1;
GRANT USAGE ON SEQUENCE PREDMET_N_PREDMET TO PK_MSTIG_2;
GRANT USAGE ON SEQUENCE PREDMET_N_PREDMET TO PK_MSTIG_3;
GRANT USAGE ON SEQUENCE PREDMET_N_PREDMET TO PK_MSTIG_4;
GRANT USAGE ON SEQUENCE PREDMET_N_PREDMET TO PK_MSTIG_P1;
GRANT USAGE ON SEQUENCE PREDMET_N_PREDMET TO PK_MSTIG_P2;
GRANT USAGE ON SEQUENCE PREDMET_N_PREDMET TO PK_MVSP1;
GRANT USAGE ON SEQUENCE PREDMET_N_PREDMET TO PK_MVSP2;
GRANT USAGE ON SEQUENCE PREDMET_N_PREDMET TO PK_MVS_1;
GRANT USAGE ON SEQUENCE PREDMET_N_PREDMET TO PK_MVS_2;
GRANT USAGE ON SEQUENCE PREDMET_N_PREDMET TO PK_MVS_3;
GRANT USAGE ON SEQUENCE PREDMET_N_PREDMET TO PK_MVS_4;
GRANT USAGE ON SEQUENCE PREDMET_N_PREDMET TO PK_MVS_P1;
GRANT USAGE ON SEQUENCE PREDMET_N_PREDMET TO PK_MVS_P2;
GRANT USAGE ON SEQUENCE PREDMET_N_PREDMET TO PK_OFKIT1;
GRANT USAGE ON SEQUENCE PREDMET_N_PREDMET TO PK_OFKITP1;
GRANT USAGE ON SEQUENCE PREDMET_N_PREDMET TO PK_OFKITP2;
GRANT USAGE ON SEQUENCE PREDMET_N_PREDMET TO PK_OFK_1;
GRANT USAGE ON SEQUENCE PREDMET_N_PREDMET TO PK_OFK_2;
GRANT USAGE ON SEQUENCE PREDMET_N_PREDMET TO PK_OFK_3;
GRANT USAGE ON SEQUENCE PREDMET_N_PREDMET TO PK_OFK_4;
GRANT USAGE ON SEQUENCE PREDMET_N_PREDMET TO PK_OFK_P1;
GRANT USAGE ON SEQUENCE PREDMET_N_PREDMET TO PK_OFK_P2;
GRANT USAGE ON SEQUENCE PREDMET_N_PREDMET TO PK_OTV1;
GRANT USAGE ON SEQUENCE PREDMET_N_PREDMET TO PK_OTV2;
GRANT USAGE ON SEQUENCE PREDMET_N_PREDMET TO PK_OTV3;
GRANT USAGE ON SEQUENCE PREDMET_N_PREDMET TO PK_OTV4;
GRANT USAGE ON SEQUENCE PREDMET_N_PREDMET TO PK_SIIEP1;
GRANT USAGE ON SEQUENCE PREDMET_N_PREDMET TO PK_SIIEP2;
GRANT USAGE ON SEQUENCE PREDMET_N_PREDMET TO PK_SIIEP3;
GRANT USAGE ON SEQUENCE PREDMET_N_PREDMET TO PK_SIIE_1;
GRANT USAGE ON SEQUENCE PREDMET_N_PREDMET TO PK_SIIE_2;
GRANT USAGE ON SEQUENCE PREDMET_N_PREDMET TO PK_SIIE_3;
GRANT USAGE ON SEQUENCE PREDMET_N_PREDMET TO PK_SIIE_4;
GRANT USAGE ON SEQUENCE PREDMET_N_PREDMET TO PK_SIIE_P1;
GRANT USAGE ON SEQUENCE PREDMET_N_PREDMET TO PK_SIIE_P2;
GRANT USAGE ON SEQUENCE PREDMET_N_PREDMET TO PUBLIC;
GRANT USAGE ON SEQUENCE PREDMET_N_PREDMET TO SYSDBA WITH GRANT OPTION;