/******************************************************************************/

/******************************************************************************/
/***      Following SET SQL DIALECT is just for the Database Comparer       ***/
/******************************************************************************/


/******************************************************************************/
/***                                 Views                                  ***/
/******************************************************************************/


/* View: MOODLE_PEOPLE_SPEC */
CREATE OR ALTER VIEW MOODLE_PEOPLE_SPEC(
    FAM,
    N_SPECIALIZ,
    N_ZACHET,
    KURS,
    NOMER,
    STATUS_KURS,
    N_PLAN,
    SEMESTR,
    VID_EDU,
    N_FAC,
    YEAR_PLAN,
    NAME_OBJECT)
AS
select people.fam,  people.n_specializ, people.n_zachet, people.kurs, people.nomer, people.status_kurs, plan_real_spec.n_plan, plan_real_spec.semestr, people.vid_edu, plan_real_spec.n_fac, plan_real_spec.year_plan, plan_real_spec.name_object
 from plan_real_spec, people, moodle
where ((people.status_kurs <> 1
     and plan_real_spec.year_plan = moodle.edu_year
     and (moodle.edu_year - people.kurs = plan_real_spec.year_plan - plan_real_spec.semestr/2
         or moodle.edu_year - people.kurs = plan_real_spec.year_plan - plan_real_spec.semestr/2 - 0.5))
         or (people.status_kurs = 1
            and (plan_real_spec.year_plan = moodle.edu_year
            and (moodle.edu_year - people.kurs = plan_real_spec.year_plan - plan_real_spec.semestr/2
               or moodle.edu_year - people.kurs  = plan_real_spec.year_plan - plan_real_spec.semestr/2 - 0.5)

          or (plan_real_spec.year_plan = moodle.edu_year-1
              and (moodle.edu_year - people.kurs = plan_real_spec.year_plan - plan_real_spec.semestr/2
                   or moodle.edu_year - people.kurs  = plan_real_spec.year_plan - plan_real_spec.semestr/2 - 0.5)
             )))
      )
     and people.vid_edu = plan_real_spec.vid_edu_plan
     and people.n_fac = plan_real_spec.n_fac
     and people.status_people = 1
     and people.n_specializ = plan_real_spec.n_specializ
;




/******************************************************************************/
/***                               Privileges                               ***/
/******************************************************************************/


/* Privileges of users */
GRANT ALL ON MOODLE_PEOPLE_SPEC TO ABITUR1;
GRANT ALL ON MOODLE_PEOPLE_SPEC TO ABITUR2;
GRANT ALL ON MOODLE_PEOPLE_SPEC TO ABITUR3;
GRANT ALL ON MOODLE_PEOPLE_SPEC TO ABITUR4;
GRANT ALL ON MOODLE_PEOPLE_SPEC TO ALENA_2109;
GRANT ALL ON MOODLE_PEOPLE_SPEC TO ALEXANDER_GONCHAROV;
GRANT ALL ON MOODLE_PEOPLE_SPEC TO ALINA_E;
GRANT ALL ON MOODLE_PEOPLE_SPEC TO ANNA;
GRANT ALL ON MOODLE_PEOPLE_SPEC TO ASPA;
GRANT ALL ON MOODLE_PEOPLE_SPEC TO ASPIRANTURA;
GRANT ALL ON MOODLE_PEOPLE_SPEC TO BAKS16;
GRANT ALL ON MOODLE_PEOPLE_SPEC TO BAKS68878;
GRANT ALL ON MOODLE_PEOPLE_SPEC TO BOBROVICH_O;
GRANT ALL ON MOODLE_PEOPLE_SPEC TO DEVELOPER;
GRANT ALL ON MOODLE_PEOPLE_SPEC TO DOBROVOLSKAYA;
GRANT ALL ON MOODLE_PEOPLE_SPEC TO DVORETSKAYA_K;
GRANT ALL ON MOODLE_PEOPLE_SPEC TO GONCHAROV434_2;
GRANT ALL ON MOODLE_PEOPLE_SPEC TO GUNICH_O;
GRANT ALL ON MOODLE_PEOPLE_SPEC TO GUNICH_OKSANA;
GRANT ALL ON MOODLE_PEOPLE_SPEC TO HOSTEL_PK1;
GRANT ALL ON MOODLE_PEOPLE_SPEC TO HOSTEL_PK2;
GRANT ALL ON MOODLE_PEOPLE_SPEC TO IMSIT_Z;
GRANT ALL ON MOODLE_PEOPLE_SPEC TO IRONSKULL;
GRANT ALL ON MOODLE_PEOPLE_SPEC TO IT5;
GRANT ALL ON MOODLE_PEOPLE_SPEC TO IT8;
GRANT ALL ON MOODLE_PEOPLE_SPEC TO IT_8;
GRANT ALL ON MOODLE_PEOPLE_SPEC TO IVANOVA_A;
GRANT ALL ON MOODLE_PEOPLE_SPEC TO JKMUF2507;
GRANT ALL ON MOODLE_PEOPLE_SPEC TO KANDRUKEVICH_M;
GRANT ALL ON MOODLE_PEOPLE_SPEC TO KAND_M;
GRANT ALL ON MOODLE_PEOPLE_SPEC TO KOSIK_N;
GRANT ALL ON MOODLE_PEOPLE_SPEC TO KRISTINA;
GRANT ALL ON MOODLE_PEOPLE_SPEC TO LAVRENOVA_V;
GRANT ALL ON MOODLE_PEOPLE_SPEC TO LENAUSOVA;
GRANT ALL ON MOODLE_PEOPLE_SPEC TO LIASHKOVICH_I;
GRANT ALL ON MOODLE_PEOPLE_SPEC TO LTRFYFN2019;
GRANT ALL ON MOODLE_PEOPLE_SPEC TO MAGISTR;
GRANT ALL ON MOODLE_PEOPLE_SPEC TO MARINA;
GRANT ALL ON MOODLE_PEOPLE_SPEC TO MATUSEVICH;
GRANT ALL ON MOODLE_PEOPLE_SPEC TO M_2;
GRANT ALL ON MOODLE_PEOPLE_SPEC TO OKSANA;
GRANT ALL ON MOODLE_PEOPLE_SPEC TO OK_STUD_2;
GRANT ALL ON MOODLE_PEOPLE_SPEC TO PK_MSTIG1;
GRANT ALL ON MOODLE_PEOPLE_SPEC TO PK_MSTIG2;
GRANT ALL ON MOODLE_PEOPLE_SPEC TO PK_MSTIG3;
GRANT ALL ON MOODLE_PEOPLE_SPEC TO PK_MSTIG4;
GRANT ALL ON MOODLE_PEOPLE_SPEC TO PK_MSTIGP1;
GRANT ALL ON MOODLE_PEOPLE_SPEC TO PK_MSTIGP2;
GRANT ALL ON MOODLE_PEOPLE_SPEC TO PK_MSTIG_1;
GRANT ALL ON MOODLE_PEOPLE_SPEC TO PK_MSTIG_2;
GRANT ALL ON MOODLE_PEOPLE_SPEC TO PK_MSTIG_3;
GRANT ALL ON MOODLE_PEOPLE_SPEC TO PK_MSTIG_4;
GRANT ALL ON MOODLE_PEOPLE_SPEC TO PK_MSTIG_P1;
GRANT ALL ON MOODLE_PEOPLE_SPEC TO PK_MSTIG_P2;
GRANT ALL ON MOODLE_PEOPLE_SPEC TO PK_MVS1;
GRANT ALL ON MOODLE_PEOPLE_SPEC TO PK_MVS4;
GRANT ALL ON MOODLE_PEOPLE_SPEC TO PK_MVSP1;
GRANT ALL ON MOODLE_PEOPLE_SPEC TO PK_MVSP2;
GRANT ALL ON MOODLE_PEOPLE_SPEC TO PK_MVS_1;
GRANT ALL ON MOODLE_PEOPLE_SPEC TO PK_MVS_2;
GRANT ALL ON MOODLE_PEOPLE_SPEC TO PK_MVS_3;
GRANT ALL ON MOODLE_PEOPLE_SPEC TO PK_MVS_4;
GRANT ALL ON MOODLE_PEOPLE_SPEC TO PK_MVS_P1;
GRANT ALL ON MOODLE_PEOPLE_SPEC TO PK_MVS_P2;
GRANT ALL ON MOODLE_PEOPLE_SPEC TO PK_OFKITP1;
GRANT ALL ON MOODLE_PEOPLE_SPEC TO PK_OFKITP2;
GRANT ALL ON MOODLE_PEOPLE_SPEC TO PK_OFK_1;
GRANT ALL ON MOODLE_PEOPLE_SPEC TO PK_OFK_2;
GRANT ALL ON MOODLE_PEOPLE_SPEC TO PK_OFK_3;
GRANT ALL ON MOODLE_PEOPLE_SPEC TO PK_OFK_4;
GRANT ALL ON MOODLE_PEOPLE_SPEC TO PK_OFK_P1;
GRANT ALL ON MOODLE_PEOPLE_SPEC TO PK_OFK_P2;
GRANT ALL ON MOODLE_PEOPLE_SPEC TO PK_OTV1;
GRANT ALL ON MOODLE_PEOPLE_SPEC TO PK_OTV2;
GRANT ALL ON MOODLE_PEOPLE_SPEC TO PK_OTV3;
GRANT ALL ON MOODLE_PEOPLE_SPEC TO PK_OTV4;
GRANT ALL ON MOODLE_PEOPLE_SPEC TO PK_SIIEP1;
GRANT ALL ON MOODLE_PEOPLE_SPEC TO PK_SIIEP2;
GRANT ALL ON MOODLE_PEOPLE_SPEC TO PK_SIIE_1;
GRANT ALL ON MOODLE_PEOPLE_SPEC TO PK_SIIE_2;
GRANT ALL ON MOODLE_PEOPLE_SPEC TO PK_SIIE_3;
GRANT ALL ON MOODLE_PEOPLE_SPEC TO PK_SIIE_4;
GRANT ALL ON MOODLE_PEOPLE_SPEC TO PK_SIIE_P1;
GRANT ALL ON MOODLE_PEOPLE_SPEC TO PK_SIIE_P2;
GRANT ALL ON MOODLE_PEOPLE_SPEC TO PLANIDA_E;
GRANT ALL ON MOODLE_PEOPLE_SPEC TO SADIK;
GRANT ALL ON MOODLE_PEOPLE_SPEC TO SEL_COM;
GRANT ALL ON MOODLE_PEOPLE_SPEC TO SERAFIMOVICH_Y;
GRANT ALL ON MOODLE_PEOPLE_SPEC TO SETUN1998;
GRANT ALL ON MOODLE_PEOPLE_SPEC TO SHMAENKOVA_M;
GRANT ALL ON MOODLE_PEOPLE_SPEC TO SHPAKEVICH_P;
GRANT ALL ON MOODLE_PEOPLE_SPEC TO SMOLENKOVA_T;
GRANT ALL ON MOODLE_PEOPLE_SPEC TO SVETA;
GRANT ALL ON MOODLE_PEOPLE_SPEC TO VIEWER_MOB;
GRANT ALL ON MOODLE_PEOPLE_SPEC TO VNUK;
GRANT ALL ON MOODLE_PEOPLE_SPEC TO VOROBEI75;
GRANT ALL ON MOODLE_PEOPLE_SPEC TO YAUHENI_HATSURA;
GRANT ALL ON MOODLE_PEOPLE_SPEC TO ZHANNA_73;