/******************************************************************************/

/******************************************************************************/
/***      Following SET SQL DIALECT is just for the Database Comparer       ***/
/******************************************************************************/


/******************************************************************************/
/***                                 Views                                  ***/
/******************************************************************************/


/* View: PLAN_REAL_JOINT */
CREATE OR ALTER VIEW PLAN_REAL_JOINT(
    N_PLAN,
    SEMESTR,
    N_FAC,
    YEAR_PLAN,
    VID_EDU_PLAN,
    NAME_OBJECT)
AS
select edu_plan.n_plan, edu_plan.semestr, edu_plan.n_fac, edu_plan.year_plan, edu_plan.vid_edu_plan, object_plan.name_object
     from edu_plan, moodle, object_plan
     where (edu_plan.year_plan = moodle.edu_year or edu_plan.year_plan = moodle.edu_year-1)
     and edu_plan.n_object = object_plan.n_object
     and (not exists (select * from spec_plan where spec_plan.n_plan = edu_plan.n_plan))
;




/******************************************************************************/
/***                               Privileges                               ***/
/******************************************************************************/


/* Privileges of users */
GRANT ALL ON PLAN_REAL_JOINT TO ABITUR1;
GRANT ALL ON PLAN_REAL_JOINT TO ABITUR2;
GRANT ALL ON PLAN_REAL_JOINT TO ABITUR3;
GRANT ALL ON PLAN_REAL_JOINT TO ABITUR4;
GRANT ALL ON PLAN_REAL_JOINT TO ALENA_2109;
GRANT ALL ON PLAN_REAL_JOINT TO ALEXANDER_GONCHAROV;
GRANT ALL ON PLAN_REAL_JOINT TO ALINA_E;
GRANT ALL ON PLAN_REAL_JOINT TO ANNA;
GRANT ALL ON PLAN_REAL_JOINT TO ASPA;
GRANT ALL ON PLAN_REAL_JOINT TO ASPIRANTURA;
GRANT ALL ON PLAN_REAL_JOINT TO BAKS16;
GRANT ALL ON PLAN_REAL_JOINT TO BAKS68878;
GRANT ALL ON PLAN_REAL_JOINT TO BOBROVICH_O;
GRANT ALL ON PLAN_REAL_JOINT TO DEVELOPER;
GRANT ALL ON PLAN_REAL_JOINT TO DOBROVOLSKAYA;
GRANT ALL ON PLAN_REAL_JOINT TO DVORETSKAYA_K;
GRANT ALL ON PLAN_REAL_JOINT TO GONCHAROV434_2;
GRANT ALL ON PLAN_REAL_JOINT TO GUNICH_O;
GRANT ALL ON PLAN_REAL_JOINT TO GUNICH_OKSANA;
GRANT ALL ON PLAN_REAL_JOINT TO HOSTEL_PK1;
GRANT ALL ON PLAN_REAL_JOINT TO HOSTEL_PK2;
GRANT ALL ON PLAN_REAL_JOINT TO IMSIT_Z;
GRANT ALL ON PLAN_REAL_JOINT TO IRONSKULL;
GRANT ALL ON PLAN_REAL_JOINT TO IT5;
GRANT ALL ON PLAN_REAL_JOINT TO IT8;
GRANT ALL ON PLAN_REAL_JOINT TO IT_8;
GRANT ALL ON PLAN_REAL_JOINT TO IVANOVA_A;
GRANT ALL ON PLAN_REAL_JOINT TO JKMUF2507;
GRANT ALL ON PLAN_REAL_JOINT TO KANDRUKEVICH_M;
GRANT ALL ON PLAN_REAL_JOINT TO KAND_M;
GRANT ALL ON PLAN_REAL_JOINT TO KOSIK_N;
GRANT ALL ON PLAN_REAL_JOINT TO KRISTINA;
GRANT ALL ON PLAN_REAL_JOINT TO LAVRENOVA_V;
GRANT ALL ON PLAN_REAL_JOINT TO LENAUSOVA;
GRANT ALL ON PLAN_REAL_JOINT TO LIASHKOVICH_I;
GRANT ALL ON PLAN_REAL_JOINT TO LTRFYFN2019;
GRANT ALL ON PLAN_REAL_JOINT TO MAGISTR;
GRANT ALL ON PLAN_REAL_JOINT TO MARINA;
GRANT ALL ON PLAN_REAL_JOINT TO MATUSEVICH;
GRANT ALL ON PLAN_REAL_JOINT TO M_2;
GRANT ALL ON PLAN_REAL_JOINT TO OKSANA;
GRANT ALL ON PLAN_REAL_JOINT TO OK_STUD_2;
GRANT ALL ON PLAN_REAL_JOINT TO PK_MSTIG1;
GRANT ALL ON PLAN_REAL_JOINT TO PK_MSTIG2;
GRANT ALL ON PLAN_REAL_JOINT TO PK_MSTIG3;
GRANT ALL ON PLAN_REAL_JOINT TO PK_MSTIG4;
GRANT ALL ON PLAN_REAL_JOINT TO PK_MSTIGP1;
GRANT ALL ON PLAN_REAL_JOINT TO PK_MSTIGP2;
GRANT ALL ON PLAN_REAL_JOINT TO PK_MSTIG_1;
GRANT ALL ON PLAN_REAL_JOINT TO PK_MSTIG_2;
GRANT ALL ON PLAN_REAL_JOINT TO PK_MSTIG_3;
GRANT ALL ON PLAN_REAL_JOINT TO PK_MSTIG_4;
GRANT ALL ON PLAN_REAL_JOINT TO PK_MSTIG_P1;
GRANT ALL ON PLAN_REAL_JOINT TO PK_MSTIG_P2;
GRANT ALL ON PLAN_REAL_JOINT TO PK_MVS1;
GRANT ALL ON PLAN_REAL_JOINT TO PK_MVS4;
GRANT ALL ON PLAN_REAL_JOINT TO PK_MVSP1;
GRANT ALL ON PLAN_REAL_JOINT TO PK_MVSP2;
GRANT ALL ON PLAN_REAL_JOINT TO PK_MVS_1;
GRANT ALL ON PLAN_REAL_JOINT TO PK_MVS_2;
GRANT ALL ON PLAN_REAL_JOINT TO PK_MVS_3;
GRANT ALL ON PLAN_REAL_JOINT TO PK_MVS_4;
GRANT ALL ON PLAN_REAL_JOINT TO PK_MVS_P1;
GRANT ALL ON PLAN_REAL_JOINT TO PK_MVS_P2;
GRANT ALL ON PLAN_REAL_JOINT TO PK_OFKITP1;
GRANT ALL ON PLAN_REAL_JOINT TO PK_OFKITP2;
GRANT ALL ON PLAN_REAL_JOINT TO PK_OFK_1;
GRANT ALL ON PLAN_REAL_JOINT TO PK_OFK_2;
GRANT ALL ON PLAN_REAL_JOINT TO PK_OFK_3;
GRANT ALL ON PLAN_REAL_JOINT TO PK_OFK_4;
GRANT ALL ON PLAN_REAL_JOINT TO PK_OFK_P1;
GRANT ALL ON PLAN_REAL_JOINT TO PK_OFK_P2;
GRANT ALL ON PLAN_REAL_JOINT TO PK_OTV1;
GRANT ALL ON PLAN_REAL_JOINT TO PK_OTV2;
GRANT ALL ON PLAN_REAL_JOINT TO PK_OTV3;
GRANT ALL ON PLAN_REAL_JOINT TO PK_OTV4;
GRANT ALL ON PLAN_REAL_JOINT TO PK_SIIEP1;
GRANT ALL ON PLAN_REAL_JOINT TO PK_SIIEP2;
GRANT ALL ON PLAN_REAL_JOINT TO PK_SIIE_1;
GRANT ALL ON PLAN_REAL_JOINT TO PK_SIIE_2;
GRANT ALL ON PLAN_REAL_JOINT TO PK_SIIE_3;
GRANT ALL ON PLAN_REAL_JOINT TO PK_SIIE_4;
GRANT ALL ON PLAN_REAL_JOINT TO PK_SIIE_P1;
GRANT ALL ON PLAN_REAL_JOINT TO PK_SIIE_P2;
GRANT ALL ON PLAN_REAL_JOINT TO PLANIDA_E;
GRANT ALL ON PLAN_REAL_JOINT TO SADIK;
GRANT ALL ON PLAN_REAL_JOINT TO SEL_COM;
GRANT ALL ON PLAN_REAL_JOINT TO SERAFIMOVICH_Y;
GRANT ALL ON PLAN_REAL_JOINT TO SETUN1998;
GRANT ALL ON PLAN_REAL_JOINT TO SHMAENKOVA_M;
GRANT ALL ON PLAN_REAL_JOINT TO SHPAKEVICH_P;
GRANT ALL ON PLAN_REAL_JOINT TO SMOLENKOVA_T;
GRANT ALL ON PLAN_REAL_JOINT TO SVETA;
GRANT ALL ON PLAN_REAL_JOINT TO VIEWER_MOB;
GRANT ALL ON PLAN_REAL_JOINT TO VNUK;
GRANT ALL ON PLAN_REAL_JOINT TO VOROBEI75;
GRANT ALL ON PLAN_REAL_JOINT TO YAUHENI_HATSURA;
GRANT ALL ON PLAN_REAL_JOINT TO ZHANNA_73;