/******************************************************************************/

/******************************************************************************/
/***      Following SET SQL DIALECT is just for the Database Comparer       ***/
/******************************************************************************/


/******************************************************************************/
/***                                 Views                                  ***/
/******************************************************************************/


/* View: PLAN_REAL */
CREATE OR ALTER VIEW PLAN_REAL(
    N_PLAN,
    SEMESTR,
    N_FAC,
    YEAR_PLAN,
    VID_EDU_PLAN,
    NAME_OBJECT)
AS
SELECT
    edu_plan.n_plan,
    edu_plan.semestr,
    edu_plan.n_fac,
    edu_plan.year_plan,
    edu_plan.vid_edu_plan,
    object_plan.name_object
FROM
    edu_plan,
    moodle,
    object_plan
WHERE
(
        edu_plan.year_plan = moodle.edu_year
    OR
        edu_plan.year_plan = moodle.edu_year - 1
)
AND
    edu_plan.n_object = object_plan.n_object
;




/******************************************************************************/
/***                               Privileges                               ***/
/******************************************************************************/


/* Privileges of users */
GRANT ALL ON PLAN_REAL TO ABITUR1;
GRANT ALL ON PLAN_REAL TO ABITUR2;
GRANT ALL ON PLAN_REAL TO ABITUR3;
GRANT ALL ON PLAN_REAL TO ABITUR4;
GRANT ALL ON PLAN_REAL TO ALENA_2109;
GRANT ALL ON PLAN_REAL TO ALEXANDER_GONCHAROV;
GRANT ALL ON PLAN_REAL TO ALINA_E;
GRANT ALL ON PLAN_REAL TO ANNA;
GRANT ALL ON PLAN_REAL TO ASPA;
GRANT ALL ON PLAN_REAL TO ASPIRANTURA;
GRANT ALL ON PLAN_REAL TO BAKS16;
GRANT ALL ON PLAN_REAL TO BAKS68878;
GRANT ALL ON PLAN_REAL TO BOBROVICH_O;
GRANT ALL ON PLAN_REAL TO DEVELOPER;
GRANT ALL ON PLAN_REAL TO DOBROVOLSKAYA;
GRANT ALL ON PLAN_REAL TO DVORETSKAYA_K;
GRANT ALL ON PLAN_REAL TO GONCHAROV434_2;
GRANT ALL ON PLAN_REAL TO GUNICH_O;
GRANT ALL ON PLAN_REAL TO GUNICH_OKSANA;
GRANT ALL ON PLAN_REAL TO HOSTEL_PK1;
GRANT ALL ON PLAN_REAL TO HOSTEL_PK2;
GRANT ALL ON PLAN_REAL TO IMSIT_Z;
GRANT ALL ON PLAN_REAL TO IRONSKULL;
GRANT ALL ON PLAN_REAL TO IT5;
GRANT ALL ON PLAN_REAL TO IT8;
GRANT ALL ON PLAN_REAL TO IT_8;
GRANT ALL ON PLAN_REAL TO IVANOVA_A;
GRANT ALL ON PLAN_REAL TO JKMUF2507;
GRANT ALL ON PLAN_REAL TO KANDRUKEVICH_M;
GRANT ALL ON PLAN_REAL TO KAND_M;
GRANT ALL ON PLAN_REAL TO KOSIK_N;
GRANT ALL ON PLAN_REAL TO KRISTINA;
GRANT ALL ON PLAN_REAL TO LAVRENOVA_V;
GRANT ALL ON PLAN_REAL TO LENAUSOVA;
GRANT ALL ON PLAN_REAL TO LIASHKOVICH_I;
GRANT ALL ON PLAN_REAL TO LTRFYFN2019;
GRANT ALL ON PLAN_REAL TO MAGISTR;
GRANT ALL ON PLAN_REAL TO MARINA;
GRANT ALL ON PLAN_REAL TO MATUSEVICH;
GRANT ALL ON PLAN_REAL TO M_2;
GRANT ALL ON PLAN_REAL TO OKSANA;
GRANT ALL ON PLAN_REAL TO OK_STUD_2;
GRANT ALL ON PLAN_REAL TO PK_MSTIG1;
GRANT ALL ON PLAN_REAL TO PK_MSTIG2;
GRANT ALL ON PLAN_REAL TO PK_MSTIG3;
GRANT ALL ON PLAN_REAL TO PK_MSTIG4;
GRANT ALL ON PLAN_REAL TO PK_MSTIGP1;
GRANT ALL ON PLAN_REAL TO PK_MSTIGP2;
GRANT ALL ON PLAN_REAL TO PK_MSTIG_1;
GRANT ALL ON PLAN_REAL TO PK_MSTIG_2;
GRANT ALL ON PLAN_REAL TO PK_MSTIG_3;
GRANT ALL ON PLAN_REAL TO PK_MSTIG_4;
GRANT ALL ON PLAN_REAL TO PK_MSTIG_P1;
GRANT ALL ON PLAN_REAL TO PK_MSTIG_P2;
GRANT ALL ON PLAN_REAL TO PK_MVS1;
GRANT ALL ON PLAN_REAL TO PK_MVS4;
GRANT ALL ON PLAN_REAL TO PK_MVSP1;
GRANT ALL ON PLAN_REAL TO PK_MVSP2;
GRANT ALL ON PLAN_REAL TO PK_MVS_1;
GRANT ALL ON PLAN_REAL TO PK_MVS_2;
GRANT ALL ON PLAN_REAL TO PK_MVS_3;
GRANT ALL ON PLAN_REAL TO PK_MVS_4;
GRANT ALL ON PLAN_REAL TO PK_MVS_P1;
GRANT ALL ON PLAN_REAL TO PK_MVS_P2;
GRANT ALL ON PLAN_REAL TO PK_OFKITP1;
GRANT ALL ON PLAN_REAL TO PK_OFKITP2;
GRANT ALL ON PLAN_REAL TO PK_OFK_1;
GRANT ALL ON PLAN_REAL TO PK_OFK_2;
GRANT ALL ON PLAN_REAL TO PK_OFK_3;
GRANT ALL ON PLAN_REAL TO PK_OFK_4;
GRANT ALL ON PLAN_REAL TO PK_OFK_P1;
GRANT ALL ON PLAN_REAL TO PK_OFK_P2;
GRANT ALL ON PLAN_REAL TO PK_OTV1;
GRANT ALL ON PLAN_REAL TO PK_OTV2;
GRANT ALL ON PLAN_REAL TO PK_OTV3;
GRANT ALL ON PLAN_REAL TO PK_OTV4;
GRANT ALL ON PLAN_REAL TO PK_SIIEP1;
GRANT ALL ON PLAN_REAL TO PK_SIIEP2;
GRANT ALL ON PLAN_REAL TO PK_SIIE_1;
GRANT ALL ON PLAN_REAL TO PK_SIIE_2;
GRANT ALL ON PLAN_REAL TO PK_SIIE_3;
GRANT ALL ON PLAN_REAL TO PK_SIIE_4;
GRANT ALL ON PLAN_REAL TO PK_SIIE_P1;
GRANT ALL ON PLAN_REAL TO PK_SIIE_P2;
GRANT ALL ON PLAN_REAL TO PLANIDA_E;
GRANT ALL ON PLAN_REAL TO SADIK;
GRANT ALL ON PLAN_REAL TO SEL_COM;
GRANT ALL ON PLAN_REAL TO SERAFIMOVICH_Y;
GRANT ALL ON PLAN_REAL TO SETUN1998;
GRANT ALL ON PLAN_REAL TO SHMAENKOVA_M;
GRANT ALL ON PLAN_REAL TO SHPAKEVICH_P;
GRANT ALL ON PLAN_REAL TO SMOLENKOVA_T;
GRANT ALL ON PLAN_REAL TO SVETA;
GRANT ALL ON PLAN_REAL TO VIEWER_MOB;
GRANT ALL ON PLAN_REAL TO VNUK;
GRANT ALL ON PLAN_REAL TO VOROBEI75;
GRANT ALL ON PLAN_REAL TO YAUHENI_HATSURA;
GRANT ALL ON PLAN_REAL TO ZHANNA_73;

/* Privileges of views */
GRANT SELECT ON EDU_PLAN TO VIEW PLAN_REAL;
GRANT SELECT ON MOODLE TO VIEW PLAN_REAL;
GRANT SELECT ON OBJECT_PLAN TO VIEW PLAN_REAL;