/******************************************************************************/

/******************************************************************************/
/***      Following SET SQL DIALECT is just for the Database Comparer       ***/
/******************************************************************************/


/******************************************************************************/
/***                                 Views                                  ***/
/******************************************************************************/


/* View: STUDENT_RESTORE */
CREATE OR ALTER VIEW STUDENT_RESTORE(
    NOMER,
    D_PRIKAZ_RES)
AS
select a.nomer, max(a.d_prikaz_res) from restore a
where a.d_prikaz_res < "01.04.2018"
group by a.nomer
;




/******************************************************************************/
/***                               Privileges                               ***/
/******************************************************************************/


/* Privileges of users */
GRANT ALL ON STUDENT_RESTORE TO ALENA_2109;
GRANT ALL ON STUDENT_RESTORE TO ALEXANDER_GONCHAROV;
GRANT ALL ON STUDENT_RESTORE TO ALINA_E;
GRANT ALL ON STUDENT_RESTORE TO ASPIRANTURA;
GRANT ALL ON STUDENT_RESTORE TO DOBROVOLSKAYA;
GRANT ALL ON STUDENT_RESTORE TO DVORETSKAYA_K;
GRANT ALL ON STUDENT_RESTORE TO GONCHAROV434_2;
GRANT ALL ON STUDENT_RESTORE TO GUNICH_O;
GRANT ALL ON STUDENT_RESTORE TO HOSTEL_PK1;
GRANT ALL ON STUDENT_RESTORE TO HOSTEL_PK2;
GRANT ALL ON STUDENT_RESTORE TO IMSIT_Z;
GRANT ALL ON STUDENT_RESTORE TO IVANOVA_A;
GRANT ALL ON STUDENT_RESTORE TO KANDRUKEVICH_M;
GRANT ALL ON STUDENT_RESTORE TO KAND_M;
GRANT ALL ON STUDENT_RESTORE TO KOSIK_N;
GRANT ALL ON STUDENT_RESTORE TO KRISTINA;
GRANT ALL ON STUDENT_RESTORE TO LIASHKOVICH_I;
GRANT ALL ON STUDENT_RESTORE TO LTRFYFN2019;
GRANT ALL ON STUDENT_RESTORE TO MAGISTR;
GRANT ALL ON STUDENT_RESTORE TO MARINA;
GRANT ALL ON STUDENT_RESTORE TO MATUSEVICH;
GRANT ALL ON STUDENT_RESTORE TO OKSANA;
GRANT ALL ON STUDENT_RESTORE TO OK_STUD_2;
GRANT ALL ON STUDENT_RESTORE TO PK_MSTIG1;
GRANT ALL ON STUDENT_RESTORE TO PK_MSTIG_1;
GRANT ALL ON STUDENT_RESTORE TO PK_MSTIG_2;
GRANT ALL ON STUDENT_RESTORE TO PK_MSTIG_3;
GRANT ALL ON STUDENT_RESTORE TO PK_MSTIG_4;
GRANT ALL ON STUDENT_RESTORE TO PK_MSTIG_P1;
GRANT ALL ON STUDENT_RESTORE TO PK_MSTIG_P2;
GRANT ALL ON STUDENT_RESTORE TO PK_MVS1;
GRANT ALL ON STUDENT_RESTORE TO PK_MVS4;
GRANT ALL ON STUDENT_RESTORE TO PK_MVS_1;
GRANT ALL ON STUDENT_RESTORE TO PK_MVS_2;
GRANT ALL ON STUDENT_RESTORE TO PK_MVS_3;
GRANT ALL ON STUDENT_RESTORE TO PK_MVS_4;
GRANT ALL ON STUDENT_RESTORE TO PK_MVS_P1;
GRANT ALL ON STUDENT_RESTORE TO PK_MVS_P2;
GRANT ALL ON STUDENT_RESTORE TO PK_OFK_1;
GRANT ALL ON STUDENT_RESTORE TO PK_OFK_2;
GRANT ALL ON STUDENT_RESTORE TO PK_OFK_3;
GRANT ALL ON STUDENT_RESTORE TO PK_OFK_4;
GRANT ALL ON STUDENT_RESTORE TO PK_OFK_P1;
GRANT ALL ON STUDENT_RESTORE TO PK_OFK_P2;
GRANT ALL ON STUDENT_RESTORE TO PK_OTV1;
GRANT ALL ON STUDENT_RESTORE TO PK_OTV2;
GRANT ALL ON STUDENT_RESTORE TO PK_OTV3;
GRANT ALL ON STUDENT_RESTORE TO PK_OTV4;
GRANT ALL ON STUDENT_RESTORE TO PK_SIIE_1;
GRANT ALL ON STUDENT_RESTORE TO PK_SIIE_2;
GRANT ALL ON STUDENT_RESTORE TO PK_SIIE_3;
GRANT ALL ON STUDENT_RESTORE TO PK_SIIE_4;
GRANT ALL ON STUDENT_RESTORE TO PK_SIIE_P1;
GRANT ALL ON STUDENT_RESTORE TO PK_SIIE_P2;
GRANT ALL ON STUDENT_RESTORE TO SADIK;
GRANT ALL ON STUDENT_RESTORE TO SEL_COM;
GRANT ALL ON STUDENT_RESTORE TO SETUN1998;
GRANT ALL ON STUDENT_RESTORE TO SHPAKEVICH_P;
GRANT ALL ON STUDENT_RESTORE TO SMOLENKOVA_T;
GRANT ALL ON STUDENT_RESTORE TO ZHANNA_73;