/******************************************************************************/

/******************************************************************************/
/***      Following SET SQL DIALECT is just for the Database Comparer       ***/
/******************************************************************************/


/******************************************************************************/
/***                                 Views                                  ***/
/******************************************************************************/


/* View: VYPDIP */
CREATE OR ALTER VIEW VYPDIP(
    PERSONAL_NOMER,
    NOMER)
AS
select vypuskniki.l, diploma.nomer from vypuskniki v, diploma d
where vypuskniki.k = diploma.nom_diplom
;




/******************************************************************************/
/***                               Privileges                               ***/
/******************************************************************************/


/* Privileges of users */
GRANT ALL ON VYPDIP TO ABITUR1;
GRANT ALL ON VYPDIP TO ABITUR2;
GRANT ALL ON VYPDIP TO ABITUR3;
GRANT ALL ON VYPDIP TO ABITUR4;
GRANT ALL ON VYPDIP TO ALENA_2109;
GRANT ALL ON VYPDIP TO ALEXANDER_GONCHAROV;
GRANT ALL ON VYPDIP TO ALINA_E;
GRANT ALL ON VYPDIP TO ANNA;
GRANT ALL ON VYPDIP TO ASPA;
GRANT ALL ON VYPDIP TO ASPIRANTURA;
GRANT ALL ON VYPDIP TO BAKS16;
GRANT ALL ON VYPDIP TO BAKS68878;
GRANT ALL ON VYPDIP TO BOBROVICH_O;
GRANT ALL ON VYPDIP TO DEVELOPER;
GRANT ALL ON VYPDIP TO DOBROVOLSKAYA;
GRANT ALL ON VYPDIP TO DVORETSKAYA_K;
GRANT ALL ON VYPDIP TO GONCHAROV434_2;
GRANT ALL ON VYPDIP TO GUNICH_O;
GRANT ALL ON VYPDIP TO GUNICH_OKSANA;
GRANT ALL ON VYPDIP TO HOSTEL_PK1;
GRANT ALL ON VYPDIP TO HOSTEL_PK2;
GRANT ALL ON VYPDIP TO IMSIT_Z;
GRANT ALL ON VYPDIP TO IT8;
GRANT ALL ON VYPDIP TO IT_8;
GRANT ALL ON VYPDIP TO IVANOVA_A;
GRANT ALL ON VYPDIP TO JKMUF2507;
GRANT ALL ON VYPDIP TO KANDRUKEVICH_M;
GRANT ALL ON VYPDIP TO KAND_M;
GRANT ALL ON VYPDIP TO KOSIK_N;
GRANT ALL ON VYPDIP TO KRISTINA;
GRANT ALL ON VYPDIP TO LAVRENOVA_V;
GRANT ALL ON VYPDIP TO LENAUSOVA;
GRANT ALL ON VYPDIP TO LIASHKOVICH_I;
GRANT ALL ON VYPDIP TO LTRFYFN2019;
GRANT ALL ON VYPDIP TO MAGISTR;
GRANT ALL ON VYPDIP TO MARINA;
GRANT ALL ON VYPDIP TO MATUSEVICH;
GRANT ALL ON VYPDIP TO M_2;
GRANT ALL ON VYPDIP TO OKSANA;
GRANT ALL ON VYPDIP TO OK_STUD_2;
GRANT ALL ON VYPDIP TO PK_MSTIG1;
GRANT ALL ON VYPDIP TO PK_MSTIG2;
GRANT ALL ON VYPDIP TO PK_MSTIG3;
GRANT ALL ON VYPDIP TO PK_MSTIG4;
GRANT ALL ON VYPDIP TO PK_MSTIGP1;
GRANT ALL ON VYPDIP TO PK_MSTIGP2;
GRANT ALL ON VYPDIP TO PK_MSTIG_1;
GRANT ALL ON VYPDIP TO PK_MSTIG_2;
GRANT ALL ON VYPDIP TO PK_MSTIG_3;
GRANT ALL ON VYPDIP TO PK_MSTIG_4;
GRANT ALL ON VYPDIP TO PK_MSTIG_P1;
GRANT ALL ON VYPDIP TO PK_MSTIG_P2;
GRANT ALL ON VYPDIP TO PK_MVS1;
GRANT ALL ON VYPDIP TO PK_MVS4;
GRANT ALL ON VYPDIP TO PK_MVSP1;
GRANT ALL ON VYPDIP TO PK_MVSP2;
GRANT ALL ON VYPDIP TO PK_MVS_1;
GRANT ALL ON VYPDIP TO PK_MVS_2;
GRANT ALL ON VYPDIP TO PK_MVS_3;
GRANT ALL ON VYPDIP TO PK_MVS_4;
GRANT ALL ON VYPDIP TO PK_MVS_P1;
GRANT ALL ON VYPDIP TO PK_MVS_P2;
GRANT ALL ON VYPDIP TO PK_OFKITP1;
GRANT ALL ON VYPDIP TO PK_OFKITP2;
GRANT ALL ON VYPDIP TO PK_OFK_1;
GRANT ALL ON VYPDIP TO PK_OFK_2;
GRANT ALL ON VYPDIP TO PK_OFK_3;
GRANT ALL ON VYPDIP TO PK_OFK_4;
GRANT ALL ON VYPDIP TO PK_OFK_P1;
GRANT ALL ON VYPDIP TO PK_OFK_P2;
GRANT ALL ON VYPDIP TO PK_OTV1;
GRANT ALL ON VYPDIP TO PK_OTV2;
GRANT ALL ON VYPDIP TO PK_OTV3;
GRANT ALL ON VYPDIP TO PK_OTV4;
GRANT ALL ON VYPDIP TO PK_SIIEP1;
GRANT ALL ON VYPDIP TO PK_SIIEP2;
GRANT ALL ON VYPDIP TO PK_SIIE_1;
GRANT ALL ON VYPDIP TO PK_SIIE_2;
GRANT ALL ON VYPDIP TO PK_SIIE_3;
GRANT ALL ON VYPDIP TO PK_SIIE_4;
GRANT ALL ON VYPDIP TO PK_SIIE_P1;
GRANT ALL ON VYPDIP TO PK_SIIE_P2;
GRANT ALL ON VYPDIP TO PLANIDA_E;
GRANT ALL ON VYPDIP TO SADIK;
GRANT ALL ON VYPDIP TO SEL_COM;
GRANT ALL ON VYPDIP TO SERAFIMOVICH_Y;
GRANT ALL ON VYPDIP TO SETUN1998;
GRANT ALL ON VYPDIP TO SHMAENKOVA_M;
GRANT ALL ON VYPDIP TO SHPAKEVICH_P;
GRANT ALL ON VYPDIP TO SMOLENKOVA_T;
GRANT ALL ON VYPDIP TO SVETA;
GRANT ALL ON VYPDIP TO VIEWER_MOB;
GRANT ALL ON VYPDIP TO VNUK;
GRANT ALL ON VYPDIP TO VOROBEI75;
GRANT ALL ON VYPDIP TO YAUHENI_HATSURA;
GRANT ALL ON VYPDIP TO ZHANNA_73;