/******************************************************************************/
/***          Generated by IBExpert 2018.3.1.1 08.04.2022 8:24:15           ***/
/******************************************************************************/

SET NAMES WIN1251;

SET CLIENTLIB 'D:\DbFireBird\fbclient.dll';

CREATE DATABASE
    '172.16.1.30:abiturient'
    USER
        'SYSDBA'
    PASSWORD
        'dbudfV544703'
    PAGE_SIZE
        4096
DEFAULT CHARACTER SET WIN1251 COLLATION WIN1251;
