/* View: NEW_VIEW */
CREATE OR ALTER
    VIEW
        NEW_VIEW
        (
            NOMER_AB,
            BALL,
            SUM_BALL,
            MIDDLE_BALL
        )
AS
    SELECT
        Abitura.NOMER_AB,
        SUM( Examen.BALL ),
        Abitura.SUM_BALL,
        abitura.middle_ball
    FROM
        ABITURA Abitura
    INNER JOIN
        EXAMEN Examen
        ON
            (Abitura.NOMER_AB = Examen.NOMER_AB)  
        WHERE
            (Abitura.NOMER_AB = 3)
            -- (Abitura.n_fac =:N_FAC)
            -- Abitura.sum_ball <>  SUM( Examen.BALL ) + abitura.middle_ball
            -- and  Abitura.sum_ball <>  SUM( Examen.BALL)
        GROUP BY
            Abitura.NOMER_AB,
            Abitura.SUM_BALL,
            abitura.middle_ball
;




/******************************************************************************/
/***                               Privileges                               ***/
/******************************************************************************/


/* Privileges of users */
GRANT ALL ON NEW_VIEW TO ABITUR1;
GRANT ALL ON NEW_VIEW TO ABITUR2;
GRANT ALL ON NEW_VIEW TO ABITUR3;
GRANT ALL ON NEW_VIEW TO ABITUR4;
GRANT ALL ON NEW_VIEW TO ABITURA;
GRANT ALL ON NEW_VIEW TO ALEXANDER_GONCHAROV;
GRANT ALL ON NEW_VIEW TO IVANOVA_A;
GRANT ALL ON NEW_VIEW TO OKSANA;
GRANT ALL ON NEW_VIEW TO PK_MSTIG1;
GRANT ALL ON NEW_VIEW TO PK_MSTIG2;
GRANT ALL ON NEW_VIEW TO PK_MSTIG3;
GRANT ALL ON NEW_VIEW TO PK_MSTIG4;
GRANT ALL ON NEW_VIEW TO PK_MSTIGP1;
GRANT ALL ON NEW_VIEW TO PK_MSTIGP2;
GRANT ALL ON NEW_VIEW TO PK_MSTIG_1;
GRANT ALL ON NEW_VIEW TO PK_MSTIG_2;
GRANT ALL ON NEW_VIEW TO PK_MSTIG_3;
GRANT ALL ON NEW_VIEW TO PK_MSTIG_4;
GRANT ALL ON NEW_VIEW TO PK_MSTIG_P1;
GRANT ALL ON NEW_VIEW TO PK_MSTIG_P2;
GRANT ALL ON NEW_VIEW TO PK_MVSP1;
GRANT ALL ON NEW_VIEW TO PK_MVSP2;
GRANT ALL ON NEW_VIEW TO PK_MVS_1;
GRANT ALL ON NEW_VIEW TO PK_MVS_2;
GRANT ALL ON NEW_VIEW TO PK_MVS_3;
GRANT ALL ON NEW_VIEW TO PK_MVS_4;
GRANT ALL ON NEW_VIEW TO PK_MVS_P1;
GRANT ALL ON NEW_VIEW TO PK_MVS_P2;
GRANT ALL ON NEW_VIEW TO PK_OFKIT1;
GRANT ALL ON NEW_VIEW TO PK_OFKITP1;
GRANT ALL ON NEW_VIEW TO PK_OFKITP2;
GRANT ALL ON NEW_VIEW TO PK_OFK_1;
GRANT ALL ON NEW_VIEW TO PK_OFK_2;
GRANT ALL ON NEW_VIEW TO PK_OFK_3;
GRANT ALL ON NEW_VIEW TO PK_OFK_4;
GRANT ALL ON NEW_VIEW TO PK_OFK_P1;
GRANT ALL ON NEW_VIEW TO PK_OFK_P2;
GRANT ALL ON NEW_VIEW TO PK_OTV1;
GRANT ALL ON NEW_VIEW TO PK_OTV2;
GRANT ALL ON NEW_VIEW TO PK_OTV3;
GRANT ALL ON NEW_VIEW TO PK_OTV4;
GRANT ALL ON NEW_VIEW TO PK_SIIEP1;
GRANT ALL ON NEW_VIEW TO PK_SIIEP2;
GRANT ALL ON NEW_VIEW TO PK_SIIEP3;
GRANT ALL ON NEW_VIEW TO PK_SIIE_1;
GRANT ALL ON NEW_VIEW TO PK_SIIE_2;
GRANT ALL ON NEW_VIEW TO PK_SIIE_3;
GRANT ALL ON NEW_VIEW TO PK_SIIE_4;
GRANT ALL ON NEW_VIEW TO PK_SIIE_P1;
GRANT ALL ON NEW_VIEW TO PK_SIIE_P2;