/* View: SUMM_BALLS */
CREATE OR ALTER
    VIEW
        SUMM_BALLS
        (
            NOMER_AB,
            BALLS,
            MIDDLE
        )
AS
    SELECT
        sertificat.nomer_ab,
        sertificat.balls,
        abitura.middle_ball
    FROM
        sertificat,
        abitura
    WHERE
        sertificat.nomer_ab = abitura.nomer_ab
;




/******************************************************************************/
/***                               Privileges                               ***/
/******************************************************************************/


/* Privileges of users */
GRANT ALL ON SUMM_BALLS TO ABITUR1;
GRANT ALL ON SUMM_BALLS TO ABITUR2;
GRANT ALL ON SUMM_BALLS TO ABITUR3;
GRANT ALL ON SUMM_BALLS TO ABITUR4;
GRANT ALL ON SUMM_BALLS TO ABITURA;
GRANT ALL ON SUMM_BALLS TO ALEXANDER_GONCHAROV;
GRANT ALL ON SUMM_BALLS TO ASU;
GRANT ALL ON SUMM_BALLS TO ASU1;
GRANT ALL ON SUMM_BALLS TO ASU2;
GRANT ALL ON SUMM_BALLS TO ASU3;
GRANT ALL ON SUMM_BALLS TO ASU4;
GRANT ALL ON SUMM_BALLS TO DEVELOPER;
GRANT ALL ON SUMM_BALLS TO DEVELOPER WITH GRANT OPTION;
GRANT ALL ON SUMM_BALLS TO IVANOVA_A;
GRANT ALL ON SUMM_BALLS TO OKSANA;
GRANT ALL ON SUMM_BALLS TO PK;
GRANT ALL ON SUMM_BALLS TO PK_IT;
GRANT ALL ON SUMM_BALLS TO PK_IT1;
GRANT ALL ON SUMM_BALLS TO PK_IT2;
GRANT ALL ON SUMM_BALLS TO PK_IT3;
GRANT ALL ON SUMM_BALLS TO PK_IT4;
GRANT ALL ON SUMM_BALLS TO PK_IT5;
GRANT ALL ON SUMM_BALLS TO PK_MSTIG1;
GRANT ALL ON SUMM_BALLS TO PK_MSTIG2;
GRANT ALL ON SUMM_BALLS TO PK_MSTIG3;
GRANT ALL ON SUMM_BALLS TO PK_MSTIG4;
GRANT ALL ON SUMM_BALLS TO PK_MSTIGP1;
GRANT ALL ON SUMM_BALLS TO PK_MSTIGP2;
GRANT ALL ON SUMM_BALLS TO PK_MSTIG_1;
GRANT ALL ON SUMM_BALLS TO PK_MSTIG_2;
GRANT ALL ON SUMM_BALLS TO PK_MSTIG_3;
GRANT ALL ON SUMM_BALLS TO PK_MSTIG_4;
GRANT ALL ON SUMM_BALLS TO PK_MSTIG_P1;
GRANT ALL ON SUMM_BALLS TO PK_MSTIG_P2;
GRANT ALL ON SUMM_BALLS TO PK_MVS;
GRANT ALL ON SUMM_BALLS TO PK_MVS1;
GRANT ALL ON SUMM_BALLS TO PK_MVS2;
GRANT ALL ON SUMM_BALLS TO PK_MVS3;
GRANT ALL ON SUMM_BALLS TO PK_MVS4;
GRANT ALL ON SUMM_BALLS TO PK_MVS5;
GRANT ALL ON SUMM_BALLS TO PK_MVSP1;
GRANT ALL ON SUMM_BALLS TO PK_MVSP2;
GRANT ALL ON SUMM_BALLS TO PK_MVS_1;
GRANT ALL ON SUMM_BALLS TO PK_MVS_2;
GRANT ALL ON SUMM_BALLS TO PK_MVS_3;
GRANT ALL ON SUMM_BALLS TO PK_MVS_4;
GRANT ALL ON SUMM_BALLS TO PK_MVS_P1;
GRANT ALL ON SUMM_BALLS TO PK_MVS_P2;
GRANT ALL ON SUMM_BALLS TO PK_OFKIT;
GRANT ALL ON SUMM_BALLS TO PK_OFKIT1;
GRANT ALL ON SUMM_BALLS TO PK_OFKIT2;
GRANT ALL ON SUMM_BALLS TO PK_OFKIT3;
GRANT ALL ON SUMM_BALLS TO PK_OFKIT4;
GRANT ALL ON SUMM_BALLS TO PK_OFKIT5;
GRANT ALL ON SUMM_BALLS TO PK_OFKITP1;
GRANT ALL ON SUMM_BALLS TO PK_OFKITP2;
GRANT ALL ON SUMM_BALLS TO PK_OFK_1;
GRANT ALL ON SUMM_BALLS TO PK_OFK_2;
GRANT ALL ON SUMM_BALLS TO PK_OFK_3;
GRANT ALL ON SUMM_BALLS TO PK_OFK_4;
GRANT ALL ON SUMM_BALLS TO PK_OFK_P1;
GRANT ALL ON SUMM_BALLS TO PK_OFK_P2;
GRANT ALL ON SUMM_BALLS TO PK_OTV1;
GRANT ALL ON SUMM_BALLS TO PK_OTV2;
GRANT ALL ON SUMM_BALLS TO PK_OTV3;
GRANT ALL ON SUMM_BALLS TO PK_OTV4;
GRANT ALL ON SUMM_BALLS TO PK_SIIE;
GRANT ALL ON SUMM_BALLS TO PK_SIIE1;
GRANT ALL ON SUMM_BALLS TO PK_SIIE2;
GRANT ALL ON SUMM_BALLS TO PK_SIIE3;
GRANT ALL ON SUMM_BALLS TO PK_SIIE4;
GRANT ALL ON SUMM_BALLS TO PK_SIIE5;
GRANT ALL ON SUMM_BALLS TO PK_SIIEP1;
GRANT ALL ON SUMM_BALLS TO PK_SIIEP2;
GRANT ALL ON SUMM_BALLS TO PK_SIIEP3;
GRANT ALL ON SUMM_BALLS TO PK_SIIE_1;
GRANT ALL ON SUMM_BALLS TO PK_SIIE_2;
GRANT ALL ON SUMM_BALLS TO PK_SIIE_3;
GRANT ALL ON SUMM_BALLS TO PK_SIIE_4;
GRANT ALL ON SUMM_BALLS TO PK_SIIE_P1;
GRANT ALL ON SUMM_BALLS TO PK_SIIE_P2;