/* View: SUM_EXAM */
CREATE OR ALTER
    VIEW
        SUM_EXAM
        (
            NOMER_AB,
            SUM_BAL
        )
AS
    SELECT
        examen.nomer_ab,
        sum(examen.ball)
    FROM
        examen
    GROUP BY
        examen.nomer_ab
;




/******************************************************************************/
/***                               Privileges                               ***/
/******************************************************************************/


/* Privileges of users */
GRANT ALL ON SUM_EXAM TO ALEXANDER_GONCHAROV;
GRANT ALL ON SUM_EXAM TO IVANOVA_A;
GRANT ALL ON SUM_EXAM TO PK_MSTIG_1;
GRANT ALL ON SUM_EXAM TO PK_MSTIG_2;
GRANT ALL ON SUM_EXAM TO PK_MSTIG_3;
GRANT ALL ON SUM_EXAM TO PK_MSTIG_4;
GRANT ALL ON SUM_EXAM TO PK_MSTIG_P1;
GRANT ALL ON SUM_EXAM TO PK_MSTIG_P2;
GRANT ALL ON SUM_EXAM TO PK_MVS_1;
GRANT ALL ON SUM_EXAM TO PK_MVS_2;
GRANT ALL ON SUM_EXAM TO PK_MVS_3;
GRANT ALL ON SUM_EXAM TO PK_MVS_4;
GRANT ALL ON SUM_EXAM TO PK_MVS_P1;
GRANT ALL ON SUM_EXAM TO PK_MVS_P2;
GRANT ALL ON SUM_EXAM TO PK_OFK_1;
GRANT ALL ON SUM_EXAM TO PK_OFK_2;
GRANT ALL ON SUM_EXAM TO PK_OFK_3;
GRANT ALL ON SUM_EXAM TO PK_OFK_4;
GRANT ALL ON SUM_EXAM TO PK_OFK_P1;
GRANT ALL ON SUM_EXAM TO PK_OFK_P2;
GRANT ALL ON SUM_EXAM TO PK_OTV1;
GRANT ALL ON SUM_EXAM TO PK_OTV2;
GRANT ALL ON SUM_EXAM TO PK_OTV3;
GRANT ALL ON SUM_EXAM TO PK_OTV4;
GRANT ALL ON SUM_EXAM TO PK_SIIE_1;
GRANT ALL ON SUM_EXAM TO PK_SIIE_2;
GRANT ALL ON SUM_EXAM TO PK_SIIE_3;
GRANT ALL ON SUM_EXAM TO PK_SIIE_4;
GRANT ALL ON SUM_EXAM TO PK_SIIE_P1;
GRANT ALL ON SUM_EXAM TO PK_SIIE_P2;