/* View: SUMM_ERROR */
CREATE OR ALTER
    VIEW
        SUMM_ERROR
        (
            NOMER_AB,
            SUM_AB,
            SUM_SERT
        )
AS
    SELECT
        summa.nomer_ab,
        abitura.sum_ball,
        summa.summ_bal
    FROM
        summa,
        abitura
    WHERE
            summa.nomer_ab = abitura.nomer_ab
        AND
            summa.summ_bal <> abitura.sum_ball
;




/******************************************************************************/
/***                               Privileges                               ***/
/******************************************************************************/


/* Privileges of users */
GRANT ALL ON SUMM_ERROR TO ABITUR1;
GRANT ALL ON SUMM_ERROR TO ABITUR2;
GRANT ALL ON SUMM_ERROR TO ABITUR3;
GRANT ALL ON SUMM_ERROR TO ABITUR4;
GRANT ALL ON SUMM_ERROR TO ABITURA;
GRANT ALL ON SUMM_ERROR TO ALEXANDER_GONCHAROV;
GRANT ALL ON SUMM_ERROR TO ASU;
GRANT ALL ON SUMM_ERROR TO ASU1;
GRANT ALL ON SUMM_ERROR TO ASU2;
GRANT ALL ON SUMM_ERROR TO ASU3;
GRANT ALL ON SUMM_ERROR TO ASU4;
GRANT ALL ON SUMM_ERROR TO DEVELOPER;
GRANT ALL ON SUMM_ERROR TO DEVELOPER WITH GRANT OPTION;
GRANT ALL ON SUMM_ERROR TO IVANOVA_A;
GRANT ALL ON SUMM_ERROR TO OKSANA;
GRANT ALL ON SUMM_ERROR TO PK;
GRANT ALL ON SUMM_ERROR TO PK_IT;
GRANT ALL ON SUMM_ERROR TO PK_IT1;
GRANT ALL ON SUMM_ERROR TO PK_IT2;
GRANT ALL ON SUMM_ERROR TO PK_IT3;
GRANT ALL ON SUMM_ERROR TO PK_IT4;
GRANT ALL ON SUMM_ERROR TO PK_IT5;
GRANT ALL ON SUMM_ERROR TO PK_MSTIG1;
GRANT ALL ON SUMM_ERROR TO PK_MSTIG2;
GRANT ALL ON SUMM_ERROR TO PK_MSTIG3;
GRANT ALL ON SUMM_ERROR TO PK_MSTIG4;
GRANT ALL ON SUMM_ERROR TO PK_MSTIGP1;
GRANT ALL ON SUMM_ERROR TO PK_MSTIGP2;
GRANT ALL ON SUMM_ERROR TO PK_MSTIG_1;
GRANT ALL ON SUMM_ERROR TO PK_MSTIG_2;
GRANT ALL ON SUMM_ERROR TO PK_MSTIG_3;
GRANT ALL ON SUMM_ERROR TO PK_MSTIG_4;
GRANT ALL ON SUMM_ERROR TO PK_MSTIG_P1;
GRANT ALL ON SUMM_ERROR TO PK_MSTIG_P2;
GRANT ALL ON SUMM_ERROR TO PK_MVS;
GRANT ALL ON SUMM_ERROR TO PK_MVS1;
GRANT ALL ON SUMM_ERROR TO PK_MVS2;
GRANT ALL ON SUMM_ERROR TO PK_MVS3;
GRANT ALL ON SUMM_ERROR TO PK_MVS4;
GRANT ALL ON SUMM_ERROR TO PK_MVS5;
GRANT ALL ON SUMM_ERROR TO PK_MVSP1;
GRANT ALL ON SUMM_ERROR TO PK_MVSP2;
GRANT ALL ON SUMM_ERROR TO PK_MVS_1;
GRANT ALL ON SUMM_ERROR TO PK_MVS_2;
GRANT ALL ON SUMM_ERROR TO PK_MVS_3;
GRANT ALL ON SUMM_ERROR TO PK_MVS_4;
GRANT ALL ON SUMM_ERROR TO PK_MVS_P1;
GRANT ALL ON SUMM_ERROR TO PK_MVS_P2;
GRANT ALL ON SUMM_ERROR TO PK_OFKIT;
GRANT ALL ON SUMM_ERROR TO PK_OFKIT1;
GRANT ALL ON SUMM_ERROR TO PK_OFKIT2;
GRANT ALL ON SUMM_ERROR TO PK_OFKIT3;
GRANT ALL ON SUMM_ERROR TO PK_OFKIT4;
GRANT ALL ON SUMM_ERROR TO PK_OFKIT5;
GRANT ALL ON SUMM_ERROR TO PK_OFKITP1;
GRANT ALL ON SUMM_ERROR TO PK_OFKITP2;
GRANT ALL ON SUMM_ERROR TO PK_OFK_1;
GRANT ALL ON SUMM_ERROR TO PK_OFK_2;
GRANT ALL ON SUMM_ERROR TO PK_OFK_3;
GRANT ALL ON SUMM_ERROR TO PK_OFK_4;
GRANT ALL ON SUMM_ERROR TO PK_OFK_P1;
GRANT ALL ON SUMM_ERROR TO PK_OFK_P2;
GRANT ALL ON SUMM_ERROR TO PK_OTV1;
GRANT ALL ON SUMM_ERROR TO PK_OTV2;
GRANT ALL ON SUMM_ERROR TO PK_OTV3;
GRANT ALL ON SUMM_ERROR TO PK_OTV4;
GRANT ALL ON SUMM_ERROR TO PK_SIIE;
GRANT ALL ON SUMM_ERROR TO PK_SIIE1;
GRANT ALL ON SUMM_ERROR TO PK_SIIE2;
GRANT ALL ON SUMM_ERROR TO PK_SIIE3;
GRANT ALL ON SUMM_ERROR TO PK_SIIE4;
GRANT ALL ON SUMM_ERROR TO PK_SIIE5;
GRANT ALL ON SUMM_ERROR TO PK_SIIEP1;
GRANT ALL ON SUMM_ERROR TO PK_SIIEP2;
GRANT ALL ON SUMM_ERROR TO PK_SIIEP3;
GRANT ALL ON SUMM_ERROR TO PK_SIIE_1;
GRANT ALL ON SUMM_ERROR TO PK_SIIE_2;
GRANT ALL ON SUMM_ERROR TO PK_SIIE_3;
GRANT ALL ON SUMM_ERROR TO PK_SIIE_4;
GRANT ALL ON SUMM_ERROR TO PK_SIIE_P1;
GRANT ALL ON SUMM_ERROR TO PK_SIIE_P2;