CREATE GENERATOR
    GEN_ABITUR_LOGBOOK_ID;

CREATE TABLE IF NOT EXISTS
ABITUR_LOGBOOK
(
    ID_LOG          INTEGER,
    NOM_DELA        SMALLINT,
    NOMER_AB        INTEGER,
    DATE_IN         DATE,
    VID_EDU         SMALLINT,
    PRICE           SMALLINT,
    TERM_EDU        SMALLINT,
    ADDRESS_BEFORE  VARCHAR(100) COLLATE PXW_CYRL,
    N_CK            SMALLINT,
    DATE_OUT        DATE,
    N_SPECIALIZ     SMALLINT,
    N_FAC           SMALLINT,
    KONKURS         SMALLINT,
    CATEGORY        SMALLINT
);




/******************************************************************************/
/***                              Primary keys                              ***/
/******************************************************************************/

ALTER TABLE
    ABITUR_LOGBOOK
ADD
    CONSTRAINT
        PK_ABITUR_LOGBOOK
    PRIMARY KEY
        (ID_LOG);


/******************************************************************************/
/***                                Triggers                                ***/
/******************************************************************************/



SET TERM ^ ;



/******************************************************************************/
/***                          Triggers for tables                           ***/
/******************************************************************************/



/* Trigger: ABITUR_LOGBOOK_BI (Before INSERT) */
CREATE OR ALTER
    TRIGGER
        ABITUR_LOGBOOK_BI
FOR
    ABITUR_LOGBOOK
ACTIVE
    BEFORE INSERT
        POSITION 0
AS
BEGIN
    IF (NEW.ID_LOG IS NULL)
    THEN
        NEW.ID_LOG = GEN_ID(GEN_ABITUR_LOGBOOK_ID, 1);
END
^

SET TERM ; ^



/******************************************************************************/
/***                          Fields descriptions                           ***/
/******************************************************************************/

COMMENT ON COLUMN ABITUR_LOGBOOK.ID_LOG IS 
'Идентификатор записи';

COMMENT ON COLUMN ABITUR_LOGBOOK.NOM_DELA IS 
'Номер дела';

COMMENT ON COLUMN ABITUR_LOGBOOK.NOMER_AB IS 
'Номер абитуриента';

COMMENT ON COLUMN ABITUR_LOGBOOK.DATE_IN IS 
'Дата приёма документов';

COMMENT ON COLUMN ABITUR_LOGBOOK.VID_EDU IS 
'Форма обучения';

COMMENT ON COLUMN ABITUR_LOGBOOK.PRICE IS 
'Форма оплаты';

COMMENT ON COLUMN ABITUR_LOGBOOK.TERM_EDU IS 
'Полный (1 курс) / Cокращённый (2 и старше)';

COMMENT ON COLUMN ABITUR_LOGBOOK.ADDRESS_BEFORE IS 
'Адрес';

COMMENT ON COLUMN ABITUR_LOGBOOK.N_CK IS 
'№ района откуда ЦК (Целевой Контракт) (Связь с полем REGIONAL_CENTRE.N_CENTRE), -1 - нет';

COMMENT ON COLUMN ABITUR_LOGBOOK.DATE_OUT IS 
'Дата возврата документов';

COMMENT ON COLUMN ABITUR_LOGBOOK.N_SPECIALIZ IS 
'Направление специализации';

COMMENT ON COLUMN ABITUR_LOGBOOK.N_FAC IS 
'Факультет';

COMMENT ON COLUMN ABITUR_LOGBOOK.KONKURS IS 
'0 - общий
1 - без вступительных экзаменов
2 - вне конкурса
3 - целевой контракт';

COMMENT ON COLUMN ABITUR_LOGBOOK.CATEGORY IS 
'Связь с табл. CATEGORY';



/******************************************************************************/
/***                               Privileges                               ***/
/******************************************************************************/


/* Privileges of users */
GRANT ALL ON ABITUR_LOGBOOK TO ABITUR1;
GRANT ALL ON ABITUR_LOGBOOK TO ABITUR2;
GRANT ALL ON ABITUR_LOGBOOK TO ABITUR3;
GRANT ALL ON ABITUR_LOGBOOK TO ABITUR4;
GRANT ALL ON ABITUR_LOGBOOK TO ABITURA;
GRANT ALL ON ABITUR_LOGBOOK TO ALEXANDER_GONCHAROV;
GRANT ALL ON ABITUR_LOGBOOK TO ASU;
GRANT ALL ON ABITUR_LOGBOOK TO ASU1;
GRANT ALL ON ABITUR_LOGBOOK TO ASU2;
GRANT ALL ON ABITUR_LOGBOOK TO ASU3;
GRANT ALL ON ABITUR_LOGBOOK TO ASU4;
GRANT ALL ON ABITUR_LOGBOOK TO DEVELOPER;
GRANT ALL ON ABITUR_LOGBOOK TO IVANOVA_A;
GRANT ALL ON ABITUR_LOGBOOK TO OKSANA;
GRANT ALL ON ABITUR_LOGBOOK TO PK;
GRANT ALL ON ABITUR_LOGBOOK TO PK_IT;
GRANT ALL ON ABITUR_LOGBOOK TO PK_IT1;
GRANT ALL ON ABITUR_LOGBOOK TO PK_IT2;
GRANT ALL ON ABITUR_LOGBOOK TO PK_IT3;
GRANT ALL ON ABITUR_LOGBOOK TO PK_IT4;
GRANT ALL ON ABITUR_LOGBOOK TO PK_IT5;
GRANT ALL ON ABITUR_LOGBOOK TO PK_MSTIG1;
GRANT ALL ON ABITUR_LOGBOOK TO PK_MSTIG2;
GRANT ALL ON ABITUR_LOGBOOK TO PK_MSTIG3;
GRANT ALL ON ABITUR_LOGBOOK TO PK_MSTIG4;
GRANT ALL ON ABITUR_LOGBOOK TO PK_MSTIGP1;
GRANT ALL ON ABITUR_LOGBOOK TO PK_MSTIGP2;
GRANT ALL ON ABITUR_LOGBOOK TO PK_MSTIG_1;
GRANT ALL ON ABITUR_LOGBOOK TO PK_MSTIG_2;
GRANT ALL ON ABITUR_LOGBOOK TO PK_MSTIG_3;
GRANT ALL ON ABITUR_LOGBOOK TO PK_MSTIG_4;
GRANT ALL ON ABITUR_LOGBOOK TO PK_MSTIG_P1;
GRANT ALL ON ABITUR_LOGBOOK TO PK_MSTIG_P2;
GRANT ALL ON ABITUR_LOGBOOK TO PK_MVS;
GRANT ALL ON ABITUR_LOGBOOK TO PK_MVS1;
GRANT ALL ON ABITUR_LOGBOOK TO PK_MVS2;
GRANT ALL ON ABITUR_LOGBOOK TO PK_MVS3;
GRANT ALL ON ABITUR_LOGBOOK TO PK_MVS4;
GRANT ALL ON ABITUR_LOGBOOK TO PK_MVS5;
GRANT ALL ON ABITUR_LOGBOOK TO PK_MVSP1;
GRANT ALL ON ABITUR_LOGBOOK TO PK_MVSP2;
GRANT ALL ON ABITUR_LOGBOOK TO PK_MVS_1;
GRANT ALL ON ABITUR_LOGBOOK TO PK_MVS_2;
GRANT ALL ON ABITUR_LOGBOOK TO PK_MVS_3;
GRANT ALL ON ABITUR_LOGBOOK TO PK_MVS_4;
GRANT ALL ON ABITUR_LOGBOOK TO PK_MVS_P1;
GRANT ALL ON ABITUR_LOGBOOK TO PK_MVS_P2;
GRANT ALL ON ABITUR_LOGBOOK TO PK_OFKIT;
GRANT ALL ON ABITUR_LOGBOOK TO PK_OFKIT1;
GRANT ALL ON ABITUR_LOGBOOK TO PK_OFKIT2;
GRANT ALL ON ABITUR_LOGBOOK TO PK_OFKIT3;
GRANT ALL ON ABITUR_LOGBOOK TO PK_OFKIT4;
GRANT ALL ON ABITUR_LOGBOOK TO PK_OFKIT5;
GRANT ALL ON ABITUR_LOGBOOK TO PK_OFKITP1;
GRANT ALL ON ABITUR_LOGBOOK TO PK_OFKITP2;
GRANT ALL ON ABITUR_LOGBOOK TO PK_OFK_1;
GRANT ALL ON ABITUR_LOGBOOK TO PK_OFK_2;
GRANT ALL ON ABITUR_LOGBOOK TO PK_OFK_3;
GRANT ALL ON ABITUR_LOGBOOK TO PK_OFK_4;
GRANT ALL ON ABITUR_LOGBOOK TO PK_OFK_P1;
GRANT ALL ON ABITUR_LOGBOOK TO PK_OFK_P2;
GRANT ALL ON ABITUR_LOGBOOK TO PK_OTV1;
GRANT ALL ON ABITUR_LOGBOOK TO PK_OTV2;
GRANT ALL ON ABITUR_LOGBOOK TO PK_OTV3;
GRANT ALL ON ABITUR_LOGBOOK TO PK_OTV4;
GRANT ALL ON ABITUR_LOGBOOK TO PK_SIIE;
GRANT ALL ON ABITUR_LOGBOOK TO PK_SIIE1;
GRANT ALL ON ABITUR_LOGBOOK TO PK_SIIE2;
GRANT ALL ON ABITUR_LOGBOOK TO PK_SIIE3;
GRANT ALL ON ABITUR_LOGBOOK TO PK_SIIE4;
GRANT ALL ON ABITUR_LOGBOOK TO PK_SIIE5;
GRANT ALL ON ABITUR_LOGBOOK TO PK_SIIEP1;
GRANT ALL ON ABITUR_LOGBOOK TO PK_SIIEP2;
GRANT ALL ON ABITUR_LOGBOOK TO PK_SIIEP3;
GRANT ALL ON ABITUR_LOGBOOK TO PK_SIIE_1;
GRANT ALL ON ABITUR_LOGBOOK TO PK_SIIE_2;
GRANT ALL ON ABITUR_LOGBOOK TO PK_SIIE_3;
GRANT ALL ON ABITUR_LOGBOOK TO PK_SIIE_4;
GRANT ALL ON ABITUR_LOGBOOK TO PK_SIIE_P1;
GRANT ALL ON ABITUR_LOGBOOK TO PK_SIIE_P2;