CREATE TABLE IF NOT EXISTS
    BALL
    (
        NOM_BALL  SMALLINT,
        BALL      VARCHAR(15) COLLATE PXW_CYRL
    );




/******************************************************************************/
/***                              Primary keys                              ***/
/******************************************************************************/

ALTER TABLE
    BALL
ADD
    PRIMARY KEY
        (NOM_BALL);


/******************************************************************************/
/***                                Indices                                 ***/
/******************************************************************************/

CREATE INDEX
    BALL_TEXT_BALL
ON
    BALL
    (
        BALL
    );


/******************************************************************************/
/***                                Triggers                                ***/
/******************************************************************************/



SET TERM ^ ;



/******************************************************************************/
/***                          Triggers for tables                           ***/
/******************************************************************************/



/* Trigger: TI_BALL */
CREATE OR ALTER TRIGGER TI_BALL FOR BALL
ACTIVE BEFORE INSERT POSITION 0
AS
BEGIN
NEW.NOM_BALL=GEN_ID(BALL_NOM_BALL,1);
END
^

SET TERM ; ^



/******************************************************************************/
/***                               Privileges                               ***/
/******************************************************************************/


/* Privileges of users */
GRANT ALL ON BALL TO ABITUR1;
GRANT ALL ON BALL TO ABITUR2;
GRANT ALL ON BALL TO ABITUR3;
GRANT ALL ON BALL TO ABITUR4;
GRANT ALL ON BALL TO ABITURA;
GRANT ALL ON BALL TO ALEXANDER_GONCHAROV;
GRANT ALL ON BALL TO ASU;
GRANT ALL ON BALL TO ASU1;
GRANT ALL ON BALL TO ASU2;
GRANT ALL ON BALL TO ASU3;
GRANT ALL ON BALL TO ASU4;
GRANT ALL ON BALL TO DEVELOPER;
GRANT ALL ON BALL TO DEVELOPER2;
GRANT ALL ON BALL TO IT1;
GRANT ALL ON BALL TO IT2;
GRANT ALL ON BALL TO IT3;
GRANT ALL ON BALL TO IVANOVA_A;
GRANT ALL ON BALL TO MVS1;
GRANT ALL ON BALL TO MVS2;
GRANT ALL ON BALL TO MVS3;
GRANT ALL ON BALL TO MVS4;
GRANT ALL ON BALL TO OFKIT1;
GRANT ALL ON BALL TO OFKIT2;
GRANT ALL ON BALL TO OFKIT3;
GRANT ALL ON BALL TO OFKIT4;
GRANT ALL ON BALL TO OKSANA;
GRANT ALL ON BALL TO PK;
GRANT ALL ON BALL TO PK_IT;
GRANT ALL ON BALL TO PK_IT1;
GRANT ALL ON BALL TO PK_IT2;
GRANT ALL ON BALL TO PK_IT3;
GRANT ALL ON BALL TO PK_IT4;
GRANT ALL ON BALL TO PK_IT5;
GRANT ALL ON BALL TO PK_MSTIG1;
GRANT ALL ON BALL TO PK_MSTIG2;
GRANT ALL ON BALL TO PK_MSTIG3;
GRANT ALL ON BALL TO PK_MSTIG4;
GRANT ALL ON BALL TO PK_MSTIGP1;
GRANT ALL ON BALL TO PK_MSTIGP2;
GRANT ALL ON BALL TO PK_MSTIG_1;
GRANT ALL ON BALL TO PK_MSTIG_2;
GRANT ALL ON BALL TO PK_MSTIG_3;
GRANT ALL ON BALL TO PK_MSTIG_4;
GRANT ALL ON BALL TO PK_MSTIG_P1;
GRANT ALL ON BALL TO PK_MSTIG_P2;
GRANT ALL ON BALL TO PK_MVS;
GRANT ALL ON BALL TO PK_MVS1;
GRANT ALL ON BALL TO PK_MVS2;
GRANT ALL ON BALL TO PK_MVS3;
GRANT ALL ON BALL TO PK_MVS4;
GRANT ALL ON BALL TO PK_MVS5;
GRANT ALL ON BALL TO PK_MVSP1;
GRANT ALL ON BALL TO PK_MVSP2;
GRANT ALL ON BALL TO PK_MVS_1;
GRANT ALL ON BALL TO PK_MVS_2;
GRANT ALL ON BALL TO PK_MVS_3;
GRANT ALL ON BALL TO PK_MVS_4;
GRANT ALL ON BALL TO PK_MVS_P1;
GRANT ALL ON BALL TO PK_MVS_P2;
GRANT ALL ON BALL TO PK_OFKIT;
GRANT ALL ON BALL TO PK_OFKIT1;
GRANT ALL ON BALL TO PK_OFKIT2;
GRANT ALL ON BALL TO PK_OFKIT3;
GRANT ALL ON BALL TO PK_OFKIT4;
GRANT ALL ON BALL TO PK_OFKIT5;
GRANT ALL ON BALL TO PK_OFKITP1;
GRANT ALL ON BALL TO PK_OFKITP2;
GRANT ALL ON BALL TO PK_OFK_1;
GRANT ALL ON BALL TO PK_OFK_2;
GRANT ALL ON BALL TO PK_OFK_3;
GRANT ALL ON BALL TO PK_OFK_4;
GRANT ALL ON BALL TO PK_OFK_P1;
GRANT ALL ON BALL TO PK_OFK_P2;
GRANT ALL ON BALL TO PK_OTV1;
GRANT ALL ON BALL TO PK_OTV2;
GRANT ALL ON BALL TO PK_OTV3;
GRANT ALL ON BALL TO PK_OTV4;
GRANT ALL ON BALL TO PK_SIIE;
GRANT ALL ON BALL TO PK_SIIE1;
GRANT ALL ON BALL TO PK_SIIE2;
GRANT ALL ON BALL TO PK_SIIE3;
GRANT ALL ON BALL TO PK_SIIE4;
GRANT ALL ON BALL TO PK_SIIE5;
GRANT ALL ON BALL TO PK_SIIEP1;
GRANT ALL ON BALL TO PK_SIIEP2;
GRANT ALL ON BALL TO PK_SIIEP3;
GRANT ALL ON BALL TO PK_SIIE_1;
GRANT ALL ON BALL TO PK_SIIE_2;
GRANT ALL ON BALL TO PK_SIIE_3;
GRANT ALL ON BALL TO PK_SIIE_4;
GRANT ALL ON BALL TO PK_SIIE_P1;
GRANT ALL ON BALL TO PK_SIIE_P2;
GRANT ALL ON BALL TO SIIE1;
GRANT ALL ON BALL TO SIIE2;
GRANT ALL ON BALL TO SIIE3;
GRANT ALL ON BALL TO SIIE4;
GRANT ALL ON BALL TO UO_LAB;
GRANT ALL ON BALL TO UO_N;
GRANT ALL ON BALL TO UO_Z;