CREATE GENERATOR
    GEN_CALL_ABITURIENT_ID;

CREATE TABLE IF NOT EXISTS
    CALL_ABITURIENT
    (
        ID_CALL            SMALLINT,
        N_FAC              SMALLINT,
        N_CALL_ABITURIENT  SMALLINT,
        P_CALL             SMALLINT,
        P_SOUND_01         SMALLINT,
        P_SOUND_02         SMALLINT,
        P_SOUND_03         SMALLINT
    );




/******************************************************************************/
/***                              Primary keys                              ***/
/******************************************************************************/

ALTER TABLE
    CALL_ABITURIENT
ADD
    CONSTRAINT
        PK_CALL_ABITURIENT
    PRIMARY KEY
        (ID_CALL);


/******************************************************************************/
/***                                Triggers                                ***/
/******************************************************************************/



SET TERM ^ ;



/******************************************************************************/
/***                          Triggers for tables                           ***/
/******************************************************************************/



/* Trigger: CALL_ABITURIENT_BI */
CREATE OR ALTER TRIGGER CALL_ABITURIENT_BI FOR CALL_ABITURIENT
ACTIVE BEFORE INSERT POSITION 0
as
begin
  if (new.id_call is null) then
    new.id_call = gen_id(gen_call_abiturient_id,1);
end
^

SET TERM ; ^



/******************************************************************************/
/***                          Fields descriptions                           ***/
/******************************************************************************/

COMMENT ON COLUMN CALL_ABITURIENT.N_CALL_ABITURIENT IS 
'Номер очереди вызываемого абитуриента';

COMMENT ON COLUMN CALL_ABITURIENT.P_CALL IS 
'Признак вызова:
0 - работа
1 - вызов';

COMMENT ON COLUMN CALL_ABITURIENT.P_SOUND_01 IS 
'Признак голосового вызова 1 табло:
0 - нет
1 - голос';

COMMENT ON COLUMN CALL_ABITURIENT.P_SOUND_02 IS 
'Признак голосового вызова 2 табло:
0 - нет
1 - голос';

COMMENT ON COLUMN CALL_ABITURIENT.P_SOUND_03 IS 
'Признак голосового вызова 3 табло:
0 - нет
1 - голос';



/******************************************************************************/
/***                               Privileges                               ***/
/******************************************************************************/


/* Privileges of users */
GRANT ALL ON CALL_ABITURIENT TO ABITUR1;
GRANT ALL ON CALL_ABITURIENT TO ABITUR2;
GRANT ALL ON CALL_ABITURIENT TO ABITUR3;
GRANT ALL ON CALL_ABITURIENT TO ABITUR4;
GRANT ALL ON CALL_ABITURIENT TO ABITURA;
GRANT ALL ON CALL_ABITURIENT TO ALEXANDER_GONCHAROV;
GRANT ALL ON CALL_ABITURIENT TO ASU;
GRANT ALL ON CALL_ABITURIENT TO ASU1;
GRANT ALL ON CALL_ABITURIENT TO ASU2;
GRANT ALL ON CALL_ABITURIENT TO ASU3;
GRANT ALL ON CALL_ABITURIENT TO ASU4;
GRANT ALL ON CALL_ABITURIENT TO DEVELOPER;
GRANT ALL ON CALL_ABITURIENT TO IVANOVA_A;
GRANT ALL ON CALL_ABITURIENT TO OKSANA;
GRANT ALL ON CALL_ABITURIENT TO PK;
GRANT ALL ON CALL_ABITURIENT TO PK_IT;
GRANT ALL ON CALL_ABITURIENT TO PK_IT1;
GRANT ALL ON CALL_ABITURIENT TO PK_IT2;
GRANT ALL ON CALL_ABITURIENT TO PK_IT3;
GRANT ALL ON CALL_ABITURIENT TO PK_IT4;
GRANT ALL ON CALL_ABITURIENT TO PK_IT5;
GRANT ALL ON CALL_ABITURIENT TO PK_MSTIG1;
GRANT ALL ON CALL_ABITURIENT TO PK_MSTIG2;
GRANT ALL ON CALL_ABITURIENT TO PK_MSTIG3;
GRANT ALL ON CALL_ABITURIENT TO PK_MSTIG4;
GRANT ALL ON CALL_ABITURIENT TO PK_MSTIGP1;
GRANT ALL ON CALL_ABITURIENT TO PK_MSTIGP2;
GRANT ALL ON CALL_ABITURIENT TO PK_MSTIG_1;
GRANT ALL ON CALL_ABITURIENT TO PK_MSTIG_2;
GRANT ALL ON CALL_ABITURIENT TO PK_MSTIG_3;
GRANT ALL ON CALL_ABITURIENT TO PK_MSTIG_4;
GRANT ALL ON CALL_ABITURIENT TO PK_MSTIG_P1;
GRANT ALL ON CALL_ABITURIENT TO PK_MSTIG_P2;
GRANT ALL ON CALL_ABITURIENT TO PK_MVS;
GRANT ALL ON CALL_ABITURIENT TO PK_MVS1;
GRANT ALL ON CALL_ABITURIENT TO PK_MVS2;
GRANT ALL ON CALL_ABITURIENT TO PK_MVS3;
GRANT ALL ON CALL_ABITURIENT TO PK_MVS4;
GRANT ALL ON CALL_ABITURIENT TO PK_MVS5;
GRANT ALL ON CALL_ABITURIENT TO PK_MVSP1;
GRANT ALL ON CALL_ABITURIENT TO PK_MVSP2;
GRANT ALL ON CALL_ABITURIENT TO PK_MVS_1;
GRANT ALL ON CALL_ABITURIENT TO PK_MVS_2;
GRANT ALL ON CALL_ABITURIENT TO PK_MVS_3;
GRANT ALL ON CALL_ABITURIENT TO PK_MVS_4;
GRANT ALL ON CALL_ABITURIENT TO PK_MVS_P1;
GRANT ALL ON CALL_ABITURIENT TO PK_MVS_P2;
GRANT ALL ON CALL_ABITURIENT TO PK_OFKIT;
GRANT ALL ON CALL_ABITURIENT TO PK_OFKIT1;
GRANT ALL ON CALL_ABITURIENT TO PK_OFKIT2;
GRANT ALL ON CALL_ABITURIENT TO PK_OFKIT3;
GRANT ALL ON CALL_ABITURIENT TO PK_OFKIT4;
GRANT ALL ON CALL_ABITURIENT TO PK_OFKIT5;
GRANT ALL ON CALL_ABITURIENT TO PK_OFKITP1;
GRANT ALL ON CALL_ABITURIENT TO PK_OFKITP2;
GRANT ALL ON CALL_ABITURIENT TO PK_OFK_1;
GRANT ALL ON CALL_ABITURIENT TO PK_OFK_2;
GRANT ALL ON CALL_ABITURIENT TO PK_OFK_3;
GRANT ALL ON CALL_ABITURIENT TO PK_OFK_4;
GRANT ALL ON CALL_ABITURIENT TO PK_OFK_P1;
GRANT ALL ON CALL_ABITURIENT TO PK_OFK_P2;
GRANT ALL ON CALL_ABITURIENT TO PK_OTV1;
GRANT ALL ON CALL_ABITURIENT TO PK_OTV2;
GRANT ALL ON CALL_ABITURIENT TO PK_OTV3;
GRANT ALL ON CALL_ABITURIENT TO PK_OTV4;
GRANT ALL ON CALL_ABITURIENT TO PK_SIIE;
GRANT ALL ON CALL_ABITURIENT TO PK_SIIE1;
GRANT ALL ON CALL_ABITURIENT TO PK_SIIE2;
GRANT ALL ON CALL_ABITURIENT TO PK_SIIE3;
GRANT ALL ON CALL_ABITURIENT TO PK_SIIE4;
GRANT ALL ON CALL_ABITURIENT TO PK_SIIE5;
GRANT ALL ON CALL_ABITURIENT TO PK_SIIEP1;
GRANT ALL ON CALL_ABITURIENT TO PK_SIIEP2;
GRANT ALL ON CALL_ABITURIENT TO PK_SIIEP3;
GRANT ALL ON CALL_ABITURIENT TO PK_SIIE_1;
GRANT ALL ON CALL_ABITURIENT TO PK_SIIE_2;
GRANT ALL ON CALL_ABITURIENT TO PK_SIIE_3;
GRANT ALL ON CALL_ABITURIENT TO PK_SIIE_4;
GRANT ALL ON CALL_ABITURIENT TO PK_SIIE_P1;
GRANT ALL ON CALL_ABITURIENT TO PK_SIIE_P2;