CREATE TABLE IF NOT EXISTS
    CATEGORY
    (
        N_SPORT_CATEGORY  SMALLINT,
        SPORT_CATEGORY    VARCHAR(50) COLLATE PXW_CYRL
    );




/******************************************************************************/
/***                              Primary keys                              ***/
/******************************************************************************/

ALTER TABLE
    CATEGORY
ADD
    PRIMARY KEY
        (N_SPORT_CATEGORY);


/******************************************************************************/
/***                                Indices                                 ***/
/******************************************************************************/

CREATE INDEX
    CATEGORY_SPORT_CATEGORY
ON
    CATEGORY
    (
        SPORT_CATEGORY
    );


/******************************************************************************/
/***                                Triggers                                ***/
/******************************************************************************/



SET TERM ^ ;



/******************************************************************************/
/***                          Triggers for tables                           ***/
/******************************************************************************/



/* Trigger: TI_CATEGORY */
CREATE OR ALTER TRIGGER TI_CATEGORY FOR CATEGORY
ACTIVE BEFORE INSERT POSITION 0
AS
BEGIN
NEW.N_SPORT_CATEGORY=GEN_ID(CATEGORY_N_SPORT_CATEGORY,1);
END
^

SET TERM ; ^



/******************************************************************************/
/***                               Privileges                               ***/
/******************************************************************************/


/* Privileges of users */
GRANT ALL ON CATEGORY TO ABITUR1;
GRANT ALL ON CATEGORY TO ABITUR2;
GRANT ALL ON CATEGORY TO ABITUR3;
GRANT ALL ON CATEGORY TO ABITUR4;
GRANT ALL ON CATEGORY TO ABITURA;
GRANT ALL ON CATEGORY TO ALEXANDER_GONCHAROV;
GRANT ALL ON CATEGORY TO ASU;
GRANT ALL ON CATEGORY TO ASU1;
GRANT ALL ON CATEGORY TO ASU2;
GRANT ALL ON CATEGORY TO ASU3;
GRANT ALL ON CATEGORY TO ASU4;
GRANT ALL ON CATEGORY TO DEVELOPER;
GRANT ALL ON CATEGORY TO DEVELOPER2;
GRANT ALL ON CATEGORY TO IT1;
GRANT ALL ON CATEGORY TO IT2;
GRANT ALL ON CATEGORY TO IT3;
GRANT ALL ON CATEGORY TO IVANOVA_A;
GRANT ALL ON CATEGORY TO MVS1;
GRANT ALL ON CATEGORY TO MVS2;
GRANT ALL ON CATEGORY TO MVS3;
GRANT ALL ON CATEGORY TO MVS4;
GRANT ALL ON CATEGORY TO OFKIT1;
GRANT ALL ON CATEGORY TO OFKIT2;
GRANT ALL ON CATEGORY TO OFKIT3;
GRANT ALL ON CATEGORY TO OFKIT4;
GRANT ALL ON CATEGORY TO OKSANA;
GRANT ALL ON CATEGORY TO PK;
GRANT ALL ON CATEGORY TO PK_IT;
GRANT ALL ON CATEGORY TO PK_IT1;
GRANT ALL ON CATEGORY TO PK_IT2;
GRANT ALL ON CATEGORY TO PK_IT3;
GRANT ALL ON CATEGORY TO PK_IT4;
GRANT ALL ON CATEGORY TO PK_IT5;
GRANT ALL ON CATEGORY TO PK_MSTIG1;
GRANT ALL ON CATEGORY TO PK_MSTIG2;
GRANT ALL ON CATEGORY TO PK_MSTIG3;
GRANT ALL ON CATEGORY TO PK_MSTIG4;
GRANT ALL ON CATEGORY TO PK_MSTIGP1;
GRANT ALL ON CATEGORY TO PK_MSTIGP2;
GRANT ALL ON CATEGORY TO PK_MSTIG_1;
GRANT ALL ON CATEGORY TO PK_MSTIG_2;
GRANT ALL ON CATEGORY TO PK_MSTIG_3;
GRANT ALL ON CATEGORY TO PK_MSTIG_4;
GRANT ALL ON CATEGORY TO PK_MSTIG_P1;
GRANT ALL ON CATEGORY TO PK_MSTIG_P2;
GRANT ALL ON CATEGORY TO PK_MVS;
GRANT ALL ON CATEGORY TO PK_MVS1;
GRANT ALL ON CATEGORY TO PK_MVS2;
GRANT ALL ON CATEGORY TO PK_MVS3;
GRANT ALL ON CATEGORY TO PK_MVS4;
GRANT ALL ON CATEGORY TO PK_MVS5;
GRANT ALL ON CATEGORY TO PK_MVSP1;
GRANT ALL ON CATEGORY TO PK_MVSP2;
GRANT ALL ON CATEGORY TO PK_MVS_1;
GRANT ALL ON CATEGORY TO PK_MVS_2;
GRANT ALL ON CATEGORY TO PK_MVS_3;
GRANT ALL ON CATEGORY TO PK_MVS_4;
GRANT ALL ON CATEGORY TO PK_MVS_P1;
GRANT ALL ON CATEGORY TO PK_MVS_P2;
GRANT ALL ON CATEGORY TO PK_OFKIT;
GRANT ALL ON CATEGORY TO PK_OFKIT1;
GRANT ALL ON CATEGORY TO PK_OFKIT2;
GRANT ALL ON CATEGORY TO PK_OFKIT3;
GRANT ALL ON CATEGORY TO PK_OFKIT4;
GRANT ALL ON CATEGORY TO PK_OFKIT5;
GRANT ALL ON CATEGORY TO PK_OFKITP1;
GRANT ALL ON CATEGORY TO PK_OFKITP2;
GRANT ALL ON CATEGORY TO PK_OFK_1;
GRANT ALL ON CATEGORY TO PK_OFK_2;
GRANT ALL ON CATEGORY TO PK_OFK_3;
GRANT ALL ON CATEGORY TO PK_OFK_4;
GRANT ALL ON CATEGORY TO PK_OFK_P1;
GRANT ALL ON CATEGORY TO PK_OFK_P2;
GRANT ALL ON CATEGORY TO PK_OTV1;
GRANT ALL ON CATEGORY TO PK_OTV2;
GRANT ALL ON CATEGORY TO PK_OTV3;
GRANT ALL ON CATEGORY TO PK_OTV4;
GRANT ALL ON CATEGORY TO PK_SIIE;
GRANT ALL ON CATEGORY TO PK_SIIE1;
GRANT ALL ON CATEGORY TO PK_SIIE2;
GRANT ALL ON CATEGORY TO PK_SIIE3;
GRANT ALL ON CATEGORY TO PK_SIIE4;
GRANT ALL ON CATEGORY TO PK_SIIE5;
GRANT ALL ON CATEGORY TO PK_SIIEP1;
GRANT ALL ON CATEGORY TO PK_SIIEP2;
GRANT ALL ON CATEGORY TO PK_SIIEP3;
GRANT ALL ON CATEGORY TO PK_SIIE_1;
GRANT ALL ON CATEGORY TO PK_SIIE_2;
GRANT ALL ON CATEGORY TO PK_SIIE_3;
GRANT ALL ON CATEGORY TO PK_SIIE_4;
GRANT ALL ON CATEGORY TO PK_SIIE_P1;
GRANT ALL ON CATEGORY TO PK_SIIE_P2;
GRANT ALL ON CATEGORY TO SIIE1;
GRANT ALL ON CATEGORY TO SIIE2;
GRANT ALL ON CATEGORY TO SIIE3;
GRANT ALL ON CATEGORY TO SIIE4;
GRANT ALL ON CATEGORY TO UO_LAB;
GRANT ALL ON CATEGORY TO UO_N;
GRANT ALL ON CATEGORY TO UO_Z;