CREATE TABLE IF NOT EXISTS
    CERTIFICATES_LOGBOOK
    (
        ID_LOG     INTEGER,
        N_PREDMET  SMALLINT,
        SERIA_S    VARCHAR(10),
        NOMER_S    VARCHAR(15),
        BALL       SMALLINT,
        DESCRIBE   VARCHAR(150),
        RUS_BEL    SMALLINT
    );




/******************************************************************************/
/***                               Privileges                               ***/
/******************************************************************************/


/* Privileges of users */
GRANT ALL ON CERTIFICATES_LOGBOOK TO ABITUR1;
GRANT ALL ON CERTIFICATES_LOGBOOK TO ABITUR2;
GRANT ALL ON CERTIFICATES_LOGBOOK TO ABITUR3;
GRANT ALL ON CERTIFICATES_LOGBOOK TO ABITUR4;
GRANT ALL ON CERTIFICATES_LOGBOOK TO ABITURA;
GRANT ALL ON CERTIFICATES_LOGBOOK TO ALEXANDER_GONCHAROV;
GRANT ALL ON CERTIFICATES_LOGBOOK TO ASU;
GRANT ALL ON CERTIFICATES_LOGBOOK TO ASU1;
GRANT ALL ON CERTIFICATES_LOGBOOK TO ASU2;
GRANT ALL ON CERTIFICATES_LOGBOOK TO ASU3;
GRANT ALL ON CERTIFICATES_LOGBOOK TO ASU4;
GRANT ALL ON CERTIFICATES_LOGBOOK TO DEVELOPER;
GRANT ALL ON CERTIFICATES_LOGBOOK TO IVANOVA_A;
GRANT ALL ON CERTIFICATES_LOGBOOK TO OKSANA;
GRANT ALL ON CERTIFICATES_LOGBOOK TO PK;
GRANT ALL ON CERTIFICATES_LOGBOOK TO PK_IT;
GRANT ALL ON CERTIFICATES_LOGBOOK TO PK_IT1;
GRANT ALL ON CERTIFICATES_LOGBOOK TO PK_IT2;
GRANT ALL ON CERTIFICATES_LOGBOOK TO PK_IT3;
GRANT ALL ON CERTIFICATES_LOGBOOK TO PK_IT4;
GRANT ALL ON CERTIFICATES_LOGBOOK TO PK_IT5;
GRANT ALL ON CERTIFICATES_LOGBOOK TO PK_MSTIG1;
GRANT ALL ON CERTIFICATES_LOGBOOK TO PK_MSTIG2;
GRANT ALL ON CERTIFICATES_LOGBOOK TO PK_MSTIG3;
GRANT ALL ON CERTIFICATES_LOGBOOK TO PK_MSTIG4;
GRANT ALL ON CERTIFICATES_LOGBOOK TO PK_MSTIGP1;
GRANT ALL ON CERTIFICATES_LOGBOOK TO PK_MSTIGP2;
GRANT ALL ON CERTIFICATES_LOGBOOK TO PK_MSTIG_1;
GRANT ALL ON CERTIFICATES_LOGBOOK TO PK_MSTIG_2;
GRANT ALL ON CERTIFICATES_LOGBOOK TO PK_MSTIG_3;
GRANT ALL ON CERTIFICATES_LOGBOOK TO PK_MSTIG_4;
GRANT ALL ON CERTIFICATES_LOGBOOK TO PK_MSTIG_P1;
GRANT ALL ON CERTIFICATES_LOGBOOK TO PK_MSTIG_P2;
GRANT ALL ON CERTIFICATES_LOGBOOK TO PK_MVS;
GRANT ALL ON CERTIFICATES_LOGBOOK TO PK_MVS1;
GRANT ALL ON CERTIFICATES_LOGBOOK TO PK_MVS2;
GRANT ALL ON CERTIFICATES_LOGBOOK TO PK_MVS3;
GRANT ALL ON CERTIFICATES_LOGBOOK TO PK_MVS4;
GRANT ALL ON CERTIFICATES_LOGBOOK TO PK_MVS5;
GRANT ALL ON CERTIFICATES_LOGBOOK TO PK_MVSP1;
GRANT ALL ON CERTIFICATES_LOGBOOK TO PK_MVSP2;
GRANT ALL ON CERTIFICATES_LOGBOOK TO PK_MVS_1;
GRANT ALL ON CERTIFICATES_LOGBOOK TO PK_MVS_2;
GRANT ALL ON CERTIFICATES_LOGBOOK TO PK_MVS_3;
GRANT ALL ON CERTIFICATES_LOGBOOK TO PK_MVS_4;
GRANT ALL ON CERTIFICATES_LOGBOOK TO PK_MVS_P1;
GRANT ALL ON CERTIFICATES_LOGBOOK TO PK_MVS_P2;
GRANT ALL ON CERTIFICATES_LOGBOOK TO PK_OFKIT;
GRANT ALL ON CERTIFICATES_LOGBOOK TO PK_OFKIT1;
GRANT ALL ON CERTIFICATES_LOGBOOK TO PK_OFKIT2;
GRANT ALL ON CERTIFICATES_LOGBOOK TO PK_OFKIT3;
GRANT ALL ON CERTIFICATES_LOGBOOK TO PK_OFKIT4;
GRANT ALL ON CERTIFICATES_LOGBOOK TO PK_OFKIT5;
GRANT ALL ON CERTIFICATES_LOGBOOK TO PK_OFKITP1;
GRANT ALL ON CERTIFICATES_LOGBOOK TO PK_OFKITP2;
GRANT ALL ON CERTIFICATES_LOGBOOK TO PK_OFK_1;
GRANT ALL ON CERTIFICATES_LOGBOOK TO PK_OFK_2;
GRANT ALL ON CERTIFICATES_LOGBOOK TO PK_OFK_3;
GRANT ALL ON CERTIFICATES_LOGBOOK TO PK_OFK_4;
GRANT ALL ON CERTIFICATES_LOGBOOK TO PK_OFK_P1;
GRANT ALL ON CERTIFICATES_LOGBOOK TO PK_OFK_P2;
GRANT ALL ON CERTIFICATES_LOGBOOK TO PK_OTV1;
GRANT ALL ON CERTIFICATES_LOGBOOK TO PK_OTV2;
GRANT ALL ON CERTIFICATES_LOGBOOK TO PK_OTV3;
GRANT ALL ON CERTIFICATES_LOGBOOK TO PK_OTV4;
GRANT ALL ON CERTIFICATES_LOGBOOK TO PK_SIIE;
GRANT ALL ON CERTIFICATES_LOGBOOK TO PK_SIIE1;
GRANT ALL ON CERTIFICATES_LOGBOOK TO PK_SIIE2;
GRANT ALL ON CERTIFICATES_LOGBOOK TO PK_SIIE3;
GRANT ALL ON CERTIFICATES_LOGBOOK TO PK_SIIE4;
GRANT ALL ON CERTIFICATES_LOGBOOK TO PK_SIIE5;
GRANT ALL ON CERTIFICATES_LOGBOOK TO PK_SIIEP1;
GRANT ALL ON CERTIFICATES_LOGBOOK TO PK_SIIEP2;
GRANT ALL ON CERTIFICATES_LOGBOOK TO PK_SIIEP3;
GRANT ALL ON CERTIFICATES_LOGBOOK TO PK_SIIE_1;
GRANT ALL ON CERTIFICATES_LOGBOOK TO PK_SIIE_2;
GRANT ALL ON CERTIFICATES_LOGBOOK TO PK_SIIE_3;
GRANT ALL ON CERTIFICATES_LOGBOOK TO PK_SIIE_4;
GRANT ALL ON CERTIFICATES_LOGBOOK TO PK_SIIE_P1;
GRANT ALL ON CERTIFICATES_LOGBOOK TO PK_SIIE_P2;