CREATE TABLE IF NOT EXISTS
    CK_PLAN
    (
        ID_CK_PLAN   INTEGER,
        N_SPECIALIZ  SMALLINT,
        KOL_PLACE    SMALLINT,
        TERM_EDUC    SMALLINT
    );




/******************************************************************************/
/***                              Primary keys                              ***/
/******************************************************************************/

ALTER TABLE
    CK_PLAN
ADD 
    CONSTRAINT
        PK_CK_PLAN
    PRIMARY KEY
        (ID_CK_PLAN);


/******************************************************************************/
/***                          Fields descriptions                           ***/
/******************************************************************************/

COMMENT ON COLUMN CK_PLAN.N_SPECIALIZ IS 
'Связь с таблицей SPECIALIZ Деканат';



/******************************************************************************/
/***                               Privileges                               ***/
/******************************************************************************/


/* Privileges of users */
GRANT ALL ON CK_PLAN TO ABITUR1;
GRANT ALL ON CK_PLAN TO ABITUR2;
GRANT ALL ON CK_PLAN TO ABITUR3;
GRANT ALL ON CK_PLAN TO ABITUR4;
GRANT ALL ON CK_PLAN TO ABITURA;
GRANT ALL ON CK_PLAN TO ALEXANDER_GONCHAROV;
GRANT ALL ON CK_PLAN TO ASU;
GRANT ALL ON CK_PLAN TO ASU1;
GRANT ALL ON CK_PLAN TO ASU2;
GRANT ALL ON CK_PLAN TO ASU3;
GRANT ALL ON CK_PLAN TO ASU4;
GRANT ALL ON CK_PLAN TO DEVELOPER;
GRANT ALL ON CK_PLAN TO IT1;
GRANT ALL ON CK_PLAN TO IT2;
GRANT ALL ON CK_PLAN TO IT3;
GRANT ALL ON CK_PLAN TO IVANOVA_A;
GRANT ALL ON CK_PLAN TO OFKIT1;
GRANT ALL ON CK_PLAN TO OFKIT2;
GRANT ALL ON CK_PLAN TO OFKIT3;
GRANT ALL ON CK_PLAN TO OFKIT4;
GRANT ALL ON CK_PLAN TO OKSANA;
GRANT ALL ON CK_PLAN TO PK;
GRANT ALL ON CK_PLAN TO PK_IT;
GRANT ALL ON CK_PLAN TO PK_IT1;
GRANT ALL ON CK_PLAN TO PK_IT2;
GRANT ALL ON CK_PLAN TO PK_IT3;
GRANT ALL ON CK_PLAN TO PK_IT4;
GRANT ALL ON CK_PLAN TO PK_IT5;
GRANT ALL ON CK_PLAN TO PK_MSTIG1;
GRANT ALL ON CK_PLAN TO PK_MSTIG2;
GRANT ALL ON CK_PLAN TO PK_MSTIG3;
GRANT ALL ON CK_PLAN TO PK_MSTIG4;
GRANT ALL ON CK_PLAN TO PK_MSTIGP1;
GRANT ALL ON CK_PLAN TO PK_MSTIGP2;
GRANT ALL ON CK_PLAN TO PK_MSTIG_1;
GRANT ALL ON CK_PLAN TO PK_MSTIG_2;
GRANT ALL ON CK_PLAN TO PK_MSTIG_3;
GRANT ALL ON CK_PLAN TO PK_MSTIG_4;
GRANT ALL ON CK_PLAN TO PK_MSTIG_P1;
GRANT ALL ON CK_PLAN TO PK_MSTIG_P2;
GRANT ALL ON CK_PLAN TO PK_MVS;
GRANT ALL ON CK_PLAN TO PK_MVS1;
GRANT ALL ON CK_PLAN TO PK_MVS2;
GRANT ALL ON CK_PLAN TO PK_MVS3;
GRANT ALL ON CK_PLAN TO PK_MVS4;
GRANT ALL ON CK_PLAN TO PK_MVS5;
GRANT ALL ON CK_PLAN TO PK_MVSP1;
GRANT ALL ON CK_PLAN TO PK_MVSP2;
GRANT ALL ON CK_PLAN TO PK_MVS_1;
GRANT ALL ON CK_PLAN TO PK_MVS_2;
GRANT ALL ON CK_PLAN TO PK_MVS_3;
GRANT ALL ON CK_PLAN TO PK_MVS_4;
GRANT ALL ON CK_PLAN TO PK_MVS_P1;
GRANT ALL ON CK_PLAN TO PK_MVS_P2;
GRANT ALL ON CK_PLAN TO PK_OFKIT;
GRANT ALL ON CK_PLAN TO PK_OFKIT1;
GRANT ALL ON CK_PLAN TO PK_OFKIT2;
GRANT ALL ON CK_PLAN TO PK_OFKIT3;
GRANT ALL ON CK_PLAN TO PK_OFKIT4;
GRANT ALL ON CK_PLAN TO PK_OFKIT5;
GRANT ALL ON CK_PLAN TO PK_OFKITP1;
GRANT ALL ON CK_PLAN TO PK_OFKITP2;
GRANT ALL ON CK_PLAN TO PK_OFK_1;
GRANT ALL ON CK_PLAN TO PK_OFK_2;
GRANT ALL ON CK_PLAN TO PK_OFK_3;
GRANT ALL ON CK_PLAN TO PK_OFK_4;
GRANT ALL ON CK_PLAN TO PK_OFK_P1;
GRANT ALL ON CK_PLAN TO PK_OFK_P2;
GRANT ALL ON CK_PLAN TO PK_OTV1;
GRANT ALL ON CK_PLAN TO PK_OTV2;
GRANT ALL ON CK_PLAN TO PK_OTV3;
GRANT ALL ON CK_PLAN TO PK_OTV4;
GRANT ALL ON CK_PLAN TO PK_SIIE;
GRANT ALL ON CK_PLAN TO PK_SIIE1;
GRANT ALL ON CK_PLAN TO PK_SIIE2;
GRANT ALL ON CK_PLAN TO PK_SIIE3;
GRANT ALL ON CK_PLAN TO PK_SIIE4;
GRANT ALL ON CK_PLAN TO PK_SIIE5;
GRANT ALL ON CK_PLAN TO PK_SIIEP1;
GRANT ALL ON CK_PLAN TO PK_SIIEP2;
GRANT ALL ON CK_PLAN TO PK_SIIEP3;
GRANT ALL ON CK_PLAN TO PK_SIIE_1;
GRANT ALL ON CK_PLAN TO PK_SIIE_2;
GRANT ALL ON CK_PLAN TO PK_SIIE_3;
GRANT ALL ON CK_PLAN TO PK_SIIE_4;
GRANT ALL ON CK_PLAN TO PK_SIIE_P1;
GRANT ALL ON CK_PLAN TO PK_SIIE_P2;