CREATE GENERATOR
    GEN_CONTROL_EXERC_ID;

CREATE TABLE IF NOT EXISTS
CONTROL_EXERC
(
    ID_CONTROL_EXERC  INTEGER,
    N_FAC             SMALLINT,
    N_SPECIALIZ       SMALLINT,
    POL               CHAR(1),
    NUM_EXERC_GRP     SMALLINT,
    ID_EXERC          SMALLINT
);




/******************************************************************************/
/***                              Primary keys                              ***/
/******************************************************************************/

ALTER TABLE
    CONTROL_EXERC
ADD
    CONSTRAINT
        PK_CONTROL_EXERC
    PRIMARY KEY
        (ID_CONTROL_EXERC);


/******************************************************************************/
/***                              Foreign keys                              ***/
/******************************************************************************/

ALTER TABLE
    CONTROL_EXERC
ADD
    CONSTRAINT 
        FK_CONTROL_EXERC_1
    FOREIGN KEY
        (ID_EXERC)
    REFERENCES
        EXERCISE
        (
            ID_EXERC
        );


/******************************************************************************/
/***                                Triggers                                ***/
/******************************************************************************/



SET TERM ^ ;



/******************************************************************************/
/***                          Triggers for tables                           ***/
/******************************************************************************/



/* Trigger: CONTROL_EXERC_BI */
CREATE OR ALTER TRIGGER CONTROL_EXERC_BI FOR CONTROL_EXERC
ACTIVE BEFORE INSERT POSITION 0
as
begin
  if (new.id_control_exerc is null) then
    new.id_control_exerc = gen_id(gen_control_exerc_id,1);
end
^

SET TERM ; ^



/******************************************************************************/
/***                          Fields descriptions                           ***/
/******************************************************************************/

COMMENT ON COLUMN CONTROL_EXERC.N_FAC IS 
'Связь с таблицей Faculty (из Деканата)-факультеты
1-СИиЕ
2-МВС
3-ОФКиТ
4-ИТ';

COMMENT ON COLUMN CONTROL_EXERC.N_SPECIALIZ IS 
'Связь с таблицей SPECIALIZ - специализация (из Деканата)';

COMMENT ON COLUMN CONTROL_EXERC.POL IS 
'Пол - связь с таблицей Abitura, поле POL';

COMMENT ON COLUMN CONTROL_EXERC.NUM_EXERC_GRP IS 
'Номер группы КУ из соответствующей таблицы КУ';

COMMENT ON COLUMN CONTROL_EXERC.ID_EXERC IS 
'Номер КУ из таблицы EXERCISE';



/******************************************************************************/
/***                               Privileges                               ***/
/******************************************************************************/


/* Privileges of users */
GRANT ALL ON CONTROL_EXERC TO ABITUR1;
GRANT ALL ON CONTROL_EXERC TO ABITUR2;
GRANT ALL ON CONTROL_EXERC TO ABITUR3;
GRANT ALL ON CONTROL_EXERC TO ABITUR4;
GRANT ALL ON CONTROL_EXERC TO ABITURA;
GRANT ALL ON CONTROL_EXERC TO ALEXANDER_GONCHAROV;
GRANT ALL ON CONTROL_EXERC TO ASU;
GRANT ALL ON CONTROL_EXERC TO ASU1;
GRANT ALL ON CONTROL_EXERC TO ASU2;
GRANT ALL ON CONTROL_EXERC TO ASU3;
GRANT ALL ON CONTROL_EXERC TO ASU4;
GRANT ALL ON CONTROL_EXERC TO DEVELOPER;
GRANT ALL ON CONTROL_EXERC TO DEVELOPER2;
GRANT ALL ON CONTROL_EXERC TO IT1;
GRANT ALL ON CONTROL_EXERC TO IT2;
GRANT ALL ON CONTROL_EXERC TO IT3;
GRANT ALL ON CONTROL_EXERC TO IVANOVA_A;
GRANT ALL ON CONTROL_EXERC TO OFKIT1;
GRANT ALL ON CONTROL_EXERC TO OFKIT2;
GRANT ALL ON CONTROL_EXERC TO OFKIT3;
GRANT ALL ON CONTROL_EXERC TO OFKIT4;
GRANT ALL ON CONTROL_EXERC TO OKSANA;
GRANT ALL ON CONTROL_EXERC TO PK;
GRANT ALL ON CONTROL_EXERC TO PK_IT;
GRANT ALL ON CONTROL_EXERC TO PK_IT1;
GRANT ALL ON CONTROL_EXERC TO PK_IT2;
GRANT ALL ON CONTROL_EXERC TO PK_IT3;
GRANT ALL ON CONTROL_EXERC TO PK_IT4;
GRANT ALL ON CONTROL_EXERC TO PK_IT5;
GRANT ALL ON CONTROL_EXERC TO PK_MSTIG1;
GRANT ALL ON CONTROL_EXERC TO PK_MSTIG2;
GRANT ALL ON CONTROL_EXERC TO PK_MSTIG3;
GRANT ALL ON CONTROL_EXERC TO PK_MSTIG4;
GRANT ALL ON CONTROL_EXERC TO PK_MSTIGP1;
GRANT ALL ON CONTROL_EXERC TO PK_MSTIGP2;
GRANT ALL ON CONTROL_EXERC TO PK_MSTIG_1;
GRANT ALL ON CONTROL_EXERC TO PK_MSTIG_2;
GRANT ALL ON CONTROL_EXERC TO PK_MSTIG_3;
GRANT ALL ON CONTROL_EXERC TO PK_MSTIG_4;
GRANT ALL ON CONTROL_EXERC TO PK_MSTIG_P1;
GRANT ALL ON CONTROL_EXERC TO PK_MSTIG_P2;
GRANT ALL ON CONTROL_EXERC TO PK_MVS;
GRANT ALL ON CONTROL_EXERC TO PK_MVS1;
GRANT ALL ON CONTROL_EXERC TO PK_MVS2;
GRANT ALL ON CONTROL_EXERC TO PK_MVS3;
GRANT ALL ON CONTROL_EXERC TO PK_MVS4;
GRANT ALL ON CONTROL_EXERC TO PK_MVS5;
GRANT ALL ON CONTROL_EXERC TO PK_MVSP1;
GRANT ALL ON CONTROL_EXERC TO PK_MVSP2;
GRANT ALL ON CONTROL_EXERC TO PK_MVS_1;
GRANT ALL ON CONTROL_EXERC TO PK_MVS_2;
GRANT ALL ON CONTROL_EXERC TO PK_MVS_3;
GRANT ALL ON CONTROL_EXERC TO PK_MVS_4;
GRANT ALL ON CONTROL_EXERC TO PK_MVS_P1;
GRANT ALL ON CONTROL_EXERC TO PK_MVS_P2;
GRANT ALL ON CONTROL_EXERC TO PK_OFKIT;
GRANT ALL ON CONTROL_EXERC TO PK_OFKIT1;
GRANT ALL ON CONTROL_EXERC TO PK_OFKIT2;
GRANT ALL ON CONTROL_EXERC TO PK_OFKIT3;
GRANT ALL ON CONTROL_EXERC TO PK_OFKIT4;
GRANT ALL ON CONTROL_EXERC TO PK_OFKIT5;
GRANT ALL ON CONTROL_EXERC TO PK_OFKITP1;
GRANT ALL ON CONTROL_EXERC TO PK_OFKITP2;
GRANT ALL ON CONTROL_EXERC TO PK_OFK_1;
GRANT ALL ON CONTROL_EXERC TO PK_OFK_2;
GRANT ALL ON CONTROL_EXERC TO PK_OFK_3;
GRANT ALL ON CONTROL_EXERC TO PK_OFK_4;
GRANT ALL ON CONTROL_EXERC TO PK_OFK_P1;
GRANT ALL ON CONTROL_EXERC TO PK_OFK_P2;
GRANT ALL ON CONTROL_EXERC TO PK_OTV1;
GRANT ALL ON CONTROL_EXERC TO PK_OTV2;
GRANT ALL ON CONTROL_EXERC TO PK_OTV3;
GRANT ALL ON CONTROL_EXERC TO PK_OTV4;
GRANT ALL ON CONTROL_EXERC TO PK_SIIE;
GRANT ALL ON CONTROL_EXERC TO PK_SIIE1;
GRANT ALL ON CONTROL_EXERC TO PK_SIIE2;
GRANT ALL ON CONTROL_EXERC TO PK_SIIE3;
GRANT ALL ON CONTROL_EXERC TO PK_SIIE4;
GRANT ALL ON CONTROL_EXERC TO PK_SIIE5;
GRANT ALL ON CONTROL_EXERC TO PK_SIIEP1;
GRANT ALL ON CONTROL_EXERC TO PK_SIIEP2;
GRANT ALL ON CONTROL_EXERC TO PK_SIIEP3;
GRANT ALL ON CONTROL_EXERC TO PK_SIIE_1;
GRANT ALL ON CONTROL_EXERC TO PK_SIIE_2;
GRANT ALL ON CONTROL_EXERC TO PK_SIIE_3;
GRANT ALL ON CONTROL_EXERC TO PK_SIIE_4;
GRANT ALL ON CONTROL_EXERC TO PK_SIIE_P1;
GRANT ALL ON CONTROL_EXERC TO PK_SIIE_P2;