CREATE GENERATOR
    GEN_EXERCISE_ID;

CREATE TABLE IF NOT EXISTS
EXERCISE
(
    ID_EXERC    SMALLINT,
    NAME_EXERC  VARCHAR(255)
);




/******************************************************************************/
/***                              Primary keys                              ***/
/******************************************************************************/

ALTER TABLE
    EXERCISE
ADD
    CONSTRAINT
        PK_EXERCISE
    PRIMARY KEY
        (ID_EXERC);


/******************************************************************************/
/***                                Triggers                                ***/
/******************************************************************************/



SET TERM ^ ;



/******************************************************************************/
/***                          Triggers for tables                           ***/
/******************************************************************************/



/* Trigger: EXERCISE_BI */
CREATE OR ALTER
    TRIGGER
        EXERCISE_BI
FOR
    EXERCISE
ACTIVE
    BEFORE INSERT
        POSITION 0
AS
BEGIN
  IF (NEW.ID_EXERC IS NULL)
  THEN
    NEW.ID_EXERC = GEN_ID(GEN_EXERCISE_ID, 1);
END
^

SET TERM ; ^



/******************************************************************************/
/***                          Fields descriptions                           ***/
/******************************************************************************/

COMMENT ON COLUMN EXERCISE.ID_EXERC IS 
'ID контрольного упражнения';

COMMENT ON COLUMN EXERCISE.NAME_EXERC IS 
'Наименование контрольного упражнения';



/******************************************************************************/
/***                               Privileges                               ***/
/******************************************************************************/


/* Privileges of users */
GRANT ALL ON EXERCISE TO ABITUR1;
GRANT ALL ON EXERCISE TO ABITUR2;
GRANT ALL ON EXERCISE TO ABITUR3;
GRANT ALL ON EXERCISE TO ABITUR4;
GRANT ALL ON EXERCISE TO ABITURA;
GRANT ALL ON EXERCISE TO ALEXANDER_GONCHAROV;
GRANT ALL ON EXERCISE TO ASU;
GRANT ALL ON EXERCISE TO ASU1;
GRANT ALL ON EXERCISE TO ASU2;
GRANT ALL ON EXERCISE TO ASU3;
GRANT ALL ON EXERCISE TO ASU4;
GRANT ALL ON EXERCISE TO DEVELOPER;
GRANT ALL ON EXERCISE TO DEVELOPER2;
GRANT ALL ON EXERCISE TO IVANOVA_A;
GRANT ALL ON EXERCISE TO OKSANA;
GRANT ALL ON EXERCISE TO PK;
GRANT ALL ON EXERCISE TO PK_IT;
GRANT ALL ON EXERCISE TO PK_IT1;
GRANT ALL ON EXERCISE TO PK_IT2;
GRANT ALL ON EXERCISE TO PK_IT3;
GRANT ALL ON EXERCISE TO PK_IT4;
GRANT ALL ON EXERCISE TO PK_IT5;
GRANT ALL ON EXERCISE TO PK_MSTIG1;
GRANT ALL ON EXERCISE TO PK_MSTIG2;
GRANT ALL ON EXERCISE TO PK_MSTIG3;
GRANT ALL ON EXERCISE TO PK_MSTIG4;
GRANT ALL ON EXERCISE TO PK_MSTIGP1;
GRANT ALL ON EXERCISE TO PK_MSTIGP2;
GRANT ALL ON EXERCISE TO PK_MSTIG_1;
GRANT ALL ON EXERCISE TO PK_MSTIG_2;
GRANT ALL ON EXERCISE TO PK_MSTIG_3;
GRANT ALL ON EXERCISE TO PK_MSTIG_4;
GRANT ALL ON EXERCISE TO PK_MSTIG_P1;
GRANT ALL ON EXERCISE TO PK_MSTIG_P2;
GRANT ALL ON EXERCISE TO PK_MVS;
GRANT ALL ON EXERCISE TO PK_MVS1;
GRANT ALL ON EXERCISE TO PK_MVS2;
GRANT ALL ON EXERCISE TO PK_MVS3;
GRANT ALL ON EXERCISE TO PK_MVS4;
GRANT ALL ON EXERCISE TO PK_MVS5;
GRANT ALL ON EXERCISE TO PK_MVSP1;
GRANT ALL ON EXERCISE TO PK_MVSP2;
GRANT ALL ON EXERCISE TO PK_MVS_1;
GRANT ALL ON EXERCISE TO PK_MVS_2;
GRANT ALL ON EXERCISE TO PK_MVS_3;
GRANT ALL ON EXERCISE TO PK_MVS_4;
GRANT ALL ON EXERCISE TO PK_MVS_P1;
GRANT ALL ON EXERCISE TO PK_MVS_P2;
GRANT ALL ON EXERCISE TO PK_OFKIT;
GRANT ALL ON EXERCISE TO PK_OFKIT1;
GRANT ALL ON EXERCISE TO PK_OFKIT2;
GRANT ALL ON EXERCISE TO PK_OFKIT3;
GRANT ALL ON EXERCISE TO PK_OFKIT4;
GRANT ALL ON EXERCISE TO PK_OFKIT5;
GRANT ALL ON EXERCISE TO PK_OFKITP1;
GRANT ALL ON EXERCISE TO PK_OFKITP2;
GRANT ALL ON EXERCISE TO PK_OFK_1;
GRANT ALL ON EXERCISE TO PK_OFK_2;
GRANT ALL ON EXERCISE TO PK_OFK_3;
GRANT ALL ON EXERCISE TO PK_OFK_4;
GRANT ALL ON EXERCISE TO PK_OFK_P1;
GRANT ALL ON EXERCISE TO PK_OFK_P2;
GRANT ALL ON EXERCISE TO PK_OTV1;
GRANT ALL ON EXERCISE TO PK_OTV2;
GRANT ALL ON EXERCISE TO PK_OTV3;
GRANT ALL ON EXERCISE TO PK_OTV4;
GRANT ALL ON EXERCISE TO PK_SIIE;
GRANT ALL ON EXERCISE TO PK_SIIE1;
GRANT ALL ON EXERCISE TO PK_SIIE2;
GRANT ALL ON EXERCISE TO PK_SIIE3;
GRANT ALL ON EXERCISE TO PK_SIIE4;
GRANT ALL ON EXERCISE TO PK_SIIE5;
GRANT ALL ON EXERCISE TO PK_SIIEP1;
GRANT ALL ON EXERCISE TO PK_SIIEP2;
GRANT ALL ON EXERCISE TO PK_SIIEP3;
GRANT ALL ON EXERCISE TO PK_SIIE_1;
GRANT ALL ON EXERCISE TO PK_SIIE_2;
GRANT ALL ON EXERCISE TO PK_SIIE_3;
GRANT ALL ON EXERCISE TO PK_SIIE_4;
GRANT ALL ON EXERCISE TO PK_SIIE_P1;
GRANT ALL ON EXERCISE TO PK_SIIE_P2;