CREATE TABLE IF NOT EXISTS
FACULTY
(
    N_FAC    INTEGER,
    FAC      VARCHAR(70) COLLATE PXW_CYRL,
    FAC1     VARCHAR(20) COLLATE PXW_CYRL,
    KOD_FAC  SMALLINT,
    DEAN     VARCHAR(30),
    FAC_RP   VARCHAR(70)
);




/******************************************************************************/
/***                               Privileges                               ***/
/******************************************************************************/


/* Privileges of users */
GRANT ALL ON FACULTY TO ABITUR1;
GRANT ALL ON FACULTY TO ABITUR2;
GRANT ALL ON FACULTY TO ABITUR3;
GRANT ALL ON FACULTY TO ABITUR4;
GRANT ALL ON FACULTY TO ABITURA;
GRANT ALL ON FACULTY TO ALEXANDER_GONCHAROV;
GRANT ALL ON FACULTY TO DEVELOPER;
GRANT ALL ON FACULTY TO IVANOVA_A;
GRANT ALL ON FACULTY TO OKSANA;
GRANT ALL ON FACULTY TO PK_MSTIG1;
GRANT ALL ON FACULTY TO PK_MSTIG2;
GRANT ALL ON FACULTY TO PK_MSTIG3;
GRANT ALL ON FACULTY TO PK_MSTIG4;
GRANT ALL ON FACULTY TO PK_MSTIGP1;
GRANT ALL ON FACULTY TO PK_MSTIGP2;
GRANT ALL ON FACULTY TO PK_MSTIG_1;
GRANT ALL ON FACULTY TO PK_MSTIG_2;
GRANT ALL ON FACULTY TO PK_MSTIG_3;
GRANT ALL ON FACULTY TO PK_MSTIG_4;
GRANT ALL ON FACULTY TO PK_MSTIG_P1;
GRANT ALL ON FACULTY TO PK_MSTIG_P2;
GRANT ALL ON FACULTY TO PK_MVS1;
GRANT ALL ON FACULTY TO PK_MVS2;
GRANT ALL ON FACULTY TO PK_MVS3;
GRANT ALL ON FACULTY TO PK_MVSP1;
GRANT ALL ON FACULTY TO PK_MVSP2;
GRANT ALL ON FACULTY TO PK_MVS_1;
GRANT ALL ON FACULTY TO PK_MVS_2;
GRANT ALL ON FACULTY TO PK_MVS_3;
GRANT ALL ON FACULTY TO PK_MVS_4;
GRANT ALL ON FACULTY TO PK_MVS_P1;
GRANT ALL ON FACULTY TO PK_MVS_P2;
GRANT ALL ON FACULTY TO PK_OFKIT1;
GRANT ALL ON FACULTY TO PK_OFKIT2;
GRANT SELECT, INSERT, UPDATE, REFERENCES ON FACULTY TO PK_OFKIT3;
GRANT ALL ON FACULTY TO PK_OFKITP1;
GRANT ALL ON FACULTY TO PK_OFKITP2;
GRANT ALL ON FACULTY TO PK_OFK_1;
GRANT ALL ON FACULTY TO PK_OFK_2;
GRANT ALL ON FACULTY TO PK_OFK_3;
GRANT ALL ON FACULTY TO PK_OFK_4;
GRANT ALL ON FACULTY TO PK_OFK_P1;
GRANT ALL ON FACULTY TO PK_OFK_P2;
GRANT ALL ON FACULTY TO PK_OTV1;
GRANT ALL ON FACULTY TO PK_OTV2;
GRANT ALL ON FACULTY TO PK_OTV3;
GRANT ALL ON FACULTY TO PK_OTV4;
GRANT ALL ON FACULTY TO PK_SIIE1;
GRANT ALL ON FACULTY TO PK_SIIE2;
GRANT ALL ON FACULTY TO PK_SIIE3;
GRANT ALL ON FACULTY TO PK_SIIE4;
GRANT ALL ON FACULTY TO PK_SIIEP1;
GRANT ALL ON FACULTY TO PK_SIIEP2;
GRANT ALL ON FACULTY TO PK_SIIEP3;
GRANT ALL ON FACULTY TO PK_SIIE_1;
GRANT ALL ON FACULTY TO PK_SIIE_2;
GRANT ALL ON FACULTY TO PK_SIIE_3;
GRANT ALL ON FACULTY TO PK_SIIE_4;
GRANT ALL ON FACULTY TO PK_SIIE_P1;
GRANT ALL ON FACULTY TO PK_SIIE_P2;