CREATE TABLE IF NOT EXISTS
KOL_PLACE
(
    N_KOL_PLACE  SMALLINT,
    N_SPECIALIZ  SMALLINT,
    KOL_PLACE    SMALLINT,
    TEXT         SMALLINT,
    N_FAC        SMALLINT,
    VID_EDU      SMALLINT,
    PRICE        SMALLINT DEFAULT 0,
    RECRUIT      SMALLINT DEFAULT 1 NOT NULL
);




/******************************************************************************/
/***                              Primary keys                              ***/
/******************************************************************************/

ALTER TABLE
    KOL_PLACE
ADD
    PRIMARY KEY
        (N_KOL_PLACE);


/******************************************************************************/
/***                                Indices                                 ***/
/******************************************************************************/

CREATE INDEX KOL_PLACE_FAC          ON KOL_PLACE (N_FAC);
CREATE INDEX KOL_PLACE_FAC_EDU      ON KOL_PLACE (N_FAC, VID_EDU);
CREATE INDEX KOL_PLACE_FAC_EDU_SPEC ON KOL_PLACE (N_FAC, VID_EDU, N_SPECIALIZ);
CREATE INDEX KOL_PLACE_SPECIALIZ    ON KOL_PLACE (N_SPECIALIZ);
CREATE INDEX KOL_PLACE_TEXT         ON KOL_PLACE (TEXT);
CREATE INDEX KOL_PLACE_VID_EDU      ON KOL_PLACE (VID_EDU);


/******************************************************************************/
/***                                Triggers                                ***/
/******************************************************************************/



SET TERM ^ ;



/******************************************************************************/
/***                          Triggers for tables                           ***/
/******************************************************************************/



/* Trigger: TI_KOL_PLACE */
CREATE OR ALTER
    TRIGGER
        TI_KOL_PLACE
FOR
    KOL_PLACE
ACTIVE
    BEFORE INSERT
        POSITION 0
AS
BEGIN
NEW.N_KOL_PLACE = GEN_ID(KOL_PLACE_N_KOL_PLACE, 1);
END
^

SET TERM ; ^



/******************************************************************************/
/***                          Fields descriptions                           ***/
/******************************************************************************/

COMMENT ON COLUMN KOL_PLACE.TEXT IS 
'БЫЛО:
0 - город
1 - село
2 - целевые (и не использовалось)
3 - за оплату

СТАЛО:
0 - полная форма обучения
1 - сокращённая форма обучения';

COMMENT ON COLUMN KOL_PLACE.PRICE IS 
'Оплата:
0 - бюджет
1 - на платной основе';

COMMENT ON COLUMN KOL_PLACE.RECRUIT IS 
'0 - приём не проводится
1 - приём проводится';



/******************************************************************************/
/***                               Privileges                               ***/
/******************************************************************************/


/* Privileges of users */
GRANT ALL ON KOL_PLACE TO ABITUR1;
GRANT ALL ON KOL_PLACE TO ABITUR2;
GRANT ALL ON KOL_PLACE TO ABITUR3;
GRANT ALL ON KOL_PLACE TO ABITUR4;
GRANT ALL ON KOL_PLACE TO ABITURA;
GRANT ALL ON KOL_PLACE TO ALEXANDER_GONCHAROV;
GRANT ALL ON KOL_PLACE TO ASU;
GRANT ALL ON KOL_PLACE TO ASU1;
GRANT ALL ON KOL_PLACE TO ASU2;
GRANT ALL ON KOL_PLACE TO ASU3;
GRANT ALL ON KOL_PLACE TO ASU4;
GRANT ALL ON KOL_PLACE TO DEVELOPER;
GRANT ALL ON KOL_PLACE TO DEVELOPER2;
GRANT ALL ON KOL_PLACE TO IT1;
GRANT ALL ON KOL_PLACE TO IT2;
GRANT ALL ON KOL_PLACE TO IT3;
GRANT ALL ON KOL_PLACE TO IVANOVA_A;
GRANT ALL ON KOL_PLACE TO MVS1;
GRANT ALL ON KOL_PLACE TO MVS2;
GRANT ALL ON KOL_PLACE TO MVS3;
GRANT ALL ON KOL_PLACE TO MVS4;
GRANT ALL ON KOL_PLACE TO OFKIT1;
GRANT ALL ON KOL_PLACE TO OFKIT2;
GRANT ALL ON KOL_PLACE TO OFKIT3;
GRANT ALL ON KOL_PLACE TO OFKIT4;
GRANT ALL ON KOL_PLACE TO OKSANA;
GRANT ALL ON KOL_PLACE TO PK;
GRANT ALL ON KOL_PLACE TO PK_IT;
GRANT ALL ON KOL_PLACE TO PK_IT1;
GRANT ALL ON KOL_PLACE TO PK_IT2;
GRANT ALL ON KOL_PLACE TO PK_IT3;
GRANT ALL ON KOL_PLACE TO PK_IT4;
GRANT ALL ON KOL_PLACE TO PK_IT5;
GRANT ALL ON KOL_PLACE TO PK_MSTIG1;
GRANT ALL ON KOL_PLACE TO PK_MSTIG2;
GRANT ALL ON KOL_PLACE TO PK_MSTIG3;
GRANT ALL ON KOL_PLACE TO PK_MSTIG4;
GRANT ALL ON KOL_PLACE TO PK_MSTIGP1;
GRANT ALL ON KOL_PLACE TO PK_MSTIGP2;
GRANT ALL ON KOL_PLACE TO PK_MSTIG_1;
GRANT ALL ON KOL_PLACE TO PK_MSTIG_2;
GRANT ALL ON KOL_PLACE TO PK_MSTIG_3;
GRANT ALL ON KOL_PLACE TO PK_MSTIG_4;
GRANT ALL ON KOL_PLACE TO PK_MSTIG_P1;
GRANT ALL ON KOL_PLACE TO PK_MSTIG_P2;
GRANT ALL ON KOL_PLACE TO PK_MVS;
GRANT ALL ON KOL_PLACE TO PK_MVS1;
GRANT ALL ON KOL_PLACE TO PK_MVS2;
GRANT ALL ON KOL_PLACE TO PK_MVS3;
GRANT ALL ON KOL_PLACE TO PK_MVS4;
GRANT ALL ON KOL_PLACE TO PK_MVS5;
GRANT ALL ON KOL_PLACE TO PK_MVSP1;
GRANT ALL ON KOL_PLACE TO PK_MVSP2;
GRANT ALL ON KOL_PLACE TO PK_MVS_1;
GRANT ALL ON KOL_PLACE TO PK_MVS_2;
GRANT ALL ON KOL_PLACE TO PK_MVS_3;
GRANT ALL ON KOL_PLACE TO PK_MVS_4;
GRANT ALL ON KOL_PLACE TO PK_MVS_P1;
GRANT ALL ON KOL_PLACE TO PK_MVS_P2;
GRANT ALL ON KOL_PLACE TO PK_OFKIT;
GRANT ALL ON KOL_PLACE TO PK_OFKIT1;
GRANT ALL ON KOL_PLACE TO PK_OFKIT2;
GRANT ALL ON KOL_PLACE TO PK_OFKIT3;
GRANT ALL ON KOL_PLACE TO PK_OFKIT4;
GRANT ALL ON KOL_PLACE TO PK_OFKIT5;
GRANT ALL ON KOL_PLACE TO PK_OFKITP1;
GRANT ALL ON KOL_PLACE TO PK_OFKITP2;
GRANT ALL ON KOL_PLACE TO PK_OFK_1;
GRANT ALL ON KOL_PLACE TO PK_OFK_2;
GRANT ALL ON KOL_PLACE TO PK_OFK_3;
GRANT ALL ON KOL_PLACE TO PK_OFK_4;
GRANT ALL ON KOL_PLACE TO PK_OFK_P1;
GRANT ALL ON KOL_PLACE TO PK_OFK_P2;
GRANT ALL ON KOL_PLACE TO PK_OTV1;
GRANT ALL ON KOL_PLACE TO PK_OTV2;
GRANT ALL ON KOL_PLACE TO PK_OTV3;
GRANT ALL ON KOL_PLACE TO PK_OTV4;
GRANT ALL ON KOL_PLACE TO PK_SIIE;
GRANT ALL ON KOL_PLACE TO PK_SIIE1;
GRANT ALL ON KOL_PLACE TO PK_SIIE2;
GRANT ALL ON KOL_PLACE TO PK_SIIE3;
GRANT ALL ON KOL_PLACE TO PK_SIIE4;
GRANT ALL ON KOL_PLACE TO PK_SIIE5;
GRANT ALL ON KOL_PLACE TO PK_SIIEP1;
GRANT ALL ON KOL_PLACE TO PK_SIIEP2;
GRANT ALL ON KOL_PLACE TO PK_SIIEP3;
GRANT ALL ON KOL_PLACE TO PK_SIIE_1;
GRANT ALL ON KOL_PLACE TO PK_SIIE_2;
GRANT ALL ON KOL_PLACE TO PK_SIIE_3;
GRANT ALL ON KOL_PLACE TO PK_SIIE_4;
GRANT ALL ON KOL_PLACE TO PK_SIIE_P1;
GRANT ALL ON KOL_PLACE TO PK_SIIE_P2;
GRANT ALL ON KOL_PLACE TO SIIE1;
GRANT ALL ON KOL_PLACE TO SIIE2;
GRANT ALL ON KOL_PLACE TO SIIE3;
GRANT ALL ON KOL_PLACE TO SIIE4;
GRANT ALL ON KOL_PLACE TO UO_LAB;
GRANT ALL ON KOL_PLACE TO UO_N;
GRANT ALL ON KOL_PLACE TO UO_Z;