CREATE TABLE IF NOT EXISTS
LIST_DOC
(
    NOMER_AB   INTEGER NOT NULL,
    N_DOC      SMALLINT NOT NULL,
    DATE_DOC   DATE,
    DOC_INDEX  VARCHAR(20)
);




/******************************************************************************/
/***                               Privileges                               ***/
/******************************************************************************/


/* Privileges of users */
GRANT ALL ON LIST_DOC TO ABITUR1;
GRANT ALL ON LIST_DOC TO ABITUR2;
GRANT ALL ON LIST_DOC TO ABITUR3;
GRANT ALL ON LIST_DOC TO ABITUR4;
GRANT ALL ON LIST_DOC TO ABITURA;
GRANT ALL ON LIST_DOC TO ALEXANDER_GONCHAROV;
GRANT ALL ON LIST_DOC TO ANNA;
GRANT ALL ON LIST_DOC TO ASPIRANTURA;
GRANT ALL ON LIST_DOC TO ASU;
GRANT ALL ON LIST_DOC TO ASU1;
GRANT ALL ON LIST_DOC TO ASU2;
GRANT ALL ON LIST_DOC TO ASU3;
GRANT ALL ON LIST_DOC TO ASU4;
GRANT ALL ON LIST_DOC TO BAKS68878;
GRANT ALL ON LIST_DOC TO DEV;
GRANT ALL ON LIST_DOC TO DEVELOPER;
GRANT ALL ON LIST_DOC TO DEVELOPER2;
GRANT ALL ON LIST_DOC TO DOBROVOLSKAYA;
GRANT ALL ON LIST_DOC TO GUNICH_OKSANA;
GRANT ALL ON LIST_DOC TO IT1;
GRANT ALL ON LIST_DOC TO IT2;
GRANT ALL ON LIST_DOC TO IT3;
GRANT ALL ON LIST_DOC TO IT5;
GRANT ALL ON LIST_DOC TO IT7;
GRANT ALL ON LIST_DOC TO IT_8;
GRANT ALL ON LIST_DOC TO IT_Z;
GRANT ALL ON LIST_DOC TO IVANOVA_A;
GRANT ALL ON LIST_DOC TO JKMUF2507;
GRANT ALL ON LIST_DOC TO LAVRENOVA_V;
GRANT ALL ON LIST_DOC TO LENAUSOVA;
GRANT ALL ON LIST_DOC TO MAGISTR;
GRANT ALL ON LIST_DOC TO MATUSEVICH;
GRANT ALL ON LIST_DOC TO MVS1;
GRANT ALL ON LIST_DOC TO MVS2;
GRANT ALL ON LIST_DOC TO MVS3;
GRANT ALL ON LIST_DOC TO MVS4;
GRANT ALL ON LIST_DOC TO MVS_D;
GRANT ALL ON LIST_DOC TO MVS_Z;
GRANT ALL ON LIST_DOC TO MVS_Z_L;
GRANT ALL ON LIST_DOC TO M_2;
GRANT ALL ON LIST_DOC TO OFKIT1;
GRANT ALL ON LIST_DOC TO OFKIT2;
GRANT ALL ON LIST_DOC TO OFKIT3;
GRANT ALL ON LIST_DOC TO OFKIT4;
GRANT ALL ON LIST_DOC TO OFKIT_A;
GRANT ALL ON LIST_DOC TO OFKIT_D;
GRANT ALL ON LIST_DOC TO OFKIT_M;
GRANT ALL ON LIST_DOC TO OFKIT_N;
GRANT ALL ON LIST_DOC TO OKSANA;
GRANT ALL ON LIST_DOC TO OK_STUD_1;
GRANT ALL ON LIST_DOC TO PK;
GRANT ALL ON LIST_DOC TO PK_IT;
GRANT ALL ON LIST_DOC TO PK_IT1;
GRANT ALL ON LIST_DOC TO PK_IT2;
GRANT ALL ON LIST_DOC TO PK_IT3;
GRANT ALL ON LIST_DOC TO PK_IT4;
GRANT ALL ON LIST_DOC TO PK_IT5;
GRANT ALL ON LIST_DOC TO PK_MSTIG1;
GRANT ALL ON LIST_DOC TO PK_MSTIG2;
GRANT ALL ON LIST_DOC TO PK_MSTIG3;
GRANT ALL ON LIST_DOC TO PK_MSTIG4;
GRANT ALL ON LIST_DOC TO PK_MSTIGP1;
GRANT ALL ON LIST_DOC TO PK_MSTIGP2;
GRANT ALL ON LIST_DOC TO PK_MSTIG_1;
GRANT ALL ON LIST_DOC TO PK_MSTIG_2;
GRANT ALL ON LIST_DOC TO PK_MSTIG_3;
GRANT ALL ON LIST_DOC TO PK_MSTIG_4;
GRANT ALL ON LIST_DOC TO PK_MSTIG_P1;
GRANT ALL ON LIST_DOC TO PK_MSTIG_P2;
GRANT ALL ON LIST_DOC TO PK_MVS;
GRANT ALL ON LIST_DOC TO PK_MVS1;
GRANT ALL ON LIST_DOC TO PK_MVS2;
GRANT ALL ON LIST_DOC TO PK_MVS3;
GRANT ALL ON LIST_DOC TO PK_MVS4;
GRANT ALL ON LIST_DOC TO PK_MVS5;
GRANT ALL ON LIST_DOC TO PK_MVSP1;
GRANT ALL ON LIST_DOC TO PK_MVSP2;
GRANT ALL ON LIST_DOC TO PK_MVS_1;
GRANT ALL ON LIST_DOC TO PK_MVS_2;
GRANT ALL ON LIST_DOC TO PK_MVS_3;
GRANT ALL ON LIST_DOC TO PK_MVS_4;
GRANT ALL ON LIST_DOC TO PK_MVS_P1;
GRANT ALL ON LIST_DOC TO PK_MVS_P2;
GRANT ALL ON LIST_DOC TO PK_OFKIT;
GRANT ALL ON LIST_DOC TO PK_OFKIT1;
GRANT ALL ON LIST_DOC TO PK_OFKIT2;
GRANT ALL ON LIST_DOC TO PK_OFKIT3;
GRANT ALL ON LIST_DOC TO PK_OFKIT4;
GRANT ALL ON LIST_DOC TO PK_OFKIT5;
GRANT ALL ON LIST_DOC TO PK_OFKITP1;
GRANT ALL ON LIST_DOC TO PK_OFKITP2;
GRANT ALL ON LIST_DOC TO PK_OFK_1;
GRANT ALL ON LIST_DOC TO PK_OFK_2;
GRANT ALL ON LIST_DOC TO PK_OFK_3;
GRANT ALL ON LIST_DOC TO PK_OFK_4;
GRANT ALL ON LIST_DOC TO PK_OFK_P1;
GRANT ALL ON LIST_DOC TO PK_OFK_P2;
GRANT ALL ON LIST_DOC TO PK_OTV1;
GRANT ALL ON LIST_DOC TO PK_OTV2;
GRANT ALL ON LIST_DOC TO PK_OTV3;
GRANT ALL ON LIST_DOC TO PK_OTV4;
GRANT ALL ON LIST_DOC TO PK_SIIE;
GRANT ALL ON LIST_DOC TO PK_SIIE1;
GRANT ALL ON LIST_DOC TO PK_SIIE2;
GRANT ALL ON LIST_DOC TO PK_SIIE3;
GRANT ALL ON LIST_DOC TO PK_SIIE4;
GRANT ALL ON LIST_DOC TO PK_SIIE5;
GRANT ALL ON LIST_DOC TO PK_SIIEP1;
GRANT ALL ON LIST_DOC TO PK_SIIEP2;
GRANT ALL ON LIST_DOC TO PK_SIIEP3;
GRANT ALL ON LIST_DOC TO PK_SIIE_1;
GRANT ALL ON LIST_DOC TO PK_SIIE_2;
GRANT ALL ON LIST_DOC TO PK_SIIE_3;
GRANT ALL ON LIST_DOC TO PK_SIIE_4;
GRANT ALL ON LIST_DOC TO PK_SIIE_P1;
GRANT ALL ON LIST_DOC TO PK_SIIE_P2;
GRANT ALL ON LIST_DOC TO PLANIDA_E;
GRANT ALL ON LIST_DOC TO PUBLIC;
GRANT ALL ON LIST_DOC TO SHMAENKOVA_M;
GRANT ALL ON LIST_DOC TO SIIE1;
GRANT ALL ON LIST_DOC TO SIIE1234;
GRANT ALL ON LIST_DOC TO SIIE2;
GRANT ALL ON LIST_DOC TO SIIE3;
GRANT ALL ON LIST_DOC TO SIIE4;
GRANT ALL ON LIST_DOC TO SIIE_Z1;
GRANT ALL ON LIST_DOC TO STUD_KADR1;
GRANT ALL ON LIST_DOC TO STUD_KADR4;
GRANT ALL ON LIST_DOC TO SVETA;
GRANT ALL ON LIST_DOC TO UO_LAB;
GRANT ALL ON LIST_DOC TO UO_N;
GRANT ALL ON LIST_DOC TO UO_Z;
GRANT ALL ON LIST_DOC TO VIEWER_MOB;
GRANT ALL ON LIST_DOC TO VNUK;
GRANT ALL ON LIST_DOC TO VOROBEI75;
GRANT ALL ON LIST_DOC TO YAUHENI_HATSURA;