
CREATE TABLE IF NOT EXISTS
LOCALITY
(
    ID             INTEGER,
    N_REGION       SMALLINT,
    N_DISTRICT     SMALLINT,
    NAME_LOCALITY  VARCHAR(30),
    CODE_SOATO     VARCHAR(30),
    CODE_CATEGORY  SMALLINT,
    TYPE_LOCALITY  SMALLINT
);