CREATE TABLE IF NOT EXISTS
N_GROUP
(
    N_GROUP      SMALLINT,
    NOM_GROUP    VARCHAR(5) COLLATE PXW_CYRL,
    N_SPECIALIZ  SMALLINT,
    VID_EDU      SMALLINT,
    DESCRIBE     VARCHAR(150),
    N_FAC        SMALLINT,
    N_COUNT      SMALLINT
);




/******************************************************************************/
/***                                Indices                                 ***/
/******************************************************************************/

CREATE        INDEX N_GROUP_COUNT        ON N_GROUP (N_COUNT);
CREATE        INDEX N_GROUP_DESC         ON N_GROUP (DESCRIBE);
CREATE        INDEX N_GROUP_FAC          ON N_GROUP (N_FAC);
CREATE        INDEX N_GROUP_FAC_EDU      ON N_GROUP (N_FAC, VID_EDU);
CREATE        INDEX N_GROUP_FAC_EDU_DESC ON N_GROUP (N_FAC, VID_EDU, DESCRIBE);
CREATE UNIQUE INDEX N_GROUP_INC          ON N_GROUP (N_GROUP);
CREATE        INDEX N_GROUP_NOM_GROUP    ON N_GROUP (NOM_GROUP);
CREATE        INDEX N_GROUP_VID_EDU      ON N_GROUP (VID_EDU);


/******************************************************************************/
/***                                Triggers                                ***/
/******************************************************************************/



SET TERM ^ ;



/******************************************************************************/
/***                          Triggers for tables                           ***/
/******************************************************************************/



/* Trigger: INS_N_GROUP */
CREATE OR ALTER
    TRIGGER
        INS_N_GROUP
FOR
    N_GROUP
ACTIVE
    BEFORE INSERT
        POSITION 0
AS
BEGIN
NEW.N_GROUP = GEN_ID(NOMER_GROUP, 1);
END
^

SET TERM ; ^



/******************************************************************************/
/***                               Privileges                               ***/
/******************************************************************************/


/* Privileges of users */
GRANT ALL ON N_GROUP TO ABITUR1;
GRANT ALL ON N_GROUP TO ABITUR2;
GRANT ALL ON N_GROUP TO ABITUR3;
GRANT ALL ON N_GROUP TO ABITUR4;
GRANT ALL ON N_GROUP TO ABITURA;
GRANT ALL ON N_GROUP TO ALEXANDER_GONCHAROV;
GRANT ALL ON N_GROUP TO ASU;
GRANT ALL ON N_GROUP TO ASU1;
GRANT ALL ON N_GROUP TO ASU2;
GRANT ALL ON N_GROUP TO ASU3;
GRANT ALL ON N_GROUP TO ASU4;
GRANT ALL ON N_GROUP TO DEVELOPER;
GRANT ALL ON N_GROUP TO DEVELOPER2;
GRANT ALL ON N_GROUP TO IT1;
GRANT ALL ON N_GROUP TO IT2;
GRANT ALL ON N_GROUP TO IT3;
GRANT ALL ON N_GROUP TO IVANOVA_A;
GRANT ALL ON N_GROUP TO MVS1;
GRANT ALL ON N_GROUP TO MVS2;
GRANT ALL ON N_GROUP TO MVS3;
GRANT ALL ON N_GROUP TO MVS4;
GRANT ALL ON N_GROUP TO OFKIT1;
GRANT ALL ON N_GROUP TO OFKIT2;
GRANT ALL ON N_GROUP TO OFKIT3;
GRANT ALL ON N_GROUP TO OFKIT4;
GRANT ALL ON N_GROUP TO OKSANA;
GRANT ALL ON N_GROUP TO PK;
GRANT ALL ON N_GROUP TO PK_IT;
GRANT ALL ON N_GROUP TO PK_IT1;
GRANT ALL ON N_GROUP TO PK_IT2;
GRANT ALL ON N_GROUP TO PK_IT3;
GRANT ALL ON N_GROUP TO PK_IT4;
GRANT ALL ON N_GROUP TO PK_IT5;
GRANT ALL ON N_GROUP TO PK_MSTIG1;
GRANT ALL ON N_GROUP TO PK_MSTIG2;
GRANT ALL ON N_GROUP TO PK_MSTIG3;
GRANT ALL ON N_GROUP TO PK_MSTIG4;
GRANT ALL ON N_GROUP TO PK_MSTIGP1;
GRANT ALL ON N_GROUP TO PK_MSTIGP2;
GRANT ALL ON N_GROUP TO PK_MSTIG_1;
GRANT ALL ON N_GROUP TO PK_MSTIG_2;
GRANT ALL ON N_GROUP TO PK_MSTIG_3;
GRANT ALL ON N_GROUP TO PK_MSTIG_4;
GRANT ALL ON N_GROUP TO PK_MSTIG_P1;
GRANT ALL ON N_GROUP TO PK_MSTIG_P2;
GRANT ALL ON N_GROUP TO PK_MVS;
GRANT ALL ON N_GROUP TO PK_MVS1;
GRANT ALL ON N_GROUP TO PK_MVS2;
GRANT ALL ON N_GROUP TO PK_MVS3;
GRANT ALL ON N_GROUP TO PK_MVS4;
GRANT ALL ON N_GROUP TO PK_MVS5;
GRANT ALL ON N_GROUP TO PK_MVSP1;
GRANT ALL ON N_GROUP TO PK_MVSP2;
GRANT ALL ON N_GROUP TO PK_MVS_1;
GRANT ALL ON N_GROUP TO PK_MVS_2;
GRANT ALL ON N_GROUP TO PK_MVS_3;
GRANT ALL ON N_GROUP TO PK_MVS_4;
GRANT ALL ON N_GROUP TO PK_MVS_P1;
GRANT ALL ON N_GROUP TO PK_MVS_P2;
GRANT ALL ON N_GROUP TO PK_OFKIT;
GRANT ALL ON N_GROUP TO PK_OFKIT1;
GRANT ALL ON N_GROUP TO PK_OFKIT2;
GRANT ALL ON N_GROUP TO PK_OFKIT3;
GRANT ALL ON N_GROUP TO PK_OFKIT4;
GRANT ALL ON N_GROUP TO PK_OFKIT5;
GRANT ALL ON N_GROUP TO PK_OFKITP1;
GRANT ALL ON N_GROUP TO PK_OFKITP2;
GRANT ALL ON N_GROUP TO PK_OFK_1;
GRANT ALL ON N_GROUP TO PK_OFK_2;
GRANT ALL ON N_GROUP TO PK_OFK_3;
GRANT ALL ON N_GROUP TO PK_OFK_4;
GRANT ALL ON N_GROUP TO PK_OFK_P1;
GRANT ALL ON N_GROUP TO PK_OFK_P2;
GRANT ALL ON N_GROUP TO PK_OTV1;
GRANT ALL ON N_GROUP TO PK_OTV2;
GRANT ALL ON N_GROUP TO PK_OTV3;
GRANT ALL ON N_GROUP TO PK_OTV4;
GRANT ALL ON N_GROUP TO PK_SIIE;
GRANT ALL ON N_GROUP TO PK_SIIE1;
GRANT ALL ON N_GROUP TO PK_SIIE2;
GRANT ALL ON N_GROUP TO PK_SIIE3;
GRANT ALL ON N_GROUP TO PK_SIIE4;
GRANT ALL ON N_GROUP TO PK_SIIE5;
GRANT ALL ON N_GROUP TO PK_SIIEP1;
GRANT ALL ON N_GROUP TO PK_SIIEP2;
GRANT ALL ON N_GROUP TO PK_SIIEP3;
GRANT ALL ON N_GROUP TO PK_SIIE_1;
GRANT ALL ON N_GROUP TO PK_SIIE_2;
GRANT ALL ON N_GROUP TO PK_SIIE_3;
GRANT ALL ON N_GROUP TO PK_SIIE_4;
GRANT ALL ON N_GROUP TO PK_SIIE_P1;
GRANT ALL ON N_GROUP TO PK_SIIE_P2;
GRANT ALL ON N_GROUP TO SIIE1;
GRANT ALL ON N_GROUP TO SIIE2;
GRANT ALL ON N_GROUP TO SIIE3;
GRANT ALL ON N_GROUP TO SIIE4;
GRANT ALL ON N_GROUP TO UO_LAB;
GRANT ALL ON N_GROUP TO UO_N;
GRANT ALL ON N_GROUP TO UO_Z;