CREATE GENERATOR
    GEN_ORDER_SPECIALIZ_ID;

CREATE TABLE IF NOT EXISTS
ORDER_SPECIALIZ
(
    N_OR_SPEC    INTEGER,
    N_SPECIALIZ  INTEGER,
    ORDER_SP     INTEGER
);




/******************************************************************************/
/***                              Primary keys                              ***/
/******************************************************************************/

ALTER TABLE
    ORDER_SPECIALIZ
ADD
    PRIMARY KEY
        (N_OR_SPEC);


/******************************************************************************/
/***                                Indices                                 ***/
/******************************************************************************/

CREATE INDEX OR_SPEC_ORDER     ON ORDER_SPECIALIZ (ORDER_SP);
CREATE INDEX OR_SPEC_OR_SP     ON ORDER_SPECIALIZ (N_SPECIALIZ, ORDER_SP);
CREATE INDEX OR_SPEC_SPECIALIZ ON ORDER_SPECIALIZ (N_SPECIALIZ);


/******************************************************************************/
/***                                Triggers                                ***/
/******************************************************************************/



SET TERM ^ ;



/******************************************************************************/
/***                          Triggers for tables                           ***/
/******************************************************************************/



/* Trigger: ORDER_SPECIALIZ_BI */
CREATE OR ALTER
    TRIGGER
        ORDER_SPECIALIZ_BI
FOR
    ORDER_SPECIALIZ
ACTIVE
    BEFORE INSERT
        POSITION 0
AS
BEGIN
  IF (NEW.N_OR_SPEC IS NULL)
  THEN
    NEW.N_OR_SPEC = GEN_ID(GEN_ORDER_SPECIALIZ_ID, 1);
END
^

SET TERM ; ^



/******************************************************************************/
/***                          Fields descriptions                           ***/
/******************************************************************************/

COMMENT ON COLUMN ORDER_SPECIALIZ.N_OR_SPEC IS 
'Инкремент';

COMMENT ON COLUMN ORDER_SPECIALIZ.N_SPECIALIZ IS 
'Номер специализации';

COMMENT ON COLUMN ORDER_SPECIALIZ.ORDER_SP IS 
'Порядковый номер для показа';



/******************************************************************************/
/***                               Privileges                               ***/
/******************************************************************************/


/* Privileges of users */
GRANT ALL ON ORDER_SPECIALIZ TO ABITUR1;
GRANT ALL ON ORDER_SPECIALIZ TO ABITUR2;
GRANT ALL ON ORDER_SPECIALIZ TO ABITUR3;
GRANT ALL ON ORDER_SPECIALIZ TO ABITUR4;
GRANT ALL ON ORDER_SPECIALIZ TO ABITURA;
GRANT ALL ON ORDER_SPECIALIZ TO ALEXANDER_GONCHAROV;
GRANT ALL ON ORDER_SPECIALIZ TO ASU;
GRANT ALL ON ORDER_SPECIALIZ TO ASU1;
GRANT ALL ON ORDER_SPECIALIZ TO ASU2;
GRANT ALL ON ORDER_SPECIALIZ TO ASU3;
GRANT ALL ON ORDER_SPECIALIZ TO ASU4;
GRANT ALL ON ORDER_SPECIALIZ TO DEVELOPER;
GRANT ALL ON ORDER_SPECIALIZ TO DEVELOPER2;
GRANT ALL ON ORDER_SPECIALIZ TO IT1;
GRANT ALL ON ORDER_SPECIALIZ TO IT2;
GRANT ALL ON ORDER_SPECIALIZ TO IT3;
GRANT ALL ON ORDER_SPECIALIZ TO IVANOVA_A;
GRANT ALL ON ORDER_SPECIALIZ TO MVS1;
GRANT ALL ON ORDER_SPECIALIZ TO MVS2;
GRANT ALL ON ORDER_SPECIALIZ TO MVS3;
GRANT ALL ON ORDER_SPECIALIZ TO MVS4;
GRANT ALL ON ORDER_SPECIALIZ TO OFKIT1;
GRANT ALL ON ORDER_SPECIALIZ TO OFKIT2;
GRANT ALL ON ORDER_SPECIALIZ TO OFKIT3;
GRANT ALL ON ORDER_SPECIALIZ TO OFKIT4;
GRANT ALL ON ORDER_SPECIALIZ TO OKSANA;
GRANT ALL ON ORDER_SPECIALIZ TO PK;
GRANT ALL ON ORDER_SPECIALIZ TO PK_IT;
GRANT ALL ON ORDER_SPECIALIZ TO PK_IT1;
GRANT ALL ON ORDER_SPECIALIZ TO PK_IT2;
GRANT ALL ON ORDER_SPECIALIZ TO PK_IT3;
GRANT ALL ON ORDER_SPECIALIZ TO PK_IT4;
GRANT ALL ON ORDER_SPECIALIZ TO PK_IT5;
GRANT ALL ON ORDER_SPECIALIZ TO PK_MSTIG1;
GRANT ALL ON ORDER_SPECIALIZ TO PK_MSTIG2;
GRANT ALL ON ORDER_SPECIALIZ TO PK_MSTIG3;
GRANT ALL ON ORDER_SPECIALIZ TO PK_MSTIG4;
GRANT ALL ON ORDER_SPECIALIZ TO PK_MSTIGP1;
GRANT ALL ON ORDER_SPECIALIZ TO PK_MSTIGP2;
GRANT ALL ON ORDER_SPECIALIZ TO PK_MSTIG_1;
GRANT ALL ON ORDER_SPECIALIZ TO PK_MSTIG_2;
GRANT ALL ON ORDER_SPECIALIZ TO PK_MSTIG_3;
GRANT ALL ON ORDER_SPECIALIZ TO PK_MSTIG_4;
GRANT ALL ON ORDER_SPECIALIZ TO PK_MSTIG_P1;
GRANT ALL ON ORDER_SPECIALIZ TO PK_MSTIG_P2;
GRANT ALL ON ORDER_SPECIALIZ TO PK_MVS;
GRANT ALL ON ORDER_SPECIALIZ TO PK_MVS1;
GRANT ALL ON ORDER_SPECIALIZ TO PK_MVS2;
GRANT ALL ON ORDER_SPECIALIZ TO PK_MVS3;
GRANT ALL ON ORDER_SPECIALIZ TO PK_MVS4;
GRANT ALL ON ORDER_SPECIALIZ TO PK_MVS5;
GRANT ALL ON ORDER_SPECIALIZ TO PK_MVSP1;
GRANT ALL ON ORDER_SPECIALIZ TO PK_MVSP2;
GRANT ALL ON ORDER_SPECIALIZ TO PK_MVS_1;
GRANT ALL ON ORDER_SPECIALIZ TO PK_MVS_2;
GRANT ALL ON ORDER_SPECIALIZ TO PK_MVS_3;
GRANT ALL ON ORDER_SPECIALIZ TO PK_MVS_4;
GRANT ALL ON ORDER_SPECIALIZ TO PK_MVS_P1;
GRANT ALL ON ORDER_SPECIALIZ TO PK_MVS_P2;
GRANT ALL ON ORDER_SPECIALIZ TO PK_OFKIT;
GRANT ALL ON ORDER_SPECIALIZ TO PK_OFKIT1;
GRANT ALL ON ORDER_SPECIALIZ TO PK_OFKIT2;
GRANT ALL ON ORDER_SPECIALIZ TO PK_OFKIT3;
GRANT ALL ON ORDER_SPECIALIZ TO PK_OFKIT4;
GRANT ALL ON ORDER_SPECIALIZ TO PK_OFKIT5;
GRANT ALL ON ORDER_SPECIALIZ TO PK_OFKITP1;
GRANT ALL ON ORDER_SPECIALIZ TO PK_OFKITP2;
GRANT ALL ON ORDER_SPECIALIZ TO PK_OFK_1;
GRANT ALL ON ORDER_SPECIALIZ TO PK_OFK_2;
GRANT ALL ON ORDER_SPECIALIZ TO PK_OFK_3;
GRANT ALL ON ORDER_SPECIALIZ TO PK_OFK_4;
GRANT ALL ON ORDER_SPECIALIZ TO PK_OFK_P1;
GRANT ALL ON ORDER_SPECIALIZ TO PK_OFK_P2;
GRANT ALL ON ORDER_SPECIALIZ TO PK_OTV1;
GRANT ALL ON ORDER_SPECIALIZ TO PK_OTV2;
GRANT ALL ON ORDER_SPECIALIZ TO PK_OTV3;
GRANT ALL ON ORDER_SPECIALIZ TO PK_OTV4;
GRANT ALL ON ORDER_SPECIALIZ TO PK_SIIE;
GRANT ALL ON ORDER_SPECIALIZ TO PK_SIIE1;
GRANT ALL ON ORDER_SPECIALIZ TO PK_SIIE2;
GRANT ALL ON ORDER_SPECIALIZ TO PK_SIIE3;
GRANT ALL ON ORDER_SPECIALIZ TO PK_SIIE4;
GRANT ALL ON ORDER_SPECIALIZ TO PK_SIIE5;
GRANT ALL ON ORDER_SPECIALIZ TO PK_SIIEP1;
GRANT ALL ON ORDER_SPECIALIZ TO PK_SIIEP2;
GRANT ALL ON ORDER_SPECIALIZ TO PK_SIIEP3;
GRANT ALL ON ORDER_SPECIALIZ TO PK_SIIE_1;
GRANT ALL ON ORDER_SPECIALIZ TO PK_SIIE_2;
GRANT ALL ON ORDER_SPECIALIZ TO PK_SIIE_3;
GRANT ALL ON ORDER_SPECIALIZ TO PK_SIIE_4;
GRANT ALL ON ORDER_SPECIALIZ TO PK_SIIE_P1;
GRANT ALL ON ORDER_SPECIALIZ TO PK_SIIE_P2;
GRANT ALL ON ORDER_SPECIALIZ TO SIIE1;
GRANT ALL ON ORDER_SPECIALIZ TO SIIE2;
GRANT ALL ON ORDER_SPECIALIZ TO SIIE3;
GRANT ALL ON ORDER_SPECIALIZ TO SIIE4;
GRANT ALL ON ORDER_SPECIALIZ TO UO_LAB;
GRANT ALL ON ORDER_SPECIALIZ TO UO_N;
GRANT ALL ON ORDER_SPECIALIZ TO UO_Z;