CREATE TABLE IF NOT EXISTS
PERSONAL_TYPE
(
    ID_TYPE    INTEGER NOT NULL,
    NAME_TYPE  VARCHAR(50) COLLATE PXW_CYRL
);




/******************************************************************************/
/***                              Primary keys                              ***/
/******************************************************************************/

ALTER TABLE
    PERSONAL_TYPE
ADD
    CONSTRAINT
        PK_PERSONAL_TYPE
    PRIMARY KEY
        (ID_TYPE);


/******************************************************************************/
/***                               Privileges                               ***/
/******************************************************************************/


/* Privileges of users */
GRANT ALL ON PERSONAL_TYPE TO ABITUR1;
GRANT ALL ON PERSONAL_TYPE TO ABITURA;
GRANT ALL ON PERSONAL_TYPE TO ALEXANDER_GONCHAROV;
GRANT ALL ON PERSONAL_TYPE TO DEVELOPER;
GRANT ALL ON PERSONAL_TYPE TO IVANOVA_A;
GRANT ALL ON PERSONAL_TYPE TO OKSANA;
GRANT ALL ON PERSONAL_TYPE TO PK_MSTIG_1;
GRANT ALL ON PERSONAL_TYPE TO PK_MSTIG_2;
GRANT ALL ON PERSONAL_TYPE TO PK_MSTIG_3;
GRANT ALL ON PERSONAL_TYPE TO PK_MSTIG_4;
GRANT ALL ON PERSONAL_TYPE TO PK_MSTIG_P1;
GRANT ALL ON PERSONAL_TYPE TO PK_MSTIG_P2;
GRANT ALL ON PERSONAL_TYPE TO PK_MVS_1;
GRANT ALL ON PERSONAL_TYPE TO PK_MVS_2;
GRANT ALL ON PERSONAL_TYPE TO PK_MVS_3;
GRANT ALL ON PERSONAL_TYPE TO PK_MVS_4;
GRANT ALL ON PERSONAL_TYPE TO PK_MVS_P1;
GRANT ALL ON PERSONAL_TYPE TO PK_MVS_P2;
GRANT ALL ON PERSONAL_TYPE TO PK_OFK_1;
GRANT ALL ON PERSONAL_TYPE TO PK_OFK_2;
GRANT ALL ON PERSONAL_TYPE TO PK_OFK_3;
GRANT ALL ON PERSONAL_TYPE TO PK_OFK_4;
GRANT ALL ON PERSONAL_TYPE TO PK_OFK_P1;
GRANT ALL ON PERSONAL_TYPE TO PK_OFK_P2;
GRANT ALL ON PERSONAL_TYPE TO PK_OTV1;
GRANT ALL ON PERSONAL_TYPE TO PK_OTV2;
GRANT ALL ON PERSONAL_TYPE TO PK_OTV3;
GRANT ALL ON PERSONAL_TYPE TO PK_OTV4;
GRANT ALL ON PERSONAL_TYPE TO PK_SIIEP2;
GRANT ALL ON PERSONAL_TYPE TO PK_SIIE_1;
GRANT ALL ON PERSONAL_TYPE TO PK_SIIE_2;
GRANT ALL ON PERSONAL_TYPE TO PK_SIIE_3;
GRANT ALL ON PERSONAL_TYPE TO PK_SIIE_4;
GRANT ALL ON PERSONAL_TYPE TO PK_SIIE_P1;
GRANT ALL ON PERSONAL_TYPE TO PK_SIIE_P2;