CREATE TABLE IF NOT EXISTS
PREDMET
(
    N_PREDMET     SMALLINT,
    TEXT_PREDMET  VARCHAR(100)
);




/******************************************************************************/
/***                              Primary keys                              ***/
/******************************************************************************/

ALTER TABLE
    PREDMET
ADD
    PRIMARY KEY
        (N_PREDMET);


/******************************************************************************/
/***                                Indices                                 ***/
/******************************************************************************/

CREATE INDEX
    PREDMET_TEXT_PREDMET
ON
    PREDMET
    (
        TEXT_PREDMET
    );


/******************************************************************************/
/***                                Triggers                                ***/
/******************************************************************************/



SET TERM ^ ;



/******************************************************************************/
/***                          Triggers for tables                           ***/
/******************************************************************************/



/* Trigger: TI_PREDMET */
CREATE OR ALTER
    TRIGGER
        TI_PREDMET
FOR
    PREDMET
ACTIVE
    BEFORE INSERT
        POSITION 0
AS
BEGIN
NEW.N_PREDMET = GEN_ID(PREDMET_N_PREDMET, 1);
END
^

SET TERM ; ^



/******************************************************************************/
/***                               Privileges                               ***/
/******************************************************************************/


/* Privileges of users */
GRANT ALL ON PREDMET TO ABITUR1;
GRANT ALL ON PREDMET TO ABITUR2;
GRANT ALL ON PREDMET TO ABITUR3;
GRANT ALL ON PREDMET TO ABITUR4;
GRANT ALL ON PREDMET TO ABITURA;
GRANT ALL ON PREDMET TO ALEXANDER_GONCHAROV;
GRANT ALL ON PREDMET TO ASU;
GRANT ALL ON PREDMET TO ASU1;
GRANT ALL ON PREDMET TO ASU2;
GRANT ALL ON PREDMET TO ASU3;
GRANT ALL ON PREDMET TO ASU4;
GRANT ALL ON PREDMET TO DEVELOPER;
GRANT ALL ON PREDMET TO DEVELOPER2;
GRANT ALL ON PREDMET TO IT1;
GRANT ALL ON PREDMET TO IT2;
GRANT ALL ON PREDMET TO IT3;
GRANT ALL ON PREDMET TO IVANOVA_A;
GRANT ALL ON PREDMET TO MVS1;
GRANT ALL ON PREDMET TO MVS2;
GRANT ALL ON PREDMET TO MVS3;
GRANT ALL ON PREDMET TO MVS4;
GRANT ALL ON PREDMET TO OFKIT1;
GRANT ALL ON PREDMET TO OFKIT2;
GRANT ALL ON PREDMET TO OFKIT3;
GRANT ALL ON PREDMET TO OFKIT4;
GRANT ALL ON PREDMET TO OKSANA;
GRANT ALL ON PREDMET TO PK;
GRANT ALL ON PREDMET TO PK_IT;
GRANT ALL ON PREDMET TO PK_IT1;
GRANT ALL ON PREDMET TO PK_IT2;
GRANT ALL ON PREDMET TO PK_IT3;
GRANT ALL ON PREDMET TO PK_IT4;
GRANT ALL ON PREDMET TO PK_IT5;
GRANT ALL ON PREDMET TO PK_MSTIG1;
GRANT ALL ON PREDMET TO PK_MSTIG2;
GRANT ALL ON PREDMET TO PK_MSTIG3;
GRANT ALL ON PREDMET TO PK_MSTIG4;
GRANT ALL ON PREDMET TO PK_MSTIGP1;
GRANT ALL ON PREDMET TO PK_MSTIGP2;
GRANT ALL ON PREDMET TO PK_MSTIG_1;
GRANT ALL ON PREDMET TO PK_MSTIG_2;
GRANT ALL ON PREDMET TO PK_MSTIG_3;
GRANT ALL ON PREDMET TO PK_MSTIG_4;
GRANT ALL ON PREDMET TO PK_MSTIG_P1;
GRANT ALL ON PREDMET TO PK_MSTIG_P2;
GRANT ALL ON PREDMET TO PK_MVS;
GRANT ALL ON PREDMET TO PK_MVS1;
GRANT ALL ON PREDMET TO PK_MVS2;
GRANT ALL ON PREDMET TO PK_MVS3;
GRANT ALL ON PREDMET TO PK_MVS4;
GRANT ALL ON PREDMET TO PK_MVS5;
GRANT ALL ON PREDMET TO PK_MVSP1;
GRANT ALL ON PREDMET TO PK_MVSP2;
GRANT ALL ON PREDMET TO PK_MVS_1;
GRANT ALL ON PREDMET TO PK_MVS_2;
GRANT ALL ON PREDMET TO PK_MVS_3;
GRANT ALL ON PREDMET TO PK_MVS_4;
GRANT ALL ON PREDMET TO PK_MVS_P1;
GRANT ALL ON PREDMET TO PK_MVS_P2;
GRANT ALL ON PREDMET TO PK_OFKIT;
GRANT ALL ON PREDMET TO PK_OFKIT1;
GRANT ALL ON PREDMET TO PK_OFKIT2;
GRANT ALL ON PREDMET TO PK_OFKIT3;
GRANT ALL ON PREDMET TO PK_OFKIT4;
GRANT ALL ON PREDMET TO PK_OFKIT5;
GRANT ALL ON PREDMET TO PK_OFKITP1;
GRANT ALL ON PREDMET TO PK_OFKITP2;
GRANT ALL ON PREDMET TO PK_OFK_1;
GRANT ALL ON PREDMET TO PK_OFK_2;
GRANT ALL ON PREDMET TO PK_OFK_3;
GRANT ALL ON PREDMET TO PK_OFK_4;
GRANT ALL ON PREDMET TO PK_OFK_P1;
GRANT ALL ON PREDMET TO PK_OFK_P2;
GRANT ALL ON PREDMET TO PK_OTV1;
GRANT ALL ON PREDMET TO PK_OTV2;
GRANT ALL ON PREDMET TO PK_OTV3;
GRANT ALL ON PREDMET TO PK_OTV4;
GRANT ALL ON PREDMET TO PK_SIIE;
GRANT ALL ON PREDMET TO PK_SIIE1;
GRANT ALL ON PREDMET TO PK_SIIE2;
GRANT ALL ON PREDMET TO PK_SIIE3;
GRANT ALL ON PREDMET TO PK_SIIE4;
GRANT ALL ON PREDMET TO PK_SIIE5;
GRANT ALL ON PREDMET TO PK_SIIEP1;
GRANT ALL ON PREDMET TO PK_SIIEP2;
GRANT ALL ON PREDMET TO PK_SIIEP3;
GRANT ALL ON PREDMET TO PK_SIIE_1;
GRANT ALL ON PREDMET TO PK_SIIE_2;
GRANT ALL ON PREDMET TO PK_SIIE_3;
GRANT ALL ON PREDMET TO PK_SIIE_4;
GRANT ALL ON PREDMET TO PK_SIIE_P1;
GRANT ALL ON PREDMET TO PK_SIIE_P2;
GRANT ALL ON PREDMET TO SIIE1;
GRANT ALL ON PREDMET TO SIIE2;
GRANT ALL ON PREDMET TO SIIE3;
GRANT ALL ON PREDMET TO SIIE4;
GRANT ALL ON PREDMET TO UO_LAB;
GRANT ALL ON PREDMET TO UO_N;
GRANT ALL ON PREDMET TO UO_Z;