CREATE TABLE IF NOT EXISTS
PRIVILEG_LOG
(
    ID_LOG    INTEGER,
    N_PRIV    SMALLINT,
    SEL_PRIV  SMALLINT,
    DAT_PRIV  SMALLINT
);




/******************************************************************************/
/***                          Fields descriptions                           ***/
/******************************************************************************/

COMMENT ON COLUMN PRIVILEG_LOG.ID_LOG IS 
'ID из ABITUR_LOGBOOK';

COMMENT ON COLUMN PRIVILEG_LOG.N_PRIV IS 
'0 - БВИ, 1 - ВК, 3 - другие';

COMMENT ON COLUMN PRIVILEG_LOG.SEL_PRIV IS 
'№ переключателя привилегии';

COMMENT ON COLUMN PRIVILEG_LOG.DAT_PRIV IS 
'Значение переключателя привилегии';



/******************************************************************************/
/***                               Privileges                               ***/
/******************************************************************************/


/* Privileges of users */
GRANT ALL ON PRIVILEG_LOG TO ABITUR1;
GRANT ALL ON PRIVILEG_LOG TO ABITUR2;
GRANT ALL ON PRIVILEG_LOG TO ABITUR3;
GRANT ALL ON PRIVILEG_LOG TO ABITUR4;
GRANT ALL ON PRIVILEG_LOG TO ABITURA;
GRANT ALL ON PRIVILEG_LOG TO ALEXANDER_GONCHAROV;
GRANT ALL ON PRIVILEG_LOG TO ASU;
GRANT ALL ON PRIVILEG_LOG TO ASU1;
GRANT ALL ON PRIVILEG_LOG TO ASU2;
GRANT ALL ON PRIVILEG_LOG TO ASU3;
GRANT ALL ON PRIVILEG_LOG TO ASU4;
GRANT ALL ON PRIVILEG_LOG TO DEVELOPER;
GRANT ALL ON PRIVILEG_LOG TO IVANOVA_A;
GRANT ALL ON PRIVILEG_LOG TO OKSANA;
GRANT ALL ON PRIVILEG_LOG TO PK;
GRANT ALL ON PRIVILEG_LOG TO PK_IT;
GRANT ALL ON PRIVILEG_LOG TO PK_IT1;
GRANT ALL ON PRIVILEG_LOG TO PK_IT2;
GRANT ALL ON PRIVILEG_LOG TO PK_IT3;
GRANT ALL ON PRIVILEG_LOG TO PK_IT4;
GRANT ALL ON PRIVILEG_LOG TO PK_IT5;
GRANT ALL ON PRIVILEG_LOG TO PK_MSTIG1;
GRANT ALL ON PRIVILEG_LOG TO PK_MSTIG2;
GRANT ALL ON PRIVILEG_LOG TO PK_MSTIG3;
GRANT ALL ON PRIVILEG_LOG TO PK_MSTIG4;
GRANT ALL ON PRIVILEG_LOG TO PK_MSTIGP1;
GRANT ALL ON PRIVILEG_LOG TO PK_MSTIGP2;
GRANT ALL ON PRIVILEG_LOG TO PK_MSTIG_1;
GRANT ALL ON PRIVILEG_LOG TO PK_MSTIG_2;
GRANT ALL ON PRIVILEG_LOG TO PK_MSTIG_3;
GRANT ALL ON PRIVILEG_LOG TO PK_MSTIG_4;
GRANT ALL ON PRIVILEG_LOG TO PK_MSTIG_P1;
GRANT ALL ON PRIVILEG_LOG TO PK_MSTIG_P2;
GRANT ALL ON PRIVILEG_LOG TO PK_MVS;
GRANT ALL ON PRIVILEG_LOG TO PK_MVS1;
GRANT ALL ON PRIVILEG_LOG TO PK_MVS2;
GRANT ALL ON PRIVILEG_LOG TO PK_MVS3;
GRANT ALL ON PRIVILEG_LOG TO PK_MVS4;
GRANT ALL ON PRIVILEG_LOG TO PK_MVS5;
GRANT ALL ON PRIVILEG_LOG TO PK_MVSP1;
GRANT ALL ON PRIVILEG_LOG TO PK_MVSP2;
GRANT ALL ON PRIVILEG_LOG TO PK_MVS_1;
GRANT ALL ON PRIVILEG_LOG TO PK_MVS_2;
GRANT ALL ON PRIVILEG_LOG TO PK_MVS_3;
GRANT ALL ON PRIVILEG_LOG TO PK_MVS_4;
GRANT ALL ON PRIVILEG_LOG TO PK_MVS_P1;
GRANT ALL ON PRIVILEG_LOG TO PK_MVS_P2;
GRANT ALL ON PRIVILEG_LOG TO PK_OFKIT;
GRANT ALL ON PRIVILEG_LOG TO PK_OFKIT1;
GRANT ALL ON PRIVILEG_LOG TO PK_OFKIT2;
GRANT ALL ON PRIVILEG_LOG TO PK_OFKIT3;
GRANT ALL ON PRIVILEG_LOG TO PK_OFKIT4;
GRANT ALL ON PRIVILEG_LOG TO PK_OFKIT5;
GRANT ALL ON PRIVILEG_LOG TO PK_OFKITP1;
GRANT ALL ON PRIVILEG_LOG TO PK_OFKITP2;
GRANT ALL ON PRIVILEG_LOG TO PK_OFK_1;
GRANT ALL ON PRIVILEG_LOG TO PK_OFK_2;
GRANT ALL ON PRIVILEG_LOG TO PK_OFK_3;
GRANT ALL ON PRIVILEG_LOG TO PK_OFK_4;
GRANT ALL ON PRIVILEG_LOG TO PK_OFK_P1;
GRANT ALL ON PRIVILEG_LOG TO PK_OFK_P2;
GRANT ALL ON PRIVILEG_LOG TO PK_OTV1;
GRANT ALL ON PRIVILEG_LOG TO PK_OTV2;
GRANT ALL ON PRIVILEG_LOG TO PK_OTV3;
GRANT ALL ON PRIVILEG_LOG TO PK_OTV4;
GRANT ALL ON PRIVILEG_LOG TO PK_SIIE;
GRANT ALL ON PRIVILEG_LOG TO PK_SIIE1;
GRANT ALL ON PRIVILEG_LOG TO PK_SIIE2;
GRANT ALL ON PRIVILEG_LOG TO PK_SIIE3;
GRANT ALL ON PRIVILEG_LOG TO PK_SIIE4;
GRANT ALL ON PRIVILEG_LOG TO PK_SIIE5;
GRANT ALL ON PRIVILEG_LOG TO PK_SIIEP1;
GRANT ALL ON PRIVILEG_LOG TO PK_SIIEP2;
GRANT ALL ON PRIVILEG_LOG TO PK_SIIEP3;
GRANT ALL ON PRIVILEG_LOG TO PK_SIIE_1;
GRANT ALL ON PRIVILEG_LOG TO PK_SIIE_2;
GRANT ALL ON PRIVILEG_LOG TO PK_SIIE_3;
GRANT ALL ON PRIVILEG_LOG TO PK_SIIE_4;
GRANT ALL ON PRIVILEG_LOG TO PK_SIIE_P1;
GRANT ALL ON PRIVILEG_LOG TO PK_SIIE_P2;