CREATE TABLE IF NOT EXISTS
PRIVILEGE
(
    ID_PRIV          SMALLINT,
    NAME_PRIV        VARCHAR(80) COLLATE PXW_CYRL,
    SHORT_NAME       VARCHAR(15) COLLATE PXW_CYRL,
    N_WITHOUT_TESTS  SMALLINT,
    N_OUT_TESTS      SMALLINT,
    N_OTHERS         SMALLINT
);




/******************************************************************************/
/***                              Primary keys                              ***/
/******************************************************************************/

ALTER TABLE
    PRIVILEGE
ADD
    CONSTRAINT
        PK_PRIVILEGE
    PRIMARY KEY
        (ID_PRIV);


/******************************************************************************/
/***                          Fields descriptions                           ***/
/******************************************************************************/

COMMENT ON COLUMN PRIVILEGE.SHORT_NAME IS 
'Короткое имя';



/******************************************************************************/
/***                               Privileges                               ***/
/******************************************************************************/


/* Privileges of users */
GRANT ALL ON PRIVILEGE TO ABITUR1;
GRANT ALL ON PRIVILEGE TO ABITUR2;
GRANT ALL ON PRIVILEGE TO ABITUR3;
GRANT ALL ON PRIVILEGE TO ABITUR4;
GRANT ALL ON PRIVILEGE TO ABITURA;
GRANT ALL ON PRIVILEGE TO ALEXANDER_GONCHAROV;
GRANT ALL ON PRIVILEGE TO ASU;
GRANT ALL ON PRIVILEGE TO ASU1;
GRANT ALL ON PRIVILEGE TO ASU2;
GRANT ALL ON PRIVILEGE TO ASU3;
GRANT ALL ON PRIVILEGE TO ASU4;
GRANT ALL ON PRIVILEGE TO DEVELOPER;
GRANT ALL ON PRIVILEGE TO IVANOVA_A;
GRANT ALL ON PRIVILEGE TO OKSANA;
GRANT ALL ON PRIVILEGE TO PK;
GRANT ALL ON PRIVILEGE TO PK_IT;
GRANT ALL ON PRIVILEGE TO PK_IT1;
GRANT ALL ON PRIVILEGE TO PK_IT2;
GRANT ALL ON PRIVILEGE TO PK_IT3;
GRANT ALL ON PRIVILEGE TO PK_IT4;
GRANT ALL ON PRIVILEGE TO PK_IT5;
GRANT ALL ON PRIVILEGE TO PK_MSTIG1;
GRANT ALL ON PRIVILEGE TO PK_MSTIG2;
GRANT ALL ON PRIVILEGE TO PK_MSTIG3;
GRANT ALL ON PRIVILEGE TO PK_MSTIG4;
GRANT ALL ON PRIVILEGE TO PK_MSTIGP1;
GRANT ALL ON PRIVILEGE TO PK_MSTIGP2;
GRANT ALL ON PRIVILEGE TO PK_MSTIG_1;
GRANT ALL ON PRIVILEGE TO PK_MSTIG_2;
GRANT ALL ON PRIVILEGE TO PK_MSTIG_3;
GRANT ALL ON PRIVILEGE TO PK_MSTIG_4;
GRANT ALL ON PRIVILEGE TO PK_MSTIG_P1;
GRANT ALL ON PRIVILEGE TO PK_MSTIG_P2;
GRANT ALL ON PRIVILEGE TO PK_MVS;
GRANT ALL ON PRIVILEGE TO PK_MVS1;
GRANT ALL ON PRIVILEGE TO PK_MVS2;
GRANT ALL ON PRIVILEGE TO PK_MVS3;
GRANT ALL ON PRIVILEGE TO PK_MVS4;
GRANT ALL ON PRIVILEGE TO PK_MVS5;
GRANT ALL ON PRIVILEGE TO PK_MVSP1;
GRANT ALL ON PRIVILEGE TO PK_MVSP2;
GRANT ALL ON PRIVILEGE TO PK_MVS_1;
GRANT ALL ON PRIVILEGE TO PK_MVS_2;
GRANT ALL ON PRIVILEGE TO PK_MVS_3;
GRANT ALL ON PRIVILEGE TO PK_MVS_4;
GRANT ALL ON PRIVILEGE TO PK_MVS_P1;
GRANT ALL ON PRIVILEGE TO PK_MVS_P2;
GRANT ALL ON PRIVILEGE TO PK_OFKIT;
GRANT ALL ON PRIVILEGE TO PK_OFKIT1;
GRANT ALL ON PRIVILEGE TO PK_OFKIT2;
GRANT ALL ON PRIVILEGE TO PK_OFKIT3;
GRANT ALL ON PRIVILEGE TO PK_OFKIT4;
GRANT ALL ON PRIVILEGE TO PK_OFKIT5;
GRANT ALL ON PRIVILEGE TO PK_OFKITP1;
GRANT ALL ON PRIVILEGE TO PK_OFKITP2;
GRANT ALL ON PRIVILEGE TO PK_OFK_1;
GRANT ALL ON PRIVILEGE TO PK_OFK_2;
GRANT ALL ON PRIVILEGE TO PK_OFK_3;
GRANT ALL ON PRIVILEGE TO PK_OFK_4;
GRANT ALL ON PRIVILEGE TO PK_OFK_P1;
GRANT ALL ON PRIVILEGE TO PK_OFK_P2;
GRANT ALL ON PRIVILEGE TO PK_OTV1;
GRANT ALL ON PRIVILEGE TO PK_OTV2;
GRANT ALL ON PRIVILEGE TO PK_OTV3;
GRANT ALL ON PRIVILEGE TO PK_OTV4;
GRANT ALL ON PRIVILEGE TO PK_SIIE;
GRANT ALL ON PRIVILEGE TO PK_SIIE1;
GRANT ALL ON PRIVILEGE TO PK_SIIE2;
GRANT ALL ON PRIVILEGE TO PK_SIIE3;
GRANT ALL ON PRIVILEGE TO PK_SIIE4;
GRANT ALL ON PRIVILEGE TO PK_SIIE5;
GRANT ALL ON PRIVILEGE TO PK_SIIEP1;
GRANT ALL ON PRIVILEGE TO PK_SIIEP2;
GRANT ALL ON PRIVILEGE TO PK_SIIEP3;
GRANT ALL ON PRIVILEGE TO PK_SIIE_1;
GRANT ALL ON PRIVILEGE TO PK_SIIE_2;
GRANT ALL ON PRIVILEGE TO PK_SIIE_3;
GRANT ALL ON PRIVILEGE TO PK_SIIE_4;
GRANT ALL ON PRIVILEGE TO PK_SIIE_P1;
GRANT ALL ON PRIVILEGE TO PK_SIIE_P2;