CREATE TABLE IF NOT EXISTS
QUEUE
(
    TIME_QUEUE           DATE,
    SIGN                 INTEGER,
    REFERENCE            INTEGER,
    SIIE_DEKAN           INTEGER,
    MVS_DEKAN            INTEGER,
    OFK_DEKAN            INTEGER,
    MSTIG_DEKAN          INTEGER,
    SIIE                 INTEGER,
    MVS                  INTEGER,
    OFK                  INTEGER,
    MSTIG                INTEGER,
    SIGN_ONLINE          INTEGER,
    REFERENCE_ONLINE     INTEGER,
    SIIE_DEKAN_ONLINE    INTEGER,
    MVS_DEKAN_ONLINE     INTEGER,
    OFK_DEKAN_ONLINE     INTEGER,
    MSTIG_DEKAN_ONLINE   INTEGER,
    SIIE_DEKAN_PICK_UP   INTEGER,
    MVS_DEKAN_PICK_UP    INTEGER,
    OFK_DEKAN_PICK_UP    INTEGER,
    MSTIG_DEKAN_PICK_UP  INTEGER,
    SIIE_PICK_UP         INTEGER,
    MVS_PICK_UP          INTEGER,
    OFK_PICK_UP          INTEGER,
    MSTIG_PICK_UP        INTEGER
);




/******************************************************************************/
/***                               Privileges                               ***/
/******************************************************************************/


/* Privileges of users */
GRANT ALL ON QUEUE TO ALEXANDER_GONCHAROV;
GRANT ALL ON QUEUE TO DEVELOPER;
GRANT ALL ON QUEUE TO IVANOVA_A;
GRANT ALL ON QUEUE TO PK_MSTIG_1;
GRANT ALL ON QUEUE TO PK_MSTIG_2;
GRANT ALL ON QUEUE TO PK_MSTIG_3;
GRANT ALL ON QUEUE TO PK_MSTIG_4;
GRANT ALL ON QUEUE TO PK_MSTIG_P1;
GRANT ALL ON QUEUE TO PK_MSTIG_P2;
GRANT ALL ON QUEUE TO PK_MVS_1;
GRANT ALL ON QUEUE TO PK_MVS_2;
GRANT ALL ON QUEUE TO PK_MVS_3;
GRANT ALL ON QUEUE TO PK_MVS_4;
GRANT ALL ON QUEUE TO PK_MVS_P1;
GRANT ALL ON QUEUE TO PK_MVS_P2;
GRANT ALL ON QUEUE TO PK_OFK_1;
GRANT ALL ON QUEUE TO PK_OFK_2;
GRANT ALL ON QUEUE TO PK_OFK_3;
GRANT ALL ON QUEUE TO PK_OFK_4;
GRANT ALL ON QUEUE TO PK_OFK_P1;
GRANT ALL ON QUEUE TO PK_OFK_P2;
GRANT ALL ON QUEUE TO PK_OTV1;
GRANT ALL ON QUEUE TO PK_OTV2;
GRANT ALL ON QUEUE TO PK_OTV3;
GRANT ALL ON QUEUE TO PK_OTV4;
GRANT ALL ON QUEUE TO PK_SIIE_1;
GRANT ALL ON QUEUE TO PK_SIIE_2;
GRANT ALL ON QUEUE TO PK_SIIE_3;
GRANT ALL ON QUEUE TO PK_SIIE_4;
GRANT ALL ON QUEUE TO PK_SIIE_P1;
GRANT ALL ON QUEUE TO PK_SIIE_P2;