CREATE TABLE IF NOT EXISTS
REGION
(
    N_REGION     SMALLINT,
    TEXT_REGION  VARCHAR(40) COLLATE PXW_CYRL
);




/******************************************************************************/
/***                              Primary keys                              ***/
/******************************************************************************/

ALTER TABLE
    REGION
ADD
    PRIMARY KEY
        (N_REGION);


/******************************************************************************/
/***                                Indices                                 ***/
/******************************************************************************/

CREATE INDEX
    REGION_TEXT_REGION
ON
    REGION
    (
        TEXT_REGION
    );


/******************************************************************************/
/***                                Triggers                                ***/
/******************************************************************************/



SET TERM ^ ;



/******************************************************************************/
/***                          Triggers for tables                           ***/
/******************************************************************************/



/* Trigger: TI_REGION */
CREATE OR ALTER
    TRIGGER
        TI_REGION
FOR
    REGION
ACTIVE
    BEFORE INSERT
        POSITION 0
AS
BEGIN
NEW.N_REGION = GEN_ID(REGION_N_REGION, 1);
END
^

SET TERM ; ^



/******************************************************************************/
/***                               Privileges                               ***/
/******************************************************************************/


/* Privileges of users */
GRANT ALL ON REGION TO ABITUR1;
GRANT ALL ON REGION TO ABITUR2;
GRANT ALL ON REGION TO ABITUR3;
GRANT ALL ON REGION TO ABITUR4;
GRANT ALL ON REGION TO ABITURA;
GRANT ALL ON REGION TO ALEXANDER_GONCHAROV;
GRANT ALL ON REGION TO ASU;
GRANT ALL ON REGION TO ASU1;
GRANT ALL ON REGION TO ASU2;
GRANT ALL ON REGION TO ASU3;
GRANT ALL ON REGION TO ASU4;
GRANT ALL ON REGION TO DEVELOPER;
GRANT ALL ON REGION TO DEVELOPER2;
GRANT ALL ON REGION TO IT1;
GRANT ALL ON REGION TO IT2;
GRANT ALL ON REGION TO IT3;
GRANT ALL ON REGION TO IVANOVA_A;
GRANT ALL ON REGION TO MVS1;
GRANT ALL ON REGION TO MVS2;
GRANT ALL ON REGION TO MVS3;
GRANT ALL ON REGION TO MVS4;
GRANT ALL ON REGION TO OFKIT1;
GRANT ALL ON REGION TO OFKIT2;
GRANT ALL ON REGION TO OFKIT3;
GRANT ALL ON REGION TO OFKIT4;
GRANT ALL ON REGION TO OKSANA;
GRANT ALL ON REGION TO PK;
GRANT ALL ON REGION TO PK_IT;
GRANT ALL ON REGION TO PK_IT1;
GRANT ALL ON REGION TO PK_IT2;
GRANT ALL ON REGION TO PK_IT3;
GRANT ALL ON REGION TO PK_IT4;
GRANT ALL ON REGION TO PK_IT5;
GRANT ALL ON REGION TO PK_MSTIG1;
GRANT ALL ON REGION TO PK_MSTIG2;
GRANT ALL ON REGION TO PK_MSTIG3;
GRANT ALL ON REGION TO PK_MSTIG4;
GRANT ALL ON REGION TO PK_MSTIGP1;
GRANT ALL ON REGION TO PK_MSTIGP2;
GRANT ALL ON REGION TO PK_MSTIG_1;
GRANT ALL ON REGION TO PK_MSTIG_2;
GRANT ALL ON REGION TO PK_MSTIG_3;
GRANT ALL ON REGION TO PK_MSTIG_4;
GRANT ALL ON REGION TO PK_MSTIG_P1;
GRANT ALL ON REGION TO PK_MSTIG_P2;
GRANT ALL ON REGION TO PK_MVS;
GRANT ALL ON REGION TO PK_MVS1;
GRANT ALL ON REGION TO PK_MVS2;
GRANT ALL ON REGION TO PK_MVS3;
GRANT ALL ON REGION TO PK_MVS4;
GRANT ALL ON REGION TO PK_MVS5;
GRANT ALL ON REGION TO PK_MVSP1;
GRANT ALL ON REGION TO PK_MVSP2;
GRANT ALL ON REGION TO PK_MVS_1;
GRANT ALL ON REGION TO PK_MVS_2;
GRANT ALL ON REGION TO PK_MVS_3;
GRANT ALL ON REGION TO PK_MVS_4;
GRANT ALL ON REGION TO PK_MVS_P1;
GRANT ALL ON REGION TO PK_MVS_P2;
GRANT ALL ON REGION TO PK_OFKIT;
GRANT ALL ON REGION TO PK_OFKIT1;
GRANT ALL ON REGION TO PK_OFKIT2;
GRANT ALL ON REGION TO PK_OFKIT3;
GRANT ALL ON REGION TO PK_OFKIT4;
GRANT ALL ON REGION TO PK_OFKIT5;
GRANT ALL ON REGION TO PK_OFKITP1;
GRANT ALL ON REGION TO PK_OFKITP2;
GRANT ALL ON REGION TO PK_OFK_1;
GRANT ALL ON REGION TO PK_OFK_2;
GRANT ALL ON REGION TO PK_OFK_3;
GRANT ALL ON REGION TO PK_OFK_4;
GRANT ALL ON REGION TO PK_OFK_P1;
GRANT ALL ON REGION TO PK_OFK_P2;
GRANT ALL ON REGION TO PK_OTV1;
GRANT ALL ON REGION TO PK_OTV2;
GRANT ALL ON REGION TO PK_OTV3;
GRANT ALL ON REGION TO PK_OTV4;
GRANT ALL ON REGION TO PK_SIIE;
GRANT ALL ON REGION TO PK_SIIE1;
GRANT ALL ON REGION TO PK_SIIE2;
GRANT ALL ON REGION TO PK_SIIE3;
GRANT ALL ON REGION TO PK_SIIE4;
GRANT ALL ON REGION TO PK_SIIE5;
GRANT ALL ON REGION TO PK_SIIEP1;
GRANT ALL ON REGION TO PK_SIIEP2;
GRANT ALL ON REGION TO PK_SIIEP3;
GRANT ALL ON REGION TO PK_SIIE_1;
GRANT ALL ON REGION TO PK_SIIE_2;
GRANT ALL ON REGION TO PK_SIIE_3;
GRANT ALL ON REGION TO PK_SIIE_4;
GRANT ALL ON REGION TO PK_SIIE_P1;
GRANT ALL ON REGION TO PK_SIIE_P2;
GRANT ALL ON REGION TO SIIE1;
GRANT ALL ON REGION TO SIIE2;
GRANT ALL ON REGION TO SIIE3;
GRANT ALL ON REGION TO SIIE4;
GRANT ALL ON REGION TO UO_LAB;
GRANT ALL ON REGION TO UO_N;
GRANT ALL ON REGION TO UO_Z;