CREATE GENERATOR
    GEN_SEL_EXERCIZE_ID;

CREATE TABLE IF NOT EXISTS
SEL_EXERCIZE
(
    ID_SEL_EXERC   INTEGER,
    NOMER_AB       INTEGER,
    NUM_EXERC_GRP  SMALLINT,
    ID_EXERC       SMALLINT
);



/******************************************************************************/
/***                              Primary keys                              ***/
/******************************************************************************/

ALTER TABLE
    SEL_EXERCIZE
ADD
    CONSTRAINT
        PK_SEL_EXERCIZE
    PRIMARY KEY
        (ID_SEL_EXERC);


/******************************************************************************/
/***                              Foreign keys                              ***/
/******************************************************************************/

ALTER TABLE
    SEL_EXERCIZE
ADD
    CONSTRAINT
        FK_SEL_EXERCIZE_1
    FOREIGN KEY
        (ID_EXERC)
    REFERENCES
        EXERCISE
        (
            ID_EXERC
        );


/******************************************************************************/
/***                                Triggers                                ***/
/******************************************************************************/



SET TERM ^ ;



/******************************************************************************/
/***                          Triggers for tables                           ***/
/******************************************************************************/



/* Trigger: SEL_EXERCIZE_BI */
CREATE OR ALTER
    TRIGGER
        SEL_EXERCIZE_BI
FOR
    SEL_EXERCIZE
ACTIVE
    BEFORE INSERT
        POSITION 0
AS
BEGIN
    IF (NEW.ID_SEL_EXERC IS NULL)
    THEN
        NEW.ID_SEL_EXERC = GEN_ID(GEN_SEL_EXERCIZE_ID, 1);
END
^

SET TERM ; ^



/******************************************************************************/
/***                          Fields descriptions                           ***/
/******************************************************************************/

COMMENT ON COLUMN SEL_EXERCIZE.ID_SEL_EXERC IS 
'ID';

COMMENT ON COLUMN SEL_EXERCIZE.NOMER_AB IS 
'Номер абонента из табл. ABITURA';

COMMENT ON COLUMN SEL_EXERCIZE.NUM_EXERC_GRP IS 
'Номер блока КУ';

COMMENT ON COLUMN SEL_EXERCIZE.ID_EXERC IS 
'ID КУ из табл. EXERCISE';



/******************************************************************************/
/***                               Privileges                               ***/
/******************************************************************************/


/* Privileges of users */
GRANT ALL ON SEL_EXERCIZE TO ABITUR1;
GRANT ALL ON SEL_EXERCIZE TO ABITUR2;
GRANT ALL ON SEL_EXERCIZE TO ABITUR3;
GRANT ALL ON SEL_EXERCIZE TO ABITUR4;
GRANT ALL ON SEL_EXERCIZE TO ABITURA;
GRANT ALL ON SEL_EXERCIZE TO ALEXANDER_GONCHAROV;
GRANT ALL ON SEL_EXERCIZE TO ASU;
GRANT ALL ON SEL_EXERCIZE TO ASU1;
GRANT ALL ON SEL_EXERCIZE TO ASU2;
GRANT ALL ON SEL_EXERCIZE TO ASU3;
GRANT ALL ON SEL_EXERCIZE TO ASU4;
GRANT ALL ON SEL_EXERCIZE TO DEVELOPER;
GRANT ALL ON SEL_EXERCIZE TO DEVELOPER2;
GRANT ALL ON SEL_EXERCIZE TO IVANOVA_A;
GRANT ALL ON SEL_EXERCIZE TO OKSANA;
GRANT ALL ON SEL_EXERCIZE TO PK;
GRANT ALL ON SEL_EXERCIZE TO PK_IT;
GRANT ALL ON SEL_EXERCIZE TO PK_IT1;
GRANT ALL ON SEL_EXERCIZE TO PK_IT2;
GRANT ALL ON SEL_EXERCIZE TO PK_IT3;
GRANT ALL ON SEL_EXERCIZE TO PK_IT4;
GRANT ALL ON SEL_EXERCIZE TO PK_IT5;
GRANT ALL ON SEL_EXERCIZE TO PK_MSTIG1;
GRANT ALL ON SEL_EXERCIZE TO PK_MSTIG2;
GRANT ALL ON SEL_EXERCIZE TO PK_MSTIG3;
GRANT ALL ON SEL_EXERCIZE TO PK_MSTIG4;
GRANT ALL ON SEL_EXERCIZE TO PK_MSTIGP1;
GRANT ALL ON SEL_EXERCIZE TO PK_MSTIGP2;
GRANT ALL ON SEL_EXERCIZE TO PK_MSTIG_1;
GRANT ALL ON SEL_EXERCIZE TO PK_MSTIG_2;
GRANT ALL ON SEL_EXERCIZE TO PK_MSTIG_3;
GRANT ALL ON SEL_EXERCIZE TO PK_MSTIG_4;
GRANT ALL ON SEL_EXERCIZE TO PK_MSTIG_P1;
GRANT ALL ON SEL_EXERCIZE TO PK_MSTIG_P2;
GRANT ALL ON SEL_EXERCIZE TO PK_MVS;
GRANT ALL ON SEL_EXERCIZE TO PK_MVS1;
GRANT ALL ON SEL_EXERCIZE TO PK_MVS2;
GRANT ALL ON SEL_EXERCIZE TO PK_MVS3;
GRANT ALL ON SEL_EXERCIZE TO PK_MVS4;
GRANT ALL ON SEL_EXERCIZE TO PK_MVS5;
GRANT ALL ON SEL_EXERCIZE TO PK_MVSP1;
GRANT ALL ON SEL_EXERCIZE TO PK_MVSP2;
GRANT ALL ON SEL_EXERCIZE TO PK_MVS_1;
GRANT ALL ON SEL_EXERCIZE TO PK_MVS_2;
GRANT ALL ON SEL_EXERCIZE TO PK_MVS_3;
GRANT ALL ON SEL_EXERCIZE TO PK_MVS_4;
GRANT ALL ON SEL_EXERCIZE TO PK_MVS_P1;
GRANT ALL ON SEL_EXERCIZE TO PK_MVS_P2;
GRANT ALL ON SEL_EXERCIZE TO PK_OFKIT;
GRANT ALL ON SEL_EXERCIZE TO PK_OFKIT1;
GRANT ALL ON SEL_EXERCIZE TO PK_OFKIT2;
GRANT ALL ON SEL_EXERCIZE TO PK_OFKIT3;
GRANT ALL ON SEL_EXERCIZE TO PK_OFKIT4;
GRANT ALL ON SEL_EXERCIZE TO PK_OFKIT5;
GRANT ALL ON SEL_EXERCIZE TO PK_OFKITP1;
GRANT ALL ON SEL_EXERCIZE TO PK_OFKITP2;
GRANT ALL ON SEL_EXERCIZE TO PK_OFK_1;
GRANT ALL ON SEL_EXERCIZE TO PK_OFK_2;
GRANT ALL ON SEL_EXERCIZE TO PK_OFK_3;
GRANT ALL ON SEL_EXERCIZE TO PK_OFK_4;
GRANT ALL ON SEL_EXERCIZE TO PK_OFK_P1;
GRANT ALL ON SEL_EXERCIZE TO PK_OFK_P2;
GRANT ALL ON SEL_EXERCIZE TO PK_OTV1;
GRANT ALL ON SEL_EXERCIZE TO PK_OTV2;
GRANT ALL ON SEL_EXERCIZE TO PK_OTV3;
GRANT ALL ON SEL_EXERCIZE TO PK_OTV4;
GRANT ALL ON SEL_EXERCIZE TO PK_SIIE;
GRANT ALL ON SEL_EXERCIZE TO PK_SIIE1;
GRANT ALL ON SEL_EXERCIZE TO PK_SIIE2;
GRANT ALL ON SEL_EXERCIZE TO PK_SIIE3;
GRANT ALL ON SEL_EXERCIZE TO PK_SIIE4;
GRANT ALL ON SEL_EXERCIZE TO PK_SIIE5;
GRANT ALL ON SEL_EXERCIZE TO PK_SIIEP1;
GRANT ALL ON SEL_EXERCIZE TO PK_SIIEP2;
GRANT ALL ON SEL_EXERCIZE TO PK_SIIEP3;
GRANT ALL ON SEL_EXERCIZE TO PK_SIIE_1;
GRANT ALL ON SEL_EXERCIZE TO PK_SIIE_2;
GRANT ALL ON SEL_EXERCIZE TO PK_SIIE_3;
GRANT ALL ON SEL_EXERCIZE TO PK_SIIE_4;
GRANT ALL ON SEL_EXERCIZE TO PK_SIIE_P1;
GRANT ALL ON SEL_EXERCIZE TO PK_SIIE_P2;