CREATE TABLE IF NOT EXISTS
SELECTION_COMMITTEE
(
    POST       VARCHAR(30) NOT NULL COLLATE PXW_CYRL,
    FIO        VARCHAR(30)          COLLATE PXW_CYRL,
    IOF        VARCHAR(30)          COLLATE PXW_CYRL,
    SIGNATURE  BLOB SUB_TYPE 0 SEGMENT SIZE 80
);




/******************************************************************************/
/***                              Primary keys                              ***/
/******************************************************************************/

ALTER TABLE
    SELECTION_COMMITTEE
ADD
    CONSTRAINT
        PK_SELECTION_COMMITTEE
    PRIMARY KEY
        (POST);


/******************************************************************************/
/***                          Fields descriptions                           ***/
/******************************************************************************/

/* UNCOMMENT QUERIES BELOW FOR MySQL */
-- ALTER TABLE
-- 	SELECTION_COMMITTEE
-- MODIFY COLUMN
-- 	POST VARCHAR(30)
-- COMMENT
-- 	'Должность';
    
-- ALTER TABLE
-- 	SELECTION_COMMITTEE
-- MODIFY COLUMN
-- 	SIGNATURE BLOB
-- COMMENT
-- 	'Сканированное изображение подписи';

/* UNCOMMENT QUERIES BELOW FOR Firebird OR SQL */
-- COMMENT	ON COLUMN
-- 	SELECTION_COMMITTEE.POST
-- IS 'Должность';

-- COMMENT	ON COLUMN
-- 		SELECTION_COMMITTEE.SIGNATURE
-- IS 'Подпись';



/******************************************************************************/
/***                               Privileges                               ***/
/******************************************************************************/


/* Privileges of users */
GRANT ALL ON SELECTION_COMMITTEE TO ABITURA;
GRANT ALL ON SELECTION_COMMITTEE TO ALEXANDER_GONCHAROV;
GRANT ALL ON SELECTION_COMMITTEE TO IVANOVA_A;
GRANT ALL ON SELECTION_COMMITTEE TO OKSANA;
GRANT ALL ON SELECTION_COMMITTEE TO PK_MSTIG_1;
GRANT ALL ON SELECTION_COMMITTEE TO PK_MSTIG_2;
GRANT ALL ON SELECTION_COMMITTEE TO PK_MSTIG_3;
GRANT ALL ON SELECTION_COMMITTEE TO PK_MSTIG_4;
GRANT ALL ON SELECTION_COMMITTEE TO PK_MSTIG_P1;
GRANT ALL ON SELECTION_COMMITTEE TO PK_MSTIG_P2;
GRANT ALL ON SELECTION_COMMITTEE TO PK_MVS_1;
GRANT ALL ON SELECTION_COMMITTEE TO PK_MVS_2;
GRANT ALL ON SELECTION_COMMITTEE TO PK_MVS_3;
GRANT ALL ON SELECTION_COMMITTEE TO PK_MVS_4;
GRANT ALL ON SELECTION_COMMITTEE TO PK_MVS_P1;
GRANT ALL ON SELECTION_COMMITTEE TO PK_MVS_P2;
GRANT ALL ON SELECTION_COMMITTEE TO PK_OFK_1;
GRANT ALL ON SELECTION_COMMITTEE TO PK_OFK_2;
GRANT ALL ON SELECTION_COMMITTEE TO PK_OFK_3;
GRANT ALL ON SELECTION_COMMITTEE TO PK_OFK_4;
GRANT ALL ON SELECTION_COMMITTEE TO PK_OFK_P1;
GRANT ALL ON SELECTION_COMMITTEE TO PK_OFK_P2;
GRANT ALL ON SELECTION_COMMITTEE TO PK_OTV1;
GRANT ALL ON SELECTION_COMMITTEE TO PK_OTV2;
GRANT ALL ON SELECTION_COMMITTEE TO PK_OTV3;
GRANT ALL ON SELECTION_COMMITTEE TO PK_OTV4;
GRANT ALL ON SELECTION_COMMITTEE TO PK_SIIE_1;
GRANT ALL ON SELECTION_COMMITTEE TO PK_SIIE_2;
GRANT ALL ON SELECTION_COMMITTEE TO PK_SIIE_3;
GRANT ALL ON SELECTION_COMMITTEE TO PK_SIIE_4;
GRANT ALL ON SELECTION_COMMITTEE TO PK_SIIE_P1;
GRANT ALL ON SELECTION_COMMITTEE TO PK_SIIE_P2;

GRANT SELECT, REFERENCES ON SELECTION_COMMITTEE TO ABITUR1;
GRANT SELECT, REFERENCES ON SELECTION_COMMITTEE TO ABITUR2;
GRANT SELECT, REFERENCES ON SELECTION_COMMITTEE TO ABITUR3;
GRANT SELECT, REFERENCES ON SELECTION_COMMITTEE TO ABITUR4;
GRANT SELECT, REFERENCES ON SELECTION_COMMITTEE TO ANNA;
GRANT SELECT, REFERENCES ON SELECTION_COMMITTEE TO ASPIRANTURA;
GRANT SELECT, REFERENCES ON SELECTION_COMMITTEE TO ASU;
GRANT SELECT, REFERENCES ON SELECTION_COMMITTEE TO ASU1;
GRANT SELECT, REFERENCES ON SELECTION_COMMITTEE TO ASU2;
GRANT SELECT, REFERENCES ON SELECTION_COMMITTEE TO ASU3;
GRANT SELECT, REFERENCES ON SELECTION_COMMITTEE TO ASU4;
GRANT SELECT, REFERENCES ON SELECTION_COMMITTEE TO BAKS68878;
GRANT SELECT, REFERENCES ON SELECTION_COMMITTEE TO DEV;
GRANT SELECT, REFERENCES ON SELECTION_COMMITTEE TO DEVELOPER;
GRANT SELECT, REFERENCES ON SELECTION_COMMITTEE TO DEVELOPER2;
GRANT SELECT, REFERENCES ON SELECTION_COMMITTEE TO DOBROVOLSKAYA;
GRANT SELECT, REFERENCES ON SELECTION_COMMITTEE TO GUNICH_OKSANA;
GRANT SELECT, REFERENCES ON SELECTION_COMMITTEE TO IT1;
GRANT SELECT, REFERENCES ON SELECTION_COMMITTEE TO IT2;
GRANT SELECT, REFERENCES ON SELECTION_COMMITTEE TO IT3;
GRANT SELECT, REFERENCES ON SELECTION_COMMITTEE TO IT5;
GRANT SELECT, REFERENCES ON SELECTION_COMMITTEE TO IT7;
GRANT SELECT, REFERENCES ON SELECTION_COMMITTEE TO IT_8;
GRANT SELECT, REFERENCES ON SELECTION_COMMITTEE TO IT_Z;
GRANT SELECT, REFERENCES ON SELECTION_COMMITTEE TO JKMUF2507;
GRANT SELECT, REFERENCES ON SELECTION_COMMITTEE TO LAVRENOVA_V;
GRANT SELECT, REFERENCES ON SELECTION_COMMITTEE TO LENAUSOVA;
GRANT SELECT, REFERENCES ON SELECTION_COMMITTEE TO MAGISTR;
GRANT SELECT, REFERENCES ON SELECTION_COMMITTEE TO MVS1;
GRANT SELECT, REFERENCES ON SELECTION_COMMITTEE TO MVS2;
GRANT SELECT, REFERENCES ON SELECTION_COMMITTEE TO MVS3;
GRANT SELECT, REFERENCES ON SELECTION_COMMITTEE TO MVS4;
GRANT SELECT, REFERENCES ON SELECTION_COMMITTEE TO MVS_D;
GRANT SELECT, REFERENCES ON SELECTION_COMMITTEE TO MVS_Z;
GRANT SELECT, REFERENCES ON SELECTION_COMMITTEE TO MVS_Z_L;
GRANT SELECT, REFERENCES ON SELECTION_COMMITTEE TO M_2;
GRANT SELECT, REFERENCES ON SELECTION_COMMITTEE TO OFKIT1;
GRANT SELECT, REFERENCES ON SELECTION_COMMITTEE TO OFKIT2;
GRANT SELECT, REFERENCES ON SELECTION_COMMITTEE TO OFKIT3;
GRANT SELECT, REFERENCES ON SELECTION_COMMITTEE TO OFKIT4;
GRANT SELECT, REFERENCES ON SELECTION_COMMITTEE TO OFKIT_A;
GRANT SELECT, REFERENCES ON SELECTION_COMMITTEE TO OFKIT_D;
GRANT SELECT, REFERENCES ON SELECTION_COMMITTEE TO OFKIT_M;
GRANT SELECT, REFERENCES ON SELECTION_COMMITTEE TO OFKIT_N;
GRANT SELECT, REFERENCES ON SELECTION_COMMITTEE TO OK_STUD_1;
GRANT SELECT, REFERENCES ON SELECTION_COMMITTEE TO PK;
GRANT SELECT, REFERENCES ON SELECTION_COMMITTEE TO PK_IT;
GRANT SELECT, REFERENCES ON SELECTION_COMMITTEE TO PK_IT1;
GRANT SELECT, REFERENCES ON SELECTION_COMMITTEE TO PK_IT2;
GRANT SELECT, REFERENCES ON SELECTION_COMMITTEE TO PK_IT3;
GRANT SELECT, REFERENCES ON SELECTION_COMMITTEE TO PK_IT4;
GRANT SELECT, REFERENCES ON SELECTION_COMMITTEE TO PK_IT5;
GRANT SELECT, REFERENCES ON SELECTION_COMMITTEE TO PK_MSTIG1;
GRANT SELECT, REFERENCES ON SELECTION_COMMITTEE TO PK_MSTIG2;
GRANT SELECT, REFERENCES ON SELECTION_COMMITTEE TO PK_MSTIG3;
GRANT SELECT, REFERENCES ON SELECTION_COMMITTEE TO PK_MSTIG4;
GRANT SELECT, REFERENCES ON SELECTION_COMMITTEE TO PK_MSTIGP1;
GRANT SELECT, REFERENCES ON SELECTION_COMMITTEE TO PK_MSTIGP2;
GRANT SELECT, REFERENCES ON SELECTION_COMMITTEE TO PK_MVS;
GRANT SELECT, REFERENCES ON SELECTION_COMMITTEE TO PK_MVS1;
GRANT SELECT, REFERENCES ON SELECTION_COMMITTEE TO PK_MVS2;
GRANT SELECT, REFERENCES ON SELECTION_COMMITTEE TO PK_MVS3;
GRANT SELECT, REFERENCES ON SELECTION_COMMITTEE TO PK_MVS4;
GRANT SELECT, REFERENCES ON SELECTION_COMMITTEE TO PK_MVS5;
GRANT SELECT, REFERENCES ON SELECTION_COMMITTEE TO PK_MVSP1;
GRANT SELECT, REFERENCES ON SELECTION_COMMITTEE TO PK_MVSP2;
GRANT SELECT, REFERENCES ON SELECTION_COMMITTEE TO PK_OFKIT;
GRANT SELECT, REFERENCES ON SELECTION_COMMITTEE TO PK_OFKIT1;
GRANT SELECT, REFERENCES ON SELECTION_COMMITTEE TO PK_OFKIT2;
GRANT SELECT, REFERENCES ON SELECTION_COMMITTEE TO PK_OFKIT3;
GRANT SELECT, REFERENCES ON SELECTION_COMMITTEE TO PK_OFKIT4;
GRANT SELECT, REFERENCES ON SELECTION_COMMITTEE TO PK_OFKIT5;
GRANT SELECT, REFERENCES ON SELECTION_COMMITTEE TO PK_OFKITP1;
GRANT SELECT, REFERENCES ON SELECTION_COMMITTEE TO PK_OFKITP2;
GRANT SELECT, REFERENCES ON SELECTION_COMMITTEE TO PK_SIIE;
GRANT SELECT, REFERENCES ON SELECTION_COMMITTEE TO PK_SIIE1;
GRANT SELECT, REFERENCES ON SELECTION_COMMITTEE TO PK_SIIE2;
GRANT SELECT, REFERENCES ON SELECTION_COMMITTEE TO PK_SIIE3;
GRANT SELECT, REFERENCES ON SELECTION_COMMITTEE TO PK_SIIE4;
GRANT SELECT, REFERENCES ON SELECTION_COMMITTEE TO PK_SIIE5;
GRANT SELECT, REFERENCES ON SELECTION_COMMITTEE TO PK_SIIEP1;
GRANT SELECT, REFERENCES ON SELECTION_COMMITTEE TO PK_SIIEP2;
GRANT SELECT, REFERENCES ON SELECTION_COMMITTEE TO PK_SIIEP3;
GRANT SELECT, REFERENCES ON SELECTION_COMMITTEE TO PLANIDA_E;
GRANT SELECT, REFERENCES ON SELECTION_COMMITTEE TO PUBLIC;
GRANT SELECT, REFERENCES ON SELECTION_COMMITTEE TO SHMAENKOVA_M;
GRANT SELECT, REFERENCES ON SELECTION_COMMITTEE TO SIIE1;
GRANT SELECT, REFERENCES ON SELECTION_COMMITTEE TO SIIE1234;
GRANT SELECT, REFERENCES ON SELECTION_COMMITTEE TO SIIE2;
GRANT SELECT, REFERENCES ON SELECTION_COMMITTEE TO SIIE3;
GRANT SELECT, REFERENCES ON SELECTION_COMMITTEE TO SIIE4;
GRANT SELECT, REFERENCES ON SELECTION_COMMITTEE TO SIIE_Z1;
GRANT SELECT, REFERENCES ON SELECTION_COMMITTEE TO STUD_KADR1;
GRANT SELECT, REFERENCES ON SELECTION_COMMITTEE TO STUD_KADR4;
GRANT SELECT, REFERENCES ON SELECTION_COMMITTEE TO SVETA;
GRANT SELECT, REFERENCES ON SELECTION_COMMITTEE TO UO_LAB;
GRANT SELECT, REFERENCES ON SELECTION_COMMITTEE TO UO_N;
GRANT SELECT, REFERENCES ON SELECTION_COMMITTEE TO UO_Z;
GRANT SELECT, REFERENCES ON SELECTION_COMMITTEE TO VIEWER_MOB;
GRANT SELECT, REFERENCES ON SELECTION_COMMITTEE TO VNUK;
GRANT SELECT, REFERENCES ON SELECTION_COMMITTEE TO VOROBEI75;
GRANT SELECT, REFERENCES ON SELECTION_COMMITTEE TO YAUHENI_HATSURA;