CREATE TABLE IF NOT EXISTS
SERTIFICAT
(
    NOMER_AB   INTEGER,
    N_PREDMET  SMALLINT,
    SERIA_S    VARCHAR(10),
    NOMER_S    VARCHAR(15),
    BALLS      SMALLINT,
    DESCRIBE   VARCHAR(150) COLLATE PXW_CYRL,
    RUS_BEL    SMALLINT,
    PRICE      SMALLINT,
    YEAR_S     INTEGER
);



/******************************************************************************/
/***                                Indices                                 ***/
/******************************************************************************/

CREATE INDEX SERTIFICAT_BALLS            ON SERTIFICAT (BALLS);
CREATE INDEX SERTIFICAT_NOMER_AB         ON SERTIFICAT (NOMER_AB);
CREATE INDEX SERTIFICAT_NOMER_AB_PREDMET ON SERTIFICAT (NOMER_AB, N_PREDMET);
CREATE INDEX SERTIFICAT_PREDMET          ON SERTIFICAT (N_PREDMET);
CREATE INDEX SERTIFICAT_PRICE            ON SERTIFICAT (PRICE);
CREATE INDEX SERTIFICAT_RUS_BEL          ON SERTIFICAT (RUS_BEL);


/******************************************************************************/
/***                          Fields descriptions                           ***/
/******************************************************************************/

COMMENT ON COLUMN SERTIFICAT.PRICE IS 
'0-обязательное
1-платное';

COMMENT ON COLUMN SERTIFICAT.YEAR_S IS 
'Год сдачи ЦТ';



/******************************************************************************/
/***                               Privileges                               ***/
/******************************************************************************/


/* Privileges of users */
GRANT ALL ON SERTIFICAT TO ABITUR1;
GRANT ALL ON SERTIFICAT TO ABITUR2;
GRANT ALL ON SERTIFICAT TO ABITUR3;
GRANT ALL ON SERTIFICAT TO ABITUR4;
GRANT ALL ON SERTIFICAT TO ABITURA;
GRANT ALL ON SERTIFICAT TO ALEXANDER_GONCHAROV;
GRANT ALL ON SERTIFICAT TO ASU;
GRANT ALL ON SERTIFICAT TO ASU1;
GRANT ALL ON SERTIFICAT TO ASU2;
GRANT ALL ON SERTIFICAT TO ASU3;
GRANT ALL ON SERTIFICAT TO ASU4;
GRANT ALL ON SERTIFICAT TO DEVELOPER;
GRANT ALL ON SERTIFICAT TO DEVELOPER2;
GRANT ALL ON SERTIFICAT TO IT1;
GRANT ALL ON SERTIFICAT TO IT2;
GRANT ALL ON SERTIFICAT TO IT3;
GRANT ALL ON SERTIFICAT TO IVANOVA_A;
GRANT ALL ON SERTIFICAT TO MVS1;
GRANT ALL ON SERTIFICAT TO MVS2;
GRANT ALL ON SERTIFICAT TO MVS3;
GRANT ALL ON SERTIFICAT TO MVS4;
GRANT ALL ON SERTIFICAT TO OFKIT1;
GRANT ALL ON SERTIFICAT TO OFKIT2;
GRANT ALL ON SERTIFICAT TO OFKIT3;
GRANT ALL ON SERTIFICAT TO OFKIT4;
GRANT ALL ON SERTIFICAT TO OKSANA;
GRANT ALL ON SERTIFICAT TO PK;
GRANT ALL ON SERTIFICAT TO PK_IT;
GRANT ALL ON SERTIFICAT TO PK_IT1;
GRANT ALL ON SERTIFICAT TO PK_IT2;
GRANT ALL ON SERTIFICAT TO PK_IT3;
GRANT ALL ON SERTIFICAT TO PK_IT4;
GRANT ALL ON SERTIFICAT TO PK_IT5;
GRANT ALL ON SERTIFICAT TO PK_MSTIG1;
GRANT ALL ON SERTIFICAT TO PK_MSTIG2;
GRANT ALL ON SERTIFICAT TO PK_MSTIG3;
GRANT ALL ON SERTIFICAT TO PK_MSTIG4;
GRANT ALL ON SERTIFICAT TO PK_MSTIGP1;
GRANT ALL ON SERTIFICAT TO PK_MSTIGP2;
GRANT ALL ON SERTIFICAT TO PK_MSTIG_1;
GRANT ALL ON SERTIFICAT TO PK_MSTIG_2;
GRANT ALL ON SERTIFICAT TO PK_MSTIG_3;
GRANT ALL ON SERTIFICAT TO PK_MSTIG_4;
GRANT ALL ON SERTIFICAT TO PK_MSTIG_P1;
GRANT ALL ON SERTIFICAT TO PK_MSTIG_P2;
GRANT ALL ON SERTIFICAT TO PK_MVS;
GRANT ALL ON SERTIFICAT TO PK_MVS1;
GRANT ALL ON SERTIFICAT TO PK_MVS2;
GRANT ALL ON SERTIFICAT TO PK_MVS3;
GRANT ALL ON SERTIFICAT TO PK_MVS4;
GRANT ALL ON SERTIFICAT TO PK_MVS5;
GRANT ALL ON SERTIFICAT TO PK_MVSP1;
GRANT ALL ON SERTIFICAT TO PK_MVSP2;
GRANT ALL ON SERTIFICAT TO PK_MVS_1;
GRANT ALL ON SERTIFICAT TO PK_MVS_2;
GRANT ALL ON SERTIFICAT TO PK_MVS_3;
GRANT ALL ON SERTIFICAT TO PK_MVS_4;
GRANT ALL ON SERTIFICAT TO PK_MVS_P1;
GRANT ALL ON SERTIFICAT TO PK_MVS_P2;
GRANT ALL ON SERTIFICAT TO PK_OFKIT;
GRANT ALL ON SERTIFICAT TO PK_OFKIT1;
GRANT ALL ON SERTIFICAT TO PK_OFKIT2;
GRANT ALL ON SERTIFICAT TO PK_OFKIT3;
GRANT ALL ON SERTIFICAT TO PK_OFKIT4;
GRANT ALL ON SERTIFICAT TO PK_OFKIT5;
GRANT ALL ON SERTIFICAT TO PK_OFKITP1;
GRANT ALL ON SERTIFICAT TO PK_OFKITP2;
GRANT ALL ON SERTIFICAT TO PK_OFK_1;
GRANT ALL ON SERTIFICAT TO PK_OFK_2;
GRANT ALL ON SERTIFICAT TO PK_OFK_3;
GRANT ALL ON SERTIFICAT TO PK_OFK_4;
GRANT ALL ON SERTIFICAT TO PK_OFK_P1;
GRANT ALL ON SERTIFICAT TO PK_OFK_P2;
GRANT ALL ON SERTIFICAT TO PK_OTV1;
GRANT ALL ON SERTIFICAT TO PK_OTV2;
GRANT ALL ON SERTIFICAT TO PK_OTV3;
GRANT ALL ON SERTIFICAT TO PK_OTV4;
GRANT ALL ON SERTIFICAT TO PK_SIIE;
GRANT ALL ON SERTIFICAT TO PK_SIIE1;
GRANT ALL ON SERTIFICAT TO PK_SIIE2;
GRANT ALL ON SERTIFICAT TO PK_SIIE3;
GRANT ALL ON SERTIFICAT TO PK_SIIE4;
GRANT ALL ON SERTIFICAT TO PK_SIIE5;
GRANT ALL ON SERTIFICAT TO PK_SIIEP1;
GRANT ALL ON SERTIFICAT TO PK_SIIEP2;
GRANT ALL ON SERTIFICAT TO PK_SIIEP3;
GRANT ALL ON SERTIFICAT TO PK_SIIE_1;
GRANT ALL ON SERTIFICAT TO PK_SIIE_2;
GRANT ALL ON SERTIFICAT TO PK_SIIE_3;
GRANT ALL ON SERTIFICAT TO PK_SIIE_4;
GRANT ALL ON SERTIFICAT TO PK_SIIE_P1;
GRANT ALL ON SERTIFICAT TO PK_SIIE_P2;
GRANT ALL ON SERTIFICAT TO SIIE1;
GRANT ALL ON SERTIFICAT TO SIIE2;
GRANT ALL ON SERTIFICAT TO SIIE3;
GRANT ALL ON SERTIFICAT TO SIIE4;
GRANT ALL ON SERTIFICAT TO UO_LAB;
GRANT ALL ON SERTIFICAT TO UO_N;
GRANT ALL ON SERTIFICAT TO UO_Z;