CREATE TABLE IF NOT EXISTS
SPECIALITY
(
    N_SPEC     SMALLINT,
    SPEC       VARCHAR(255),
    OLD_NUM    SMALLINT DEFAULT 0,
    CODE_SPEC  VARCHAR(10)
);



/******************************************************************************/
/***                               Privileges                               ***/
/******************************************************************************/


/* Privileges of users */
GRANT ALL ON SPECIALITY TO ABITUR1;
GRANT ALL ON SPECIALITY TO ABITUR2;
GRANT ALL ON SPECIALITY TO ABITUR3;
GRANT ALL ON SPECIALITY TO ABITUR4;
GRANT ALL ON SPECIALITY TO ABITURA;
GRANT ALL ON SPECIALITY TO ALEXANDER_GONCHAROV;
GRANT ALL ON SPECIALITY TO DEVELOPER;
GRANT ALL ON SPECIALITY TO IVANOVA_A;
GRANT ALL ON SPECIALITY TO OKSANA;
GRANT ALL ON SPECIALITY TO PK_MSTIG1;
GRANT ALL ON SPECIALITY TO PK_MSTIG2;
GRANT ALL ON SPECIALITY TO PK_MSTIG3;
GRANT ALL ON SPECIALITY TO PK_MSTIG4;
GRANT ALL ON SPECIALITY TO PK_MSTIGP1;
GRANT ALL ON SPECIALITY TO PK_MSTIGP2;
GRANT ALL ON SPECIALITY TO PK_MSTIG_1;
GRANT ALL ON SPECIALITY TO PK_MSTIG_2;
GRANT ALL ON SPECIALITY TO PK_MSTIG_3;
GRANT ALL ON SPECIALITY TO PK_MSTIG_4;
GRANT ALL ON SPECIALITY TO PK_MSTIG_P1;
GRANT ALL ON SPECIALITY TO PK_MSTIG_P2;
GRANT ALL ON SPECIALITY TO PK_MVS1;
GRANT ALL ON SPECIALITY TO PK_MVS2;
GRANT ALL ON SPECIALITY TO PK_MVS3;
GRANT ALL ON SPECIALITY TO PK_MVSP1;
GRANT ALL ON SPECIALITY TO PK_MVSP2;
GRANT ALL ON SPECIALITY TO PK_MVS_1;
GRANT ALL ON SPECIALITY TO PK_MVS_2;
GRANT ALL ON SPECIALITY TO PK_MVS_3;
GRANT ALL ON SPECIALITY TO PK_MVS_4;
GRANT ALL ON SPECIALITY TO PK_MVS_P1;
GRANT ALL ON SPECIALITY TO PK_MVS_P2;
GRANT ALL ON SPECIALITY TO PK_OFKIT1;
GRANT ALL ON SPECIALITY TO PK_OFKIT2;
GRANT ALL ON SPECIALITY TO PK_OFKIT3;
GRANT ALL ON SPECIALITY TO PK_OFKITP1;
GRANT ALL ON SPECIALITY TO PK_OFKITP2;
GRANT ALL ON SPECIALITY TO PK_OFK_1;
GRANT ALL ON SPECIALITY TO PK_OFK_2;
GRANT ALL ON SPECIALITY TO PK_OFK_3;
GRANT ALL ON SPECIALITY TO PK_OFK_4;
GRANT ALL ON SPECIALITY TO PK_OFK_P1;
GRANT ALL ON SPECIALITY TO PK_OFK_P2;
GRANT ALL ON SPECIALITY TO PK_OTV1;
GRANT ALL ON SPECIALITY TO PK_OTV2;
GRANT ALL ON SPECIALITY TO PK_OTV3;
GRANT ALL ON SPECIALITY TO PK_OTV4;
GRANT ALL ON SPECIALITY TO PK_SIIE1;
GRANT ALL ON SPECIALITY TO PK_SIIE2;
GRANT ALL ON SPECIALITY TO PK_SIIE3;
GRANT ALL ON SPECIALITY TO PK_SIIE4;
GRANT ALL ON SPECIALITY TO PK_SIIEP1;
GRANT ALL ON SPECIALITY TO PK_SIIEP2;
GRANT ALL ON SPECIALITY TO PK_SIIEP3;
GRANT ALL ON SPECIALITY TO PK_SIIE_1;
GRANT ALL ON SPECIALITY TO PK_SIIE_2;
GRANT ALL ON SPECIALITY TO PK_SIIE_3;
GRANT ALL ON SPECIALITY TO PK_SIIE_4;
GRANT ALL ON SPECIALITY TO PK_SIIE_P1;
GRANT ALL ON SPECIALITY TO PK_SIIE_P2;