CREATE TABLE IF NOT EXISTS
SPECIALIZ
(
    N_SPECIALIZ             SMALLINT,
    CODE_SPECIALIZ          VARCHAR(15),
    SPECIAL                 VARCHAR(80) COLLATE PXW_CYRL,
    N_FAC                   SMALLINT,
    N_SPEC                  SMALLINT,
    SPECIAL_SKLON           VARCHAR(80) COLLATE PXW_CYRL,
    SPECIAL_DIRECTION       VARCHAR(255) COLLATE PXW_CYRL,
    N_SPEC_DIR              INTEGER,
    SPECIAL_DIRECTION_SOKR  VARCHAR(255) COLLATE PXW_CYRL
);




/******************************************************************************/
/***                               Privileges                               ***/
/******************************************************************************/


/* Privileges of users */
GRANT ALL ON SPECIALIZ TO ABITUR1;
GRANT ALL ON SPECIALIZ TO ABITUR2;
GRANT ALL ON SPECIALIZ TO ABITUR3;
GRANT ALL ON SPECIALIZ TO ABITUR4;
GRANT ALL ON SPECIALIZ TO ABITURA;
GRANT ALL ON SPECIALIZ TO ALEXANDER_GONCHAROV;
GRANT ALL ON SPECIALIZ TO DEVELOPER;
GRANT ALL ON SPECIALIZ TO IVANOVA_A;
GRANT ALL ON SPECIALIZ TO OKSANA;
GRANT ALL ON SPECIALIZ TO PK_MSTIG1;
GRANT ALL ON SPECIALIZ TO PK_MSTIG2;
GRANT ALL ON SPECIALIZ TO PK_MSTIG3;
GRANT ALL ON SPECIALIZ TO PK_MSTIG4;
GRANT ALL ON SPECIALIZ TO PK_MSTIGP1;
GRANT ALL ON SPECIALIZ TO PK_MSTIGP2;
GRANT ALL ON SPECIALIZ TO PK_MSTIG_1;
GRANT ALL ON SPECIALIZ TO PK_MSTIG_2;
GRANT ALL ON SPECIALIZ TO PK_MSTIG_3;
GRANT ALL ON SPECIALIZ TO PK_MSTIG_4;
GRANT ALL ON SPECIALIZ TO PK_MSTIG_P1;
GRANT ALL ON SPECIALIZ TO PK_MSTIG_P2;
GRANT ALL ON SPECIALIZ TO PK_MVS1;
GRANT ALL ON SPECIALIZ TO PK_MVS2;
GRANT ALL ON SPECIALIZ TO PK_MVS3;
GRANT ALL ON SPECIALIZ TO PK_MVSP1;
GRANT ALL ON SPECIALIZ TO PK_MVSP2;
GRANT ALL ON SPECIALIZ TO PK_MVS_1;
GRANT ALL ON SPECIALIZ TO PK_MVS_2;
GRANT ALL ON SPECIALIZ TO PK_MVS_3;
GRANT ALL ON SPECIALIZ TO PK_MVS_4;
GRANT ALL ON SPECIALIZ TO PK_MVS_P1;
GRANT ALL ON SPECIALIZ TO PK_MVS_P2;
GRANT ALL ON SPECIALIZ TO PK_OFKIT1;
GRANT ALL ON SPECIALIZ TO PK_OFKIT2;
GRANT ALL ON SPECIALIZ TO PK_OFKIT3;
GRANT ALL ON SPECIALIZ TO PK_OFKITP1;
GRANT ALL ON SPECIALIZ TO PK_OFKITP2;
GRANT ALL ON SPECIALIZ TO PK_OFK_1;
GRANT ALL ON SPECIALIZ TO PK_OFK_2;
GRANT ALL ON SPECIALIZ TO PK_OFK_3;
GRANT ALL ON SPECIALIZ TO PK_OFK_4;
GRANT ALL ON SPECIALIZ TO PK_OFK_P1;
GRANT ALL ON SPECIALIZ TO PK_OFK_P2;
GRANT ALL ON SPECIALIZ TO PK_OTV1;
GRANT ALL ON SPECIALIZ TO PK_OTV2;
GRANT ALL ON SPECIALIZ TO PK_OTV3;
GRANT ALL ON SPECIALIZ TO PK_OTV4;
GRANT ALL ON SPECIALIZ TO PK_SIIE1;
GRANT ALL ON SPECIALIZ TO PK_SIIE2;
GRANT ALL ON SPECIALIZ TO PK_SIIE3;
GRANT ALL ON SPECIALIZ TO PK_SIIE4;
GRANT ALL ON SPECIALIZ TO PK_SIIEP1;
GRANT ALL ON SPECIALIZ TO PK_SIIEP2;
GRANT ALL ON SPECIALIZ TO PK_SIIEP3;
GRANT ALL ON SPECIALIZ TO PK_SIIE_1;
GRANT ALL ON SPECIALIZ TO PK_SIIE_2;
GRANT ALL ON SPECIALIZ TO PK_SIIE_3;
GRANT ALL ON SPECIALIZ TO PK_SIIE_4;
GRANT ALL ON SPECIALIZ TO PK_SIIE_P1;
GRANT ALL ON SPECIALIZ TO PK_SIIE_P2;