/******************************************************************************/
/***               Generated by IBExpert 01.07.2022 14:10:39                ***/
/******************************************************************************/

/******************************************************************************/
/***      Following SET SQL DIALECT is just for the Database Comparer       ***/
/******************************************************************************/


/******************************************************************************/
/***                                 Tables                                 ***/
/******************************************************************************/



CREATE TABLE BANK (
    AUTHCODE  INTEGER,
    CARDPAN   INTEGER
);




/******************************************************************************/
/***                               Privileges                               ***/
/******************************************************************************/


/* Privileges of users */
GRANT ALL ON BANK TO GUNICH_O;
GRANT ALL ON BANK TO KOSIK_N;
GRANT ALL ON BANK TO LIASHKOVICH_I;
GRANT ALL ON BANK TO OK_STUD_2;
GRANT ALL ON BANK TO PK_OTV1;
GRANT ALL ON BANK TO PK_OTV2;
GRANT ALL ON BANK TO PK_OTV3;
GRANT ALL ON BANK TO PK_OTV4;
GRANT ALL ON BANK TO SADIK;
GRANT ALL ON BANK TO SETUN1998;
GRANT ALL ON BANK TO SMOLENKOVA_T;
GRANT ALL ON BANK TO ZHANNA_73;