/******************************************************************************/
/***               Generated by IBExpert 01.07.2022 14:23:07                ***/
/******************************************************************************/

/******************************************************************************/
/***      Following SET SQL DIALECT is just for the Database Comparer       ***/
/******************************************************************************/


/******************************************************************************/
/***                                 Tables                                 ***/
/******************************************************************************/



CREATE TABLE EDU_PLAN_PAU (
    N_PLAN            INTEGER GENERATED BY DEFAULT AS IDENTITY,
    N_OBJECT          SMALLINT,
    SEMESTR           SMALLINT,
    CLOCK_PLAN        DOUBLE PRECISION,
    YEAR_PLAN         SMALLINT,
    N_FAC             SMALLINT,
    ZACH_EXUM         SMALLINT,
    VID_EDU_PLAN      SMALLINT,
    SPECKURS          SMALLINT,
    STATUS_CONTROL    SMALLINT,
    CLOCK_PLAN_ALL    SMALLINT,
    TYPE_PLAN         SMALLINT,
    ALL_HOURS         SMALLINT,
    CLASSROOM_HOURS   SMALLINT,
    LECTURE_HOURS     SMALLINT,
    LABORATORY_HOURS  SMALLINT,
    PRACTICAL_HOURS   SMALLINT,
    SEMINAR_HOURS     SMALLINT
);




/******************************************************************************/
/***                              Primary keys                              ***/
/******************************************************************************/

ALTER TABLE EDU_PLAN_PAU ADD CONSTRAINT PK_EDU_PLAN_PAU PRIMARY KEY (N_PLAN);


/******************************************************************************/
/***                               Privileges                               ***/
/******************************************************************************/


/* Privileges of users */
GRANT ALL ON EDU_PLAN_PAU TO ALENA_2109;
GRANT ALL ON EDU_PLAN_PAU TO ALINA_E;
GRANT ALL ON EDU_PLAN_PAU TO DEVELOPER;
GRANT ALL ON EDU_PLAN_PAU TO GONCHAROV434_2;
GRANT ALL ON EDU_PLAN_PAU TO GUNICH_O;
GRANT ALL ON EDU_PLAN_PAU TO HOSTEL_PK1;
GRANT ALL ON EDU_PLAN_PAU TO HOSTEL_PK2;
GRANT ALL ON EDU_PLAN_PAU TO KANDRUKEVICH_M;
GRANT ALL ON EDU_PLAN_PAU TO KOSIK_N;
GRANT ALL ON EDU_PLAN_PAU TO LIASHKOVICH_I;
GRANT ALL ON EDU_PLAN_PAU TO MARINA;
GRANT ALL ON EDU_PLAN_PAU TO OK_STUD_2;
GRANT ALL ON EDU_PLAN_PAU TO PK_MSTIG_1;
GRANT ALL ON EDU_PLAN_PAU TO PK_MSTIG_2;
GRANT ALL ON EDU_PLAN_PAU TO PK_MSTIG_3;
GRANT ALL ON EDU_PLAN_PAU TO PK_MSTIG_4;
GRANT ALL ON EDU_PLAN_PAU TO PK_MSTIG_P1;
GRANT ALL ON EDU_PLAN_PAU TO PK_MSTIG_P2;
GRANT ALL ON EDU_PLAN_PAU TO PK_MVS_1;
GRANT ALL ON EDU_PLAN_PAU TO PK_MVS_2;
GRANT ALL ON EDU_PLAN_PAU TO PK_MVS_3;
GRANT ALL ON EDU_PLAN_PAU TO PK_MVS_4;
GRANT ALL ON EDU_PLAN_PAU TO PK_MVS_P1;
GRANT ALL ON EDU_PLAN_PAU TO PK_MVS_P2;
GRANT ALL ON EDU_PLAN_PAU TO PK_OFK_1;
GRANT ALL ON EDU_PLAN_PAU TO PK_OFK_2;
GRANT ALL ON EDU_PLAN_PAU TO PK_OFK_3;
GRANT ALL ON EDU_PLAN_PAU TO PK_OFK_4;
GRANT ALL ON EDU_PLAN_PAU TO PK_OFK_P1;
GRANT ALL ON EDU_PLAN_PAU TO PK_OFK_P2;
GRANT ALL ON EDU_PLAN_PAU TO PK_OTV1;
GRANT ALL ON EDU_PLAN_PAU TO PK_OTV2;
GRANT ALL ON EDU_PLAN_PAU TO PK_OTV3;
GRANT ALL ON EDU_PLAN_PAU TO PK_OTV4;
GRANT ALL ON EDU_PLAN_PAU TO PK_SIIE_1;
GRANT ALL ON EDU_PLAN_PAU TO PK_SIIE_2;
GRANT ALL ON EDU_PLAN_PAU TO PK_SIIE_3;
GRANT ALL ON EDU_PLAN_PAU TO PK_SIIE_4;
GRANT ALL ON EDU_PLAN_PAU TO PK_SIIE_P1;
GRANT ALL ON EDU_PLAN_PAU TO PK_SIIE_P2;
GRANT ALL ON EDU_PLAN_PAU TO SADIK;
GRANT ALL ON EDU_PLAN_PAU TO SEL_COM;
GRANT ALL ON EDU_PLAN_PAU TO SETUN1998;
GRANT ALL ON EDU_PLAN_PAU TO SMOLENKOVA_T;
GRANT ALL ON EDU_PLAN_PAU TO ZHANNA_73;