/******************************************************************************/
/***               Generated by IBExpert 01.07.2022 14:22:02                ***/
/******************************************************************************/

/******************************************************************************/
/***      Following SET SQL DIALECT is just for the Database Comparer       ***/
/******************************************************************************/


/******************************************************************************/
/***                                 Tables                                 ***/
/******************************************************************************/



CREATE TABLE EDU_LEVEL (
    ID    INTEGER GENERATED BY DEFAULT AS IDENTITY,
    NAME  VARCHAR(20)
);




/******************************************************************************/
/***                              Primary keys                              ***/
/******************************************************************************/

ALTER TABLE EDU_LEVEL ADD CONSTRAINT PK_EDU_LEVEL PRIMARY KEY (ID);


/******************************************************************************/
/***                               Privileges                               ***/
/******************************************************************************/


/* Privileges of users */
GRANT ALL ON EDU_LEVEL TO ALENA_2109;
GRANT ALL ON EDU_LEVEL TO ALINA_E;
GRANT ALL ON EDU_LEVEL TO DVORETSKAYA_K;
GRANT ALL ON EDU_LEVEL TO GONCHAROV434_2;
GRANT ALL ON EDU_LEVEL TO GUNICH_O;
GRANT ALL ON EDU_LEVEL TO HOSTEL_PK1;
GRANT ALL ON EDU_LEVEL TO HOSTEL_PK2;
GRANT ALL ON EDU_LEVEL TO KANDRUKEVICH_M;
GRANT ALL ON EDU_LEVEL TO KOSIK_N;
GRANT ALL ON EDU_LEVEL TO LIASHKOVICH_I;
GRANT ALL ON EDU_LEVEL TO LTRFYFN2019;
GRANT ALL ON EDU_LEVEL TO MARINA;
GRANT ALL ON EDU_LEVEL TO OK_STUD_2;
GRANT ALL ON EDU_LEVEL TO PK_MSTIG_1;
GRANT ALL ON EDU_LEVEL TO PK_MSTIG_2;
GRANT ALL ON EDU_LEVEL TO PK_MSTIG_3;
GRANT ALL ON EDU_LEVEL TO PK_MSTIG_4;
GRANT ALL ON EDU_LEVEL TO PK_MSTIG_P1;
GRANT ALL ON EDU_LEVEL TO PK_MSTIG_P2;
GRANT ALL ON EDU_LEVEL TO PK_MVS_1;
GRANT ALL ON EDU_LEVEL TO PK_MVS_2;
GRANT ALL ON EDU_LEVEL TO PK_MVS_3;
GRANT ALL ON EDU_LEVEL TO PK_MVS_4;
GRANT ALL ON EDU_LEVEL TO PK_MVS_P1;
GRANT ALL ON EDU_LEVEL TO PK_MVS_P2;
GRANT ALL ON EDU_LEVEL TO PK_OFK_1;
GRANT ALL ON EDU_LEVEL TO PK_OFK_2;
GRANT ALL ON EDU_LEVEL TO PK_OFK_3;
GRANT ALL ON EDU_LEVEL TO PK_OFK_4;
GRANT ALL ON EDU_LEVEL TO PK_OFK_P1;
GRANT ALL ON EDU_LEVEL TO PK_OFK_P2;
GRANT ALL ON EDU_LEVEL TO PK_OTV1;
GRANT ALL ON EDU_LEVEL TO PK_OTV2;
GRANT ALL ON EDU_LEVEL TO PK_OTV3;
GRANT ALL ON EDU_LEVEL TO PK_OTV4;
GRANT ALL ON EDU_LEVEL TO PK_SIIE_1;
GRANT ALL ON EDU_LEVEL TO PK_SIIE_2;
GRANT ALL ON EDU_LEVEL TO PK_SIIE_3;
GRANT ALL ON EDU_LEVEL TO PK_SIIE_4;
GRANT ALL ON EDU_LEVEL TO PK_SIIE_P1;
GRANT ALL ON EDU_LEVEL TO PK_SIIE_P2;
GRANT ALL ON EDU_LEVEL TO SADIK;
GRANT ALL ON EDU_LEVEL TO SEL_COM;
GRANT ALL ON EDU_LEVEL TO SETUN1998;
GRANT ALL ON EDU_LEVEL TO SMOLENKOVA_T;
GRANT ALL ON EDU_LEVEL TO ZHANNA_73;