/******************************************************************************/
/***               Generated by IBExpert 01.07.2022 14:19:56                ***/
/******************************************************************************/

/******************************************************************************/
/***      Following SET SQL DIALECT is just for the Database Comparer       ***/
/******************************************************************************/


/******************************************************************************/
/***                                 Tables                                 ***/
/******************************************************************************/



CREATE TABLE EDUCATION (
    EDUCATION_ID  INTEGER GENERATED BY DEFAULT AS IDENTITY,
    EDUCATION     VARCHAR(30)
);




/******************************************************************************/
/***                              Primary keys                              ***/
/******************************************************************************/

ALTER TABLE EDUCATION ADD CONSTRAINT PK_EDUCATION PRIMARY KEY (EDUCATION_ID);


/******************************************************************************/
/***                               Privileges                               ***/
/******************************************************************************/


/* Privileges of users */
GRANT ALL ON EDUCATION TO ALENA_2109;
GRANT ALL ON EDUCATION TO ALINA_E;
GRANT ALL ON EDUCATION TO DEVELOPER;
GRANT ALL ON EDUCATION TO DVORETSKAYA_K;
GRANT ALL ON EDUCATION TO GONCHAROV434_2;
GRANT ALL ON EDUCATION TO GUNICH_O;
GRANT ALL ON EDUCATION TO HOSTEL_PK1;
GRANT ALL ON EDUCATION TO HOSTEL_PK2;
GRANT ALL ON EDUCATION TO KANDRUKEVICH_M;
GRANT ALL ON EDUCATION TO KOSIK_N;
GRANT ALL ON EDUCATION TO LIASHKOVICH_I;
GRANT ALL ON EDUCATION TO LTRFYFN2019;
GRANT ALL ON EDUCATION TO MARINA;
GRANT ALL ON EDUCATION TO OK_STUD_2;
GRANT ALL ON EDUCATION TO PK_MSTIG_1;
GRANT ALL ON EDUCATION TO PK_MSTIG_2;
GRANT ALL ON EDUCATION TO PK_MSTIG_3;
GRANT ALL ON EDUCATION TO PK_MSTIG_4;
GRANT ALL ON EDUCATION TO PK_MSTIG_P1;
GRANT ALL ON EDUCATION TO PK_MSTIG_P2;
GRANT ALL ON EDUCATION TO PK_MVS_1;
GRANT ALL ON EDUCATION TO PK_MVS_2;
GRANT ALL ON EDUCATION TO PK_MVS_3;
GRANT ALL ON EDUCATION TO PK_MVS_4;
GRANT ALL ON EDUCATION TO PK_MVS_P1;
GRANT ALL ON EDUCATION TO PK_MVS_P2;
GRANT ALL ON EDUCATION TO PK_OFK_1;
GRANT ALL ON EDUCATION TO PK_OFK_2;
GRANT ALL ON EDUCATION TO PK_OFK_3;
GRANT ALL ON EDUCATION TO PK_OFK_4;
GRANT ALL ON EDUCATION TO PK_OFK_P1;
GRANT ALL ON EDUCATION TO PK_OFK_P2;
GRANT ALL ON EDUCATION TO PK_OTV1;
GRANT ALL ON EDUCATION TO PK_OTV2;
GRANT ALL ON EDUCATION TO PK_OTV3;
GRANT ALL ON EDUCATION TO PK_OTV4;
GRANT ALL ON EDUCATION TO PK_SIIE_1;
GRANT ALL ON EDUCATION TO PK_SIIE_2;
GRANT ALL ON EDUCATION TO PK_SIIE_3;
GRANT ALL ON EDUCATION TO PK_SIIE_4;
GRANT ALL ON EDUCATION TO PK_SIIE_P1;
GRANT ALL ON EDUCATION TO PK_SIIE_P2;
GRANT ALL ON EDUCATION TO SADIK;
GRANT ALL ON EDUCATION TO SEL_COM;
GRANT ALL ON EDUCATION TO SETUN1998;
GRANT ALL ON EDUCATION TO SMOLENKOVA_T;
GRANT ALL ON EDUCATION TO ZHANNA_73;