/******************************************************************************/
/***               Generated by IBExpert 01.07.2022 14:27:56                ***/
/******************************************************************************/

/******************************************************************************/
/***      Following SET SQL DIALECT is just for the Database Comparer       ***/
/******************************************************************************/


/******************************************************************************/
/***                                 Tables                                 ***/
/******************************************************************************/



CREATE TABLE GENDER (
    GENDER_ID  INTEGER GENERATED BY DEFAULT AS IDENTITY,
    GENDER     VARCHAR(1)
);




/******************************************************************************/
/***                              Primary keys                              ***/
/******************************************************************************/

ALTER TABLE GENDER ADD CONSTRAINT PK_GENDER PRIMARY KEY (GENDER_ID);


/******************************************************************************/
/***                               Privileges                               ***/
/******************************************************************************/


/* Privileges of users */
GRANT ALL ON GENDER TO ALENA_2109;
GRANT ALL ON GENDER TO ALINA_E;
GRANT ALL ON GENDER TO DEVELOPER;
GRANT ALL ON GENDER TO DVORETSKAYA_K;
GRANT ALL ON GENDER TO GONCHAROV434_2;
GRANT ALL ON GENDER TO GUNICH_O;
GRANT ALL ON GENDER TO HOSTEL_PK1;
GRANT ALL ON GENDER TO HOSTEL_PK2;
GRANT ALL ON GENDER TO KANDRUKEVICH_M;
GRANT ALL ON GENDER TO KOSIK_N;
GRANT ALL ON GENDER TO LIASHKOVICH_I;
GRANT ALL ON GENDER TO LTRFYFN2019;
GRANT ALL ON GENDER TO MARINA;
GRANT ALL ON GENDER TO OK_STUD_2;
GRANT ALL ON GENDER TO PK_MSTIG_1;
GRANT ALL ON GENDER TO PK_MSTIG_2;
GRANT ALL ON GENDER TO PK_MSTIG_3;
GRANT ALL ON GENDER TO PK_MSTIG_4;
GRANT ALL ON GENDER TO PK_MSTIG_P1;
GRANT ALL ON GENDER TO PK_MSTIG_P2;
GRANT ALL ON GENDER TO PK_MVS_1;
GRANT ALL ON GENDER TO PK_MVS_2;
GRANT ALL ON GENDER TO PK_MVS_3;
GRANT ALL ON GENDER TO PK_MVS_4;
GRANT ALL ON GENDER TO PK_MVS_P1;
GRANT ALL ON GENDER TO PK_MVS_P2;
GRANT ALL ON GENDER TO PK_OFK_1;
GRANT ALL ON GENDER TO PK_OFK_2;
GRANT ALL ON GENDER TO PK_OFK_3;
GRANT ALL ON GENDER TO PK_OFK_4;
GRANT ALL ON GENDER TO PK_OFK_P1;
GRANT ALL ON GENDER TO PK_OFK_P2;
GRANT ALL ON GENDER TO PK_OTV1;
GRANT ALL ON GENDER TO PK_OTV2;
GRANT ALL ON GENDER TO PK_OTV3;
GRANT ALL ON GENDER TO PK_OTV4;
GRANT ALL ON GENDER TO PK_SIIE_1;
GRANT ALL ON GENDER TO PK_SIIE_2;
GRANT ALL ON GENDER TO PK_SIIE_3;
GRANT ALL ON GENDER TO PK_SIIE_4;
GRANT ALL ON GENDER TO PK_SIIE_P1;
GRANT ALL ON GENDER TO PK_SIIE_P2;
GRANT ALL ON GENDER TO SADIK;
GRANT ALL ON GENDER TO SEL_COM;
GRANT ALL ON GENDER TO SETUN1998;
GRANT ALL ON GENDER TO SMOLENKOVA_T;
GRANT ALL ON GENDER TO ZHANNA_73;