/******************************************************************************/
/***               Generated by IBExpert 01.07.2022 14:37:11                ***/
/******************************************************************************/

/******************************************************************************/
/***      Following SET SQL DIALECT is just for the Database Comparer       ***/
/******************************************************************************/


/******************************************************************************/
/***                                 Tables                                 ***/
/******************************************************************************/


CREATE GENERATOR LOCALITY_NEW_ID;

CREATE TABLE LOCALITY_NEW (
    ID             INTEGER NOT NULL,
    N_REGION       INTEGER,
    N_DISTRICT     INTEGER,
    NAME_LOCALITY  VARCHAR(60),
    CODE_SOATO     VARCHAR(10),
    CODE_CATEGORY  INTEGER
);




/******************************************************************************/
/***                              Primary keys                              ***/
/******************************************************************************/

ALTER TABLE LOCALITY_NEW ADD CONSTRAINT PK_LOCALITY_NEW PRIMARY KEY (ID);


/******************************************************************************/
/***                                Triggers                                ***/
/******************************************************************************/



SET TERM ^ ;



/******************************************************************************/
/***                          Triggers for tables                           ***/
/******************************************************************************/



/* Trigger: LOCALITY_NEW_BI0 */
CREATE OR ALTER TRIGGER LOCALITY_NEW_BI0 FOR LOCALITY_NEW
ACTIVE BEFORE INSERT POSITION 0
AS
begin
  IF (NEW.id IS NULL) THEN
    NEW.id = GEN_ID(locality_new_id,1);
end
^

SET TERM ; ^



/******************************************************************************/
/***                               Privileges                               ***/
/******************************************************************************/


/* Privileges of users */
GRANT ALL ON LOCALITY_NEW TO ALENA_2109;
GRANT ALL ON LOCALITY_NEW TO ALINA_E;
GRANT ALL ON LOCALITY_NEW TO GONCHAROV434_2;
GRANT ALL ON LOCALITY_NEW TO GUNICH_O;
GRANT ALL ON LOCALITY_NEW TO HOSTEL_PK1;
GRANT ALL ON LOCALITY_NEW TO HOSTEL_PK2;
GRANT ALL ON LOCALITY_NEW TO KANDRUKEVICH_M;
GRANT ALL ON LOCALITY_NEW TO KOSIK_N;
GRANT ALL ON LOCALITY_NEW TO LIASHKOVICH_I;
GRANT ALL ON LOCALITY_NEW TO MARINA;
GRANT ALL ON LOCALITY_NEW TO OK_STUD_2;
GRANT ALL ON LOCALITY_NEW TO PK_MSTIG_1;
GRANT ALL ON LOCALITY_NEW TO PK_MSTIG_2;
GRANT ALL ON LOCALITY_NEW TO PK_MSTIG_3;
GRANT ALL ON LOCALITY_NEW TO PK_MSTIG_4;
GRANT ALL ON LOCALITY_NEW TO PK_MSTIG_P1;
GRANT ALL ON LOCALITY_NEW TO PK_MSTIG_P2;
GRANT ALL ON LOCALITY_NEW TO PK_MVS_1;
GRANT ALL ON LOCALITY_NEW TO PK_MVS_2;
GRANT ALL ON LOCALITY_NEW TO PK_MVS_3;
GRANT ALL ON LOCALITY_NEW TO PK_MVS_4;
GRANT ALL ON LOCALITY_NEW TO PK_MVS_P1;
GRANT ALL ON LOCALITY_NEW TO PK_MVS_P2;
GRANT ALL ON LOCALITY_NEW TO PK_OFK_1;
GRANT ALL ON LOCALITY_NEW TO PK_OFK_2;
GRANT ALL ON LOCALITY_NEW TO PK_OFK_3;
GRANT ALL ON LOCALITY_NEW TO PK_OFK_4;
GRANT ALL ON LOCALITY_NEW TO PK_OFK_P1;
GRANT ALL ON LOCALITY_NEW TO PK_OFK_P2;
GRANT ALL ON LOCALITY_NEW TO PK_OTV1;
GRANT ALL ON LOCALITY_NEW TO PK_OTV2;
GRANT ALL ON LOCALITY_NEW TO PK_OTV3;
GRANT ALL ON LOCALITY_NEW TO PK_OTV4;
GRANT ALL ON LOCALITY_NEW TO PK_SIIE_1;
GRANT ALL ON LOCALITY_NEW TO PK_SIIE_2;
GRANT ALL ON LOCALITY_NEW TO PK_SIIE_3;
GRANT ALL ON LOCALITY_NEW TO PK_SIIE_4;
GRANT ALL ON LOCALITY_NEW TO PK_SIIE_P1;
GRANT ALL ON LOCALITY_NEW TO PK_SIIE_P2;
GRANT ALL ON LOCALITY_NEW TO SADIK;
GRANT ALL ON LOCALITY_NEW TO SEL_COM;
GRANT ALL ON LOCALITY_NEW TO SETUN1998;
GRANT ALL ON LOCALITY_NEW TO SMOLENKOVA_T;
GRANT ALL ON LOCALITY_NEW TO ZHANNA_73;