/******************************************************************************/
/***               Generated by IBExpert 01.07.2022 14:37:46                ***/
/******************************************************************************/

/******************************************************************************/
/***      Following SET SQL DIALECT is just for the Database Comparer       ***/
/******************************************************************************/


/******************************************************************************/
/***                                 Tables                                 ***/
/******************************************************************************/



CREATE TABLE MARITAL_STATUS (
    MARITAL_ID  INTEGER GENERATED BY DEFAULT AS IDENTITY,
    STATUS      VARCHAR(15),
    GENDER_ID   INTEGER
);




/******************************************************************************/
/***                              Primary keys                              ***/
/******************************************************************************/

ALTER TABLE MARITAL_STATUS ADD CONSTRAINT PK_MARITAL_STATUS PRIMARY KEY (MARITAL_ID);


/******************************************************************************/
/***                              Foreign keys                              ***/
/******************************************************************************/

ALTER TABLE MARITAL_STATUS ADD CONSTRAINT FK_MARITAL_STATUS_GENDER FOREIGN KEY (GENDER_ID) REFERENCES GENDER (GENDER_ID) ON DELETE CASCADE ON UPDATE CASCADE;


/******************************************************************************/
/***                               Privileges                               ***/
/******************************************************************************/


/* Privileges of users */
GRANT ALL ON MARITAL_STATUS TO ALENA_2109;
GRANT ALL ON MARITAL_STATUS TO ALINA_E;
GRANT ALL ON MARITAL_STATUS TO DEVELOPER;
GRANT ALL ON MARITAL_STATUS TO DVORETSKAYA_K;
GRANT ALL ON MARITAL_STATUS TO GONCHAROV434_2;
GRANT ALL ON MARITAL_STATUS TO GUNICH_O;
GRANT ALL ON MARITAL_STATUS TO HOSTEL_PK1;
GRANT ALL ON MARITAL_STATUS TO HOSTEL_PK2;
GRANT ALL ON MARITAL_STATUS TO KANDRUKEVICH_M;
GRANT ALL ON MARITAL_STATUS TO KOSIK_N;
GRANT ALL ON MARITAL_STATUS TO LIASHKOVICH_I;
GRANT ALL ON MARITAL_STATUS TO LTRFYFN2019;
GRANT ALL ON MARITAL_STATUS TO MARINA;
GRANT ALL ON MARITAL_STATUS TO OK_STUD_2;
GRANT ALL ON MARITAL_STATUS TO PK_MSTIG_1;
GRANT ALL ON MARITAL_STATUS TO PK_MSTIG_2;
GRANT ALL ON MARITAL_STATUS TO PK_MSTIG_3;
GRANT ALL ON MARITAL_STATUS TO PK_MSTIG_4;
GRANT ALL ON MARITAL_STATUS TO PK_MSTIG_P1;
GRANT ALL ON MARITAL_STATUS TO PK_MSTIG_P2;
GRANT ALL ON MARITAL_STATUS TO PK_MVS_1;
GRANT ALL ON MARITAL_STATUS TO PK_MVS_2;
GRANT ALL ON MARITAL_STATUS TO PK_MVS_3;
GRANT ALL ON MARITAL_STATUS TO PK_MVS_4;
GRANT ALL ON MARITAL_STATUS TO PK_MVS_P1;
GRANT ALL ON MARITAL_STATUS TO PK_MVS_P2;
GRANT ALL ON MARITAL_STATUS TO PK_OFK_1;
GRANT ALL ON MARITAL_STATUS TO PK_OFK_2;
GRANT ALL ON MARITAL_STATUS TO PK_OFK_3;
GRANT ALL ON MARITAL_STATUS TO PK_OFK_4;
GRANT ALL ON MARITAL_STATUS TO PK_OFK_P1;
GRANT ALL ON MARITAL_STATUS TO PK_OFK_P2;
GRANT ALL ON MARITAL_STATUS TO PK_OTV1;
GRANT ALL ON MARITAL_STATUS TO PK_OTV2;
GRANT ALL ON MARITAL_STATUS TO PK_OTV3;
GRANT ALL ON MARITAL_STATUS TO PK_OTV4;
GRANT ALL ON MARITAL_STATUS TO PK_SIIE_1;
GRANT ALL ON MARITAL_STATUS TO PK_SIIE_2;
GRANT ALL ON MARITAL_STATUS TO PK_SIIE_3;
GRANT ALL ON MARITAL_STATUS TO PK_SIIE_4;
GRANT ALL ON MARITAL_STATUS TO PK_SIIE_P1;
GRANT ALL ON MARITAL_STATUS TO PK_SIIE_P2;
GRANT ALL ON MARITAL_STATUS TO SADIK;
GRANT ALL ON MARITAL_STATUS TO SEL_COM;
GRANT ALL ON MARITAL_STATUS TO SETUN1998;
GRANT ALL ON MARITAL_STATUS TO SMOLENKOVA_T;
GRANT ALL ON MARITAL_STATUS TO ZHANNA_73;