/******************************************************************************/
/***               Generated by IBExpert 01.07.2022 14:47:17                ***/
/******************************************************************************/

/******************************************************************************/
/***      Following SET SQL DIALECT is just for the Database Comparer       ***/
/******************************************************************************/


/******************************************************************************/
/***                                 Tables                                 ***/
/******************************************************************************/



CREATE TABLE PASS_PAU (
    NOMER      INTEGER,
    N_CAUSE    SMALLINT,
    D_PASS     DATE,
    HOUR_PASS  SMALLINT
);




/******************************************************************************/
/***                              Foreign keys                              ***/
/******************************************************************************/

ALTER TABLE PASS_PAU ADD CONSTRAINT FK_PASS_PAU_NOMER FOREIGN KEY (NOMER) REFERENCES PEOPLE_AFTER_UNIVERSITY (NOMER);
ALTER TABLE PASS_PAU ADD CONSTRAINT FK_PASS_PAU_N_CAUSE FOREIGN KEY (N_CAUSE) REFERENCES CAUSE_PASS (N_CAUSE)
  USING DESCENDING INDEX FK_PASS_PAU_N_CAUSE;


/******************************************************************************/
/***                               Privileges                               ***/
/******************************************************************************/


/* Privileges of users */
GRANT ALL ON PASS_PAU TO ALENA_2109;
GRANT ALL ON PASS_PAU TO ALINA_E;
GRANT ALL ON PASS_PAU TO DEVELOPER;
GRANT ALL ON PASS_PAU TO GONCHAROV434_2;
GRANT ALL ON PASS_PAU TO GUNICH_O;
GRANT ALL ON PASS_PAU TO HOSTEL_PK1;
GRANT ALL ON PASS_PAU TO HOSTEL_PK2;
GRANT ALL ON PASS_PAU TO KANDRUKEVICH_M;
GRANT ALL ON PASS_PAU TO KOSIK_N;
GRANT ALL ON PASS_PAU TO LIASHKOVICH_I;
GRANT ALL ON PASS_PAU TO MARINA;
GRANT ALL ON PASS_PAU TO OK_STUD_2;
GRANT ALL ON PASS_PAU TO PK_MSTIG_1;
GRANT ALL ON PASS_PAU TO PK_MSTIG_2;
GRANT ALL ON PASS_PAU TO PK_MSTIG_3;
GRANT ALL ON PASS_PAU TO PK_MSTIG_4;
GRANT ALL ON PASS_PAU TO PK_MSTIG_P1;
GRANT ALL ON PASS_PAU TO PK_MSTIG_P2;
GRANT ALL ON PASS_PAU TO PK_MVS_1;
GRANT ALL ON PASS_PAU TO PK_MVS_2;
GRANT ALL ON PASS_PAU TO PK_MVS_3;
GRANT ALL ON PASS_PAU TO PK_MVS_4;
GRANT ALL ON PASS_PAU TO PK_MVS_P1;
GRANT ALL ON PASS_PAU TO PK_MVS_P2;
GRANT ALL ON PASS_PAU TO PK_OFK_1;
GRANT ALL ON PASS_PAU TO PK_OFK_2;
GRANT ALL ON PASS_PAU TO PK_OFK_3;
GRANT ALL ON PASS_PAU TO PK_OFK_4;
GRANT ALL ON PASS_PAU TO PK_OFK_P1;
GRANT ALL ON PASS_PAU TO PK_OFK_P2;
GRANT ALL ON PASS_PAU TO PK_OTV1;
GRANT ALL ON PASS_PAU TO PK_OTV2;
GRANT ALL ON PASS_PAU TO PK_OTV3;
GRANT ALL ON PASS_PAU TO PK_OTV4;
GRANT ALL ON PASS_PAU TO PK_SIIE_1;
GRANT ALL ON PASS_PAU TO PK_SIIE_2;
GRANT ALL ON PASS_PAU TO PK_SIIE_3;
GRANT ALL ON PASS_PAU TO PK_SIIE_4;
GRANT ALL ON PASS_PAU TO PK_SIIE_P1;
GRANT ALL ON PASS_PAU TO PK_SIIE_P2;
GRANT ALL ON PASS_PAU TO SADIK;
GRANT ALL ON PASS_PAU TO SEL_COM;
GRANT ALL ON PASS_PAU TO SETUN1998;
GRANT ALL ON PASS_PAU TO SMOLENKOVA_T;
GRANT ALL ON PASS_PAU TO ZHANNA_73;