/******************************************************************************/
/***               Generated by IBExpert 01.07.2022 15:01:49                ***/
/******************************************************************************/

/******************************************************************************/
/***      Following SET SQL DIALECT is just for the Database Comparer       ***/
/******************************************************************************/


/******************************************************************************/
/***                                 Tables                                 ***/
/******************************************************************************/



CREATE TABLE PROST (
    ID    INTEGER GENERATED BY DEFAULT AS IDENTITY,
    NAME  VARCHAR(255)
);




/******************************************************************************/
/***                              Primary keys                              ***/
/******************************************************************************/

ALTER TABLE PROST ADD CONSTRAINT PK_PROST PRIMARY KEY (ID);


/******************************************************************************/
/***                               Privileges                               ***/
/******************************************************************************/


/* Privileges of users */
GRANT ALL ON PROST TO ALENA_2109;
GRANT ALL ON PROST TO ALINA_E;
GRANT ALL ON PROST TO DEVELOPER;
GRANT ALL ON PROST TO GONCHAROV434_2;
GRANT ALL ON PROST TO GUNICH_O;
GRANT ALL ON PROST TO HOSTEL_PK1;
GRANT ALL ON PROST TO HOSTEL_PK2;
GRANT ALL ON PROST TO KANDRUKEVICH_M;
GRANT ALL ON PROST TO KOSIK_N;
GRANT ALL ON PROST TO LIASHKOVICH_I;
GRANT ALL ON PROST TO OK_STUD_2;
GRANT ALL ON PROST TO PK_MSTIG_1;
GRANT ALL ON PROST TO PK_MSTIG_2;
GRANT ALL ON PROST TO PK_MSTIG_3;
GRANT ALL ON PROST TO PK_MSTIG_4;
GRANT ALL ON PROST TO PK_MSTIG_P1;
GRANT ALL ON PROST TO PK_MSTIG_P2;
GRANT ALL ON PROST TO PK_MVS_1;
GRANT ALL ON PROST TO PK_MVS_2;
GRANT ALL ON PROST TO PK_MVS_3;
GRANT ALL ON PROST TO PK_MVS_4;
GRANT ALL ON PROST TO PK_MVS_P1;
GRANT ALL ON PROST TO PK_MVS_P2;
GRANT ALL ON PROST TO PK_OFK_1;
GRANT ALL ON PROST TO PK_OFK_2;
GRANT ALL ON PROST TO PK_OFK_3;
GRANT ALL ON PROST TO PK_OFK_4;
GRANT ALL ON PROST TO PK_OFK_P1;
GRANT ALL ON PROST TO PK_OFK_P2;
GRANT ALL ON PROST TO PK_OTV1;
GRANT ALL ON PROST TO PK_OTV2;
GRANT ALL ON PROST TO PK_OTV3;
GRANT ALL ON PROST TO PK_OTV4;
GRANT ALL ON PROST TO PK_SIIE_1;
GRANT ALL ON PROST TO PK_SIIE_2;
GRANT ALL ON PROST TO PK_SIIE_3;
GRANT ALL ON PROST TO PK_SIIE_4;
GRANT ALL ON PROST TO PK_SIIE_P1;
GRANT ALL ON PROST TO PK_SIIE_P2;
GRANT ALL ON PROST TO SADIK;
GRANT ALL ON PROST TO SEL_COM;
GRANT ALL ON PROST TO SETUN1998;
GRANT ALL ON PROST TO SMOLENKOVA_T;
GRANT ALL ON PROST TO ZHANNA_73;