/******************************************************************************/
/***               Generated by IBExpert 01.07.2022 15:28:56                ***/
/******************************************************************************/

/******************************************************************************/
/***      Following SET SQL DIALECT is just for the Database Comparer       ***/
/******************************************************************************/


/******************************************************************************/
/***                                 Tables                                 ***/
/******************************************************************************/



CREATE TABLE RESTORE_PAU (
    NOMER            INTEGER NOT NULL,
    N_CAUSE_RESTORE  SMALLINT,
    VID_RESTORE      SMALLINT,
    N_PRIKAZ_RES     SMALLINT,
    D_PRIKAZ_RES     DATE,
    DESCRIBE         VARCHAR(250)
);




/******************************************************************************/
/***                              Foreign keys                              ***/
/******************************************************************************/

ALTER TABLE RESTORE_PAU ADD CONSTRAINT FK_RESTORE_PAU_NOMER FOREIGN KEY (NOMER) REFERENCES PEOPLE_AFTER_UNIVERSITY (NOMER) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE RESTORE_PAU ADD CONSTRAINT FK_RESTORE_PAU_N_CAUSE FOREIGN KEY (N_CAUSE_RESTORE) REFERENCES CAUSE_RESTORE (N_CAUSE_RESTORE)
  USING DESCENDING INDEX FK_RESTORE_PAU_N_CAUSE;
ALTER TABLE RESTORE_PAU ADD CONSTRAINT FK_RESTORE_PAU_VID_RESTORE FOREIGN KEY (VID_RESTORE) REFERENCES VID_RESTORE (N_VID_RESTORE)
  USING DESCENDING INDEX FK_RESTORE_PAU_VID_RESTORE;


/******************************************************************************/
/***                          Fields descriptions                           ***/
/******************************************************************************/

COMMENT ON COLUMN RESTORE_PAU.VID_RESTORE IS 
'0 - востановление
1 - отлисление';



/******************************************************************************/
/***                               Privileges                               ***/
/******************************************************************************/


/* Privileges of users */
GRANT ALL ON RESTORE_PAU TO ALENA_2109;
GRANT ALL ON RESTORE_PAU TO ALINA_E;
GRANT ALL ON RESTORE_PAU TO DEVELOPER;
GRANT ALL ON RESTORE_PAU TO GONCHAROV434_2;
GRANT ALL ON RESTORE_PAU TO GUNICH_O;
GRANT ALL ON RESTORE_PAU TO HOSTEL_PK1;
GRANT ALL ON RESTORE_PAU TO HOSTEL_PK2;
GRANT ALL ON RESTORE_PAU TO KANDRUKEVICH_M;
GRANT ALL ON RESTORE_PAU TO KOSIK_N;
GRANT ALL ON RESTORE_PAU TO LIASHKOVICH_I;
GRANT ALL ON RESTORE_PAU TO MARINA;
GRANT ALL ON RESTORE_PAU TO OK_STUD_2;
GRANT ALL ON RESTORE_PAU TO PK_MSTIG_1;
GRANT ALL ON RESTORE_PAU TO PK_MSTIG_2;
GRANT ALL ON RESTORE_PAU TO PK_MSTIG_3;
GRANT ALL ON RESTORE_PAU TO PK_MSTIG_4;
GRANT ALL ON RESTORE_PAU TO PK_MSTIG_P1;
GRANT ALL ON RESTORE_PAU TO PK_MSTIG_P2;
GRANT ALL ON RESTORE_PAU TO PK_MVS_1;
GRANT ALL ON RESTORE_PAU TO PK_MVS_2;
GRANT ALL ON RESTORE_PAU TO PK_MVS_3;
GRANT ALL ON RESTORE_PAU TO PK_MVS_4;
GRANT ALL ON RESTORE_PAU TO PK_MVS_P1;
GRANT ALL ON RESTORE_PAU TO PK_MVS_P2;
GRANT ALL ON RESTORE_PAU TO PK_OFK_1;
GRANT ALL ON RESTORE_PAU TO PK_OFK_2;
GRANT ALL ON RESTORE_PAU TO PK_OFK_3;
GRANT ALL ON RESTORE_PAU TO PK_OFK_4;
GRANT ALL ON RESTORE_PAU TO PK_OFK_P1;
GRANT ALL ON RESTORE_PAU TO PK_OFK_P2;
GRANT ALL ON RESTORE_PAU TO PK_OTV1;
GRANT ALL ON RESTORE_PAU TO PK_OTV2;
GRANT ALL ON RESTORE_PAU TO PK_OTV3;
GRANT ALL ON RESTORE_PAU TO PK_OTV4;
GRANT ALL ON RESTORE_PAU TO PK_SIIE_1;
GRANT ALL ON RESTORE_PAU TO PK_SIIE_2;
GRANT ALL ON RESTORE_PAU TO PK_SIIE_3;
GRANT ALL ON RESTORE_PAU TO PK_SIIE_4;
GRANT ALL ON RESTORE_PAU TO PK_SIIE_P1;
GRANT ALL ON RESTORE_PAU TO PK_SIIE_P2;
GRANT ALL ON RESTORE_PAU TO SADIK;
GRANT ALL ON RESTORE_PAU TO SEL_COM;
GRANT ALL ON RESTORE_PAU TO SETUN1998;
GRANT ALL ON RESTORE_PAU TO SMOLENKOVA_T;
GRANT ALL ON RESTORE_PAU TO ZHANNA_73;