/******************************************************************************/
/***               Generated by IBExpert 01.07.2022 15:35:17                ***/
/******************************************************************************/

/******************************************************************************/
/***      Following SET SQL DIALECT is just for the Database Comparer       ***/
/******************************************************************************/


/******************************************************************************/
/***                                 Tables                                 ***/
/******************************************************************************/



CREATE TABLE SOATO (
    ID     INTEGER,
    SOATO  VARCHAR(10)
);




/******************************************************************************/
/***                               Privileges                               ***/
/******************************************************************************/


/* Privileges of users */
GRANT ALL ON SOATO TO ALENA_2109;
GRANT ALL ON SOATO TO ALINA_E;
GRANT ALL ON SOATO TO GONCHAROV434_2;
GRANT ALL ON SOATO TO GUNICH_O;
GRANT ALL ON SOATO TO HOSTEL_PK1;
GRANT ALL ON SOATO TO HOSTEL_PK2;
GRANT ALL ON SOATO TO KANDRUKEVICH_M;
GRANT ALL ON SOATO TO KOSIK_N;
GRANT ALL ON SOATO TO LIASHKOVICH_I;
GRANT ALL ON SOATO TO MARINA;
GRANT ALL ON SOATO TO OK_STUD_2;
GRANT ALL ON SOATO TO PK_MSTIG_1;
GRANT ALL ON SOATO TO PK_MSTIG_2;
GRANT ALL ON SOATO TO PK_MSTIG_3;
GRANT ALL ON SOATO TO PK_MSTIG_4;
GRANT ALL ON SOATO TO PK_MSTIG_P1;
GRANT ALL ON SOATO TO PK_MSTIG_P2;
GRANT ALL ON SOATO TO PK_MVS_1;
GRANT ALL ON SOATO TO PK_MVS_2;
GRANT ALL ON SOATO TO PK_MVS_3;
GRANT ALL ON SOATO TO PK_MVS_4;
GRANT ALL ON SOATO TO PK_MVS_P1;
GRANT ALL ON SOATO TO PK_MVS_P2;
GRANT ALL ON SOATO TO PK_OFK_1;
GRANT ALL ON SOATO TO PK_OFK_2;
GRANT ALL ON SOATO TO PK_OFK_3;
GRANT ALL ON SOATO TO PK_OFK_4;
GRANT ALL ON SOATO TO PK_OFK_P1;
GRANT ALL ON SOATO TO PK_OFK_P2;
GRANT ALL ON SOATO TO PK_OTV1;
GRANT ALL ON SOATO TO PK_OTV2;
GRANT ALL ON SOATO TO PK_OTV3;
GRANT ALL ON SOATO TO PK_OTV4;
GRANT ALL ON SOATO TO PK_SIIE_1;
GRANT ALL ON SOATO TO PK_SIIE_2;
GRANT ALL ON SOATO TO PK_SIIE_3;
GRANT ALL ON SOATO TO PK_SIIE_4;
GRANT ALL ON SOATO TO PK_SIIE_P1;
GRANT ALL ON SOATO TO PK_SIIE_P2;
GRANT ALL ON SOATO TO SADIK;
GRANT ALL ON SOATO TO SEL_COM;
GRANT ALL ON SOATO TO SETUN1998;
GRANT ALL ON SOATO TO SMOLENKOVA_T;
GRANT ALL ON SOATO TO ZHANNA_73;