/******************************************************************************/
/***               Generated by IBExpert 01.07.2022 15:46:49                ***/
/******************************************************************************/

/******************************************************************************/
/***      Following SET SQL DIALECT is just for the Database Comparer       ***/
/******************************************************************************/


/******************************************************************************/
/***                                 Tables                                 ***/
/******************************************************************************/



CREATE TABLE SUD_CATEGORY (
    ID    INTEGER GENERATED BY DEFAULT AS IDENTITY,
    NAME  VARCHAR(35)
);




/******************************************************************************/
/***                              Primary keys                              ***/
/******************************************************************************/

ALTER TABLE SUD_CATEGORY ADD CONSTRAINT PK_SUD_CATEGORY PRIMARY KEY (ID);


/******************************************************************************/
/***                               Privileges                               ***/
/******************************************************************************/


/* Privileges of users */
GRANT ALL ON SUD_CATEGORY TO ALENA_2109;
GRANT ALL ON SUD_CATEGORY TO ALINA_E;
GRANT ALL ON SUD_CATEGORY TO DEVELOPER;
GRANT ALL ON SUD_CATEGORY TO GONCHAROV434_2;
GRANT ALL ON SUD_CATEGORY TO GUNICH_O;
GRANT ALL ON SUD_CATEGORY TO HOSTEL_PK1;
GRANT ALL ON SUD_CATEGORY TO HOSTEL_PK2;
GRANT ALL ON SUD_CATEGORY TO KANDRUKEVICH_M;
GRANT ALL ON SUD_CATEGORY TO KOSIK_N;
GRANT ALL ON SUD_CATEGORY TO LIASHKOVICH_I;
GRANT ALL ON SUD_CATEGORY TO MARINA;
GRANT ALL ON SUD_CATEGORY TO OK_STUD_2;
GRANT ALL ON SUD_CATEGORY TO PK_MSTIG_1;
GRANT ALL ON SUD_CATEGORY TO PK_MSTIG_2;
GRANT ALL ON SUD_CATEGORY TO PK_MSTIG_3;
GRANT ALL ON SUD_CATEGORY TO PK_MSTIG_4;
GRANT ALL ON SUD_CATEGORY TO PK_MSTIG_P1;
GRANT ALL ON SUD_CATEGORY TO PK_MSTIG_P2;
GRANT ALL ON SUD_CATEGORY TO PK_MVS_1;
GRANT ALL ON SUD_CATEGORY TO PK_MVS_2;
GRANT ALL ON SUD_CATEGORY TO PK_MVS_3;
GRANT ALL ON SUD_CATEGORY TO PK_MVS_4;
GRANT ALL ON SUD_CATEGORY TO PK_MVS_P1;
GRANT ALL ON SUD_CATEGORY TO PK_MVS_P2;
GRANT ALL ON SUD_CATEGORY TO PK_OFK_1;
GRANT ALL ON SUD_CATEGORY TO PK_OFK_2;
GRANT ALL ON SUD_CATEGORY TO PK_OFK_3;
GRANT ALL ON SUD_CATEGORY TO PK_OFK_4;
GRANT ALL ON SUD_CATEGORY TO PK_OFK_P1;
GRANT ALL ON SUD_CATEGORY TO PK_OFK_P2;
GRANT ALL ON SUD_CATEGORY TO PK_OTV1;
GRANT ALL ON SUD_CATEGORY TO PK_OTV2;
GRANT ALL ON SUD_CATEGORY TO PK_OTV3;
GRANT ALL ON SUD_CATEGORY TO PK_OTV4;
GRANT ALL ON SUD_CATEGORY TO PK_SIIE_1;
GRANT ALL ON SUD_CATEGORY TO PK_SIIE_2;
GRANT ALL ON SUD_CATEGORY TO PK_SIIE_3;
GRANT ALL ON SUD_CATEGORY TO PK_SIIE_4;
GRANT ALL ON SUD_CATEGORY TO PK_SIIE_P1;
GRANT ALL ON SUD_CATEGORY TO PK_SIIE_P2;
GRANT ALL ON SUD_CATEGORY TO SADIK;
GRANT ALL ON SUD_CATEGORY TO SEL_COM;
GRANT ALL ON SUD_CATEGORY TO SETUN1998;
GRANT ALL ON SUD_CATEGORY TO SMOLENKOVA_T;
GRANT ALL ON SUD_CATEGORY TO ZHANNA_73;