/******************************************************************************/
/***               Generated by IBExpert 01.07.2022 15:49:09                ***/
/******************************************************************************/

/******************************************************************************/
/***      Following SET SQL DIALECT is just for the Database Comparer       ***/
/******************************************************************************/


/******************************************************************************/
/***                                 Tables                                 ***/
/******************************************************************************/



CREATE TABLE TYPE_HOLIDAY (
    N_HOLIDAY  SMALLINT GENERATED BY DEFAULT AS IDENTITY,
    HOLIDAY    VARCHAR(70)
);




/******************************************************************************/
/***                              Primary keys                              ***/
/******************************************************************************/

ALTER TABLE TYPE_HOLIDAY ADD CONSTRAINT PK_TYPE_HOLIDAY PRIMARY KEY (N_HOLIDAY);


/******************************************************************************/
/***                               Privileges                               ***/
/******************************************************************************/


/* Privileges of users */
GRANT ALL ON TYPE_HOLIDAY TO ALENA_2109;
GRANT ALL ON TYPE_HOLIDAY TO ALINA_E;
GRANT ALL ON TYPE_HOLIDAY TO DEVELOPER;
GRANT ALL ON TYPE_HOLIDAY TO GONCHAROV434_2;
GRANT ALL ON TYPE_HOLIDAY TO GUNICH_O;
GRANT ALL ON TYPE_HOLIDAY TO HOSTEL_PK1;
GRANT ALL ON TYPE_HOLIDAY TO HOSTEL_PK2;
GRANT ALL ON TYPE_HOLIDAY TO KANDRUKEVICH_M;
GRANT ALL ON TYPE_HOLIDAY TO KOSIK_N;
GRANT ALL ON TYPE_HOLIDAY TO LIASHKOVICH_I;
GRANT ALL ON TYPE_HOLIDAY TO MARINA;
GRANT ALL ON TYPE_HOLIDAY TO OK_STUD_2;
GRANT ALL ON TYPE_HOLIDAY TO PK_MSTIG_1;
GRANT ALL ON TYPE_HOLIDAY TO PK_MSTIG_2;
GRANT ALL ON TYPE_HOLIDAY TO PK_MSTIG_3;
GRANT ALL ON TYPE_HOLIDAY TO PK_MSTIG_4;
GRANT ALL ON TYPE_HOLIDAY TO PK_MSTIG_P1;
GRANT ALL ON TYPE_HOLIDAY TO PK_MSTIG_P2;
GRANT ALL ON TYPE_HOLIDAY TO PK_MVS_1;
GRANT ALL ON TYPE_HOLIDAY TO PK_MVS_2;
GRANT ALL ON TYPE_HOLIDAY TO PK_MVS_3;
GRANT ALL ON TYPE_HOLIDAY TO PK_MVS_4;
GRANT ALL ON TYPE_HOLIDAY TO PK_MVS_P1;
GRANT ALL ON TYPE_HOLIDAY TO PK_MVS_P2;
GRANT ALL ON TYPE_HOLIDAY TO PK_OFK_1;
GRANT ALL ON TYPE_HOLIDAY TO PK_OFK_2;
GRANT ALL ON TYPE_HOLIDAY TO PK_OFK_3;
GRANT ALL ON TYPE_HOLIDAY TO PK_OFK_4;
GRANT ALL ON TYPE_HOLIDAY TO PK_OFK_P1;
GRANT ALL ON TYPE_HOLIDAY TO PK_OFK_P2;
GRANT ALL ON TYPE_HOLIDAY TO PK_OTV1;
GRANT ALL ON TYPE_HOLIDAY TO PK_OTV2;
GRANT ALL ON TYPE_HOLIDAY TO PK_OTV3;
GRANT ALL ON TYPE_HOLIDAY TO PK_OTV4;
GRANT ALL ON TYPE_HOLIDAY TO PK_SIIE_1;
GRANT ALL ON TYPE_HOLIDAY TO PK_SIIE_2;
GRANT ALL ON TYPE_HOLIDAY TO PK_SIIE_3;
GRANT ALL ON TYPE_HOLIDAY TO PK_SIIE_4;
GRANT ALL ON TYPE_HOLIDAY TO PK_SIIE_P1;
GRANT ALL ON TYPE_HOLIDAY TO PK_SIIE_P2;
GRANT ALL ON TYPE_HOLIDAY TO SADIK;
GRANT ALL ON TYPE_HOLIDAY TO SEL_COM;
GRANT ALL ON TYPE_HOLIDAY TO SETUN1998;
GRANT ALL ON TYPE_HOLIDAY TO SMOLENKOVA_T;
GRANT ALL ON TYPE_HOLIDAY TO ZHANNA_73;