/******************************************************************************/
/***               Generated by IBExpert 01.07.2022 15:55:15                ***/
/******************************************************************************/

/******************************************************************************/
/***      Following SET SQL DIALECT is just for the Database Comparer       ***/
/******************************************************************************/


/******************************************************************************/
/***                                 Tables                                 ***/
/******************************************************************************/



CREATE TABLE VEDOMOST_PAU (
    N_VED        INTEGER NOT NULL,
    N_VEDOMOST   SMALLINT,
    D_VED        DATE,
    SEMESTR_VED  SMALLINT,
    FIO_EXAM     VARCHAR(40),
    STATUS       INTEGER,
    N_PLAN       INTEGER,
    END_D_EXAM   DATE,
    INC_GROUP    SMALLINT,
    N_SPECIALIZ  SMALLINT
);




/******************************************************************************/
/***                              Primary keys                              ***/
/******************************************************************************/

ALTER TABLE VEDOMOST_PAU ADD CONSTRAINT PK_VEDOMOST_PAU PRIMARY KEY (N_VED);


/******************************************************************************/
/***                          Fields descriptions                           ***/
/******************************************************************************/

COMMENT ON COLUMN VEDOMOST_PAU.STATUS IS 
'0-основная
1-экз.лист
2-дополнительная
3-досрочная
4-ликвидация разницы';



/******************************************************************************/
/***                               Privileges                               ***/
/******************************************************************************/


/* Privileges of users */
GRANT ALL ON VEDOMOST_PAU TO ALENA_2109;
GRANT ALL ON VEDOMOST_PAU TO ALINA_E;
GRANT ALL ON VEDOMOST_PAU TO DEVELOPER;
GRANT ALL ON VEDOMOST_PAU TO GONCHAROV434_2;
GRANT ALL ON VEDOMOST_PAU TO GUNICH_O;
GRANT ALL ON VEDOMOST_PAU TO HOSTEL_PK1;
GRANT ALL ON VEDOMOST_PAU TO HOSTEL_PK2;
GRANT ALL ON VEDOMOST_PAU TO KANDRUKEVICH_M;
GRANT ALL ON VEDOMOST_PAU TO KOSIK_N;
GRANT ALL ON VEDOMOST_PAU TO LIASHKOVICH_I;
GRANT ALL ON VEDOMOST_PAU TO OK_STUD_2;
GRANT ALL ON VEDOMOST_PAU TO PK_MSTIG_1;
GRANT ALL ON VEDOMOST_PAU TO PK_MSTIG_2;
GRANT ALL ON VEDOMOST_PAU TO PK_MSTIG_3;
GRANT ALL ON VEDOMOST_PAU TO PK_MSTIG_4;
GRANT ALL ON VEDOMOST_PAU TO PK_MSTIG_P1;
GRANT ALL ON VEDOMOST_PAU TO PK_MSTIG_P2;
GRANT ALL ON VEDOMOST_PAU TO PK_MVS_1;
GRANT ALL ON VEDOMOST_PAU TO PK_MVS_2;
GRANT ALL ON VEDOMOST_PAU TO PK_MVS_3;
GRANT ALL ON VEDOMOST_PAU TO PK_MVS_4;
GRANT ALL ON VEDOMOST_PAU TO PK_MVS_P1;
GRANT ALL ON VEDOMOST_PAU TO PK_MVS_P2;
GRANT ALL ON VEDOMOST_PAU TO PK_OFK_1;
GRANT ALL ON VEDOMOST_PAU TO PK_OFK_2;
GRANT ALL ON VEDOMOST_PAU TO PK_OFK_3;
GRANT ALL ON VEDOMOST_PAU TO PK_OFK_4;
GRANT ALL ON VEDOMOST_PAU TO PK_OFK_P1;
GRANT ALL ON VEDOMOST_PAU TO PK_OFK_P2;
GRANT ALL ON VEDOMOST_PAU TO PK_OTV1;
GRANT ALL ON VEDOMOST_PAU TO PK_OTV2;
GRANT ALL ON VEDOMOST_PAU TO PK_OTV3;
GRANT ALL ON VEDOMOST_PAU TO PK_OTV4;
GRANT ALL ON VEDOMOST_PAU TO PK_SIIE_1;
GRANT ALL ON VEDOMOST_PAU TO PK_SIIE_2;
GRANT ALL ON VEDOMOST_PAU TO PK_SIIE_3;
GRANT ALL ON VEDOMOST_PAU TO PK_SIIE_4;
GRANT ALL ON VEDOMOST_PAU TO PK_SIIE_P1;
GRANT ALL ON VEDOMOST_PAU TO PK_SIIE_P2;
GRANT ALL ON VEDOMOST_PAU TO SADIK;
GRANT ALL ON VEDOMOST_PAU TO SEL_COM;
GRANT ALL ON VEDOMOST_PAU TO SETUN1998;
GRANT ALL ON VEDOMOST_PAU TO SMOLENKOVA_T;
GRANT ALL ON VEDOMOST_PAU TO ZHANNA_73;