/******************************************************************************/
/***               Generated by IBExpert 01.07.2022 15:56:19                ***/
/******************************************************************************/

/******************************************************************************/
/***      Following SET SQL DIALECT is just for the Database Comparer       ***/
/******************************************************************************/


/******************************************************************************/
/***                                 Tables                                 ***/
/******************************************************************************/



CREATE TABLE VID_EDU (
    ID_VID_EDU  INTEGER NOT NULL,
    VID_EDU     VARCHAR(50) COLLATE PXW_CYRL
);




/******************************************************************************/
/***                              Primary keys                              ***/
/******************************************************************************/

ALTER TABLE VID_EDU ADD CONSTRAINT PK_VID_EDU PRIMARY KEY (ID_VID_EDU);


/******************************************************************************/
/***                               Privileges                               ***/
/******************************************************************************/


/* Privileges of users */
GRANT ALL ON VID_EDU TO ALENA_2109;
GRANT ALL ON VID_EDU TO ALINA_E;
GRANT ALL ON VID_EDU TO DEVELOPER;
GRANT ALL ON VID_EDU TO GONCHAROV434_2;
GRANT ALL ON VID_EDU TO GUNICH_O;
GRANT ALL ON VID_EDU TO HOSTEL_PK1;
GRANT ALL ON VID_EDU TO HOSTEL_PK2;
GRANT ALL ON VID_EDU TO KANDRUKEVICH_M;
GRANT ALL ON VID_EDU TO KOSIK_N;
GRANT ALL ON VID_EDU TO LIASHKOVICH_I;
GRANT ALL ON VID_EDU TO MARINA;
GRANT ALL ON VID_EDU TO OK_STUD_2;
GRANT ALL ON VID_EDU TO PK_MSTIG_1;
GRANT ALL ON VID_EDU TO PK_MSTIG_2;
GRANT ALL ON VID_EDU TO PK_MSTIG_3;
GRANT ALL ON VID_EDU TO PK_MSTIG_4;
GRANT ALL ON VID_EDU TO PK_MSTIG_P1;
GRANT ALL ON VID_EDU TO PK_MSTIG_P2;
GRANT ALL ON VID_EDU TO PK_MVS_1;
GRANT ALL ON VID_EDU TO PK_MVS_2;
GRANT ALL ON VID_EDU TO PK_MVS_3;
GRANT ALL ON VID_EDU TO PK_MVS_4;
GRANT ALL ON VID_EDU TO PK_MVS_P1;
GRANT ALL ON VID_EDU TO PK_MVS_P2;
GRANT ALL ON VID_EDU TO PK_OFK_1;
GRANT ALL ON VID_EDU TO PK_OFK_2;
GRANT ALL ON VID_EDU TO PK_OFK_3;
GRANT ALL ON VID_EDU TO PK_OFK_4;
GRANT ALL ON VID_EDU TO PK_OFK_P1;
GRANT ALL ON VID_EDU TO PK_OFK_P2;
GRANT ALL ON VID_EDU TO PK_OTV1;
GRANT ALL ON VID_EDU TO PK_OTV2;
GRANT ALL ON VID_EDU TO PK_OTV3;
GRANT ALL ON VID_EDU TO PK_OTV4;
GRANT ALL ON VID_EDU TO PK_SIIE_1;
GRANT ALL ON VID_EDU TO PK_SIIE_2;
GRANT ALL ON VID_EDU TO PK_SIIE_3;
GRANT ALL ON VID_EDU TO PK_SIIE_4;
GRANT ALL ON VID_EDU TO PK_SIIE_P1;
GRANT ALL ON VID_EDU TO PK_SIIE_P2;
GRANT ALL ON VID_EDU TO SADIK;
GRANT ALL ON VID_EDU TO SEL_COM;
GRANT ALL ON VID_EDU TO SETUN1998;
GRANT ALL ON VID_EDU TO SMOLENKOVA_T;
GRANT ALL ON VID_EDU TO ZHANNA_73;