/******************************************************************************/
/***               Generated by IBExpert 01.07.2022 15:56:53                ***/
/******************************************************************************/

/******************************************************************************/
/***      Following SET SQL DIALECT is just for the Database Comparer       ***/
/******************************************************************************/


/******************************************************************************/
/***                                 Tables                                 ***/
/******************************************************************************/



CREATE TABLE VID_ENCOURAGE (
    N_TYPE_EN  SMALLINT NOT NULL,
    TYPE_EN    VARCHAR(20)
);




/******************************************************************************/
/***                              Primary keys                              ***/
/******************************************************************************/

ALTER TABLE VID_ENCOURAGE ADD CONSTRAINT PK_VID_ENCOURAGE PRIMARY KEY (N_TYPE_EN);


/******************************************************************************/
/***                               Privileges                               ***/
/******************************************************************************/


/* Privileges of users */
GRANT ALL ON VID_ENCOURAGE TO ALENA_2109;
GRANT ALL ON VID_ENCOURAGE TO ALINA_E;
GRANT ALL ON VID_ENCOURAGE TO DEVELOPER;
GRANT ALL ON VID_ENCOURAGE TO GONCHAROV434_2;
GRANT ALL ON VID_ENCOURAGE TO GUNICH_O;
GRANT ALL ON VID_ENCOURAGE TO HOSTEL_PK1;
GRANT ALL ON VID_ENCOURAGE TO HOSTEL_PK2;
GRANT ALL ON VID_ENCOURAGE TO KANDRUKEVICH_M;
GRANT ALL ON VID_ENCOURAGE TO KOSIK_N;
GRANT ALL ON VID_ENCOURAGE TO LIASHKOVICH_I;
GRANT ALL ON VID_ENCOURAGE TO OK_STUD_2;
GRANT ALL ON VID_ENCOURAGE TO PK_MSTIG_1;
GRANT ALL ON VID_ENCOURAGE TO PK_MSTIG_2;
GRANT ALL ON VID_ENCOURAGE TO PK_MSTIG_3;
GRANT ALL ON VID_ENCOURAGE TO PK_MSTIG_4;
GRANT ALL ON VID_ENCOURAGE TO PK_MSTIG_P1;
GRANT ALL ON VID_ENCOURAGE TO PK_MSTIG_P2;
GRANT ALL ON VID_ENCOURAGE TO PK_MVS_1;
GRANT ALL ON VID_ENCOURAGE TO PK_MVS_2;
GRANT ALL ON VID_ENCOURAGE TO PK_MVS_3;
GRANT ALL ON VID_ENCOURAGE TO PK_MVS_4;
GRANT ALL ON VID_ENCOURAGE TO PK_MVS_P1;
GRANT ALL ON VID_ENCOURAGE TO PK_MVS_P2;
GRANT ALL ON VID_ENCOURAGE TO PK_OFK_1;
GRANT ALL ON VID_ENCOURAGE TO PK_OFK_2;
GRANT ALL ON VID_ENCOURAGE TO PK_OFK_3;
GRANT ALL ON VID_ENCOURAGE TO PK_OFK_4;
GRANT ALL ON VID_ENCOURAGE TO PK_OFK_P1;
GRANT ALL ON VID_ENCOURAGE TO PK_OFK_P2;
GRANT ALL ON VID_ENCOURAGE TO PK_OTV1;
GRANT ALL ON VID_ENCOURAGE TO PK_OTV2;
GRANT ALL ON VID_ENCOURAGE TO PK_OTV3;
GRANT ALL ON VID_ENCOURAGE TO PK_OTV4;
GRANT ALL ON VID_ENCOURAGE TO PK_SIIE_1;
GRANT ALL ON VID_ENCOURAGE TO PK_SIIE_2;
GRANT ALL ON VID_ENCOURAGE TO PK_SIIE_3;
GRANT ALL ON VID_ENCOURAGE TO PK_SIIE_4;
GRANT ALL ON VID_ENCOURAGE TO PK_SIIE_P1;
GRANT ALL ON VID_ENCOURAGE TO PK_SIIE_P2;
GRANT ALL ON VID_ENCOURAGE TO SADIK;
GRANT ALL ON VID_ENCOURAGE TO SEL_COM;
GRANT ALL ON VID_ENCOURAGE TO SETUN1998;
GRANT ALL ON VID_ENCOURAGE TO SMOLENKOVA_T;
GRANT ALL ON VID_ENCOURAGE TO ZHANNA_73;