/******************************************************************************/
/***               Generated by IBExpert 01.07.2022 15:57:28                ***/
/******************************************************************************/

/******************************************************************************/
/***      Following SET SQL DIALECT is just for the Database Comparer       ***/
/******************************************************************************/


/******************************************************************************/
/***                                 Tables                                 ***/
/******************************************************************************/



CREATE TABLE VID_RESTORE (
    N_VID_RESTORE  SMALLINT NOT NULL,
    VID_RESTORE    VARCHAR(20)
);




/******************************************************************************/
/***                              Primary keys                              ***/
/******************************************************************************/

ALTER TABLE VID_RESTORE ADD CONSTRAINT PK_VID_RESTORE PRIMARY KEY (N_VID_RESTORE);


/******************************************************************************/
/***                               Privileges                               ***/
/******************************************************************************/


/* Privileges of users */
GRANT ALL ON VID_RESTORE TO ALENA_2109;
GRANT ALL ON VID_RESTORE TO ALINA_E;
GRANT ALL ON VID_RESTORE TO DEVELOPER;
GRANT ALL ON VID_RESTORE TO GONCHAROV434_2;
GRANT ALL ON VID_RESTORE TO GUNICH_O;
GRANT ALL ON VID_RESTORE TO HOSTEL_PK1;
GRANT ALL ON VID_RESTORE TO HOSTEL_PK2;
GRANT ALL ON VID_RESTORE TO KANDRUKEVICH_M;
GRANT ALL ON VID_RESTORE TO KOSIK_N;
GRANT ALL ON VID_RESTORE TO LIASHKOVICH_I;
GRANT ALL ON VID_RESTORE TO MARINA;
GRANT ALL ON VID_RESTORE TO OK_STUD_2;
GRANT ALL ON VID_RESTORE TO PK_MSTIG_1;
GRANT ALL ON VID_RESTORE TO PK_MSTIG_2;
GRANT ALL ON VID_RESTORE TO PK_MSTIG_3;
GRANT ALL ON VID_RESTORE TO PK_MSTIG_4;
GRANT ALL ON VID_RESTORE TO PK_MSTIG_P1;
GRANT ALL ON VID_RESTORE TO PK_MSTIG_P2;
GRANT ALL ON VID_RESTORE TO PK_MVS_1;
GRANT ALL ON VID_RESTORE TO PK_MVS_2;
GRANT ALL ON VID_RESTORE TO PK_MVS_3;
GRANT ALL ON VID_RESTORE TO PK_MVS_4;
GRANT ALL ON VID_RESTORE TO PK_MVS_P1;
GRANT ALL ON VID_RESTORE TO PK_MVS_P2;
GRANT ALL ON VID_RESTORE TO PK_OFK_1;
GRANT ALL ON VID_RESTORE TO PK_OFK_2;
GRANT ALL ON VID_RESTORE TO PK_OFK_3;
GRANT ALL ON VID_RESTORE TO PK_OFK_4;
GRANT ALL ON VID_RESTORE TO PK_OFK_P1;
GRANT ALL ON VID_RESTORE TO PK_OFK_P2;
GRANT ALL ON VID_RESTORE TO PK_OTV1;
GRANT ALL ON VID_RESTORE TO PK_OTV2;
GRANT ALL ON VID_RESTORE TO PK_OTV3;
GRANT ALL ON VID_RESTORE TO PK_OTV4;
GRANT ALL ON VID_RESTORE TO PK_SIIE_1;
GRANT ALL ON VID_RESTORE TO PK_SIIE_2;
GRANT ALL ON VID_RESTORE TO PK_SIIE_3;
GRANT ALL ON VID_RESTORE TO PK_SIIE_4;
GRANT ALL ON VID_RESTORE TO PK_SIIE_P1;
GRANT ALL ON VID_RESTORE TO PK_SIIE_P2;
GRANT ALL ON VID_RESTORE TO SADIK;
GRANT ALL ON VID_RESTORE TO SEL_COM;
GRANT ALL ON VID_RESTORE TO SETUN1998;
GRANT ALL ON VID_RESTORE TO SMOLENKOVA_T;
GRANT ALL ON VID_RESTORE TO ZHANNA_73;