/******************************************************************************/
/***               Generated by IBExpert 01.07.2022 15:58:25                ***/
/******************************************************************************/

/******************************************************************************/
/***      Following SET SQL DIALECT is just for the Database Comparer       ***/
/******************************************************************************/


/******************************************************************************/
/***                                 Tables                                 ***/
/******************************************************************************/


CREATE GENERATOR VILL_COUNCIL;

CREATE TABLE VILL_COUNCIL (
    ID            INTEGER NOT NULL,
    N_DISTRICT    INTEGER,
    NAME_COUNCIL  VARCHAR(60),
    COD_SOATO     FLOAT,
    COD_CATEGORY  INTEGER
);




/******************************************************************************/
/***                              Primary keys                              ***/
/******************************************************************************/

ALTER TABLE VILL_COUNCIL ADD CONSTRAINT PK_VILL_COUNCIL PRIMARY KEY (ID);


/******************************************************************************/
/***                                Triggers                                ***/
/******************************************************************************/



SET TERM ^ ;



/******************************************************************************/
/***                          Triggers for tables                           ***/
/******************************************************************************/



/* Trigger: VILL_COUNCIL_BI0 */
CREATE OR ALTER TRIGGER VILL_COUNCIL_BI0 FOR VILL_COUNCIL
ACTIVE BEFORE INSERT POSITION 0
AS
begin
  if (new.id is null) then
    new.id = gen_id(vill_council,1);
end
^

SET TERM ; ^



/******************************************************************************/
/***                               Privileges                               ***/
/******************************************************************************/


/* Privileges of users */
GRANT ALL ON VILL_COUNCIL TO ALENA_2109;
GRANT ALL ON VILL_COUNCIL TO ALINA_E;
GRANT ALL ON VILL_COUNCIL TO DVORETSKAYA_K;
GRANT ALL ON VILL_COUNCIL TO GONCHAROV434_2;
GRANT ALL ON VILL_COUNCIL TO GUNICH_O;
GRANT ALL ON VILL_COUNCIL TO HOSTEL_PK1;
GRANT ALL ON VILL_COUNCIL TO HOSTEL_PK2;
GRANT ALL ON VILL_COUNCIL TO KANDRUKEVICH_M;
GRANT ALL ON VILL_COUNCIL TO KOSIK_N;
GRANT ALL ON VILL_COUNCIL TO LIASHKOVICH_I;
GRANT ALL ON VILL_COUNCIL TO LTRFYFN2019;
GRANT ALL ON VILL_COUNCIL TO MARINA;
GRANT ALL ON VILL_COUNCIL TO OK_STUD_2;
GRANT ALL ON VILL_COUNCIL TO PK_MSTIG_1;
GRANT ALL ON VILL_COUNCIL TO PK_MSTIG_2;
GRANT ALL ON VILL_COUNCIL TO PK_MSTIG_3;
GRANT ALL ON VILL_COUNCIL TO PK_MSTIG_4;
GRANT ALL ON VILL_COUNCIL TO PK_MSTIG_P1;
GRANT ALL ON VILL_COUNCIL TO PK_MSTIG_P2;
GRANT ALL ON VILL_COUNCIL TO PK_MVS_1;
GRANT ALL ON VILL_COUNCIL TO PK_MVS_2;
GRANT ALL ON VILL_COUNCIL TO PK_MVS_3;
GRANT ALL ON VILL_COUNCIL TO PK_MVS_4;
GRANT ALL ON VILL_COUNCIL TO PK_MVS_P1;
GRANT ALL ON VILL_COUNCIL TO PK_MVS_P2;
GRANT ALL ON VILL_COUNCIL TO PK_OFK_1;
GRANT ALL ON VILL_COUNCIL TO PK_OFK_2;
GRANT ALL ON VILL_COUNCIL TO PK_OFK_3;
GRANT ALL ON VILL_COUNCIL TO PK_OFK_4;
GRANT ALL ON VILL_COUNCIL TO PK_OFK_P1;
GRANT ALL ON VILL_COUNCIL TO PK_OFK_P2;
GRANT ALL ON VILL_COUNCIL TO PK_OTV1;
GRANT ALL ON VILL_COUNCIL TO PK_OTV2;
GRANT ALL ON VILL_COUNCIL TO PK_OTV3;
GRANT ALL ON VILL_COUNCIL TO PK_OTV4;
GRANT ALL ON VILL_COUNCIL TO PK_SIIE_1;
GRANT ALL ON VILL_COUNCIL TO PK_SIIE_2;
GRANT ALL ON VILL_COUNCIL TO PK_SIIE_3;
GRANT ALL ON VILL_COUNCIL TO PK_SIIE_4;
GRANT ALL ON VILL_COUNCIL TO PK_SIIE_P1;
GRANT ALL ON VILL_COUNCIL TO PK_SIIE_P2;
GRANT ALL ON VILL_COUNCIL TO SADIK;
GRANT ALL ON VILL_COUNCIL TO SEL_COM;
GRANT ALL ON VILL_COUNCIL TO SETUN1998;
GRANT ALL ON VILL_COUNCIL TO SMOLENKOVA_T;
GRANT ALL ON VILL_COUNCIL TO ZHANNA_73;