#pragma once
#ifndef DM_UNIT_H
#define DM_UNIT_H


#include <Classes.hpp>
#include <Controls.hpp>
#include <DB.hpp>
#include <Db.hpp>
#include <Dialogs.hpp>
#include <FireDAC.Comp.Client.hpp>
#include <FireDAC.Comp.DataSet.hpp>
#include <FireDAC.DApt.hpp>
#include <FireDAC.DApt.Intf.hpp>
#include <FireDAC.DatS.hpp>
#include <FireDAC.Phys.FB.hpp>
#include <FireDAC.Phys.FBDef.hpp>
#include <FireDAC.Phys.hpp>
#include <FireDAC.Phys.IBBase.hpp>
#include <FireDAC.Phys.Intf.hpp>
#include <FireDAC.Stan.Async.hpp>
#include <FireDAC.Stan.Def.hpp>
#include <FireDAC.Stan.Error.hpp>
#include <FireDAC.Stan.Intf.hpp>
#include <FireDAC.Stan.Option.hpp>
#include <FireDAC.Stan.Param.hpp>
#include <FireDAC.Stan.Pool.hpp>
#include <FireDAC.UI.Intf.hpp>
#include <FireDAC.VCLUI.Wait.hpp>
#include <Forms.hpp>
#include <Graphics.hpp>
#include <Messages.hpp>
#include <System.hpp>
#include <SysUtils.hpp>
#include <Windows.hpp>

#include "properties.hpp"

//extern const AnsiString ADMITTION_COMMITTEE_SECRETARY_ASC;                      //   = "А.И. Лихач";
//extern const AnsiString ADMITTION_COMMITTEE_SECRETARY_DESC;                     //   = "Лихач А.И.";

extern       AnsiString cur_dir;                                                // текущая директория
extern       AnsiString dateOkonch;                                             // дата окончания видимости компонентов для статистики
extern       AnsiString DateServer;                                             // Дата с сервера
extern       AnsiString fac1;                                                   // название факультета (сокращенное)
AnsiString FIO = LegallyAuthorizedPerson::SECRETARY_DESC;
AnsiString IOF = LegallyAuthorizedPerson::SECRETARY;
extern       AnsiString out_dir;                                                // директория для сохранения выходных файлов
extern       AnsiString TextTest;

extern       bool       st_asu;                                                 // переменная статуса asu
extern       bool       st_developer;                                           // переменная статуса программиста

extern       int        IdEdu;
extern       int        n_menu;
extern       int        nom_fac;                                                // номер факультета
extern       int        oplata_konkurs;                                         // переменная для учета города и села для платников // (0 - общий конкурс; 1 - раздельный конкурс (город/село))
extern       int        perepodacha;
extern       int        pole_block;                                             // переменная для определения ограничения прав доступа пользователей //0-полный доступ; 1-ограниченный
extern       int        pr_KategIf;                                             // признак категории абитуриента: 0 - РБ, 1 - ИГ, 2 - СНГ
extern       int        press;                                                  // переменная для определения какая кнопка нажата переменная для ИТ (разрешение на переподачу)

extern       TDateTime  cur_d;



void __fastcall VidKonkurs (                                                    // установкА конкурса (вызывается если у платников общий конкурс (т.е. oplata_konkurs==0))
        TRadioGroup * RadioGroup2,
        TRadioGroup * RadioGroup3,
        TComboBox   * ComboBox1
    );



class TDM
    : public TDataModule
{
__published:
    TBlobField          * FIOSearchQrDIGIT_SIGN;
    TBlobField          * FIOSearchQrPHOTO;
    TBlobField          * QFotoQeueDIGIT_SIGN;
    TBlobField          * QFotoQeuePHOTO;
    TBlobField          * QFotoSignDIGIT_SIGN;
    TBlobField          * QFotoSignPHOTO;
    TBlobField          * QReport_RaspPHOTO;
    TBlobField          * QSelect_abDIGIT_SIGN;
    TBlobField          * QSelect_abPHOTO;
    TBlobField          * QToDekanatDIGIT_SIGN;
    TBlobField          * QToDekanatPHOTO;
    TBlobField          * Selection_CommitteeFDTableSIGNATURE;

    TBooleanField       * DocumInListQDATE_DOC;
    TBooleanField       * DocumInListQINDEX_DOC;
    TBooleanField       * ListDocFDQDATE_DOCUM;
    TBooleanField       * ListDocFDQINDEX_DOC;

    TDataSource         * BlockDS;
    TDataSource         * CkRegionDS;
    TDataSource         * CntrExrcDS;
    TDataSource         * CountryDS;
    TDataSource         * DSAb_P;
    TDataSource         * DSAb_Pr_Enter;
    TDataSource         * DSAbitur_Priv_Enter;
    TDataSource         * DSAbitura;
    TDataSource         * DSAdd_N_Group;
    TDataSource         * DSAdress;
    TDataSource         * DSBall;
    TDataSource         * DSCategory;
    TDataSource         * DSCenter;
    TDataSource         * DSCk;
    TDataSource         * DSCkQ;
    TDataSource         * DSCkToDekanat;
    TDataSource         * DSDistrict;
    TDataSource         * DSDocum;
    TDataSource         * DSEducation;
    TDataSource         * DSEduDoc;
    TDataSource         * DSExam;
    TDataSource         * DSExamSpec;
    TDataSource         * DSFaculty;
    TDataSource         * DSFoundation;
    TDataSource         * DSGroup_Count_Spec;
    TDataSource         * DSGroup_Count;
    TDataSource         * DSInc_Gr_Old;
    TDataSource         * DSKol_Place;
    TDataSource         * DSLangvich;
    TDataSource         * DSLangvichToDekanat;
    TDataSource         * DSLittle_Spisoc_GR;
    TDataSource         * DSLocality;
    TDataSource         * DSMax_Nom_Dela;
    TDataSource         * DSMax_Nomer_Ab;
    TDataSource         * DSPasport;
    TDataSource         * DSPass_User;
    TDataSource         * DSPersonalDocum;
    TDataSource         * DSPlan_Priem_All;
    TDataSource         * DSPlan_Priem_CK;
    TDataSource         * DSPredmet;
    TDataSource         * DSPrivToDekanat;
    TDataSource         * DSQSertificat_Res;
    TDataSource         * DSQShkala;
    TDataSource         * DSRegion_Center;
    TDataSource         * DSRegion;
    TDataSource         * DSReport_Rasp;
    TDataSource         * DSResult_Exam;
    TDataSource         * DSSelect_ab;
    TDataSource         * DSSertificat;
    TDataSource         * DSShow_Result_Exam;
    TDataSource         * DSSpecializ;
    TDataSource         * DSSpecializPlan_Priem;
    TDataSource         * DSSpisoc_Group_Pol;
    TDataSource         * DSSpisoc_Group;
    TDataSource         * DSStatistic_Every_Day;
    TDataSource         * DSStreet;
    TDataSource         * DSSum_Ball_Nomer;
    TDataSource         * DSSum_Ball;
    TDataSource         * DSToDekanat;
    TDataSource         * DSType_locality;
    TDataSource         * DSType_street;
    TDataSource         * DSUndo_Abit;
    TDataSource         * DSVid_Sport;
    TDataSource         * ExercDS;
    TDataSource         * FIOSearchDS;
    TDataSource         * Increment_GroupSource;
    TDataSource         * ListDocFDDS;
    TDataSource         * Selection_CommitteeDS;
    TDataSource         * SpecializDS;
    TDataSource         * SPFDDataSource;
    TDataSource         * SportQSource;

    TFDConnection       * FDConnection1;
    TFDConnection       * FDConnection2;

    TFDPhysFBDriverLink * FDPhysFBDriverLink1;

    TFDQuery            * AbiturCompQr;
    TFDQuery            * AbiturInvTmpQr;
    TFDQuery            * AbiturLogInsQr;
    TFDQuery            * AbiturSirTmpQr;
    TFDQuery            * AddrLogUpQr;
    TFDQuery            * AdresOutQr;
    TFDQuery            * AdrLogLastQr;
    TFDQuery            * BlockBtnQr;
    TFDQuery            * BlockQ;
    TFDQuery            * CategUpQr;
    TFDQuery            * CertificLogInsQr;
    TFDQuery            * CkRegionQr;
    TFDQuery            * CntrlExrcQr;
    TFDQuery            * ContrySelQr;
    TFDQuery            * CountryQr;
    TFDQuery            * DocumFDQ;
    TFDQuery            * DocumInListQ;
    TFDQuery            * FIOSearchQr;
    TFDQuery            * GrazdanToDekanatQr;
    TFDQuery            * IdAbQueueQr;
    TFDQuery            * InfCntQr;
    TFDQuery            * InfQr;
    TFDQuery            * KodSpecializQr;
    TFDQuery            * LangSelQr;
    TFDQuery            * ListDocFDQ;
    TFDQuery            * LogIDSelQr;
    TFDQuery            * LogLastQr;
    TFDQuery            * MaxExrcQr;
    TFDQuery            * OtherPrivQr;
    TFDQuery            * OutCntQr;
    TFDQuery            * OutDetQr;
    TFDQuery            * OutQr;
    TFDQuery            * OutTestQr;
    TFDQuery            * PasportFDQ;
    TFDQuery            * PrintDocQr;
    TFDQuery            * PrivCnttQr;
    TFDQuery            * PrivilegLogSelQr;
    TFDQuery            * PrivQr;
    TFDQuery            * QAb_P;
    TFDQuery            * QAb_Pr_Enter;
    TFDQuery            * QAbFIOPol;
    TFDQuery            * QAbitur_Priv_Enter;
    TFDQuery            * QAbitura;
    TFDQuery            * QAdd_N_Group;
    TFDQuery            * QAdress;
    TFDQuery            * QCenter;
    TFDQuery            * QCK_Kol_Plan;
    TFDQuery            * QCk;
    TFDQuery            * QCkToDekanat;
    TFDQuery            * QControl_Exerc;
    TFDQuery            * QDelite;
    TFDQuery            * QDistrict;
    TFDQuery            * QEducation;
    TFDQuery            * QExam;
    TFDQuery            * QExamSpec;
    TFDQuery            * QExerc_Grp;
    TFDQuery            * QFindAbiturExerc;
    TFDQuery            * QFotoQeue;
    TFDQuery            * QFotoSign;
    TFDQuery            * QGIAC2kSpec;
    TFDQuery            * QGIAC3Sert;
    TFDQuery            * QGIACAll;
    TFDQuery            * QGIACAllPrivileg;
    TFDQuery            * QGIACAllPrivileg1;
    TFDQuery            * QGIACAllSpec;
    TFDQuery            * QGIACCKSpec;
    TFDQuery            * QGIACEdLic;
    TFDQuery            * QGIACEdOSred;
    TFDQuery            * QGIACEdOSredCity;
    TFDQuery            * QGIACEdOSredVil;
    TFDQuery            * QGIACForeigner;
    TFDQuery            * QGIACInAll;
    TFDQuery            * QGIACInCel;
    TFDQuery            * QGIACKursi;
    TFDQuery            * QGIACMedal;
    TFDQuery            * QGIACMil;
    TFDQuery            * QGIACOlimp;
    TFDQuery            * QGIACPtu;
    TFDQuery            * QGIACSirot;
    TFDQuery            * QGIACYearSred;
    TFDQuery            * QGIACYearSredCity;
    TFDQuery            * QGIACYearSredSpec;
    TFDQuery            * QGIACYearSredVil;
    TFDQuery            * QGroup_Count_Spec;
    TFDQuery            * QGroup_Count;
    TFDQuery            * QInc_Gr_Old;
    TFDQuery            * QIP;
    TFDQuery            * QKod_Fac;
    TFDQuery            * QKod_Spec;
    TFDQuery            * QLangvich;
    TFDQuery            * QLangvichToDekanat;
    TFDQuery            * QLetterSource;
    TFDQuery            * QLetterSourceKol;
    TFDQuery            * QListDocToDekanat;
    TFDQuery            * QLittle_Spisoc_GR;
    TFDQuery            * QLocality;
    TFDQuery            * QMax_Nom_Dela;
    TFDQuery            * QMax_Nomer_Ab;
    TFDQuery            * QN_group;
    TFDQuery            * QNoticeFac;
    TFDQuery            * QNoticeFIO;
    TFDQuery            * QNoticeSpec;
    TFDQuery            * QPersonalDocum;
    TFDQuery            * QPlan_Priem_All_Special;
    TFDQuery            * QPlan_Priem_All;
    TFDQuery            * QPlan_Priem_CK_Special;
    TFDQuery            * QPlan_Priem_CK;
    TFDQuery            * QPlan_Priem_Konk_All_Param;
    TFDQuery            * QPlan_Priem_Konk_Special;
    TFDQuery            * QPlan_Priem_Konk;
    TFDQuery            * QPlan_Priem_Price;
    TFDQuery            * QPlanPriem2Price;
    TFDQuery            * QPlanPriemPrice;
    TFDQuery            * QPrivToDekanat;
    TFDQuery            * QProverka_RYOR;
    TFDQuery            * QProverka_sert;
    TFDQuery            * QRegion_Center;
    TFDQuery            * QRep_Abitura;
    TFDQuery            * QRep_Sel_Exerc;
    TFDQuery            * QReport_Rasp;
    TFDQuery            * QResult_Exam;
    TFDQuery            * QSelect_ab;
    TFDQuery            * QSertificat_ex_list;
    TFDQuery            * QSertificat_Res;
    TFDQuery            * QSertificat;
    TFDQuery            * QSertificatToDekanat;
    TFDQuery            * QShkala;
    TFDQuery            * QShow_Result_Exam;
    TFDQuery            * QSpecializ;
    TFDQuery            * QSpecializPlan_Priem;
    TFDQuery            * QSpisoc_Group_Pol;
    TFDQuery            * QSpisoc_Group;
    TFDQuery            * QSpisok_Spec;
    TFDQuery            * QStatistic_Every_Day_Ball_Price;
    TFDQuery            * QStatistic_Every_Day_Ball;
    TFDQuery            * QStatistic_Every_Day_Special;
    TFDQuery            * QStatistic_Every_Day;
    TFDQuery            * QStatisticEveryDay;
    TFDQuery            * QStreet;
    TFDQuery            * QSum_Ball_Nomer;
    TFDQuery            * QSum_Ball;
    TFDQuery            * QToDekanat;
    TFDQuery            * QType_locality;
    TFDQuery            * QType_street;
    TFDQuery            * QUndo_Abit;
    TFDQuery            * RegionNameQr;
    TFDQuery            * RegionQr;
    TFDQuery            * RegionUpCKQr;
    TFDQuery            * SelectLogAbiturQr;
    TFDQuery            * SelPrivLogQr;
    TFDQuery            * SerteficatSelQr;
    TFDQuery            * SertSelLogQr;
    TFDQuery            * SpecFacQr;
    TFDQuery            * SpecializNameQr;
    TFDQuery            * SpecializQr;
    TFDQuery            * SpecQr;
    TFDQuery            * SPFDQ;
    TFDQuery            * SPFDQ1;
    TFDQuery            * SportQuery;
    TFDQuery            * SspecQ;
    TFDQuery            * Stat3hAll1Qr;
    TFDQuery            * Stat3hAll2Qr;
    TFDQuery            * StatusQueueQr;
    TFDQuery            * UpDateOutQr;
    TFDQuery            * VO2KSpecializQr;
    TFDQuery            * WithoutCntQr;
    TFDQuery            * WithoutDetQr;
    TFDQuery            * WithoutQr;
    TFDQuery            * WithOutTestLogQr;
    TFDQuery            * SumBallCalculateQr;

    TFDStoredProc       * AbiturLogInsStrdPrc;
    TFDStoredProc       * CertificLogDelStrdPrc;
    TFDStoredProc       * MaxNumDelaStrdPrc;
    TFDStoredProc       * PrivDelStrdPrc;
    TFDStoredProc       * PrivilegLogDelStrdPrc;
    TFDStoredProc       * PrivilegLogInsStrdPrc;
    TFDStoredProc       * PrivInsStrdPrc;
    TFDStoredProc       * RaspredBall12StrdPrc;
    TFDStoredProc       * RaspredBall34StrdPrc;
    TFDStoredProc       * RaspredBallStrdPrc;
    TFDStoredProc       * StoredProcBall_Sertifikat;
    TFDStoredProc       * StoredProcKolk_Konk;
    TFDStoredProc       * StoredProcKolk_Konk1;
    TFDStoredProc       * StoredProcN_AB;
    TFDStoredProc       * StoredProcN_People;
    TFDStoredProc       * StoredProcSelExercIns;
    TFDStoredProc       * StoredProcStatistic_Konk;
    TFDStoredProc       * StoredProcSumm_Ball_2K;
    TFDStoredProc       * StoredProcSumm_Ball;
    TFDStoredProc       * StoredProcSumm_Ball100;

    TFDTable            * CntrExrcTbl;
    TFDTable            * Increment_GroupTable;
    TFDTable            * RegCentrTbl;
    TFDTable            * Selection_CommitteeFDTable;
    TFDTable            * TBall;
    TFDTable            * TCategory;
    TFDTable            * TCk;
    TFDTable            * TDocum;
    TFDTable            * TEduDoc;
    TFDTable            * TFaculty;
    TFDTable            * TFoundation;
    TFDTable            * TKol_Place;
    TFDTable            * TPass_User;
    TFDTable            * TPredmet;
    TFDTable            * TRegion;
    TFDTable            * TVid_Sport;

    TFDUpdateSQL        * BloskUpSQL;
    TFDUpdateSQL        * ListDocFDUp;
    TFDUpdateSQL        * PasportUp;
    TFDUpdateSQL        * QSelectUpdateSQL;
    TFDUpdateSQL        * SportUpdateSQL;
    TFDUpdateSQL        * UpAb_P;
    TFDUpdateSQL        * UpAbitur_Priv_Enter;
    TFDUpdateSQL        * UpAbitura;
    TFDUpdateSQL        * UpAdd_N_Group;
    TFDUpdateSQL        * UpCenter;
    TFDUpdateSQL        * UpCkToDekanat;
    TFDUpdateSQL        * UPFoto;
    TFDUpdateSQL        * UpInc_Gr_Old;
    TFDUpdateSQL        * UpLangvichToDekanat;
    TFDUpdateSQL        * UpListDocToDekanat;
    TFDUpdateSQL        * UpPrivToDekanat;
    TFDUpdateSQL        * UpResult_Exam;
    TFDUpdateSQL        * UpSertificatToDekanat;
    TFDUpdateSQL        * UpShow_Result_Exam;
    TFDUpdateSQL        * UpSpecializ;
    TFDUpdateSQL        * UpSum_Ball_Nomer;
    TFDUpdateSQL        * UpSum_Ball;
    TFDUpdateSQL        * UpToDekanat;
    TFDUpdateSQL        * UpUndo_Abit;

    TFloatField         * QAbituraMIDDLE_BALL;
    TFloatField         * QAbituraSTAG_SPEC;
    TFloatField         * QAbituraSTAG;
    TFloatField         * QAbituraSUM_BALL;
    TFloatField         * QExamBALL;
    TFloatField         * QExamSpecBALL;
    TFloatField         * QResult_ExamBALL;
    TFloatField         * QSelect_abMIDDLE_BALL;
    TFloatField         * QSertificat_ex_listBALL;
    TFloatField         * QShow_Result_ExamBALL;
    TFloatField         * QSpisoc_Group_PolMIDDLE_BALL;
    TFloatField         * QSpisoc_Group_PolSUM_BALL;
    TFloatField         * QSpisoc_GroupMIDDLE_BALL;
    TFloatField         * QSpisoc_GroupSUM_BALL;
    TFloatField         * QSpisok_SpecMIDDLE_BALL;
    TFloatField         * QSum_Ball_NomerMIDDLE_BALL;
    TFloatField         * QSum_Ball_NomerSUM_BALL;
    TFloatField         * QSum_Ball_NomerSUM;
    TFloatField         * QSum_BallMIDDLE_BALL;
    TFloatField         * QSum_BallSUM_BALL;
    TFloatField         * QSum_BallSUM;
    TFloatField         * QToDekanatMIDDLE_B;
    TFloatField         * StoredProcBall_SertifikatB;

    TIntegerField       * AbiturCompQrNOMER_AB;
    TIntegerField       * AdrLogLastQrID_LOG;
    TIntegerField       * AdrLogLastQrNOMER_AB;
    TIntegerField       * BlockBtnQrID_BLOCK;
    TIntegerField       * BlockQID_BLOCK;
    TIntegerField       * BlockQPEREPODACHA;
    TIntegerField       * CntrExrcTblID_CONTROL_EXERC;
    TIntegerField       * CountryQrDIGITAL_CODE;
    TIntegerField       * FIOSearchQrID_AB;
    TIntegerField       * Increment_GroupTableGOD;
    TIntegerField       * ListDocFDQNOMER_AB;
    TIntegerField       * LogIDSelQrID_LOG;
    TIntegerField       * LogLastQrID_LOG;
    TIntegerField       * MaxExrcQrMAX;
    TIntegerField       * PasportFDQNOMER;
    TIntegerField       * PrintDocQrNOMER_AB;
    TIntegerField       * PrivCnttQrCOUNT;
    TIntegerField       * QAb_PN_AB_P;
    TIntegerField       * QAb_PNOMER_AB;
    TIntegerField       * QAb_Pr_EnterNOMER_AB;
    TIntegerField       * QAb_Pr_EnterPRIV_LEVEL1;
    TIntegerField       * QAbitur_Priv_EnterNOMER_AB;
    TIntegerField       * QAbituraN_CENTRE;
    TIntegerField       * QAbituraNOMER_AB;
    TIntegerField       * QAbituraPOSTCODE;
    TIntegerField       * QAbituraSTREET;
    TIntegerField       * QAdressLOCAL_ID;
    TIntegerField       * QAdressN_DISTRICT;
    TIntegerField       * QAdressN_REGION;
    TIntegerField       * QAdressN_TYPE;
    TIntegerField       * QAdressTYPE_STREET;
    TIntegerField       * QCkToDekanatCUSTOMER;
    TIntegerField       * QCkToDekanatN_CENTRE;
    TIntegerField       * QCkToDekanatN_CK;
    TIntegerField       * QCkToDekanatN_REGION;
    TIntegerField       * QCkToDekanatN_SPECIALIZ;
    TIntegerField       * QCkToDekanatNOMER;
    TIntegerField       * QDistrictN_DISTRICT;
    TIntegerField       * QDistrictN_REGION;
    TIntegerField       * QEducationID;
    TIntegerField       * QEducationNOMER_AB;
    TIntegerField       * QExamNOMER_AB;
    TIntegerField       * QExamSpecNOMER_AB;
    TIntegerField       * QFindAbiturExercID_SEL_EXERC;
    TIntegerField       * QFotoQeueID_AB_QUEUE;
    TIntegerField       * QFotoSignNOMER_AB;
    TIntegerField       * QGIAC3SertCOUNT;
    TIntegerField       * QGIACAllPrivileg1COUNT;
    TIntegerField       * QGIACAllPrivilegCOUNT;
    TIntegerField       * QGIACInAllCOUNT;
    TIntegerField       * QGIACInCelCOUNT;
    TIntegerField       * QGIACKursiCOUNT;
    TIntegerField       * QGIACMedalCOUNT;
    TIntegerField       * QGIACMilCOUNT;
    TIntegerField       * QGIACOlimpCOUNT;
    TIntegerField       * QGIACSirotCOUNT;
    TIntegerField       * QInc_Gr_OldGOD;
    TIntegerField       * QInc_Gr_OldINC_GR_OLD;
    TIntegerField       * QInc_Gr_OldINC_GROUP;
    TIntegerField       * QIPN_IP;
    TIntegerField       * QLangvichN_LANGVICH;
    TIntegerField       * QLangvichToDekanatN_LANGVICH;
    TIntegerField       * QLangvichToDekanatNOMER;
    TIntegerField       * QLetterSourceNOMER_AB;
    TIntegerField       * QListDocToDekanatNOMER;
    TIntegerField       * QLittle_Spisoc_GRNOMER_AB;
    TIntegerField       * QLocalityID;
    TIntegerField       * QLocalityN_DISTRICT;
    TIntegerField       * QMax_Nomer_AbMAX;
    TIntegerField       * QPersonalDocumID_TYPE;
    TIntegerField       * QPlan_Priem_AllORDER_SP;
    TIntegerField       * QPlan_Priem_CK_SpecialSUM1;
    TIntegerField       * QPlan_Priem_CKSUM;
    TIntegerField       * QPlan_Priem_PriceORDER_SP;
    TIntegerField       * QPlan_Priem_PriceSUM;
    TIntegerField       * QPrivToDekanatN_PRIV;
    TIntegerField       * QPrivToDekanatNOMER;
    TIntegerField       * QProverka_sertNOMER_AB;
    TIntegerField       * QResult_ExamNOMER_AB;
    TIntegerField       * QSelect_abN_CENTRE;
    TIntegerField       * QSelect_abNOMER_AB;
    TIntegerField       * QSelect_abPOSTCODE;
    TIntegerField       * QSelect_abSTREET;
    TIntegerField       * QSertificat_ResNOMER_AB;
    TIntegerField       * QSertificatNOMER_AB;
    TIntegerField       * QSertificatToDekanatNOMER;
    TIntegerField       * QSertificatYEAR_S;
    TIntegerField       * QShow_Result_ExamNOMER_AB;
    TIntegerField       * QSpecializPlan_PriemN_SPEC_DIR;
    TIntegerField       * QSpisoc_Group_PolNOMER_AB;
    TIntegerField       * QSpisoc_GroupNOMER_AB;
    TIntegerField       * QSpisok_SpecNOMER_AB;
    TIntegerField       * QStatistic_Every_Day_BallCOUNT;
    TIntegerField       * QStatistic_Every_DayORDER_SP;
    TIntegerField       * QStreetID;
    TIntegerField       * QSum_Ball_NomerNOMER_AB;
    TIntegerField       * QSum_BallNOMER_AB;
    TIntegerField       * QToDekanatID_STREET;
    TIntegerField       * QToDekanatN_CENTRE;
    TIntegerField       * QToDekanatNOMER;
    TIntegerField       * QToDekanatNUMBER;
    TIntegerField       * QToDekanatPOSTCODE;
    TIntegerField       * QType_localityN_TYPE;
    TIntegerField       * QType_streetID;
    TIntegerField       * QUndo_AbitNOMER_AB;
    TIntegerField       * SelectLogAbiturQrID_LOG;
    TIntegerField       * SelectLogAbiturQrNOMER_AB;
    TIntegerField       * SportQueryNOMER;
    TIntegerField       * SspecQNOMER_AB;
    TIntegerField       * TCkN_CENTRE;
    TIntegerField       * VO2KSpecializQrNOMER_AB;

    TLargeintField      * InfCntQrCOUNT;
    TLargeintField      * OutCntQrCOUNT;
    TLargeintField      * QGIAC2kSpecSUM;
    TLargeintField      * QGIACAllSpecSUM;
    TLargeintField      * QGIACCKSpecSUM;
    TLargeintField      * QGIACEdLicCOUNT;
    TLargeintField      * QGIACEdOSredCityCOUNT;
    TLargeintField      * QGIACEdOSredCOUNT;
    TLargeintField      * QGIACEdOSredVilCOUNT;
    TLargeintField      * QGIACForeignerCOUNT;
    TLargeintField      * QGIACYearSredCityCOUNT;
    TLargeintField      * QGIACYearSredCOUNT;
    TLargeintField      * QGIACYearSredSpecCOUNT;
    TLargeintField      * QGIACYearSredVilCOUNT;
    TLargeintField      * QGroup_Count_SpecCOUNT;
    TLargeintField      * QGroup_CountCOUNT;
    TLargeintField      * QLetterSourceKolCOUNT;
    TLargeintField      * QPlan_Priem_All_SpecialSUM1;
    TLargeintField      * QPlan_Priem_AllSUM;
    TLargeintField      * QPlan_Priem_Konk_SpecialSUM1;
    TLargeintField      * QStatistic_Every_Day_Ball_PriceCOUNT;
    TLargeintField      * QStatistic_Every_Day_SpecialCOUNT;
    TLargeintField      * QStatistic_Every_DayCOUNT;
    TLargeintField      * QStatisticEveryDaySUM;
    TLargeintField      * Stat3hAll1QrCOUNT;
    TLargeintField      * Stat3hAll2QrCOUNT;
    TLargeintField      * WithoutCntQrCOUNT;

    TSingleField        * QToDekanatSCHOLARSHIP;

    TSmallintField      * AbiturCompQrCATEGORY_AB;
    TSmallintField      * AbiturCompQrCATEGORY_IF;
    TSmallintField      * AbiturCompQrEDUCATION;
    TSmallintField      * AbiturCompQrKONKURS;
    TSmallintField      * AbiturCompQrN_FAC;
    TSmallintField      * AbiturCompQrN_SPEC;
    TSmallintField      * AbiturCompQrN_SPECIALIZ;
    TSmallintField      * AbiturCompQrPRICE;
    TSmallintField      * AbiturCompQrSTATUS;
    TSmallintField      * AbiturCompQrTERM_EDU;
    TSmallintField      * AbiturCompQrVID_EDU;
    TSmallintField      * AbiturInvTmpQrDAT_PRIV;
    TSmallintField      * AbiturSirTmpQrDAT_PRIV;
    TSmallintField      * BlockBtnQrADD_ABITUR;
    TSmallintField      * BlockBtnQrRE_INSIDE_FAC;
    TSmallintField      * BlockBtnQrRESTOR_LIST;
    TSmallintField      * BlockBtnQrTOOK_DOC1;
    TSmallintField      * BlockBtnQrTOOK_DOC2;
    TSmallintField      * BlockQADD_ABITUR;
    TSmallintField      * BlockQBLOCK;
    TSmallintField      * BlockQN_FAC;
    TSmallintField      * BlockQRE_INSIDE_FAC;
    TSmallintField      * BlockQRESTOR_LIST;
    TSmallintField      * BlockQTOOK_DOC1;
    TSmallintField      * BlockQTOOK_DOC2;
    TSmallintField      * CkRegionQrN_CENTRE;
    TSmallintField      * CkRegionQrN_REGION;
    TSmallintField      * CntrExrcTblID_EXERC;
    TSmallintField      * CntrExrcTblN_FAC;
    TSmallintField      * CntrExrcTblN_SPECIALIZ;
    TSmallintField      * CntrExrcTblNUM_EXERC_GRP;
    TSmallintField      * CntrlExrcQrID_EXERC;
    TSmallintField      * DocumFDQN_DOC;
    TSmallintField      * DocumInListQN_DOC;
    TSmallintField      * FIOSearchQrCATEGORY_AB;
    TSmallintField      * FIOSearchQrCATEGORY_EDU;
    TSmallintField      * FIOSearchQrCATEGORY_IF;
    TSmallintField      * FIOSearchQrKONKURS;
    TSmallintField      * FIOSearchQrN_FAC;
    TSmallintField      * FIOSearchQrN_SPEC;
    TSmallintField      * FIOSearchQrN_SPECIALIZ;
    TSmallintField      * FIOSearchQrPRICE;
    TSmallintField      * FIOSearchQrSTATUS_QUEUE;
    TSmallintField      * FIOSearchQrTERM_EDU;
    TSmallintField      * FIOSearchQrVID_EDU;
    TSmallintField      * Increment_GroupTableINC_GROUP;
    TSmallintField      * Increment_GroupTableVID_EDU;
    TSmallintField      * InfQrID_PRIV;
    TSmallintField      * InfQrN_OTHERS;
    TSmallintField      * KodSpecializQrN_SPEC_DIR;
    TSmallintField      * ListDocFDQN_DOC;
    TSmallintField      * OutDetQrID_DET;
    TSmallintField      * OutDetQrN_ITEM;
    TSmallintField      * OutQrID_PRIV;
    TSmallintField      * OutQrN_OUT_TESTS;
    TSmallintField      * PasportFDQID_TYPE;
    TSmallintField      * PasportFDQN_REGION;
    TSmallintField      * PrivilegLogSelQrDAT_PRIV;
    TSmallintField      * PrivilegLogSelQrN_PRIV;
    TSmallintField      * PrivilegLogSelQrSEL_PRIV;
    TSmallintField      * PrivQrDAT_PRIV;
    TSmallintField      * PrivQrN_PRIV;
    TSmallintField      * PrivQrSEL_PRIV;
    TSmallintField      * QAb_PKONKURS_DO;
    TSmallintField      * QAb_PKONKURS_PO;
    TSmallintField      * QAb_PN_CK;
    TSmallintField      * QAb_PN_SPEC_DO;
    TSmallintField      * QAb_PN_SPEC_PO;
    TSmallintField      * QAb_PN_SPECIALIZ_DO;
    TSmallintField      * QAb_PN_SPECIALIZ_PO;
    TSmallintField      * QAb_PNOM_DELA_DO;
    TSmallintField      * QAb_PNOM_DELA_PO;
    TSmallintField      * QAb_PPRICE_DO;
    TSmallintField      * QAb_PPRICE_PO;
    TSmallintField      * QAb_Pr_EnterN_PRIV;
    TSmallintField      * QAb_PVID_EDU_DO;
    TSmallintField      * QAb_PVID_EDU_PO;
    TSmallintField      * QAbitur_Priv_EnterN_PRIV;
    TSmallintField      * QAbituraCATEGORY_AB;
    TSmallintField      * QAbituraCATEGORY_IF;
    TSmallintField      * QAbituraCITIZENSHIP;
    TSmallintField      * QAbituraDISABLED;
    TSmallintField      * QAbituraEDUCATION;
    TSmallintField      * QAbituraFLAT;
    TSmallintField      * QAbituraID_TYPE;
    TSmallintField      * QAbituraKONKURS;
    TSmallintField      * QAbituraN_CK;
    TSmallintField      * QAbituraN_FAC;
    TSmallintField      * QAbituraN_FOUND;
    TSmallintField      * QAbituraN_LANGVICH;
    TSmallintField      * QAbituraN_PRIKAZ_INCLUDE;
    TSmallintField      * QAbituraN_REGION;
    TSmallintField      * QAbituraN_SPEC;
    TSmallintField      * QAbituraN_SPECIALIZ;
    TSmallintField      * QAbituraN_SPORT_CATEGORY;
    TSmallintField      * QAbituraN_VID_SPORT;
    TSmallintField      * QAbituraNOM_DELA;
    TSmallintField      * QAbituraPRICE;
    TSmallintField      * QAbituraRUS_BEL;
    TSmallintField      * QAbituraSTATUS;
    TSmallintField      * QAbituraTERM_EDU;
    TSmallintField      * QAbituraTOWN_VILLAGE;
    TSmallintField      * QAbituraTYPE_SCHOOL;
    TSmallintField      * QAbituraVID_EDU;
    TSmallintField      * QAbituraWHEN_EDU_MIDDLE;
    TSmallintField      * QAbituraWHEN_EDU_SPEC;
    TSmallintField      * QAdd_N_GroupN_COUNT;
    TSmallintField      * QAdd_N_GroupN_FAC;
    TSmallintField      * QAdd_N_GroupN_GROUP;
    TSmallintField      * QAdd_N_GroupVID_EDU;
    TSmallintField      * QCenterFLAG;
    TSmallintField      * QCenterN_CENTRE;
    TSmallintField      * QCenterN_REGION;
    TSmallintField      * QCK_Kol_PlanKOL_PLACE;
    TSmallintField      * QCkKOL_P;
    TSmallintField      * QCkN_CK;
    TSmallintField      * QCkN_REGION;
    TSmallintField      * QCkN_SPECIALIZ;
    TSmallintField      * QCkToDekanatSTATUS_CK;
    TSmallintField      * QEducationN_EDU_DOC;
    TSmallintField      * QExamCATEGORY_IF;
    TSmallintField      * QExamDISABLED;
    TSmallintField      * QExamEDUCATION;
    TSmallintField      * QExamKONKURS;
    TSmallintField      * QExamN_FAC;
    TSmallintField      * QExamN_PREDMET;
    TSmallintField      * QExamN_SPECIALIZ;
    TSmallintField      * QExamN_SPORT_CATEGORY;
    TSmallintField      * QExamNOM_BALL;
    TSmallintField      * QExamNOM_DELA;
    TSmallintField      * QExamPRICE;
    TSmallintField      * QExamRUS_BEL;
    TSmallintField      * QExamSpecCATEGORY_IF;
    TSmallintField      * QExamSpecDISABLED;
    TSmallintField      * QExamSpecEDUCATION;
    TSmallintField      * QExamSpecKONKURS;
    TSmallintField      * QExamSpecN_FAC;
    TSmallintField      * QExamSpecN_PREDMET;
    TSmallintField      * QExamSpecN_SPECIALIZ;
    TSmallintField      * QExamSpecN_SPORT_CATEGORY;
    TSmallintField      * QExamSpecNOM_BALL;
    TSmallintField      * QExamSpecNOM_DELA;
    TSmallintField      * QExamSpecPRICE;
    TSmallintField      * QExamSpecRUS_BEL;
    TSmallintField      * QExamSpecSTATUS_BALL;
    TSmallintField      * QExamSpecTERM_EDU;
    TSmallintField      * QExamSpecVID_EDU;
    TSmallintField      * QExamSTATUS_BALL;
    TSmallintField      * QExamTERM_EDU;
    TSmallintField      * QExamVID_EDU;
    TSmallintField      * QExerc_GrpID_EXERC;
    TSmallintField      * QFindAbiturExercID_EXERC;
    TSmallintField      * QInc_Gr_OldVID_EDU;
    TSmallintField      * QIPFLAG;
    TSmallintField      * QIPPROGRAM;
    TSmallintField      * QListDocToDekanatNAME_DOC;
    TSmallintField      * QMax_Nom_DelaMAX;
    TSmallintField      * QN_groupN_COUNT;
    TSmallintField      * QN_groupN_FAC;
    TSmallintField      * QN_groupN_GROUP;
    TSmallintField      * QN_groupVID_EDU;
    TSmallintField      * QNoticeFION_FAC;
    TSmallintField      * QNoticeFION_PRIKAZ_INCLUDE;
    TSmallintField      * QNoticeFION_SPECIALIZ;
    TSmallintField      * QNoticeFIOTERM_EDU;
    TSmallintField      * QNoticeFIOVID_EDU;
    TSmallintField      * QNoticeSpecN_SPEC_DIR;
    TSmallintField      * QPlan_Priem_All_SpecialN_SPEC;
    TSmallintField      * QPlan_Priem_All_SpecialVID_EDU;
    TSmallintField      * QPlan_Priem_AllN_SPECIALIZ;
    TSmallintField      * QPlan_Priem_AllVID_EDU;
    TSmallintField      * QPlan_Priem_CK_SpecialN_SPEC;
    TSmallintField      * QPlan_Priem_CK_SpecialVID_EDU;
    TSmallintField      * QPlan_Priem_CKN_SPECIALIZ;
    TSmallintField      * QPlan_Priem_CKVID_EDU;
    TSmallintField      * QPlan_Priem_Konk_All_ParamKOL_PLACE;
    TSmallintField      * QPlan_Priem_Konk_All_ParamN_SPECIALIZ;
    TSmallintField      * QPlan_Priem_Konk_SpecialN_SPEC;
    TSmallintField      * QPlan_Priem_Konk_SpecialTEXT;
    TSmallintField      * QPlan_Priem_KonkKOL_PLACE;
    TSmallintField      * QPlan_Priem_KonkN_SPECIALIZ;
    TSmallintField      * QPlan_Priem_KonkTEXT;
    TSmallintField      * QPlan_Priem_PriceN_SPECIALIZ;
    TSmallintField      * QPlan_Priem_PricePRICE;
    TSmallintField      * QPlan_Priem_PriceTEXT;
    TSmallintField      * QPlan_Priem_PriceVID_EDU;
    TSmallintField      * QPlanPriem2PriceKOL_PLACE;
    TSmallintField      * QPlanPriem2PriceN_SPECIALIZ;
    TSmallintField      * QPlanPriemPriceKOL_PLACE;
    TSmallintField      * QPlanPriemPriceN_SPECIALIZ;
    TSmallintField      * QPrivToDekanatUCH_GOD;
    TSmallintField      * QPrivToDekanatVID_PRIV;
    TSmallintField      * QProverka_RYORN_FAC;
    TSmallintField      * QProverka_RYORVID_EDU;
    TSmallintField      * QRegion_CenterFLAG;
    TSmallintField      * QRegion_CenterN_CENTRE;
    TSmallintField      * QRegion_CenterN_REGION;
    TSmallintField      * QRep_Sel_ExercNUM_EXERC_GRP;
    TSmallintField      * QReport_RaspN_FAC;
    TSmallintField      * QReport_RaspN_SPECIALIZ;
    TSmallintField      * QReport_RaspNOM_DELA;
    TSmallintField      * QReport_RaspTERM_EDU;
    TSmallintField      * QReport_RaspVID_EDU;
    TSmallintField      * QReport_RaspWHEN_EDU_MIDDLE;
    TSmallintField      * QReport_RaspWHEN_EDU_SPEC;
    TSmallintField      * QResult_ExamN_PREDMET;
    TSmallintField      * QResult_ExamNOM_BALL;
    TSmallintField      * QResult_ExamSTATUS_BALL;
    TSmallintField      * QSelect_abCITIZENSHIP;
    TSmallintField      * QSelect_abEDUCATION;
    TSmallintField      * QSelect_abFLAT;
    TSmallintField      * QSelect_abID_TYPE;
    TSmallintField      * QSelect_abLANGV_BALL;
    TSmallintField      * QSelect_abN_CK;
    TSmallintField      * QSelect_abN_FOUND;
    TSmallintField      * QSelect_abN_LANGVICH;
    TSmallintField      * QSelect_abN_PRIKAZ_INCLUDE;
    TSmallintField      * QSelect_abN_PRIVILEGE_EXAM;
    TSmallintField      * QSelect_abN_REGION;
    TSmallintField      * QSelect_abN_SPORT_CATEGORY;
    TSmallintField      * QSelect_abN_VID_SPORT;
    TSmallintField      * QSelect_abSTATUS;
    TSmallintField      * QSelect_abWHEN_EDU_MIDDLE;
    TSmallintField      * QSelect_abWHEN_EDU_SPEC;
    TSmallintField      * QSertificat_ex_listRUS_BEL;
    TSmallintField      * QSertificat_ResBALLS;
    TSmallintField      * QSertificat_ResN_FAC;
    TSmallintField      * QSertificat_ResN_PREDMET;
    TSmallintField      * QSertificat_ResRUS_BEL;
    TSmallintField      * QSertificat_ResVID_EDU;
    TSmallintField      * QSertificatBALLS;
    TSmallintField      * QSertificatN_PREDMET;
    TSmallintField      * QSertificatPRICE;
    TSmallintField      * QSertificatRUS_BEL;
    TSmallintField      * QSertificatToDekanatNAME_DOC;
    TSmallintField      * QShow_Result_ExamN_PREDMET;
    TSmallintField      * QShow_Result_ExamNOM_BALL;
    TSmallintField      * QShow_Result_ExamNOM_DELA;
    TSmallintField      * QShow_Result_ExamSTATUS_BALL;
    TSmallintField      * QSpecializN_FAC;
    TSmallintField      * QSpecializN_SPEC;
    TSmallintField      * QSpecializN_SPECIALIZ;
    TSmallintField      * QSpecializPlan_PriemN_SPEC;
    TSmallintField      * QSpecializPlan_PriemN_SPECIALIZ;
    TSmallintField      * QSpisoc_Group_PolKONKURS;
    TSmallintField      * QSpisoc_Group_PolN_CK;
    TSmallintField      * QSpisoc_Group_PolN_FAC;
    TSmallintField      * QSpisoc_Group_PolN_PRIVILEGE_EXAM;
    TSmallintField      * QSpisoc_Group_PolN_SPECIALIZ;
    TSmallintField      * QSpisoc_Group_PolN_SPORT_CATEGORY;
    TSmallintField      * QSpisoc_Group_PolPRICE;
    TSmallintField      * QSpisoc_Group_PolVID_EDU;
    TSmallintField      * QSpisoc_GroupKONKURS;
    TSmallintField      * QSpisoc_GroupN_CK;
    TSmallintField      * QSpisoc_GroupN_FAC;
    TSmallintField      * QSpisoc_GroupN_PRIVILEGE_EXAM;
    TSmallintField      * QSpisoc_GroupN_SPECIALIZ;
    TSmallintField      * QSpisoc_GroupN_SPORT_CATEGORY;
    TSmallintField      * QSpisoc_GroupPRICE;
    TSmallintField      * QSpisoc_GroupTERM_EDU;
    TSmallintField      * QSpisoc_GroupVID_EDU;
    TSmallintField      * QSpisok_SpecKONKURS;
    TSmallintField      * QSpisok_SpecN_CK;
    TSmallintField      * QSpisok_SpecN_FAC;
    TSmallintField      * QSpisok_SpecN_PRIVILEGE_EXAM;
    TSmallintField      * QSpisok_SpecN_SPECIALIZ;
    TSmallintField      * QSpisok_SpecN_SPORT_CATEGORY;
    TSmallintField      * QSpisok_SpecPRICE;
    TSmallintField      * QSpisok_SpecVID_EDU;
    TSmallintField      * QStatistic_Every_Day_Ball_PriceKONKURS;
    TSmallintField      * QStatistic_Every_Day_BallKONKURS;
    TSmallintField      * QStatistic_Every_Day_BallPRICE;
    TSmallintField      * QStatistic_Every_Day_SpecialKONKURS;
    TSmallintField      * QStatistic_Every_Day_SpecialN_SPEC;
    TSmallintField      * QStatistic_Every_Day_SpecialPRICE;
    TSmallintField      * QStatistic_Every_Day_SpecialVID_EDU;
    TSmallintField      * QStatistic_Every_DayKONKURS;
    TSmallintField      * QStatistic_Every_DayN_SPECIALIZ;
    TSmallintField      * QStatistic_Every_DayPRICE;
    TSmallintField      * QStatistic_Every_DayVID_EDU;
    TSmallintField      * QStatisticEveryDayN_SPECIALIZ;
    TSmallintField      * QToDekanatEDUCATION;
    TSmallintField      * QToDekanatFLAT;
    TSmallintField      * QToDekanatINC_GROUP;
    TSmallintField      * QToDekanatKURS;
    TSmallintField      * QToDekanatMARIAGE;
    TSmallintField      * QToDekanatN_FAC;
    TSmallintField      * QToDekanatN_FOUND_INCLUDE;
    TSmallintField      * QToDekanatN_FOUND;
    TSmallintField      * QToDekanatN_PRIKAZ_INCLUDE;
    TSmallintField      * QToDekanatN_PRIKAZ_KURS;
    TSmallintField      * QToDekanatN_SPEC;
    TSmallintField      * QToDekanatN_SPECIALIZ;
    TSmallintField      * QToDekanatN_VID_SPORT;
    TSmallintField      * QToDekanatSTATUS_PEOPLE;
    TSmallintField      * QToDekanatVID_EDU_INCLUDE;
    TSmallintField      * QToDekanatVID_EDU;
    TSmallintField      * QToDekanatWHEN_EDUC;
    TSmallintField      * QUndo_AbitSTATUS;
    TSmallintField      * RegCentrTblFLAG;
    TSmallintField      * RegCentrTblN_CENTRE;
    TSmallintField      * RegCentrTblN_REGION;
    TSmallintField      * SelectLogAbiturQrCATEGORY;
    TSmallintField      * SelectLogAbiturQrCITIZENSHIP;
    TSmallintField      * SelectLogAbiturQrKONKURS;
    TSmallintField      * SelectLogAbiturQrN_CK;
    TSmallintField      * SelectLogAbiturQrN_PRIKAZ_INCLUDE;
    TSmallintField      * SelectLogAbiturQrN_SPECIALIZ;
    TSmallintField      * SelectLogAbiturQrNOM_DELA_1;
    TSmallintField      * SelectLogAbiturQrNOM_DELA;
    TSmallintField      * SelectLogAbiturQrTERM_EDU;
    TSmallintField      * SelPrivLogQrDAT_PRIV;
    TSmallintField      * SelPrivLogQrN_PRIV;
    TSmallintField      * SelPrivLogQrSEL_PRIV;
    TSmallintField      * SerteficatSelQrBALLS;
    TSmallintField      * SerteficatSelQrN_PREDMET;
    TSmallintField      * SerteficatSelQrRUS_BEL;
    TSmallintField      * SertSelLogQrBALLS;
    TSmallintField      * SertSelLogQrRUS_BEL;
    TSmallintField      * SpecFacQrN_SPECIALIZ;
    TSmallintField      * SpecializQrN_SPECIALIZ;
    TSmallintField      * SPFDQKOD_FAC;
    TSmallintField      * SPFDQN_FAC;
    TSmallintField      * SportQueryN_PRIKAZ_SPORT;
    TSmallintField      * SportQueryN_PRIKAZ_SUD;
    TSmallintField      * SportQueryN_VID_SPORT;
    TSmallintField      * SportQuerySPORT_CATEGORY;
    TSmallintField      * SportQuerySUD_CATEGORY;
    TSmallintField      * Stat3hAll1QrKONKURS;
    TSmallintField      * Stat3hAll2QrKONKURS;
    TSmallintField      * TBallNOM_BALL;
    TSmallintField      * TCategoryN_SPORT_CATEGORY;
    TSmallintField      * TCkCUSTOMER;
    TSmallintField      * TCkKOL_P;
    TSmallintField      * TCkN_CK;
    TSmallintField      * TCkN_FAC;
    TSmallintField      * TCkN_REGION;
    TSmallintField      * TCkN_SPECIALIZ;
    TSmallintField      * TDocumN_DOC;
    TSmallintField      * TEduDocN_EDU_DOC;
    TSmallintField      * TFacultyKOD_FAC;
    TSmallintField      * TFacultyN_FAC;
    TSmallintField      * TFoundationN_FOUND;
    TSmallintField      * TKol_PlaceKOL_PLACE;
    TSmallintField      * TKol_PlaceN_FAC;
    TSmallintField      * TKol_PlaceN_KOL_PLACE;
    TSmallintField      * TKol_PlaceN_SPECIALIZ;
    TSmallintField      * TKol_PlacePRICE;
    TSmallintField      * TKol_PlaceTEXT;
    TSmallintField      * TKol_PlaceVID_EDU;
    TSmallintField      * TPass_UserN_FAC;
    TSmallintField      * TPredmetN_PREDMET;
    TSmallintField      * TRegionN_REGION;
    TSmallintField      * TVid_SportN_VID_SPORT;
    TSmallintField      * WithoutDetQrID_DET;
    TSmallintField      * WithoutDetQrN_ITEM;
    TSmallintField      * WithoutQrID_PRIV;
    TSmallintField      * WithoutQrN_WITHOUT_TESTS;

    TSQLTimeStampField  * AdrLogLastQrDATE_IN;
    TSQLTimeStampField  * ListDocFDQDATE_DOC;
    TSQLTimeStampField  * LogLastQrDATE_OUT;
    TSQLTimeStampField  * PasportFDQDATE_GIVE;
    TSQLTimeStampField  * PasportFDQDATE_VALID;
    TSQLTimeStampField  * QAb_PDATE_P;
    TSQLTimeStampField  * QAbituraD_PRIKAZ_INCLUDE;
    TSQLTimeStampField  * QAbituraDATE_OK;
    TSQLTimeStampField  * QAbituraDATE_PRIEM;
    TSQLTimeStampField  * QAbituraDATE_R;
    TSQLTimeStampField  * QAbituraDATE_V;
    TSQLTimeStampField  * QAbituraDATE_VOZVRAT;
    TSQLTimeStampField  * QListDocToDekanatDOC_DATE;
    TSQLTimeStampField  * QNoticeFIOD_PRIKAZ_INCLUDE;
    TSQLTimeStampField  * QPrivToDekanatDATA_C;
    TSQLTimeStampField  * QPrivToDekanatDATA_PO;
    TSQLTimeStampField  * QReport_RaspDATE_PRIEM;
    TSQLTimeStampField  * QSelect_abD_PRIKAZ_INCLUDE;
    TSQLTimeStampField  * QSelect_abDATE_OK;
    TSQLTimeStampField  * QSelect_abDATE_R;
    TSQLTimeStampField  * QSelect_abDATE_V;
    TSQLTimeStampField  * QSertificat_ex_listDATE_PRIEM;
    TSQLTimeStampField  * QToDekanatD_INCLUDE;
    TSQLTimeStampField  * QToDekanatD_PRIKAZ_INCLUDE;
    TSQLTimeStampField  * QToDekanatDATA_R;
    TSQLTimeStampField  * QToDekanatDATE_END;
    TSQLTimeStampField  * SelectLogAbiturQrD_PRIKAZ_INCLUDE;
    TSQLTimeStampField  * SelectLogAbiturQrDATE_IN;
    TSQLTimeStampField  * SelectLogAbiturQrDATE_OUT;
    TSQLTimeStampField  * SportQueryD_PRIKAZ_SPORT;
    TSQLTimeStampField  * SportQueryD_PRIKAZ_SUD;

    TStringField        * BlockQNOTE_PEREPODACHA;
    TStringField        * BlockQNOTE;
    TStringField        * CkRegionQrCENTRE;
    TStringField        * CntrExrcTblEXERC2;
    TStringField        * CntrExrcTblPOL;
    TStringField        * CntrExrcTblSPECIALIZ_N;
    TStringField        * CntrlExrcQrNAME_EXERC;
    TStringField        * ContrySelQrSHORT_NAME;
    TStringField        * CountryQrFULL_NAME;
    TStringField        * CountryQrSHORT_NAME;
    TStringField        * DocumFDQTEXT_DOC;
    TStringField        * DocumInListQTEXT_DOC;
    TStringField        * FIOSearchQrFAM;
    TStringField        * FIOSearchQrFIO;
    TStringField        * FIOSearchQrNAME;
    TStringField        * FIOSearchQrOTCH;
    TStringField        * GrazdanToDekanatQrSHORT_NAME;
    TStringField        * Increment_GroupTableN_GROUP;
    TStringField        * InfQrNAME_PRIV;
    TStringField        * KodSpecializQrCODE_SPEC_DIR;
    TStringField        * LangSelQrLANGV;
    TStringField        * ListDocFDQDOC_INDEX;
    TStringField        * ListDocFDQTEXT_DOC;
    TStringField        * OtherPrivQrSHORT_NAME;
    TStringField        * OutDetQrNAME_DETAIS;
    TStringField        * OutQrNAME_PRIV;
    TStringField        * OutTestQrSHORT_NAME_1;
    TStringField        * OutTestQrSHORT_NAME;
    TStringField        * PasportFDQNUMBER;
    TStringField        * PasportFDQPERSONAL_NUMBER;
    TStringField        * PasportFDQSERIES;
    TStringField        * PasportFDQWHO_GIVE;
    TStringField        * PrintDocQrFAM;
    TStringField        * PrintDocQrNAME;
    TStringField        * PrintDocQrOTCH;
    TStringField        * QAb_PNOM_GROUP_DO;
    TStringField        * QAb_PNOM_GROUP_PO;
    TStringField        * QAb_Pr_EnterTEXT_PR_EN1;
    TStringField        * QAbFIOPolFAM;
    TStringField        * QAbFIOPolNAME;
    TStringField        * QAbFIOPolOTCH;
    TStringField        * QAbFIOPolPOL;
    TStringField        * QAbitur_Priv_EnterPRIV_ENTER1;
    TStringField        * QAbituraADDRESS_BEFORE;
    TStringField        * QAbituraADDRESS_LIFE;
    TStringField        * QAbituraADDRESS_MAMA;
    TStringField        * QAbituraADDRESS_PAPA;
    TStringField        * QAbituraFAM;
    TStringField        * QAbituraGRAGDAN;
    TStringField        * QAbituraHOUSE;
    TStringField        * QAbituraKONKURS1;
    TStringField        * QAbituraMAMA;
    TStringField        * QAbituraNAME_EDU_MIDDLE;
    TStringField        * QAbituraNAME_EDU_SPEC;
    TStringField        * QAbituraNAME;
    TStringField        * QAbituraNOM_ATTEST;
    TStringField        * QAbituraNOM_DELA1;
    TStringField        * QAbituraNOM_DIPLOM;
    TStringField        * QAbituraNOM_GROUP;
    TStringField        * QAbituraORGAN_V;
    TStringField        * QAbituraOTCH;
    TStringField        * QAbituraPAPA;
    TStringField        * QAbituraPASPORT;
    TStringField        * QAbituraPERSONAL_NOMER;
    TStringField        * QAbituraPHONE;
    TStringField        * QAbituraPLACE_R;
    TStringField        * QAbituraPOL;
    TStringField        * QAbituraPRICE1;
    TStringField        * QAbituraSPECIALIZ1;
    TStringField        * QAbituraWHERE_EDU_MIDDLE;
    TStringField        * QAbituraWHERE_EDU_SPEC;
    TStringField        * QAbituraWORK_BEFORE;
    TStringField        * QAbituraWORK_MAMA;
    TStringField        * QAbituraWORK_PAPA;
    TStringField        * QAdd_N_GroupDESCRIBE;
    TStringField        * QAdd_N_GroupNOM_GROUP;
    TStringField        * QAdd_N_GroupSPEC1;
    TStringField        * QAdd_N_GroupVID_EDU1;
    TStringField        * QAdressNAME_DISTRICT;
    TStringField        * QAdressNAME_LOCALITY;
    TStringField        * QAdressNAME_TYPE;
    TStringField        * QAdressTYPE;
    TStringField        * QCenterCENTRE;
    TStringField        * QCenterFLAG1;
    TStringField        * QCkCUSTOMER_PLACE;
    TStringField        * QCkTEXT_DEP;
    TStringField        * QControl_ExercNAME_EXERC;
    TStringField        * QDistrictNAME_DISTRICT;
    TStringField        * QEducationNAME_EDU;
    TStringField        * QEducationNOM_DOC;
    TStringField        * QEducationWHEN_EDU;
    TStringField        * QEducationWHERE_EDU;
    TStringField        * QExamBALL1;
    TStringField        * QExamFAM;
    TStringField        * QExamNAME;
    TStringField        * QExamOTCH;
    TStringField        * QExamPOL;
    TStringField        * QExamPREDM;
    TStringField        * QExamSpecBALL1;
    TStringField        * QExamSpecFAM;
    TStringField        * QExamSpecNAME;
    TStringField        * QExamSpecOTCH;
    TStringField        * QExamSpecPOL;
    TStringField        * QExamSpecPREDM;
    TStringField        * QExamSpecWITHOUT;
    TStringField        * QExamWITHOUT;
    TStringField        * QExerc_GrpNAME_EXERC;
    TStringField        * QGroup_CountNOM_GROUP;
    TStringField        * QInc_Gr_OldDESCRIBE;
    TStringField        * QInc_Gr_OldN_GROUP;
    TStringField        * QIPGRUPPA;
    TStringField        * QIPIP_NAME;
    TStringField        * QIPIP;
    TStringField        * QKod_FacFAC;
    TStringField        * QKod_SpecSPECIAL_DIRECTION;
    TStringField        * QLangvichLANGV;
    TStringField        * QLetterSourceADDRESS_BEFORE;
    TStringField        * QLetterSourceFAM;
    TStringField        * QLetterSourceNAME;
    TStringField        * QLetterSourceOTCH;
    TStringField        * QListDocToDekanatDOC_INDEX;
    TStringField        * QListDocToDekanatNOTE;
    TStringField        * QLittle_Spisoc_GRFAM;
    TStringField        * QLittle_Spisoc_GRNAME;
    TStringField        * QLittle_Spisoc_GROTCH;
    TStringField        * QLocalityNAME_LOCALITY;
    TStringField        * QN_groupDESCRIBE;
    TStringField        * QN_groupNOM_GROUP;
    TStringField        * QNoticeFacFAC;
    TStringField        * QNoticeFIOADDRESS_BEFORE;
    TStringField        * QNoticeFIOFAM;
    TStringField        * QNoticeFIONAME;
    TStringField        * QNoticeFIOOTCH;
    TStringField        * QNoticeSpecCODE_SPEC_DIR;
    TStringField        * QNoticeSpecSPECIAL_DIRECTION;
    TStringField        * QPersonalDocumNAME_TYPE;
    TStringField        * QPlan_Priem_All_SpecialCODE_SPEC;
    TStringField        * QPlan_Priem_All_SpecialSPEC;
    TStringField        * QPlan_Priem_AllSPECIALIZ1;
    TStringField        * QPlan_Priem_AllSPECIALIZ2;
    TStringField        * QPlan_Priem_Konk_All_ParamSPECIALIZ2;
    // TStringField        * QPlan_Priem_Konk_All_ParamSPECIALIZ2;
    TStringField        * QPlan_Priem_PriceSPECIALIZ2;
    TStringField        * QPrivToDekanatDESCRIBE;
    TStringField        * QPrivToDekanatDOC_PRIV;
    TStringField        * QPrivToDekanatTEXT_PRIV;
    TStringField        * QProverka_RYORFAM;
    TStringField        * QProverka_RYORNAME_EDU_MIDDLE;
    TStringField        * QProverka_RYORPRIV;
    TStringField        * QRegion_CenterCENTRE;
    TStringField        * QRep_AbituraFAM;
    TStringField        * QRep_AbituraNAME;
    TStringField        * QRep_AbituraNOM_GROUP;
    TStringField        * QRep_AbituraOTCH;
    TStringField        * QRep_Sel_ExercNAME_EXERC;
    TStringField        * QReport_RaspFAM;
    TStringField        * QReport_RaspFIO;
    TStringField        * QReport_RaspN_FAC1;
    TStringField        * QReport_RaspNAME_EDU_MIDDLE;
    TStringField        * QReport_RaspNAME_EDU_SPEC;
    TStringField        * QReport_RaspNAME;
    TStringField        * QReport_RaspNOM_ATTEST;
    TStringField        * QReport_RaspNOM_DIPLOM;
    TStringField        * QReport_RaspNOM_GROUP;
    TStringField        * QReport_RaspOTCH;
    TStringField        * QReport_RaspSPECIAL1;
    TStringField        * QReport_RaspVID_EDU1;
    TStringField        * QReport_RaspWHERE_EDU_MIDDLE;
    TStringField        * QReport_RaspWHERE_EDU_SPEC;
    TStringField        * QResult_ExamB1;
    TStringField        * QSelect_abADDRESS_BEFORE;
    TStringField        * QSelect_abADDRESS_LIFE;
    TStringField        * QSelect_abADDRESS_MAMA;
    TStringField        * QSelect_abADDRESS_PAPA;
    TStringField        * QSelect_abFAM;
    TStringField        * QSelect_abHOUSE;
    TStringField        * QSelect_abMAMA;
    TStringField        * QSelect_abNAME_EDU_MIDDLE;
    TStringField        * QSelect_abNAME_EDU_SPEC;
    TStringField        * QSelect_abNAME;
    TStringField        * QSelect_abORGAN_V;
    TStringField        * QSelect_abOTCH;
    TStringField        * QSelect_abPAPA;
    TStringField        * QSelect_abPASPORT;
    TStringField        * QSelect_abPERSONAL_NOMER;
    TStringField        * QSelect_abPHONE;
    TStringField        * QSelect_abPLACE_R;
    TStringField        * QSelect_abPOL;
    TStringField        * QSelect_abPRIV;
    TStringField        * QSelect_abV_K;
    TStringField        * QSelect_abWHERE_EDU_MIDDLE;
    TStringField        * QSelect_abWHERE_EDU_SPEC;
    TStringField        * QSelect_abWITHOUT;
    TStringField        * QSelect_abWORK_BEFORE;
    TStringField        * QSelect_abWORK_MAMA;
    TStringField        * QSelect_abWORK_PAPA;
    TStringField        * QSertificat_ex_listTEXT_PREDMET;
    TStringField        * QSertificat_ResDESCRIBE;
    TStringField        * QSertificat_ResFAM;
    TStringField        * QSertificat_ResFIO;
    TStringField        * QSertificat_ResNAME;
    TStringField        * QSertificat_ResNOM_GROUP;
    TStringField        * QSertificat_ResNOMER_S;
    TStringField        * QSertificat_ResOTCH;
    TStringField        * QSertificat_ResSERIA_S;
    TStringField        * QSertificatDESCRIBE;
    TStringField        * QSertificatNOMER_S;
    TStringField        * QSertificatPREDMET1;
    TStringField        * QSertificatRUS_BEL1;
    TStringField        * QSertificatSERIA_S;
    TStringField        * QSertificatToDekanatDOC_INDEX;
    TStringField        * QShow_Result_ExamBALL1;
    TStringField        * QShow_Result_ExamFAM;
    TStringField        * QShow_Result_ExamNAME;
    TStringField        * QShow_Result_ExamOTCH;
    TStringField        * QSpecializCODE_SPECIALIZ;
    TStringField        * QSpecializPlan_PriemSPECIAL;
    TStringField        * QSpecializSPECIAL_DIRECTION;
    TStringField        * QSpecializSPECIAL;
    TStringField        * QSpisoc_Group_PolFAM;
    TStringField        * QSpisoc_Group_PolGRAGDAN;
    TStringField        * QSpisoc_Group_PolNAME;
    TStringField        * QSpisoc_Group_PolNOM_GROUP;
    TStringField        * QSpisoc_Group_PolOTCH;
    TStringField        * QSpisoc_Group_PolPRIV;
    TStringField        * QSpisoc_Group_PolSPECIALIZ1;
    TStringField        * QSpisoc_Group_PolSPECIALIZ2;
    TStringField        * QSpisoc_Group_PolV_K;
    TStringField        * QSpisoc_Group_PolVID_EDU1;
    TStringField        * QSpisoc_Group_PolWITHOUT;
    TStringField        * QSpisoc_GroupFAM;
    TStringField        * QSpisoc_GroupGRAGDAN;
    TStringField        * QSpisoc_GroupNAME;
    TStringField        * QSpisoc_GroupNOM_GROUP;
    TStringField        * QSpisoc_GroupOTCH;
    TStringField        * QSpisoc_GroupPRIV;
    TStringField        * QSpisoc_GroupSPECIALIZ1;
    TStringField        * QSpisoc_GroupSPECIALIZ2;
    TStringField        * QSpisoc_GroupV_K;
    TStringField        * QSpisoc_GroupVID_EDU1;
    TStringField        * QSpisoc_GroupWITHOUT;
    TStringField        * QSpisok_SpecFAM;
    TStringField        * QSpisok_SpecFIO;
    TStringField        * QSpisok_SpecGRAGDAN;
    TStringField        * QSpisok_SpecNAME;
    TStringField        * QSpisok_SpecNOM_GROUP;
    TStringField        * QSpisok_SpecOTCH;
    TStringField        * QSpisok_SpecPRIV;
    TStringField        * QSpisok_SpecSPECIALIZ1;
    TStringField        * QSpisok_SpecV_K;
    TStringField        * QSpisok_SpecVID_EDU1;
    TStringField        * QSpisok_SpecWITHOUT;
    TStringField        * QStatisticEveryDaySPECIALIZ2;
    TStringField        * QStreetNAME_IN_RUS;
    TStringField        * QToDekanatADDRESS_BEFORE;
    TStringField        * QToDekanatADDRESS_LIFE;
    TStringField        * QToDekanatADDRESS_MAMA;
    TStringField        * QToDekanatADDRESS_PAPA;
    TStringField        * QToDekanatADDRESS_POSLE;
    TStringField        * QToDekanatADDRESS;
    TStringField        * QToDekanatFAM;
    TStringField        * QToDekanatGRAGDAN;
    TStringField        * QToDekanatHOUSE;
    TStringField        * QToDekanatMAMA;
    TStringField        * QToDekanatN_GROUP;
    TStringField        * QToDekanatNAME_EDUC;
    TStringField        * QToDekanatNAME;
    TStringField        * QToDekanatOTCH;
    TStringField        * QToDekanatPAPA;
    TStringField        * QToDekanatPASPORT;
    TStringField        * QToDekanatPERSONAL_NOMER;
    TStringField        * QToDekanatPHONE_POSLE;
    TStringField        * QToDekanatPHONE;
    TStringField        * QToDekanatPLACE_R;
    TStringField        * QToDekanatPOL;
    TStringField        * QToDekanatWHERE_EDUC;
    TStringField        * QToDekanatWORK_BEFORE;
    TStringField        * QType_localityNAME_TYPE;
    TStringField        * QType_localitySHORT_TYPE_NAME;
    TStringField        * QType_streetSHORT_TYPE;
    TStringField        * QType_streetTYPE;
    TStringField        * QUndo_AbitFAM;
    TStringField        * QUndo_AbitNAME;
    TStringField        * QUndo_AbitOTCH;
    TStringField        * RegCentrTblCENTRE;
    TStringField        * RegionNameQrCENTRE;
    TStringField        * RegionQrCENTRE;
    TStringField        * Selection_CommitteeFDTableFIO;
    TStringField        * Selection_CommitteeFDTableIOF;
    TStringField        * Selection_CommitteeFDTablePOST;
    TStringField        * SelectLogAbiturQrADDRESS_BEFORE;
    TStringField        * SelectLogAbiturQrFAM;
    TStringField        * SelectLogAbiturQrNAME;
    TStringField        * SelectLogAbiturQrOTCH;
    TStringField        * SerteficatSelQrDESCRIBE;
    TStringField        * SerteficatSelQrNOMER_S;
    TStringField        * SerteficatSelQrSERIA_S;
    TStringField        * SertSelLogQrNOMER_S;
    TStringField        * SertSelLogQrSERIA_S;
    TStringField        * SertSelLogQrTEXT_PREDMET;
    TStringField        * SpecFacQrSPECIAL;
    TStringField        * SpecializNameQrSPECIAL_DIRECTION;
    TStringField        * SpecializNameQrSPECIAL;
    TStringField        * SpecializQrSPECIAL;
    TStringField        * SpecQrSPECIAL;
    TStringField        * SPFDQDEAN;
    TStringField        * SPFDQFAC_RP;
    TStringField        * SPFDQFAC;
    TStringField        * SPFDQFAC1;
    TStringField        * SportQueryWHO_GIVE_SUD;
    TStringField        * SportQueryWHO_GIVE;
    TStringField        * TBallBALL;
    TStringField        * TCategorySPORT_CATEGORY;
    TStringField        * TCkCUSTOMER_PLACE;
    TStringField        * TCkREGION2;
    TStringField        * TCkSPECIALIZ3;
    TStringField        * TCkTEXT_DEP;
    TStringField        * TDocumTEXT_DOC;
    TStringField        * TEduDocEDU_DOC;
    TStringField        * TFacultyDEAN;
    TStringField        * TFacultyFAC_RP;
    TStringField        * TFacultyFAC;
    TStringField        * TFacultyFAC1;
    TStringField        * TFoundationVID_FOUND;
    TStringField        * TKol_PlacePRICE1;
    TStringField        * TKol_PlaceSPECIALIZ2;
    TStringField        * TKol_PlaceTEXT1;
    TStringField        * TKol_PlaceVID_EDU1;
    TStringField        * TPass_UserUSER_NAME;
    TStringField        * TPass_UserUSER_PASSWORD;
    TStringField        * TPredmetTEXT_PREDMET;
    TStringField        * TRegionTEXT_REGION;
    TStringField        * TVid_SportVID_SPORT;
    TStringField        * WithoutDetQrNAME_DETAIS;
    TStringField        * WithoutQrNAME_PRIV;
    TStringField        * WithOutTestLogQrSHORT_NAME_1;
    TStringField        * WithOutTestLogQrSHORT_NAME;

    void __fastcall AbiturLogInsStrdPrcCalcFields (TDataSet * DataSet);
    void __fastcall FIOSearchDSDataChange         (
            TObject * Sender,
            TField  * Field
        );
    void __fastcall Increment_GroupTableNewRecord (TDataSet * DataSet);
    void __fastcall QAbituraAfterInsert           (TDataSet * DataSet);
    void __fastcall QAbituraCalcFields            (TDataSet * DataSet);
    void __fastcall QAdd_N_GroupCalcFields        (TDataSet * DataSet);
    void __fastcall QCenterCalcFields             (TDataSet * DataSet);
    void __fastcall QExamCalcFields               (TDataSet * DataSet);
    void __fastcall QLittle_Spisoc_GRCalcFields   (TDataSet * DataSet);
    void __fastcall QReport_RaspCalcFields        (TDataSet * DataSet);
    void __fastcall QSertificat_ResCalcFields     (TDataSet * DataSet);
    void __fastcall QSertificatCalcFields         (TDataSet * DataSet);
    void __fastcall QSpisoc_GroupCalcFields       (TDataSet * DataSet);
    void __fastcall QSpisok_SpecCalcFields        (TDataSet * DataSet);
    void __fastcall QToDekanatAfterInsert         (TDataSet * DataSet);
    // void __fastcall RxLoginDialog1CheckUser       (
    //               TObject    * Sender,
    //         const AnsiString   UserName,
    //         const AnsiString   Password,
    //               bool       & AllowLogin
    //     );
    void __fastcall TCategoryNewRecord            (TDataSet * DataSet);
    void __fastcall TCkNewRecord                  (TDataSet * DataSet);
    void __fastcall TDocumNewRecord               (TDataSet * DataSet);
    void __fastcall TFacultyNewRecord             (TDataSet * DataSet);
    void __fastcall TFoundationNewRecord          (TDataSet * DataSet);
    void __fastcall TKol_PlaceCalcFields          (TDataSet * DataSet);
    void __fastcall TKol_PlaceNewRecord           (TDataSet * DataSet);
    void __fastcall TPredmetNewRecord             (TDataSet * DataSet);
    void __fastcall TRegionAfterOpen              (TDataSet * DataSet);
    void __fastcall TRegionNewRecord              (TDataSet * DataSet);
    void __fastcall TVid_SportNewRecord           (TDataSet * DataSet);
private:
public:
    virtual __fastcall TDM (TComponent * AOwner);

    double                ball_result        (                                  // функция, которая возвращает результат сертификата
            int b,
            int f
        );
    float                 ball_result_float  (
            int b,
            int predmet,
            int rus_bel,
            int k
        );
    AnsiString            get_version        ();                                // функция возвращает версию программы
    String                NumDelaString      (                                  // функция возвращает составной номер дела
            int vid_edu,
            int term_edu,
            int price,
            int nom_dela
        );
    void       __fastcall vozvrat_inc_ab     ();                                // функция возвращает инкремент номера абитуриента
    void       __fastcall vozvrat_inc_people ();                                // функция возвращает инкремент номера  студента
    AnsiString            vozvrat_spec       (int spec);                        // функция возвращает название направления специальности


    bool printdlg;
    int  ID_from_QUEUE;                                                         // ID  с очереди
};

extern PACKAGE TDM * DM;

#endif  // DM_UNIT_H