
@startuml Priv_EnterUnit.cpp

title Исходный файл: "Priv_EnterUnit.cpp"

scale 750 width

"<b>TPriv_EnterForm</b>" -up-|> "<b>TForm</b>"

hide "<b>TForm</b>" members

class "<b>TPriv_EnterForm</b>"
{
    + BitBtn1 \t\t: <i>TBitBtn *</i>
    + BitBtn2 \t\t: <i>TBitBtn *</i>
    + BitBtn3 \t\t: <i>TBitBtn *</i>
    + BitBtn4 \t\t: <i>TBitBtn *</i>
    + BitBtn5 \t\t: <i>TBitBtn *</i>
    ..
    + DBGrid1 \t: <i>TDBGrid *</i>
    ..
    + DBText1 \t: <i>TDBText *</i>
    + DBText2 \t: <i>TDBText *</i>
    + DBText3 \t: <i>TDBText *</i>
    ..
    + Panel1 \t\t: <i>TPanel *</i>
    + Panel2 \t\t: <i>TPanel *</i>
    + Panel3 \t\t: <i>TPanel *</i>
    --
    
    + <b>TPriv_EnterForm \t(Owner \t: <i>TComponent *</i>)</b>

    + BitBtn1Click \t\t(Sender \t: <i>TObject *</i>) : <i>void</i>
    + BitBtn2Click \t\t(Sender \t: <i>TObject *</i>) : <i>void</i>
    + BitBtn3Click \t\t(Sender \t: <i>TObject *</i>) : <i>void</i>
    + BitBtn4Click \t\t(Sender \t: <i>TObject *</i>) : <i>void</i>
    + BitBtn5Click \t\t(Sender \t: <i>TObject *</i>) : <i>void</i>
    + FormActivate \t(Sender \t: <i>TObject *</i>) : <i>void</i>
    ..
    + FormClose \t\t(
            \t\tSender \t: <i>TObject *</i>,
            \t\tAction \t: <i>TCloseAction &</i>
        \t) : <i>void</i>
}


package TPriv_EnterForm <<Folder>>
{
    class TPriv_EnterForm
    hide  TPriv_EnterForm members
}


' note right of "<b>TPriv_EnterForm</b>"::Save_Priv
' сохранение привелегий (сирота, Чаэс, инвалид)
' end note

@enduml