@startuml DMStatUnit.cpp

title Исходный файл: "DMStatUnit.cpp"

scale 750 width

class "<b>TDMStat</b>"
{
    <b>SHOWS ONLY FIELDS</b>\n (For methods, see: class_DMStatUnit)
    --
    + DSCount_Ball_Examen \t\t\t\t\t\t: <i>TDataSource *</i>
    + DSCount_CK \t\t\t\t\t\t\t\t\t: <i>TDataSource *</i>
    + DSCount_Diplom \t\t\t\t\t\t\t\t: <i>TDataSource *</i>
    + DSCount_Gimn \t\t\t\t\t\t\t\t: <i>TDataSource *</i>
    + DSCount_Gorod \t\t\t\t\t\t\t\t: <i>TDataSource *</i>
    + DSCount_Medal \t\t\t\t\t\t\t\t: <i>TDataSource *</i>
    + DSCount_Olimp \t\t\t\t\t\t\t\t: <i>TDataSource *</i>
    + DSCount_Platn \t\t\t\t\t\t\t\t: <i>TDataSource *</i>
    + DSCount_PO \t\t\t\t\t\t\t\t\t: <i>TDataSource *</i>
    + DSCount_Region \t\t\t\t\t\t\t\t: <i>TDataSource *</i>
    + DSCount_special_ab \t\t\t\t\t\t\t: <i>TDataSource *</i>
    + DSCount_Selo \t\t\t\t\t\t\t\t: <i>TDataSource *</i>
    + DSCount_Stag \t\t\t\t\t\t\t\t: <i>TDataSource *</i>
    + DSCount_Test \t\t\t\t\t\t\t\t: <i>TDataSource *</i>
    + DSF1kKol \t\t\t\t\t\t\t\t\t: <i>TDataSource *</i>
    + DSF1kAb \t\t\t\t\t\t\t\t\t: <i>TDataSource *</i>
    + DSProtokol \t\t\t\t\t\t\t\t\t: <i>TDataSource *</i>
    + DSQSpecial \t\t\t\t\t\t\t\t\t: <i>TDataSource *</i>
    + DSQ_GK_All \t\t\t\t\t\t\t\t\t: <i>TDataSource *</i>
    + DSQ_GK_Konkurs \t\t\t\t\t\t\t: <i>TDataSource *</i>
    + DSQ_GK_Medal \t\t\t\t\t\t\t\t: <i>TDataSource *</i>
    + DSQ_GK_Plan \t\t\t\t\t\t\t\t: <i>TDataSource *</i>
    + DSQ_GK_Plan_CK \t\t\t\t\t\t\t\t: <i>TDataSource *</i>
    + DSQCount_Ball_Rus_Bel_old \t\t\t\t\t: <i>TDataSource *</i>
    + DSQCount_Ball_Rus_Bel \t\t\t\t\t\t: <i>TDataSource *</i>
    + DSQF2_All_Sdal \t\t\t\t\t\t\t\t: <i>TDataSource *</i>
    + DSQF2_Sdal \t\t\t\t\t\t\t\t\t: <i>TDataSource *</i>
    + DSQF2_Zach \t\t\t\t\t\t\t\t\t: <i>TDataSource *</i>
    + DSQF2_CK \t\t\t\t\t\t\t\t\t: <i>TDataSource *</i>
    + DSRegion_Stat \t\t\t\t\t\t\t\t: <i>TDataSource *</i>
    + DSSpecial \t\t\t\t\t\t\t\t\t: <i>TDataSource *</i>
    + DSSvod_Ved \t\t\t\t\t\t\t\t\t: <i>TDataSource *</i>
    + DSSvod_Ved2 \t\t\t\t\t\t\t\t: <i>TDataSource *</i>
    + DSSport_Categ \t\t\t\t\t\t\t\t: <i>TDataSource *</i>
    ..
    + Giaz01SP \t\t\t\t\t\t\t\t\t: <i>TFDStoredProc *</i>
    + GIAZ021SP \t\t\t\t\t\t\t\t\t: <i>TFDStoredProc *</i>
    + Giaz022SP \t\t\t\t\t\t\t\t\t: <i>TFDStoredProc *</i>
    ..
    + CitizenQr \t\t\t\t\t\t\t\t\t: <i>TFDQuery *</i>
    + FullGrpS1Qr \t\t\t\t\t\t\t\t\t: <i>TFDQuery *</i>
    + LastLogQr \t\t\t\t\t\t\t\t\t: <i>TFDQuery *</i>
    + ProtokolAllQr \t\t\t\t\t\t\t\t: <i>TFDQuery *</i>
    + ProtokolCkQr \t\t\t\t\t\t\t\t: <i>TFDQuery *</i>
    + ProtokolQr \t\t\t\t\t\t\t\t\t: <i>TFDQuery *</i>
    + Q_GK_All \t\t\t\t\t\t\t\t\t: <i>TFDQuery *</i>
    + Q_GK_Konkurs \t\t\t\t\t\t\t\t: <i>TFDQuery *</i>
    + Q_GK_Medal \t\t\t\t\t\t\t\t\t: <i>TFDQuery *</i>
    + Q_GK_Plan \t\t\t\t\t\t\t\t\t: <i>TFDQuery *</i>
    + Q_GK_Plan_CK \t\t\t\t\t\t\t\t: <i>TFDQuery *</i>
    + QBall_prohod \t\t\t\t\t\t\t\t: <i>TFDQuery *</i>
    + QCount_Ball \t\t\t\t\t\t\t\t\t: <i>TFDQuery *</i>
    + QCount_Ball_Examen \t\t\t\t\t\t\t: <i>TFDQuery *</i>
    + QCount_Ball_Rus_Bel \t\t\t\t\t\t\t: <i>TFDQuery *</i>
    + QCount_Ball_Rus_Bel_old \t\t\t\t\t\t: <i>TFDQuery *</i>
    + QCount_CK \t\t\t\t\t\t\t\t\t: <i>TFDQuery *</i>
    + QCount_Gimn \t\t\t\t\t\t\t\t: <i>TFDQuery *</i>
    + QCount_Gorod \t\t\t\t\t\t\t\t: <i>TFDQuery *</i>
    + QCount_Diplom \t\t\t\t\t\t\t\t: <i>TFDQuery *</i>
    + QCount_High \t\t\t\t\t\t\t\t: <i>TFDQuery *</i>
    + QCount_Medal \t\t\t\t\t\t\t\t: <i>TFDQuery *</i>
    + QCount_Olimp \t\t\t\t\t\t\t\t: <i>TFDQuery *</i>
    + QCount_Platn \t\t\t\t\t\t\t\t: <i>TFDQuery *</i>
    + QCount_PO \t\t\t\t\t\t\t\t\t: <i>TFDQuery *</i>
    + QCount_Region \t\t\t\t\t\t\t\t: <i>TFDQuery *</i>
    + QCount_RUOR \t\t\t\t\t\t\t\t: <i>TFDQuery *</i>
    + QCount_Stag \t\t\t\t\t\t\t\t: <i>TFDQuery *</i>
    + QCount_Selo \t\t\t\t\t\t\t\t: <i>TFDQuery *</i>
    + QCount_special_ab \t\t\t\t\t\t\t: <i>TFDQuery *</i>
    + QCount_Test \t\t\t\t\t\t\t\t: <i>TFDQuery *</i>
    + QCount_VK \t\t\t\t\t\t\t\t\t: <i>TFDQuery *</i>
    + QCountAll \t\t\t\t\t\t\t\t\t: <i>TFDQuery *</i>
    + QCountSpecNapravl \t\t\t\t\t\t\t: <i>TFDQuery *</i>
    + QF1kAb \t\t\t\t\t\t\t\t\t\t: <i>TFDQuery *</i>
    + QF1kKol \t\t\t\t\t\t\t\t\t: <i>TFDQuery *</i>
    + QF2_All_Sdal \t\t\t\t\t\t\t\t\t: <i>TFDQuery *</i>
    + QF2_CK \t\t\t\t\t\t\t\t\t\t: <i>TFDQuery *</i>
    + QF2_Sdal \t\t\t\t\t\t\t\t\t: <i>TFDQuery *</i>
    + QF2_Zach \t\t\t\t\t\t\t\t\t: <i>TFDQuery *</i>
    + QProtokol \t\t\t\t\t\t\t\t\t: <i>TFDQuery *</i>
    + QRegion_Stat \t\t\t\t\t\t\t\t: <i>TFDQuery *</i>
    + QSpec_Dir \t\t\t\t\t\t\t\t\t: <i>TFDQuery *</i>
    + QSpecial \t\t\t\t\t\t\t\t\t: <i>TFDQuery *</i>
    + QSpecializ_for_Spec \t\t\t\t\t\t\t: <i>TFDQuery *</i>
    + QSpecializ_for_Spec_Dir \t\t\t\t\t\t: <i>TFDQuery *</i>
    + QSport_Categ \t\t\t\t\t\t\t\t: <i>TFDQuery *</i>
    + QSvod_Ved \t\t\t\t\t\t\t\t\t: <i>TFDQuery *</i>
    + QSvod_Ved2 \t\t\t\t\t\t\t\t\t: <i>TFDQuery *</i>
    + QZachisl_Sertificat \t\t\t\t\t\t\t: <i>TFDQuery *</i>
    ..
    + TSpecial \t\t\t\t\t\t\t\t\t: <i>TFDTable *</i>
    ..
    + QBall_prohodMIN \t\t\t\t\t\t\t\t: <i>TFloatField *</i>
    ..
    + Giaz01SPS_3S \t\t\t\t\t\t\t\t: <i>TIntegerField *</i>
    + Giaz01SPS_B_ALL \t\t\t\t\t\t\t: <i>TIntegerField *</i>
    + Giaz01SPS_B_CK \t\t\t\t\t\t\t\t: <i>TIntegerField *</i>
    + Giaz01SPS_B_2 \t\t\t\t\t\t\t\t: <i>TIntegerField *</i>
    + Giaz01SPS_P \t\t\t\t\t\t\t\t: <i>TIntegerField *</i>
    + GIAZ021SPS_16 \t\t\t\t\t\t\t\t: <i>TIntegerField *</i>
    + GIAZ021SPS_17 \t\t\t\t\t\t\t\t: <i>TIntegerField *</i>
    + GIAZ021SPS_ALL \t\t\t\t\t\t\t\t: <i>TIntegerField *</i>
    + Giaz022SPS_21 \t\t\t\t\t\t\t\t: <i>TIntegerField *</i>
    + Giaz022SPS_22_26 \t\t\t\t\t\t\t: <i>TIntegerField *</i>
    + Giaz022SPS_27 \t\t\t\t\t\t\t\t: <i>TIntegerField *</i>
    + Giaz022SPS_ALL \t\t\t\t\t\t\t\t: <i>TIntegerField *</i>
    + LastLogQrID_LOG \t\t\t\t\t\t\t: <i>TIntegerField *</i>
    + ProtokolCkQrNOMER_AB \t\t\t\t\t\t: <i>TIntegerField *</i>
    + ProtokolQrNOMER_AB \t\t\t\t\t\t: <i>TIntegerField *</i>
    + Q_GK_AllCOUNT \t\t\t\t\t\t\t\t: <i>TIntegerField *</i>
    + Q_GK_KonkursCOUNT \t\t\t\t\t\t\t: <i>TIntegerField *</i>
    + Q_GK_MedalCOUNT \t\t\t\t\t\t\t: <i>TIntegerField *</i>
    + Q_GK_Plan_CKSUM \t\t\t\t\t\t\t: <i>TIntegerField *</i>
    + Q_GK_PlanSUM \t\t\t\t\t\t\t\t: <i>TIntegerField *</i>
    + QCount_BallN_YA \t\t\t\t\t\t\t\t: <i>TIntegerField *</i>
    + QCount_BallN0 \t\t\t\t\t\t\t\t: <i>TIntegerField *</i>
    + QCount_BallN1 \t\t\t\t\t\t\t\t: <i>TIntegerField *</i>
    + QCount_BallN2 \t\t\t\t\t\t\t\t: <i>TIntegerField *</i>
    + QCount_BallN3_2 \t\t\t\t\t\t\t\t: <i>TIntegerField *</i>
    + QCount_BallN4_3 \t\t\t\t\t\t\t\t: <i>TIntegerField *</i>
    + QCount_BallN5_4 \t\t\t\t\t\t\t\t: <i>TIntegerField *</i>
    + QCount_BallN6_5 \t\t\t\t\t\t\t\t: <i>TIntegerField *</i>
    + QCount_BallN7_6 \t\t\t\t\t\t\t\t: <i>TIntegerField *</i>
    + QCount_BallN8_7 \t\t\t\t\t\t\t\t: <i>TIntegerField *</i>
    + QCount_BallN9_8 \t\t\t\t\t\t\t\t: <i>TIntegerField *</i>
    + QCount_BallN10_9 \t\t\t\t\t\t\t: <i>TIntegerField *</i>
    + QCount_Ball_ExamenCOUNT \t\t\t\t\t: <i>TIntegerField *</i>
    + QCount_Ball_Rus_BelCOUNT \t\t\t\t\t: <i>TIntegerField *</i>
    + QCount_Ball_Rus_Bel_oldCOUNT \t\t\t\t: <i>TIntegerField *</i>
    + QCount_CKCOUNT \t\t\t\t\t\t\t: <i>TIntegerField *</i>
    + QCount_DiplomCOUNT \t\t\t\t\t\t: <i>TIntegerField *</i>
    + QCount_GimnCOUNT \t\t\t\t\t\t\t: <i>TIntegerField *</i>
    + QCount_GorodCOUNT \t\t\t\t\t\t\t: <i>TIntegerField *</i>
    + QCount_HighCOUNT \t\t\t\t\t\t\t: <i>TIntegerField *</i>
    + QCount_MedalCOUNT \t\t\t\t\t\t\t: <i>TIntegerField *</i>
    + QCount_OlimpCOUNT \t\t\t\t\t\t\t: <i>TIntegerField *</i>
    + QCount_PlatnCOUNT \t\t\t\t\t\t\t: <i>TIntegerField *</i>
    + QCount_POCOUNT \t\t\t\t\t\t\t: <i>TIntegerField *</i>
    + QCount_RegionCOUNT \t\t\t\t\t\t: <i>TIntegerField *</i>
    + QCount_RUORCOUNT \t\t\t\t\t\t\t: <i>TIntegerField *</i>
    + QCount_SeloCOUNT \t\t\t\t\t\t\t: <i>TIntegerField *</i>
    + QCount_special_abCOUNT \t\t\t\t\t\t: <i>TIntegerField *</i>
    + QCount_StagCOUNT \t\t\t\t\t\t\t: <i>TIntegerField *</i>
    + QCount_TestCOUNT \t\t\t\t\t\t\t: <i>TIntegerField *</i>
    + QCount_VKCOUNT \t\t\t\t\t\t\t: <i>TIntegerField *</i>
    + QCountAllCOUNT \t\t\t\t\t\t\t\t: <i>TIntegerField *</i>
    + QCountSpecNapravlSUM \t\t\t\t\t\t: <i>TIntegerField *</i>
    + QF1kAbCOUNT_NOMER_AB \t\t\t\t\t: <i>TIntegerField *</i>
    + QF1kKolSUM_KOL_PLACE \t\t\t\t\t\t: <i>TIntegerField *</i>
    + QF2_All_SdalCOUNT \t\t\t\t\t\t\t: <i>TIntegerField *</i>
    + QF2_CKCOUNT \t\t\t\t\t\t\t\t: <i>TIntegerField *</i>
    + QF2_SdalCOUNT \t\t\t\t\t\t\t\t: <i>TIntegerField *</i>
    + QF2_ZachCOUNT \t\t\t\t\t\t\t\t: <i>TIntegerField *</i>
    + QRegion_StatCOUNT \t\t\t\t\t\t\t: <i>TIntegerField *</i>
    + QSpec_DirN_SPEC \t\t\t\t\t\t\t: <i>TIntegerField *</i>
    + QSpec_DirN_SPEC_DIR \t\t\t\t\t\t: <i>TIntegerField *</i>
    + QSpecializ_for_Spec_DirN_SPEC_DIR \t\t\t: <i>TIntegerField *</i>
    + QSpecializ_for_SpecN_SPEC_DIR \t\t\t\t: <i>TIntegerField *</i>
    + QZachisl_SertificatNOMER_AB \t\t\t\t\t: <i>TIntegerField *</i>
    ..
    + QSport_CategCOUNT \t\t\t\t\t\t\t: <i>TLargeintField *</i>
    ..
    + FullGrpS1QrCATEGORY_IF \t\t\t\t\t\t: <i>TSmallintField *</i>
    + FullGrpS1QrCITIZENSHIP \t\t\t\t\t\t: <i>TSmallintField *</i>
    + FullGrpS1QrKONKURS \t\t\t\t\t\t\t: <i>TSmallintField *</i>
    + FullGrpS1QrN_SPORT_CATEGORY \t\t\t\t: <i>TSmallintField *</i>
    + FullGrpS1QrPRICE \t\t\t\t\t\t\t: <i>TSmallintField *</i>
    + FullGrpS1QrTERM_EDU \t\t\t\t\t\t: <i>TSmallintField *</i>
    + ProtokolAllQrTERM_EDU \t\t\t\t\t\t: <i>TSmallintField *</i>
    + ProtokolCkQrTERM_EDU \t\t\t\t\t\t: <i>TSmallintField *</i>
    + ProtokolQrCATEGORY_IF \t\t\t\t\t\t: <i>TSmallintField *</i>
    + ProtokolQrKONKURS \t\t\t\t\t\t\t: <i>TSmallintField *</i>
    + ProtokolQrNOM_DELA \t\t\t\t\t\t: <i>TSmallintField *</i>
    + ProtokolQrPRICE \t\t\t\t\t\t\t\t: <i>TSmallintField *</i>
    + ProtokolQrTERM_EDU \t\t\t\t\t\t\t: <i>TSmallintField *</i>
    + QCount_Ball_ExamenN_SPECIALIZ \t\t\t\t: <i>TSmallintField *</i>
    + QCount_Ball_ExamenVID_EDU \t\t\t\t\t: <i>TSmallintField *</i>
    + QCount_Ball_Rus_Bel_oldN_SPECIALIZ \t\t\t: <i>TSmallintField *</i>
    + QCount_Ball_Rus_Bel_oldVID_EDU \t\t\t\t: <i>TSmallintField *</i>
    + QCount_Ball_Rus_BelN_SPECIALIZ \t\t\t\t: <i>TSmallintField *</i>
    + QCount_Ball_Rus_BelVID_EDU \t\t\t\t\t: <i>TSmallintField *</i>
    + QCount_CKN_SPEC \t\t\t\t\t\t\t: <i>TSmallintField *</i>
    + QCount_DiplomN_SPEC \t\t\t\t\t\t: <i>TSmallintField *</i>
    + QCount_GimnN_SPEC \t\t\t\t\t\t\t: <i>TSmallintField *</i>
    + QCount_GorodN_SPEC \t\t\t\t\t\t: <i>TSmallintField *</i>
    + QCount_HighN_SPEC \t\t\t\t\t\t\t: <i>TSmallintField *</i>
    + QCount_MedalN_SPEC \t\t\t\t\t\t: <i>TSmallintField *</i>
    + QCount_OlimpN_SPEC \t\t\t\t\t\t: <i>TSmallintField *</i>
    + QCount_PlatnN_SPEC \t\t\t\t\t\t\t: <i>TSmallintField *</i>
    + QCount_PON_SPEC \t\t\t\t\t\t\t: <i>TSmallintField *</i>
    + QCount_RegionN_SPEC \t\t\t\t\t\t: <i>TSmallintField *</i>
    + QCount_RUORN_SPEC \t\t\t\t\t\t\t: <i>TSmallintField *</i>
    + QCount_SeloN_SPEC \t\t\t\t\t\t\t: <i>TSmallintField *</i>
    + QCount_special_abN_SPEC \t\t\t\t\t: <i>TSmallintField *</i>
    + QCount_special_abPRICE \t\t\t\t\t\t: <i>TSmallintField *</i>
    + QCount_StagN_SPEC \t\t\t\t\t\t\t: <i>TSmallintField *</i>
    + QCount_TestN_SPEC \t\t\t\t\t\t\t: <i>TSmallintField *</i>
    + QCountSpecNapravlTEXT \t\t\t\t\t\t: <i>TSmallintField *</i>
    + QF1kAbCOPY_AT \t\t\t\t\t\t\t\t: <i>TSmallintField *</i>
    + QF2_All_SdalN_SPEC \t\t\t\t\t\t\t: <i>TSmallintField *</i>
    + QF2_CKN_SPEC \t\t\t\t\t\t\t\t: <i>TSmallintField *</i>
    + QF2_SdalN_SPEC \t\t\t\t\t\t\t\t: <i>TSmallintField *</i>
    + QF2_ZachN_SPEC \t\t\t\t\t\t\t\t: <i>TSmallintField *</i>
    + QProtokolOUT_N_DEL \t\t\t\t\t\t\t: <i>TSmallintField *</i>
    + QRegion_StatKONKURS \t\t\t\t\t\t: <i>TSmallintField *</i>
    + QRegion_StatN_REGION \t\t\t\t\t\t: <i>TSmallintField *</i>
    + QRegion_StatN_SPECIALIZ \t\t\t\t\t: <i>TSmallintField *</i>
    + QSpecializ_for_Spec_DirN_FAC \t\t\t\t\t: <i>TSmallintField *</i>
    + QSpecializ_for_Spec_DirN_SPEC \t\t\t\t: <i>TSmallintField *</i>
    + QSpecializ_for_Spec_DirN_SPECIALIZ \t\t\t: <i>TSmallintField *</i>
    + QSpecializ_for_SpecN_FAC \t\t\t\t\t: <i>TSmallintField *</i>
    + QSpecializ_for_SpecN_SPEC \t\t\t\t\t: <i>TSmallintField *</i>
    + QSpecializ_for_SpecN_SPECIALIZ \t\t\t\t: <i>TSmallintField *</i>
    + QSpecialN_SPEC \t\t\t\t\t\t\t\t: <i>TSmallintField *</i>
    + QSport_CategN_SPECIALIZ \t\t\t\t\t: <i>TSmallintField *</i>
    + QZachisl_SertificatBALLS \t\t\t\t\t\t: <i>TSmallintField *</i>
    + QZachisl_SertificatKONKURS \t\t\t\t\t: <i>TSmallintField *</i>
    + QZachisl_SertificatN_FOUND \t\t\t\t\t: <i>TSmallintField *</i>
    + QZachisl_SertificatN_PREDMET \t\t\t\t: <i>TSmallintField *</i>
    + QZachisl_SertificatRUS_BEL \t\t\t\t\t: <i>TSmallintField *</i>
    + TSpecialN_SPEC \t\t\t\t\t\t\t\t: <i>TSmallintField *</i>
    + TSpecialOLD_NUM \t\t\t\t\t\t\t: <i>TSmallintField *</i>
    ..
    + CitizenQrNAME \t\t\t\t\t\t\t\t: <i>TStringField *</i>
    + ProtokolAllQrFAM \t\t\t\t\t\t\t: <i>TStringField *</i>
    + ProtokolAllQrNAME \t\t\t\t\t\t\t: <i>TStringField *</i>
    + ProtokolAllQrOTCH \t\t\t\t\t\t\t: <i>TStringField *</i>
    + ProtokolCkQrFAM \t\t\t\t\t\t\t: <i>TStringField *</i>
    + ProtokolCkQrNAME \t\t\t\t\t\t\t: <i>TStringField *</i>
    + ProtokolCkQrOTCH \t\t\t\t\t\t\t: <i>TStringField *</i>
    + ProtokolQrFAM \t\t\t\t\t\t\t\t: <i>TStringField *</i>
    + ProtokolQrNAME \t\t\t\t\t\t\t\t: <i>TStringField *</i>
    + ProtokolQrOTCH \t\t\t\t\t\t\t\t: <i>TStringField *</i>
    + QCount_Ball_ExamenBALL \t\t\t\t\t\t: <i>TStringField *</i>
    + QCount_Ball_Rus_BelBALL \t\t\t\t\t\t: <i>TStringField *</i>
    + QCount_Ball_Rus_Bel_oldBALL \t\t\t\t\t: <i>TStringField *</i>
    + QF1kAbFAC1 \t\t\t\t\t\t\t\t: <i>TStringField *</i>
    + QF1kAbSPECIAL \t\t\t\t\t\t\t\t: <i>TStringField *</i>
    + QF1kKolFAC1 \t\t\t\t\t\t\t\t: <i>TStringField *</i>
    + QF1kKolSPECIAL \t\t\t\t\t\t\t\t: <i>TStringField *</i>
    + QProtokolOUT_FAM \t\t\t\t\t\t\t: <i>TStringField *</i>
    + QProtokolOUT_NAME \t\t\t\t\t\t\t: <i>TStringField *</i>
    + QProtokolOUT_OTCH \t\t\t\t\t\t\t: <i>TStringField *</i>
    + QProtokolOUT_VK \t\t\t\t\t\t\t: <i>TStringField *</i>
    + QProtokolOUT_WITHOUT \t\t\t\t\t\t: <i>TStringField *</i>
    + QSpec_DirCODE_SPEC_DIR \t\t\t\t\t: <i>TStringField *</i>
    + QSpec_DirSPEC_DIR \t\t\t\t\t\t\t: <i>TStringField *</i>
    + QSpec_DirSPEC_DIR_FULL \t\t\t\t\t\t: <i>TStringField *</i>
    + QSpecialCODE_SPEC \t\t\t\t\t\t\t: <i>TStringField *</i>
    + QSpecializ_for_SpecCODE_SPECIALIZ \t\t\t: <i>TStringField *</i>
    + QSpecializ_for_SpecSPECIAL \t\t\t\t\t: <i>TStringField *</i>
    + QSpecializ_for_SpecSPECIAL_DIRECTION \t\t: <i>TStringField *</i>
    + QSpecializ_for_SpecSPECIAL_SKLON \t\t\t: <i>TStringField *</i>
    + QSpecializ_for_Spec_DirCODE_SPECIALIZ \t\t: <i>TStringField *</i>
    + QSpecializ_for_Spec_DirSPECIAL \t\t\t\t: <i>TStringField *</i>
    + QSpecializ_for_Spec_DirSPECIAL_DIRECTION \t: <i>TStringField *</i>
    + QSpecializ_for_Spec_DirSPECIAL_SKLON \t\t: <i>TStringField *</i>
    + QSpecialSPEC \t\t\t\t\t\t\t\t: <i>TStringField *</i>
    + QSport_CategSPORT_CATEGORY \t\t\t\t: <i>TStringField *</i>
    + QSport_CategSPEC1 \t\t\t\t\t\t\t: <i>TStringField *</i>
    + QZachisl_SertificatFAM \t\t\t\t\t\t: <i>TStringField *</i>
    + QZachisl_SertificatNAME \t\t\t\t\t\t: <i>TStringField *</i>
    + QZachisl_SertificatNOMER_S \t\t\t\t\t: <i>TStringField *</i>
    + QZachisl_SertificatOTCH \t\t\t\t\t\t: <i>TStringField *</i>
    + QZachisl_SertificatPASPORT \t\t\t\t\t: <i>TStringField *</i>
    + QZachisl_SertificatSERIA_S \t\t\t\t\t: <i>TStringField *</i>
    + QZachisl_SertificatTEXT_PREDMET \t\t\t\t: <i>TStringField *</i>
    + TSpecialCODE_SPEC \t\t\t\t\t\t\t: <i>TStringField *</i>
    + TSpecialSPEC \t\t\t\t\t\t\t\t: <i>TStringField *</i>
    --
    
    + <b>TDMStat (Owner \t: <i>TComponent *</i>)</b>

}


@enduml