@startuml DMUnit.cpp

title Исходный файл: "DMUnit.cpp"

scale 750 width


class "<b>TDM</b>"
{
    <b>SHOWS ONLY FIELDS</b>\n(For methods, see: class_DMUnit)
    --
    <b>START PART 3</b> (For others, see: class_DMUnit_all_fields 1, 2 and 4)
    --
    + QSelect_abN_PRIKAZ_INCLUDE \t\t\t: <i>TSmallintField *</i>
    + QSelect_abN_FOUND \t\t\t\t\t\t: <i>TSmallintField *</i>
    + QSelect_abN_REGION \t\t\t\t\t\t: <i>TSmallintField *</i>
    + QSelect_abCITIZENSHIP \t\t\t\t\t: <i>TSmallintField *</i>
    + QSelect_abN_PRIVILEGE_EXAM \t\t\t: <i>TSmallintField *</i>
    + QSelect_abN_CK \t\t\t\t\t\t\t: <i>TSmallintField *</i>
    + QSelect_abN_LANGVICH \t\t\t\t\t: <i>TSmallintField *</i>
    + QSelect_abLANGV_BALL \t\t\t\t\t: <i>TSmallintField *</i>
    + QSertificatN_PREDMET \t\t\t\t\t: <i>TSmallintField *</i>
    + QSertificatBALLS \t\t\t\t\t\t: <i>TSmallintField *</i>
    + QSertificatRUS_BEL \t\t\t\t\t\t: <i>TSmallintField *</i>
    + QSertificatPRICE \t\t\t\t\t\t\t: <i>TSmallintField *</i>
    + QSertificat_ex_listRUS_BEL \t\t\t\t: <i>TSmallintField *</i>
    + QSertificat_ResVID_EDU \t\t\t\t\t: <i>TSmallintField *</i>
    + QSertificat_ResN_FAC \t\t\t\t\t: <i>TSmallintField *</i>
    + QSertificat_ResRUS_BEL \t\t\t\t\t: <i>TSmallintField *</i>
    + QSertificat_ResN_PREDMET \t\t\t\t: <i>TSmallintField *</i>
    + QSertificat_ResBALLS \t\t\t\t\t: <i>TSmallintField *</i>
    + QShow_Result_ExamNOM_BALL \t\t\t: <i>TSmallintField *</i>
    + QShow_Result_ExamN_PREDMET \t\t\t: <i>TSmallintField *</i>
    + QShow_Result_ExamSTATUS_BALL \t\t\t: <i>TSmallintField *</i>
    + QShow_Result_ExamNOM_DELA \t\t\t: <i>TSmallintField *</i>
    + QSpecializN_SPECIALIZ \t\t\t\t\t: <i>TSmallintField *</i>
    + QSpecializN_FAC \t\t\t\t\t\t\t: <i>TSmallintField *</i>
    + QSpecializN_SPEC \t\t\t\t\t\t: <i>TSmallintField *</i>
    + QSpisoc_GroupN_SPECIALIZ \t\t\t\t: <i>TSmallintField *</i>
    + QSpisoc_GroupN_PRIVILEGE_EXAM \t\t\t: <i>TSmallintField *</i>
    + QSpisoc_GroupN_CK \t\t\t\t\t\t: <i>TSmallintField *</i>
    + QSpisoc_GroupVID_EDU \t\t\t\t\t: <i>TSmallintField *</i>
    + QSpisoc_GroupKONKURS \t\t\t\t\t: <i>TSmallintField *</i>
    + QSpisoc_GroupN_SPORT_CATEGORY \t\t: <i>TSmallintField *</i>
    + QSpisoc_GroupN_FAC \t\t\t\t\t\t: <i>TSmallintField *</i>
    + QSpisoc_GroupPRICE \t\t\t\t\t\t: <i>TSmallintField *</i>
    + QSpisok_SpecN_SPECIALIZ \t\t\t\t: <i>TSmallintField *</i>
    + QSpisok_SpecN_PRIVILEGE_EXAM \t\t\t: <i>TSmallintField *</i>
    + QSpisok_SpecN_CK \t\t\t\t\t\t: <i>TSmallintField *</i>
    + QSpisok_SpecVID_EDU \t\t\t\t\t: <i>TSmallintField *</i>
    + QSpisok_SpecKONKURS \t\t\t\t\t: <i>TSmallintField *</i>
    + QSpisok_SpecN_SPORT_CATEGORY \t\t: <i>TSmallintField *</i>
    + QSpisok_SpecN_FAC \t\t\t\t\t\t: <i>TSmallintField *</i>
    + QSpisok_SpecPRICE \t\t\t\t\t\t: <i>TSmallintField *</i>
    + QStatistic_Every_DayKONKURS \t\t\t: <i>TSmallintField *</i>
    + QStatistic_Every_DayN_SPECIALIZ \t\t\t: <i>TSmallintField *</i>
    + QStatistic_Every_DayVID_EDU \t\t\t\t: <i>TSmallintField *</i>
    + QPlan_Priem_All_SpecialN_SPEC \t\t\t: <i>TSmallintField *</i>
    + QPlan_Priem_All_SpecialVID_EDU \t\t\t: <i>TSmallintField *</i>
    + QPlan_Priem_CK_SpecialN_SPEC \t\t\t: <i>TSmallintField *</i>
    + QPlan_Priem_CK_SpecialVID_EDU \t\t\t: <i>TSmallintField *</i>
    + QPlan_Priem_Konk_SpecialN_SPEC \t\t\t: <i>TSmallintField *</i>
    + QPlan_Priem_Konk_SpecialTEXT \t\t\t: <i>TSmallintField *</i>
    + QSpecializPlan_PriemN_SPECIALIZ \t\t\t: <i>TSmallintField *</i>
    + QSpecializPlan_PriemN_SPEC \t\t\t\t: <i>TSmallintField *</i>
    + QAbituraID_TYPE \t\t\t\t\t\t\t: <i>TSmallintField *</i>
    + QSelect_abID_TYPE \t\t\t\t\t\t: <i>TSmallintField *</i>
    + QListDocToDekanatNAME_DOC \t\t\t: <i>TSmallintField *</i>
    + QSpisoc_Group_PolN_SPECIALIZ \t\t\t: <i>TSmallintField *</i>
    + QSpisoc_Group_PolN_PRIVILEGE_EXAM \t\t: <i>TSmallintField *</i>
    + QSpisoc_Group_PolN_CK \t\t\t\t\t: <i>TSmallintField *</i>
    + QSpisoc_Group_PolVID_EDU \t\t\t\t: <i>TSmallintField *</i>
    + QSpisoc_Group_PolKONKURS \t\t\t\t: <i>TSmallintField *</i>
    + QSpisoc_Group_PolN_SPORT_CATEGORY \t: <i>TSmallintField *</i>
    + QSpisoc_Group_PolN_FAC \t\t\t\t\t: <i>TSmallintField *</i>
    + QSpisoc_Group_PolPRICE \t\t\t\t\t: <i>TSmallintField *</i>
    + QAbituraDISABLED \t\t\t\t\t\t: <i>TSmallintField *</i>
    + QAbituraFLAT \t\t\t\t\t\t\t: <i>TSmallintField *</i>
    + QToDekanatFLAT \t\t\t\t\t\t: <i>TSmallintField *</i>
    + QSelect_abFLAT \t\t\t\t\t\t\t: <i>TSmallintField *</i>
    + QStatistic_Every_DayPRICE \t\t\t\t: <i>TSmallintField *</i>
    + QStatistic_Every_Day_BallKONKURS \t\t: <i>TSmallintField *</i>
    + QStatistic_Every_Day_BallPRICE \t\t\t: <i>TSmallintField *</i>
    + QStatistic_Every_Day_Ball_PriceKONKURS \t: <i>TSmallintField *</i>
    + QStatistic_Every_Day_SpecialKONKURS \t\t: <i>TSmallintField *</i>
    + QStatistic_Every_Day_SpecialN_SPEC \t\t: <i>TSmallintField *</i>
    + QStatistic_Every_Day_SpecialVID_EDU \t\t: <i>TSmallintField *</i>
    + QStatistic_Every_Day_SpecialPRICE \t\t: <i>TSmallintField *</i>
    + QStatisticEveryDayN_SPECIALIZ \t\t\t: <i>TSmallintField *</i>
    + QToDekanatN_FOUND \t\t\t\t\t: <i>TSmallintField *</i>
    + QToDekanatMARIAGE \t\t\t\t\t: <i>TSmallintField *</i>
    + QToDekanatEDUCATION \t\t\t\t\t: <i>TSmallintField *</i>
    + QToDekanatWHEN_EDUC \t\t\t\t\t: <i>TSmallintField *</i>
    + QToDekanatN_VID_SPORT \t\t\t\t\t: <i>TSmallintField *</i>
    + QToDekanatVID_EDU \t\t\t\t\t\t: <i>TSmallintField *</i>
    + QToDekanatN_FAC \t\t\t\t\t\t: <i>TSmallintField *</i>
    + QToDekanatKURS \t\t\t\t\t\t: <i>TSmallintField *</i>
    + QToDekanatN_SPEC \t\t\t\t\t\t: <i>TSmallintField *</i>
    + QToDekanatN_SPECIALIZ \t\t\t\t\t: <i>TSmallintField *</i>
    + QToDekanatSTATUS_PEOPLE \t\t\t\t: <i>TSmallintField *</i>
    + QToDekanatINC_GROUP \t\t\t\t\t: <i>TSmallintField *</i>
    + QToDekanatN_PRIKAZ_INCLUDE \t\t\t: <i>TSmallintField *</i>
    + QToDekanatN_PRIKAZ_KURS \t\t\t\t: <i>TSmallintField *</i>
    + QToDekanatVID_EDU_INCLUDE \t\t\t\t: <i>TSmallintField *</i>
    + QToDekanatN_FOUND_INCLUDE \t\t\t: <i>TSmallintField *</i>
    + QUndo_AbitSTATUS \t\t\t\t\t\t: <i>TSmallintField *</i>
    + RegCentrTblFLAG \t\t\t\t\t\t: <i>TSmallintField *</i>
    + RegCentrTblN_CENTRE \t\t\t\t\t: <i>TSmallintField *</i>
    + RegCentrTblN_REGION \t\t\t\t\t: <i>TSmallintField *</i>
    + SelectLogAbiturQrCATEGORY \t\t\t\t: <i>TSmallintField *</i>
    + SelectLogAbiturQrCITIZENSHIP \t\t\t: <i>TSmallintField *</i>
    + SelectLogAbiturQrKONKURS \t\t\t\t: <i>TSmallintField *</i>
    + SelectLogAbiturQrN_CK \t\t\t\t\t: <i>TSmallintField *</i>
    + SelectLogAbiturQrN_PRIKAZ_INCLUDE \t\t: <i>TSmallintField *</i>
    + SelectLogAbiturQrN_SPECIALIZ \t\t\t: <i>TSmallintField *</i>
    + SelectLogAbiturQrNOM_DELA \t\t\t\t: <i>TSmallintField *</i>
    + SelectLogAbiturQrNOM_DELA_1 \t\t\t: <i>TSmallintField *</i>
    + SelectLogAbiturQrTERM_EDU \t\t\t\t: <i>TSmallintField *</i>
    + SelPrivLogQrDAT_PRIV \t\t\t\t\t: <i>TSmallintField *</i>
    + SelPrivLogQrN_PRIV \t\t\t\t\t\t: <i>TSmallintField *</i>
    + SelPrivLogQrSEL_PRIV \t\t\t\t\t: <i>TSmallintField *</i>
    + SerteficatSelQrBALLS \t\t\t\t\t: <i>TSmallintField *</i>
    + SerteficatSelQrN_PREDMET \t\t\t\t: <i>TSmallintField *</i>
    + SerteficatSelQrRUS_BEL \t\t\t\t\t: <i>TSmallintField *</i>
    + SertSelLogQrBALLS \t\t\t\t\t\t: <i>TSmallintField *</i>
    + SertSelLogQrRUS_BEL \t\t\t\t\t: <i>TSmallintField *</i>
    + SpecFacQrN_SPECIALIZ \t\t\t\t\t: <i>TSmallintField *</i>
    + SpecializQrN_SPECIALIZ \t\t\t\t\t: <i>TSmallintField *</i>
    + SPFDQKOD_FAC \t\t\t\t\t\t\t: <i>TSmallintField *</i>
    + SPFDQN_FAC \t\t\t\t\t\t\t: <i>TSmallintField *</i>
    + SportQueryN_PRIKAZ_SPORT \t\t\t\t: <i>TSmallintField *</i>
    + SportQueryN_PRIKAZ_SUD \t\t\t\t: <i>TSmallintField *</i>
    + SportQueryN_VID_SPORT \t\t\t\t\t: <i>TSmallintField *</i>
    + SportQuerySPORT_CATEGORY \t\t\t\t: <i>TSmallintField *</i>
    + SportQuerySUD_CATEGORY \t\t\t\t: <i>TSmallintField *</i>
    + Stat3hAll1QrKONKURS \t\t\t\t\t: <i>TSmallintField *</i>
    + Stat3hAll2QrKONKURS \t\t\t\t\t: <i>TSmallintField *</i>
    + TBallNOM_BALL \t\t\t\t\t\t\t: <i>TSmallintField *</i>
    + TCategoryN_SPORT_CATEGORY \t\t\t: <i>TSmallintField *</i>
    + TCkCUSTOMER \t\t\t\t\t\t\t: <i>TSmallintField *</i>
    + TCkKOL_P \t\t\t\t\t\t\t\t: <i>TSmallintField *</i>
    + TCkN_CK \t\t\t\t\t\t\t\t: <i>TSmallintField *</i>
    + TCkN_FAC \t\t\t\t\t\t\t\t: <i>TSmallintField *</i>
    + TCkN_REGION \t\t\t\t\t\t\t: <i>TSmallintField *</i>
    + TCkN_SPECIALIZ \t\t\t\t\t\t\t: <i>TSmallintField *</i>
    + TDocumN_DOC \t\t\t\t\t\t\t: <i>TSmallintField *</i>
    + TFacultyKOD_FAC \t\t\t\t\t\t: <i>TSmallintField *</i>
    + TFacultyN_FAC \t\t\t\t\t\t\t: <i>TSmallintField *</i>
    + TFoundationN_FOUND \t\t\t\t\t\t: <i>TSmallintField *</i>
    + TKol_PlaceKOL_PLACE \t\t\t\t\t: <i>TSmallintField *</i>
    + TKol_PlaceN_FAC \t\t\t\t\t\t\t: <i>TSmallintField *</i>
    + TKol_PlaceN_KOL_PLACE \t\t\t\t\t: <i>TSmallintField *</i>
    + TKol_PlaceN_SPECIALIZ \t\t\t\t\t: <i>TSmallintField *</i>
    + TKol_PlacePRICE \t\t\t\t\t\t\t: <i>TSmallintField *</i>
    + TKol_PlaceTEXT \t\t\t\t\t\t\t: <i>TSmallintField *</i>
    + TKol_PlaceVID_EDU \t\t\t\t\t\t: <i>TSmallintField *</i>
    + TPass_UserN_FAC \t\t\t\t\t\t\t: <i>TSmallintField *</i>
    + TPredmetN_PREDMET \t\t\t\t\t: <i>TSmallintField *</i>
    + TRegionN_REGION \t\t\t\t\t\t: <i>TSmallintField *</i>
    + TVid_SportN_VID_SPORT \t\t\t\t\t: <i>TSmallintField *</i>
    + WithoutDetQrID_DET \t\t\t\t\t\t: <i>TSmallintField *</i>
    + WithoutDetQrN_ITEM \t\t\t\t\t\t: <i>TSmallintField *</i>
    + WithoutQrID_PRIV \t\t\t\t\t\t: <i>TSmallintField *</i>
    + WithoutQrN_WITHOUT_TESTS \t\t\t\t: <i>TSmallintField *</i>
    ..
    + BlockQNOTE \t\t\t\t\t\t\t\t: <i>TStringField *</i>
    + BlockQNOTE_PEREPODACHA \t\t\t\t: <i>TStringField *</i>
    + CkRegionQrCENTRE \t\t\t\t\t\t: <i>TStringField *</i>
    + CntrExrcTblEXERC2 \t\t\t\t\t\t: <i>TStringField *</i>
    + CntrExrcTblPOL \t\t\t\t\t\t\t: <i>TStringField *</i>
    + CntrExrcTblSPECIALIZ_N \t\t\t\t\t: <i>TStringField *</i>
    + CntrlExrcQrNAME_EXERC \t\t\t\t\t: <i>TStringField *</i>
    + ContrySelQrNAME \t\t\t\t\t\t: <i>TStringField *</i>
    + CountryQrFULL_NAME \t\t\t\t\t\t: <i>TStringField *</i>
    + CountryQrSHORT_NAME \t\t\t\t\t: <i>TStringField *</i>
    + DocumFDQTEXT_DOC \t\t\t\t\t: <i>TStringField *</i>
    + FIOSearchQrFAM \t\t\t\t\t\t\t: <i>TStringField *</i>
    + FIOSearchQrFIO \t\t\t\t\t\t\t: <i>TStringField *</i>
    + FIOSearchQrNAME \t\t\t\t\t\t: <i>TStringField *</i>
    + FIOSearchQrOTCH \t\t\t\t\t\t: <i>TStringField *</i>
    + GrazdanToDekanatQrNAME \t\t\t\t: <i>TStringField *</i>
    + Increment_GroupTableN_GROUP \t\t\t: <i>TStringField *</i>
    + InfQrNAME_PRIV \t\t\t\t\t\t\t: <i>TStringField *</i>
    + KodSpecializQrCODE_SPEC_DIR \t\t\t: <i>TStringField *</i>
    + LangSelQrLANGV \t\t\t\t\t\t\t: <i>TStringField *</i>
    + ListDocFDQDOC_INDEX \t\t\t\t\t: <i>TStringField *</i>
    + ListDocFDQTEXT_DOC \t\t\t\t\t: <i>TStringField *</i>
    + OtherPrivQrSHORT_NAME \t\t\t\t\t: <i>TStringField *</i>
    + OutDetQrNAME_DETAIS \t\t\t\t\t: <i>TStringField *</i>
    + OutQrNAME_PRIV \t\t\t\t\t\t: <i>TStringField *</i>
    + OutTestQrSHORT_NAME \t\t\t\t\t: <i>TStringField *</i>
    + OutTestQrSHORT_NAME_1 \t\t\t\t: <i>TStringField *</i>
    + PasportFDQNUMBER \t\t\t\t\t\t: <i>TStringField *</i>
    + PasportFDQPERSONAL_NUMBER \t\t\t: <i>TStringField *</i>
    + PasportFDQSERIES \t\t\t\t\t\t: <i>TStringField *</i>
    + PasportFDQWHO_GIVE \t\t\t\t\t: <i>TStringField *</i>
    + PrintDocQrFAM \t\t\t\t\t\t\t: <i>TStringField *</i>
    + PrintDocQrNAME \t\t\t\t\t\t\t: <i>TStringField *</i>
    + PrintDocQrOTCH \t\t\t\t\t\t\t: <i>TStringField *</i>
    + QAbFIOPolFAM \t\t\t\t\t\t\t: <i>TStringField *</i>
    + QAbFIOPolNAME \t\t\t\t\t\t\t: <i>TStringField *</i>
    + QAbFIOPolOTCH \t\t\t\t\t\t\t: <i>TStringField *</i>
    + QAbFIOPolPOL \t\t\t\t\t\t\t: <i>TStringField *</i>
    + QAb_PNOM_GROUP_DO \t\t\t\t\t: <i>TStringField *</i>
    + QAb_PNOM_GROUP_PO \t\t\t\t\t: <i>TStringField *</i>
    + QAb_Pr_EnterTEXT_PR_EN1 \t\t\t\t: <i>TStringField *</i>
    + QAbitur_Priv_EnterPRIV_ENTER1 \t\t\t: <i>TStringField *</i>
    + QAbituraADDRESS_BEFORE \t\t\t\t: <i>TStringField *</i>
    + QAbituraADDRESS_LIFE \t\t\t\t\t: <i>TStringField *</i>
    + QAbituraADDRESS_MAMA \t\t\t\t\t: <i>TStringField *</i>
    + QAbituraADDRESS_PAPA \t\t\t\t\t: <i>TStringField *</i>
    + QAbituraFAM \t\t\t\t\t\t\t: <i>TStringField *</i>
    + QAbituraGRAGDAN \t\t\t\t\t\t: <i>TStringField *</i>
    + QAbituraHOUSE \t\t\t\t\t\t\t: <i>TStringField *</i>
    + QAbituraKONKURS1 \t\t\t\t\t\t: <i>TStringField *</i>
    + QAbituraMAMA \t\t\t\t\t\t\t: <i>TStringField *</i>
    + QAbituraNAME \t\t\t\t\t\t\t: <i>TStringField *</i>
    + QAbituraNAME_EDU_MIDDLE \t\t\t\t: <i>TStringField *</i>
    + QAbituraNAME_EDU_SPEC \t\t\t\t\t: <i>TStringField *</i>
    + QAbituraNOM_ATTEST \t\t\t\t\t: <i>TStringField *</i>
    + QAbituraNOM_DELA1 \t\t\t\t\t\t: <i>TStringField *</i>
    + QAbituraNOM_DIPLOM \t\t\t\t\t: <i>TStringField *</i>
    + QAbituraNOM_GROUP \t\t\t\t\t\t: <i>TStringField *</i>
    + QAbituraORGAN_V \t\t\t\t\t\t: <i>TStringField *</i>
    + QAbituraOTCH \t\t\t\t\t\t\t: <i>TStringField *</i>
    + QAbituraPAPA \t\t\t\t\t\t\t: <i>TStringField *</i>
    + QAbituraPASPORT \t\t\t\t\t\t: <i>TStringField *</i>
    + QAbituraPERSONAL_NOMER \t\t\t\t: <i>TStringField *</i>
    + QAbituraPHONE \t\t\t\t\t\t\t: <i>TStringField *</i>
    + QAbituraPLACE_R \t\t\t\t\t\t: <i>TStringField *</i>
    + QAbituraPOL \t\t\t\t\t\t\t: <i>TStringField *</i>
    + QAbituraPRICE1 \t\t\t\t\t\t\t: <i>TStringField *</i>
    + QAbituraSPECIALIZ1 \t\t\t\t\t\t: <i>TStringField *</i>
    + QAbituraWHERE_EDU_MIDDLE \t\t\t\t: <i>TStringField *</i>
    + QAbituraWHERE_EDU_SPEC \t\t\t\t: <i>TStringField *</i>
    + QAbituraWORK_BEFORE \t\t\t\t\t: <i>TStringField *</i>
    + QAbituraWORK_MAMA \t\t\t\t\t: <i>TStringField *</i>
    + QAbituraWORK_PAPA \t\t\t\t\t\t: <i>TStringField *</i>
    + QAdd_N_GroupDESCRIBE \t\t\t\t\t: <i>TStringField *</i>
    + QAdd_N_GroupNOM_GROUP \t\t\t\t: <i>TStringField *</i>
    + QAdd_N_GroupSPEC1 \t\t\t\t\t\t: <i>TStringField *</i>
    + QAdd_N_GroupVID_EDU1 \t\t\t\t\t: <i>TStringField *</i>
    + QAdressNAME_DISTRICT \t\t\t\t\t: <i>TStringField *</i>
    + QAdressNAME_LOCALITY \t\t\t\t\t: <i>TStringField *</i>
    + QAdressNAME_TYPE \t\t\t\t\t\t: <i>TStringField *</i>
    + QAdressTYPE \t\t\t\t\t\t\t: <i>TStringField *</i>
    + QCenterCENTRE \t\t\t\t\t\t\t: <i>TStringField *</i>
    + QCenterFLAG1 \t\t\t\t\t\t\t: <i>TStringField *</i>
    + QCkCUSTOMER_PLACE \t\t\t\t\t: <i>TStringField *</i>
    + QCkTEXT_DEP \t\t\t\t\t\t\t: <i>TStringField *</i>
    + QControl_ExercNAME_EXERC \t\t\t\t: <i>TStringField *</i>
    + QDistrictNAME_DISTRICT \t\t\t\t\t: <i>TStringField *</i>
    + QExamBALL1 \t\t\t\t\t\t\t: <i>TStringField *</i>
    + QExamFAM \t\t\t\t\t\t\t\t: <i>TStringField *</i>
    + QExamNAME \t\t\t\t\t\t\t\t: <i>TStringField *</i>
    + QExamOTCH \t\t\t\t\t\t\t\t: <i>TStringField *</i>
    + QExamPREDM \t\t\t\t\t\t\t: <i>TStringField *</i>
    + QExamSpecBALL1 \t\t\t\t\t\t: <i>TStringField *</i>
    + QExamSpecFAM \t\t\t\t\t\t\t: <i>TStringField *</i>
    + QExamSpecNAME \t\t\t\t\t\t: <i>TStringField *</i>
    + QExamSpecOTCH \t\t\t\t\t\t: <i>TStringField *</i>
    + QExamSpecPOL \t\t\t\t\t\t\t: <i>TStringField *</i>
    + QExamSpecPREDM \t\t\t\t\t\t: <i>TStringField *</i>
    + QExamSpecWITHOUT \t\t\t\t\t\t: <i>TStringField *</i>
    + QExamWITHOUT \t\t\t\t\t\t\t: <i>TStringField *</i>
    + QExerc_GrpNAME_EXERC \t\t\t\t\t: <i>TStringField *</i>
    + QGroup_CountNOM_GROUP \t\t\t\t: <i>TStringField *</i>
    + QIPGRUPPA \t\t\t\t\t\t\t\t: <i>TStringField *</i>
    + QIPIP \t\t\t\t\t\t\t\t\t: <i>TStringField *</i>
    + QIPIP_NAME \t\t\t\t\t\t\t\t: <i>TStringField *</i>
    + QInc_Gr_OldDESCRIBE \t\t\t\t\t: <i>TStringField *</i>
    + QInc_Gr_OldN_GROUP \t\t\t\t\t\t: <i>TStringField *</i>
    + QKod_FacFAC \t\t\t\t\t\t\t: <i>TStringField *</i>
    + QKod_SpecSPECIAL_DIRECTION \t\t\t: <i>TStringField *</i>
    + QLangvichLANGV \t\t\t\t\t\t\t: <i>TStringField *</i>
    + QLetterSourceADDRESS_BEFORE \t\t\t: <i>TStringField *</i>
    + QLetterSourceFAM \t\t\t\t\t\t: <i>TStringField *</i>
    + QLetterSourceNAME \t\t\t\t\t\t: <i>TStringField *</i>
    + QLetterSourceOTCH \t\t\t\t\t\t: <i>TStringField *</i>
    + QListDocToDekanatDOC_INDEX \t\t\t: <i>TStringField *</i>
    + QListDocToDekanatNOTE \t\t\t\t\t: <i>TStringField *</i>
    + QLittle_Spisoc_GRFAM \t\t\t\t\t: <i>TStringField *</i>
    + QLittle_Spisoc_GRNAME \t\t\t\t\t: <i>TStringField *</i>
    + QLittle_Spisoc_GROTCH \t\t\t\t\t: <i>TStringField *</i>
    + QLocalityNAME_LOCALITY \t\t\t\t\t: <i>TStringField *</i>
    + QN_groupDESCRIBE \t\t\t\t\t\t: <i>TStringField *</i>
    + QN_groupNOM_GROUP \t\t\t\t\t: <i>TStringField *</i>
    + QNoticeFIOADDRESS_BEFORE \t\t\t\t: <i>TStringField *</i>
    + QNoticeFIOFAM \t\t\t\t\t\t\t: <i>TStringField *</i>
    + QNoticeFIONAME \t\t\t\t\t\t\t: <i>TStringField *</i>
    + QNoticeFIOOTCH \t\t\t\t\t\t\t: <i>TStringField *</i>
    + QNoticeFacFAC \t\t\t\t\t\t\t: <i>TStringField *</i>
    + QNoticeSpecCODE_SPEC_DIR \t\t\t\t: <i>TStringField *</i>
    + QNoticeSpecSPECIAL_DIRECTION \t\t\t: <i>TStringField *</i>
    + QPersonalDocumNAME_TYPE \t\t\t\t: <i>TStringField *</i>
    + QPlan_Priem_AllSPECIALIZ1 \t\t\t\t: <i>TStringField *</i>
    + QPlan_Priem_AllSPECIALIZ2 \t\t\t\t: <i>TStringField *</i>
    + QPlan_Priem_All_SpecialCODE_SPEC \t\t: <i>TStringField *</i>
    + QPlan_Priem_All_SpecialSPEC \t\t\t\t: <i>TStringField *</i>
    + QPlan_Priem_Konk_All_ParamSPECIALIZ2 \t: <i>TStringField *</i>
    + QPlan_Priem_PriceSPECIALIZ2 \t\t\t\t: <i>TStringField *</i>
    + QPrivToDekanatDESCRIBE \t\t\t\t: <i>TStringField *</i>
    + QPrivToDekanatDOC_PRIV \t\t\t\t: <i>TStringField *</i>
    + QPrivToDekanatTEXT_PRIV \t\t\t\t: <i>TStringField *</i>
    + QProverka_RYORFAM \t\t\t\t\t\t: <i>TStringField *</i>
    + QProverka_RYORNAME_EDU_MIDDLE \t\t: <i>TStringField *</i>
    + QProverka_RYORPRIV \t\t\t\t\t\t: <i>TStringField *</i>
    + QRegion_CenterCENTRE \t\t\t\t\t: <i>TStringField *</i>
    + QRep_AbituraFAM \t\t\t\t\t\t: <i>TStringField *</i>
    + QRep_AbituraNAME \t\t\t\t\t\t: <i>TStringField *</i>
    + QRep_AbituraNOM_GROUP \t\t\t\t: <i>TStringField *</i>
    + QRep_AbituraOTCH \t\t\t\t\t\t: <i>TStringField *</i>
    + QRep_Sel_ExercNAME_EXERC \t\t\t\t: <i>TStringField *</i>
    + QReport_RaspFAM \t\t\t\t\t\t: <i>TStringField *</i>
    + QReport_RaspFIO \t\t\t\t\t\t: <i>TStringField *</i>
    + QReport_RaspNAME \t\t\t\t\t\t: <i>TStringField *</i>
    + QReport_RaspNAME_EDU_MIDDLE \t\t\t: <i>TStringField *</i>
    + QReport_RaspNAME_EDU_SPEC \t\t\t: <i>TStringField *</i>
    + QReport_RaspNOM_ATTEST \t\t\t\t: <i>TStringField *</i>
    + QReport_RaspNOM_DIPLOM \t\t\t\t: <i>TStringField *</i>
    + QReport_RaspNOM_GROUP \t\t\t\t: <i>TStringField *</i>
    + QReport_RaspN_FAC1 \t\t\t\t\t: <i>TStringField *</i>
    + QReport_RaspOTCH \t\t\t\t\t\t: <i>TStringField *</i>
    + QReport_RaspSPECIAL1 \t\t\t\t\t: <i>TStringField *</i>
    + QReport_RaspVID_EDU1 \t\t\t\t\t: <i>TStringField *</i>
    + QReport_RaspWHERE_EDU_MIDDLE \t\t: <i>TStringField *</i>
    + QReport_RaspWHERE_EDU_SPEC \t\t\t: <i>TStringField *</i>
    + QResult_ExamB1 \t\t\t\t\t\t\t: <i>TStringField *</i>
    + QSelect_abADDRESS_BEFORE \t\t\t\t: <i>TStringField *</i>
    + QSelect_abADDRESS_MAMA \t\t\t\t: <i>TStringField *</i>
    + QSelect_abADDRESS_PAPA \t\t\t\t: <i>TStringField *</i>
    + QSelect_abFAM \t\t\t\t\t\t\t: <i>TStringField *</i>
    + QSelect_abHOUSE \t\t\t\t\t\t: <i>TStringField *</i>
    + QSelect_abMAMA \t\t\t\t\t\t: <i>TStringField *</i>
    + QSelect_abNAME \t\t\t\t\t\t\t: <i>TStringField *</i>
    + QSelect_abNAME_EDU_MIDDLE \t\t\t: <i>TStringField *</i>
    + QSelect_abNAME_EDU_SPEC \t\t\t\t: <i>TStringField *</i>
    + QSelect_abORGAN_V \t\t\t\t\t\t: <i>TStringField *</i>
    + QSelect_abOTCH \t\t\t\t\t\t\t: <i>TStringField *</i>
    + QSelect_abPAPA \t\t\t\t\t\t\t: <i>TStringField *</i>
    + QSelect_abPASPORT \t\t\t\t\t\t: <i>TStringField *</i>
    + QSelect_abPERSONAL_NOMER \t\t\t\t: <i>TStringField *</i>
    + QSelect_abPHONE \t\t\t\t\t\t: <i>TStringField *</i>
    + QSelect_abPLACE_R \t\t\t\t\t\t: <i>TStringField *</i>
    + QSelect_abPOL \t\t\t\t\t\t\t: <i>TStringField *</i>
    + QSelect_abPRIV \t\t\t\t\t\t\t: <i>TStringField *</i>
    + QSelect_abV_K \t\t\t\t\t\t\t: <i>TStringField *</i>
    --
    <b>FINISH PART 3</b> (For others, see: class_DMUnit_all_fields 1, 2 and 4)
    --

    + <b>{abstract} TDM (AOwner \t: <i>TComponent *</i>) virtual</b>

}


@enduml