@startuml DUALLIST.cpp

title Исходный файл: "DUALLIST.cpp"

scale 750 width

"<b>TDualListDlg</b>" -up-|> "<b>TForm</b>"

hide "<b>TForm</b>" members

class "<b>TDualListDlg</b>"
{
    + CancelBtn \t: <i>TButton *</i>
    + HelpBtn \t\t: <i>TButton *</i>
    + OKBtn \t\t: <i>TButton *</i>
    ..
    + DstLabel \t: <i>TLabel *</i>
    + SrcLabel \t: <i>TLabel *</i>
    ..
    + DstList \t\t: <i>TListBox *</i>
    + SrcList \t\t: <i>TListBox *</i>
    ..
    + ExAllBtn \t: <i>TSpeedButton *</i>
    + ExcludeBtn \t: <i>TSpeedButton *</i>
    + IncAllBtn \t: <i>TSpeedButton *</i>
    + IncludeBtn \t: <i>TSpeedButton *</i>
    --
    
    + <b>TDualListDlg (Owner \t: <i>TComponent *</i>)</b>

    + DstListDblClick \t\t(Sender \t: <i>TObject *</i>) : <i>void</i>
    + ExAllBtnClick \t\t(Sender \t: <i>TObject *</i>) : <i>void</i>
    + ExcludeBtnClick \t\t(Sender \t: <i>TObject *</i>) : <i>void</i>
    + GetFirstSelection \t(List \t: <i>TCustomListBox *</i>) : <i>Integer</i>
    + IncAllBtnClick \t\t(Sender \t: <i>TObject *</i>) : <i>void</i>
    + IncludeBtnClick \t\t(Sender \t: <i>TObject *</i>) : <i>void</i>
    ..
    + MoveSelected \t\t(
            \t\tList \t\t: <i>TCustomListBox *</i>,
            \t\tItems \t: <i>TStrings *</i>
        \t) : <i>void</i>
    ..
    + OKBtnClick \t\t\t(Sender \t: <i>TObject *</i>) : <i>void</i>
    + SetButtons \t\t\t() : <i>void</i>
    ..
    + SetItem \t\t\t\t(
            \t\tList \t\t: <i>TListBox *</i>,
            \t\tIndex \t: <i>int</i>
        \t) : <i>void</i>
    ..
    + SrcListDblClick \t\t(Sender \t: <i>TObject *</i>) : <i>void</i>
}


package TDualListDlg <<Folder>>
{
    class TDualListDlg
    hide  TDualListDlg members
}


@enduml