@startuml DMUnit.cpp

title Исходный файл: "DMUnit.cpp"

scale 750 width

class "<b>TDM</b>"
{
    <b>SHOWS ONLY FIELDS</b>\n(For methods, see: class_DMUnit)
    --
    <b>START PART 2</b> (For others, see: class_DMUnit_all_fields 1, 3 and 4)
    --
    + AbiturCompQrNOMER_AB \t\t\t\t\t: <i>TIntegerField *</i>
    + AdrLogLastQrID_LOG \t\t\t\t\t\t: <i>TIntegerField *</i>
    + AdrLogLastQrNOMER_AB \t\t\t\t\t: <i>TIntegerField *</i>
    + BlockBtnQrID_BLOCK \t\t\t\t\t\t: <i>TIntegerField *</i>
    + BlockQID_BLOCK \t\t\t\t\t\t\t: <i>TIntegerField *</i>
    + BlockQPEREPODACHA \t\t\t\t\t: <i>TIntegerField *</i>
    + CntrExrcTblID_CONTROL_EXERC \t\t\t: <i>TIntegerField *</i>
    + CountryQrDIGITAL_CODE \t\t\t\t\t: <i>TIntegerField *</i>
    + FIOSearchQrID_AB \t\t\t\t\t\t: <i>TIntegerField *</i>
    + Increment_GroupTableGOD \t\t\t\t: <i>TIntegerField *</i>
    + ListDocFDQNOMER_AB \t\t\t\t\t: <i>TIntegerField *</i>
    + LogIDSelQrID_LOG \t\t\t\t\t\t: <i>TIntegerField *</i>
    + LogLastQrID_LOG \t\t\t\t\t\t: <i>TIntegerField *</i>
    + MaxExrcQrMAX \t\t\t\t\t\t\t: <i>TIntegerField *</i>
    + PasportFDQNOMER \t\t\t\t\t\t: <i>TIntegerField *</i>
    + PrintDocQrNOMER_AB \t\t\t\t\t: <i>TIntegerField *</i>
    + PrivCnttQrCOUNT \t\t\t\t\t\t: <i>TIntegerField *</i>
    + QAb_PNOMER_AB \t\t\t\t\t\t: <i>TIntegerField *</i>
    + QAb_PN_AB_P \t\t\t\t\t\t\t: <i>TIntegerField *</i>
    + QAb_Pr_EnterNOMER_AB \t\t\t\t\t: <i>TIntegerField *</i>
    + QAb_Pr_EnterPRIV_LEVEL1 \t\t\t\t: <i>TIntegerField *</i>
    + QAbitur_Priv_EnterNOMER_AB \t\t\t\t: <i>TIntegerField *</i>
    + QAbituraNOMER_AB \t\t\t\t\t\t: <i>TIntegerField *</i>
    + QAbituraN_CENTRE \t\t\t\t\t\t: <i>TIntegerField *</i>
    + QAbituraPOSTCODE \t\t\t\t\t\t: <i>TIntegerField *</i>
    + QAbituraSTREET \t\t\t\t\t\t\t: <i>TIntegerField *</i>
    + QAdressLOCAL_ID \t\t\t\t\t\t: <i>TIntegerField *</i>
    + QAdressN_DISTRICT \t\t\t\t\t\t: <i>TIntegerField *</i>
    + QAdressN_REGION \t\t\t\t\t\t: <i>TIntegerField *</i>
    + QAdressN_TYPE \t\t\t\t\t\t\t: <i>TIntegerField *</i>
    + QAdressTYPE_STREET \t\t\t\t\t: <i>TIntegerField *</i>
    + QCkToDekanatCUSTOMER \t\t\t\t: <i>TIntegerField *</i>
    + QCkToDekanatNOMER \t\t\t\t\t: <i>TIntegerField *</i>
    + QCkToDekanatN_CENTRE \t\t\t\t\t: <i>TIntegerField *</i>
    + QCkToDekanatN_CK \t\t\t\t\t\t: <i>TIntegerField *</i>
    + QCkToDekanatN_REGION \t\t\t\t\t: <i>TIntegerField *</i>
    + QCkToDekanatN_SPECIALIZ \t\t\t\t: <i>TIntegerField *</i>
    + QDistrictN_DISTRICT \t\t\t\t\t\t: <i>TIntegerField *</i>
    + QDistrictN_REGION \t\t\t\t\t\t: <i>TIntegerField *</i>
    + QExamNOMER_AB \t\t\t\t\t\t: <i>TIntegerField *</i>
    + QExamSpecNOMER_AB \t\t\t\t\t: <i>TIntegerField *</i>
    + QFindAbiturExercID_SEL_EXERC \t\t\t: <i>TIntegerField *</i>
    + QFotoQeueID_AB_QUEUE \t\t\t\t\t: <i>TIntegerField *</i>
    + QFotoSignNOMER_AB \t\t\t\t\t\t: <i>TIntegerField *</i>
    + QGIAC3SertCOUNT \t\t\t\t\t\t: <i>TIntegerField *</i>
    + QGIACAllPrivileg1COUNT \t\t\t\t\t: <i>TIntegerField *</i>
    + QGIACAllPrivilegCOUNT \t\t\t\t\t: <i>TIntegerField *</i>
    + QGIACInAllCOUNT \t\t\t\t\t\t: <i>TIntegerField *</i>
    + QGIACInCelCOUNT \t\t\t\t\t\t: <i>TIntegerField *</i>
    + QGIACKursiCOUNT \t\t\t\t\t\t: <i>TIntegerField *</i>
    + QGIACMedalCOUNT \t\t\t\t\t\t: <i>TIntegerField *</i>
    + QGIACMilCOUNT \t\t\t\t\t\t\t: <i>TIntegerField *</i>
    + QGIACOlimpCOUNT \t\t\t\t\t\t: <i>TIntegerField *</i>
    + QGIACSirotCOUNT \t\t\t\t\t\t: <i>TIntegerField *</i>
    + QIPN_IP \t\t\t\t\t\t\t\t\t: <i>TIntegerField *</i>
    + QInc_Gr_OldGOD \t\t\t\t\t\t\t: <i>TIntegerField *</i>
    + QInc_Gr_OldINC_GROUP \t\t\t\t\t: <i>TIntegerField *</i>
    + QInc_Gr_OldINC_GR_OLD \t\t\t\t\t: <i>TIntegerField *</i>
    + QLangvichN_LANGVICH \t\t\t\t\t: <i>TIntegerField *</i>
    + QLangvichToDekanatNOMER \t\t\t\t: <i>TIntegerField *</i>
    + QLangvichToDekanatN_LANGVICH \t\t\t: <i>TIntegerField *</i>
    + QLangvichToDekanatN_LANGV_BALL \t\t: <i>TIntegerField *</i>
    + QLetterSourceNOMER_AB \t\t\t\t\t: <i>TIntegerField *</i>
    + QListDocToDekanatNOMER \t\t\t\t: <i>TIntegerField *</i>
    + QLittle_Spisoc_GRNOMER_AB \t\t\t\t: <i>TIntegerField *</i>
    + QLocalityID \t\t\t\t\t\t\t\t: <i>TIntegerField *</i>
    + QLocalityN_DISTRICT \t\t\t\t\t\t: <i>TIntegerField *</i>
    + QMax_Nomer_AbMAX \t\t\t\t\t\t: <i>TIntegerField *</i>
    + QPersonalDocumID_TYPE \t\t\t\t\t: <i>TIntegerField *</i>
    + QPlan_Priem_AllORDER_SP \t\t\t\t: <i>TIntegerField *</i>
    + QPlan_Priem_CKSUM \t\t\t\t\t\t: <i>TIntegerField *</i>
    + QPlan_Priem_CK_SpecialSUM1 \t\t\t\t: <i>TIntegerField *</i>
    + QPlan_Priem_PriceORDER_SP \t\t\t\t: <i>TIntegerField *</i>
    + QPlan_Priem_PriceSUM \t\t\t\t\t: <i>TIntegerField *</i>
    + QPrivToDekanatNOMER \t\t\t\t\t: <i>TIntegerField *</i>
    + QPrivToDekanatN_PRIV \t\t\t\t\t: <i>TIntegerField *</i>
    + QProverka_sertNOMER_AB \t\t\t\t: <i>TIntegerField *</i>
    + QResult_ExamNOMER_AB \t\t\t\t\t: <i>TIntegerField *</i>
    + QSelect_abNOMER_AB \t\t\t\t\t: <i>TIntegerField *</i>
    + QSelect_abN_CENTRE \t\t\t\t\t: <i>TIntegerField *</i>
    + QSelect_abPOSTCODE \t\t\t\t\t: <i>TIntegerField *</i>
    + QSelect_abSTREET \t\t\t\t\t\t: <i>TIntegerField *</i>
    + QSertificatNOMER_AB \t\t\t\t\t: <i>TIntegerField *</i>
    + QSertificatYEAR_S \t\t\t\t\t\t: <i>TIntegerField *</i>
    + QSertificat_ResNOMER_AB \t\t\t\t: <i>TIntegerField *</i>
    + QShow_Result_ExamNOMER_AB \t\t\t: <i>TIntegerField *</i>
    + QSpecializPlan_PriemN_SPEC_DIR \t\t\t: <i>TIntegerField *</i>
    + QSpisoc_GroupNOMER_AB \t\t\t\t: <i>TIntegerField *</i>
    + QSpisoc_Group_PolNOMER_AB \t\t\t\t: <i>TIntegerField *</i>
    + QSpisok_SpecNOMER_AB \t\t\t\t\t: <i>TIntegerField *</i>
    + QStatistic_Every_DayORDER_SP \t\t\t: <i>TIntegerField *</i>
    + QStatistic_Every_Day_BallCOUNT \t\t\t: <i>TIntegerField *</i>
    + QStreetID \t\t\t\t\t\t\t\t: <i>TIntegerField *</i>
    + QSum_BallNOMER_AB \t\t\t\t\t\t: <i>TIntegerField *</i>
    + QSum_Ball_NomerNOMER_AB \t\t\t\t: <i>TIntegerField *</i>
    + QToDekanatID_STREET \t\t\t\t\t: <i>TIntegerField *</i>
    + QToDekanatNOMER \t\t\t\t\t\t: <i>TIntegerField *</i>
    + QToDekanatNUMBER \t\t\t\t\t\t: <i>TIntegerField *</i>
    + QToDekanatN_CENTRE \t\t\t\t\t: <i>TIntegerField *</i>
    + QToDekanatPOSTCODE \t\t\t\t\t: <i>TIntegerField *</i>
    + QType_localityN_TYPE \t\t\t\t\t: <i>TIntegerField *</i>
    + QType_streetID \t\t\t\t\t\t\t: <i>TIntegerField *</i>
    + QUndo_AbitNOMER_AB \t\t\t\t\t: <i>TIntegerField *</i>
    + SelectLogAbiturQrID_LOG \t\t\t\t\t: <i>TIntegerField *</i>
    + SelectLogAbiturQrNOMER_AB \t\t\t\t: <i>TIntegerField *</i>
    + SportQueryNOMER \t\t\t\t\t\t: <i>TIntegerField *</i>
    + SspecQNOMER_AB \t\t\t\t\t\t: <i>TIntegerField *</i>
    + TCkN_CENTRE \t\t\t\t\t\t\t: <i>TIntegerField *</i>
    + VO2KSpecializQrNOMER_AB \t\t\t\t: <i>TIntegerField *</i>
    --
    + AdrLogLastQrDATE_IN \t\t\t\t\t: <i>TSQLTimeStampField *</i>
    + LogLastQrDATE_OUT \t\t\t\t\t\t: <i>TSQLTimeStampField *</i>
    + ListDocFDQDATE_DOC \t\t\t\t\t: <i>TSQLTimeStampField *</i>
    + PasportFDQDATE_GIVE \t\t\t\t\t: <i>TSQLTimeStampField *</i>
    + PasportFDQDATE_VALID \t\t\t\t\t: <i>TSQLTimeStampField *</i>
    + QAb_PDATE_P \t\t\t\t\t\t\t: <i>TSQLTimeStampField *</i>
    + QAbituraD_PRIKAZ_INCLUDE \t\t\t\t: <i>TSQLTimeStampField *</i>
    + QAbituraDATE_OK \t\t\t\t\t\t: <i>TSQLTimeStampField *</i>
    + QAbituraDATE_PRIEM \t\t\t\t\t\t: <i>TSQLTimeStampField *</i>
    + QAbituraDATE_R \t\t\t\t\t\t\t: <i>TSQLTimeStampField *</i>
    + QAbituraDATE_V \t\t\t\t\t\t\t: <i>TSQLTimeStampField *</i>
    + QAbituraDATE_VOZVRAT \t\t\t\t\t: <i>TSQLTimeStampField *</i>
    + QListDocToDekanatDOC_DATE \t\t\t: <i>TSQLTimeStampField *</i>
    + QNoticeFIOD_PRIKAZ_INCLUDE \t\t\t: <i>TSQLTimeStampField *</i>
    + QPrivToDekanatDATA_C \t\t\t\t\t: <i>TSQLTimeStampField *</i>
    + QPrivToDekanatDATA_PO \t\t\t\t\t: <i>TSQLTimeStampField *</i>
    + QReport_RaspDATE_PRIEM \t\t\t\t: <i>TSQLTimeStampField *</i>
    + QSelect_abD_PRIKAZ_INCLUDE \t\t\t: <i>TSQLTimeStampField *</i>
    + QSelect_abDATE_OK \t\t\t\t\t\t: <i>TSQLTimeStampField *</i>
    + QSelect_abDATE_V \t\t\t\t\t\t: <i>TSQLTimeStampField *</i>
    + QSertificat_ex_listDATE_PRIEM \t\t\t: <i>TSQLTimeStampField *</i>
    + QToDekanatD_INCLUDE \t\t\t\t\t: <i>TSQLTimeStampField *</i>
    + QToDekanatD_PRIKAZ_INCLUDE \t\t\t: <i>TSQLTimeStampField *</i>
    + QToDekanatDATA_R \t\t\t\t\t\t: <i>TSQLTimeStampField *</i>
    + QToDekanatDATE_END \t\t\t\t\t: <i>TSQLTimeStampField *</i>
    + SelectLogAbiturQrD_PRIKAZ_INCLUDE \t\t: <i>TSQLTimeStampField *</i>
    + SelectLogAbiturQrDATE_IN \t\t\t\t: <i>TSQLTimeStampField *</i>
    + SelectLogAbiturQrDATE_OUT \t\t\t\t: <i>TSQLTimeStampField *</i>
    + SportQueryD_PRIKAZ_SPORT \t\t\t\t: <i>TSQLTimeStampField *</i>
    + SportQueryD_PRIKAZ_SUD \t\t\t\t: <i>TSQLTimeStampField *</i>
    ..
    + QToDekanatSCHOLARSHIP \t\t\t\t: <i>TSingleField *</i>
    + AbiturCompQrCATEGORY_AB \t\t\t\t: <i>TSmallintField *</i>
    + AbiturCompQrCATEGORY_IF \t\t\t\t: <i>TSmallintField *</i>
    + AbiturCompQrEDUCATION \t\t\t\t: <i>TSmallintField *</i>
    + AbiturCompQrKONKURS \t\t\t\t\t: <i>TSmallintField *</i>
    + AbiturCompQrN_FAC \t\t\t\t\t\t: <i>TSmallintField *</i>
    + AbiturCompQrN_SPECIALIZ \t\t\t\t: <i>TSmallintField *</i>
    + AbiturCompQrN_SPEC \t\t\t\t\t: <i>TSmallintField *</i>
    + AbiturCompQrPRICE \t\t\t\t\t\t: <i>TSmallintField *</i>
    + AbiturCompQrTERM_EDU \t\t\t\t\t: <i>TSmallintField *</i>
    + AbiturCompQrVID_EDU \t\t\t\t\t: <i>TSmallintField *</i>
    + AbiturInvTmpQrDAT_PRIV \t\t\t\t\t: <i>TSmallintField *</i>
    + AbiturSirTmpQrDAT_PRIV \t\t\t\t\t: <i>TSmallintField *</i>
    + BlockBtnQrADD_ABITUR \t\t\t\t\t: <i>TSmallintField *</i>
    + BlockBtnQrRE_INSIDE_FAC \t\t\t\t: <i>TSmallintField *</i>
    + BlockBtnQrRESTOR_LIST \t\t\t\t\t: <i>TSmallintField *</i>
    + BlockBtnQrTOOK_DOC1 \t\t\t\t\t: <i>TSmallintField *</i>
    + BlockBtnQrTOOK_DOC2 \t\t\t\t\t: <i>TSmallintField *</i>
    + BlockQADD_ABITUR \t\t\t\t\t\t: <i>TSmallintField *</i>
    + BlockQBLOCK \t\t\t\t\t\t\t: <i>TSmallintField *</i>
    + BlockQN_FAC \t\t\t\t\t\t\t: <i>TSmallintField *</i>
    + BlockQRE_INSIDE_FAC \t\t\t\t\t: <i>TSmallintField *</i>
    + BlockQRESTOR_LIST \t\t\t\t\t\t: <i>TSmallintField *</i>
    + BlockQTOOK_DOC1 \t\t\t\t\t\t: <i>TSmallintField *</i>
    + BlockQTOOK_DOC2 \t\t\t\t\t\t: <i>TSmallintField *</i>
    + CkRegionQrN_CENTRE \t\t\t\t\t: <i>TSmallintField *</i>
    + CkRegionQrN_REGION \t\t\t\t\t: <i>TSmallintField *</i>
    + CntrExrcTblID_EXERC \t\t\t\t\t: <i>TSmallintField *</i>
    + CntrExrcTblN_FAC \t\t\t\t\t\t: <i>TSmallintField *</i>
    + CntrExrcTblN_SPECIALIZ \t\t\t\t\t: <i>TSmallintField *</i>
    + CntrExrcTblNUM_EXERC_GRP \t\t\t\t: <i>TSmallintField *</i>
    + CntrlExrcQrID_EXERC \t\t\t\t\t\t: <i>TSmallintField *</i>
    + DocumFDQN_DOC \t\t\t\t\t\t: <i>TSmallintField *</i>
    + FIOSearchQrCATEGORY_AB \t\t\t\t: <i>TSmallintField *</i>
    + FIOSearchQrCATEGORY_EDU \t\t\t\t: <i>TSmallintField *</i>
    + FIOSearchQrCATEGORY_IF \t\t\t\t\t: <i>TSmallintField *</i>
    + FIOSearchQrKONKURS \t\t\t\t\t: <i>TSmallintField *</i>
    + FIOSearchQrN_FAC \t\t\t\t\t\t: <i>TSmallintField *</i>
    + FIOSearchQrN_SPEC \t\t\t\t\t\t: <i>TSmallintField *</i>
    + FIOSearchQrN_SPECIALIZ \t\t\t\t\t: <i>TSmallintField *</i>
    + FIOSearchQrPRICE \t\t\t\t\t\t: <i>TSmallintField *</i>
    + FIOSearchQrSTATUS_QUEUE \t\t\t\t: <i>TSmallintField *</i>
    + FIOSearchQrTERM_EDU \t\t\t\t\t: <i>TSmallintField *</i>
    + FIOSearchQrVID_EDU \t\t\t\t\t\t: <i>TSmallintField *</i>
    + Increment_GroupTableINC_GROUP \t\t\t: <i>TSmallintField *</i>
    + Increment_GroupTableVID_EDU \t\t\t: <i>TSmallintField *</i>
    + InfQrID_PRIV \t\t\t\t\t\t\t\t: <i>TSmallintField *</i>
    + InfQrN_OTHERS \t\t\t\t\t\t\t: <i>TSmallintField *</i>
    + ListDocFDQN_DOC \t\t\t\t\t\t: <i>TSmallintField *</i>
    + OutDetQrID_DET \t\t\t\t\t\t\t: <i>TSmallintField *</i>
    + OutDetQrN_ITEM \t\t\t\t\t\t\t: <i>TSmallintField *</i>
    + OutQrID_PRIV \t\t\t\t\t\t\t: <i>TSmallintField *</i>
    + OutQrN_OUT_TESTS \t\t\t\t\t\t: <i>TSmallintField *</i>
    + PasportFDQID_TYPE \t\t\t\t\t\t: <i>TSmallintField *</i>
    + PasportFDQN_REGION \t\t\t\t\t: <i>TSmallintField *</i>
    + PrivilegLogSelQrDAT_PRIV \t\t\t\t: <i>TSmallintField *</i>
    + PrivilegLogSelQrN_PRIV \t\t\t\t\t: <i>TSmallintField *</i>
    + PrivilegLogSelQrSEL_PRIV \t\t\t\t\t: <i>TSmallintField *</i>
    + PrivQrDAT_PRIV \t\t\t\t\t\t\t: <i>TSmallintField *</i>
    + PrivQrN_PRIV \t\t\t\t\t\t\t: <i>TSmallintField *</i>
    + PrivQrSEL_PRIV \t\t\t\t\t\t\t: <i>TSmallintField *</i>
    + QAb_PVID_EDU_DO \t\t\t\t\t\t: <i>TSmallintField *</i>
    + QAb_PVID_EDU_PO \t\t\t\t\t\t: <i>TSmallintField *</i>
    + QAb_PNOM_DELA_DO \t\t\t\t\t\t: <i>TSmallintField *</i>
    + QAb_PNOM_DELA_PO \t\t\t\t\t\t: <i>TSmallintField *</i>
    + QAb_PN_SPECIALIZ_DO \t\t\t\t\t: <i>TSmallintField *</i>
    + QAb_PN_SPECIALIZ_PO \t\t\t\t\t: <i>TSmallintField *</i>
    + QAb_PN_SPEC_DO \t\t\t\t\t\t: <i>TSmallintField *</i>
    + QAb_PN_SPEC_PO \t\t\t\t\t\t: <i>TSmallintField *</i>
    + QAb_PN_CK \t\t\t\t\t\t\t\t: <i>TSmallintField *</i>
    + QAb_PKONKURS_DO \t\t\t\t\t\t: <i>TSmallintField *</i>
    + QAb_PKONKURS_PO \t\t\t\t\t\t: <i>TSmallintField *</i>
    + QAb_PPRICE_DO \t\t\t\t\t\t\t: <i>TSmallintField *</i>
    + QAb_PPRICE_PO \t\t\t\t\t\t\t: <i>TSmallintField *</i>
    + QAb_Pr_EnterN_PRIV \t\t\t\t\t\t: <i>TSmallintField *</i>
    + QAbitur_Priv_EnterN_PRIV \t\t\t\t\t: <i>TSmallintField *</i>
    + QAbituraCATEGORY_AB \t\t\t\t\t: <i>TSmallintField *</i>
    + QAbituraCATEGORY_IF \t\t\t\t\t: <i>TSmallintField *</i>
    + QAbituraCITIZENSHIP \t\t\t\t\t\t: <i>TSmallintField *</i>
    + QAbituraEDUCATION \t\t\t\t\t\t: <i>TSmallintField *</i>
    + QAbituraKONKURS \t\t\t\t\t\t: <i>TSmallintField *</i>
    + QAbituraN_CK \t\t\t\t\t\t\t: <i>TSmallintField *</i>
    + QAbituraN_FAC \t\t\t\t\t\t\t: <i>TSmallintField *</i>
    + QAbituraN_FOUND \t\t\t\t\t\t: <i>TSmallintField *</i>
    + QAbituraN_LANGVICH \t\t\t\t\t\t: <i>TSmallintField *</i>
    + QAbituraN_PRIKAZ_INCLUDE \t\t\t\t: <i>TSmallintField *</i>
    + QAbituraN_REGION \t\t\t\t\t\t: <i>TSmallintField *</i>
    + QAbituraN_SPEC \t\t\t\t\t\t\t: <i>TSmallintField *</i>
    + QAbituraN_SPECIALIZ \t\t\t\t\t\t: <i>TSmallintField *</i>
    + QAbituraN_SPORT_CATEGORY \t\t\t\t: <i>TSmallintField *</i>
    + QAbituraN_VID_SPORT \t\t\t\t\t: <i>TSmallintField *</i>
    + QAbituraNOM_DELA \t\t\t\t\t\t: <i>TSmallintField *</i>
    + QAbituraPRICE \t\t\t\t\t\t\t: <i>TSmallintField *</i>
    + QAbituraRUS_BEL \t\t\t\t\t\t: <i>TSmallintField *</i>
    + QAbituraSTATUS \t\t\t\t\t\t\t: <i>TSmallintField *</i>
    + QAbituraTERM_EDU \t\t\t\t\t\t: <i>TSmallintField *</i>
    + QAbituraTOWN_VILLAGE \t\t\t\t\t: <i>TSmallintField *</i>
    + QAbituraTYPE_SCHOOL \t\t\t\t\t: <i>TSmallintField *</i>
    + QAbituraVID_EDU \t\t\t\t\t\t: <i>TSmallintField *</i>
    + QAbituraWHEN_EDU_MIDDLE \t\t\t\t: <i>TSmallintField *</i>
    + QAbituraWHEN_EDU_SPEC \t\t\t\t\t: <i>TSmallintField *</i>
    + QAdd_N_GroupN_GROUP \t\t\t\t\t: <i>TSmallintField *</i>
    + QAdd_N_GroupVID_EDU \t\t\t\t\t: <i>TSmallintField *</i>
    + QAdd_N_GroupN_FAC \t\t\t\t\t\t: <i>TSmallintField *</i>
    + QAdd_N_GroupN_COUNT \t\t\t\t\t: <i>TSmallintField *</i>
    + QCenterN_CENTRE \t\t\t\t\t\t: <i>TSmallintField *</i>
    + QCenterN_REGION \t\t\t\t\t\t: <i>TSmallintField *</i>
    + QExamSpecN_PREDMET \t\t\t\t\t: <i>TSmallintField *</i>
    + QCenterFLAG \t\t\t\t\t\t\t: <i>TSmallintField *</i>
    + QCkN_CK \t\t\t\t\t\t\t\t: <i>TSmallintField *</i>
    + QCkN_SPECIALIZ \t\t\t\t\t\t\t: <i>TSmallintField *</i>
    + QCkN_REGION \t\t\t\t\t\t\t: <i>TSmallintField *</i>
    + QCkKOL_P \t\t\t\t\t\t\t\t: <i>TSmallintField *</i>
    + QCK_Kol_PlanKOL_PLACE \t\t\t\t\t: <i>TSmallintField *</i>
    + QCkToDekanatSTATUS_CK \t\t\t\t: <i>TSmallintField *</i>
    + QExamSTATUS_BALL \t\t\t\t\t\t: <i>TSmallintField *</i>
    + QExamN_PREDMET \t\t\t\t\t\t: <i>TSmallintField *</i>
    + QExamKONKURS \t\t\t\t\t\t\t: <i>TSmallintField *</i>
    + QExamNOM_DELA \t\t\t\t\t\t: <i>TSmallintField *</i>
    + QExamVID_EDU \t\t\t\t\t\t\t: <i>TSmallintField *</i>
    + QExamRUS_BEL \t\t\t\t\t\t\t: <i>TSmallintField *</i>
    + QExamNOM_BALL \t\t\t\t\t\t: <i>TSmallintField *</i>
    + QExamTERM_EDU \t\t\t\t\t\t: <i>TSmallintField *</i>
    + QExamEDUCATION \t\t\t\t\t\t: <i>TSmallintField *</i>
    + QExamCATEGORY_IF \t\t\t\t\t\t: <i>TSmallintField *</i>
    + QExamN_SPORT_CATEGORY \t\t\t\t: <i>TSmallintField *</i>
    + QExamPRICE \t\t\t\t\t\t\t: <i>TSmallintField *</i>
    + QExamSpecSTATUS_BALL \t\t\t\t\t: <i>TSmallintField *</i>
    + QExamSpecKONKURS \t\t\t\t\t\t: <i>TSmallintField *</i>
    + QExamSpecNOM_DELA \t\t\t\t\t: <i>TSmallintField *</i>
    + QExamSpecVID_EDU \t\t\t\t\t\t: <i>TSmallintField *</i>
    + QExamSpecRUS_BEL \t\t\t\t\t\t: <i>TSmallintField *</i>
    + QExamSpecNOM_BALL \t\t\t\t\t: <i>TSmallintField *</i>
    + QExamSpecTERM_EDU \t\t\t\t\t: <i>TSmallintField *</i>
    + QExamSpecEDUCATION \t\t\t\t\t: <i>TSmallintField *</i>
    + QExamSpecCATEGORY_IF \t\t\t\t\t: <i>TSmallintField *</i>
    + QExamSpecN_SPORT_CATEGORY \t\t\t: <i>TSmallintField *</i>
    + QExamSpecPRICE \t\t\t\t\t\t: <i>TSmallintField *</i>
    + QExerc_GrpID_EXERC \t\t\t\t\t\t: <i>TSmallintField *</i>
    + QFindAbiturExercID_EXERC \t\t\t\t: <i>TSmallintField *</i>
    + QInc_Gr_OldVID_EDU \t\t\t\t\t\t: <i>TSmallintField *</i>
    + QIPPROGRAM \t\t\t\t\t\t\t: <i>TSmallintField *</i>
    + QIPFLAG \t\t\t\t\t\t\t\t: <i>TSmallintField *</i>
    + QLangvichToDekanatLANGV_BALL \t\t\t: <i>TSmallintField *</i>
    + QMax_Nom_DelaMAX \t\t\t\t\t\t: <i>TSmallintField *</i>
    + QN_groupN_GROUP \t\t\t\t\t\t: <i>TSmallintField *</i>
    + QN_groupVID_EDU \t\t\t\t\t\t: <i>TSmallintField *</i>
    + QN_groupN_FAC \t\t\t\t\t\t\t: <i>TSmallintField *</i>
    + QN_groupN_COUNT \t\t\t\t\t\t: <i>TSmallintField *</i>
    + QNoticeFION_PRIKAZ_INCLUDE \t\t\t\t: <i>TSmallintField *</i>
    + QNoticeFION_FAC \t\t\t\t\t\t: <i>TSmallintField *</i>
    + QNoticeFION_SPECIALIZ \t\t\t\t\t: <i>TSmallintField *</i>
    + QNoticeFIOTERM_EDU \t\t\t\t\t: <i>TSmallintField *</i>
    + QNoticeFIOVID_EDU \t\t\t\t\t\t: <i>TSmallintField *</i>
    + QPlan_Priem_AllN_SPECIALIZ \t\t\t\t: <i>TSmallintField *</i>
    + QPlan_Priem_AllVID_EDU \t\t\t\t\t: <i>TSmallintField *</i>
    + QPlan_Priem_CKN_SPECIALIZ \t\t\t\t: <i>TSmallintField *</i>
    + QPlan_Priem_CKVID_EDU \t\t\t\t\t: <i>TSmallintField *</i>
    + QPlan_Priem_KonkN_SPECIALIZ \t\t\t: <i>TSmallintField *</i>
    + QPlan_Priem_KonkTEXT \t\t\t\t\t: <i>TSmallintField *</i>
    + QPlan_Priem_KonkKOL_PLACE \t\t\t\t: <i>TSmallintField *</i>
    + QPlan_Priem_Konk_All_ParamN_SPECIALIZ \t: <i>TSmallintField *</i>
    + QPlan_Priem_Konk_All_ParamKOL_PLACE \t: <i>TSmallintField *</i>
    + QPlan_Priem_PriceN_SPECIALIZ \t\t\t: <i>TSmallintField *</i>
    + QPlan_Priem_PriceVID_EDU \t\t\t\t: <i>TSmallintField *</i>
    + QPlan_Priem_PriceTEXT \t\t\t\t\t: <i>TSmallintField *</i>
    + QPlan_Priem_PricePRICE \t\t\t\t\t: <i>TSmallintField *</i>
    + QPlanPriem2PriceN_SPECIALIZ \t\t\t\t: <i>TSmallintField *</i>
    + QPlanPriem2PriceKOL_PLACE \t\t\t\t: <i>TSmallintField *</i>
    + QPlanPriemPriceN_SPECIALIZ \t\t\t\t: <i>TSmallintField *</i>
    + QPlanPriemPriceKOL_PLACE \t\t\t\t: <i>TSmallintField *</i>
    + QPrivToDekanatVID_PRIV \t\t\t\t\t: <i>TSmallintField *</i>
    + QPrivToDekanatUCH_GOD \t\t\t\t\t: <i>TSmallintField *</i>
    + QProverka_RYORN_FAC \t\t\t\t\t: <i>TSmallintField *</i>
    + QProverka_RYORVID_EDU \t\t\t\t\t: <i>TSmallintField *</i>
    + QRegion_CenterN_CENTRE \t\t\t\t: <i>TSmallintField *</i>
    + QRegion_CenterN_REGION \t\t\t\t: <i>TSmallintField *</i>
    + QRegion_CenterFLAG \t\t\t\t\t\t: <i>TSmallintField *</i>
    + QRep_Sel_ExercNUM_EXERC_GRP \t\t\t: <i>TSmallintField *</i>
    + QReport_RaspN_SPECIALIZ \t\t\t\t: <i>TSmallintField *</i>
    + QReport_RaspVID_EDU \t\t\t\t\t: <i>TSmallintField *</i>
    + QReport_RaspN_FAC \t\t\t\t\t\t: <i>TSmallintField *</i>
    + QReport_RaspWHEN_EDU_MIDDLE \t\t\t: <i>TSmallintField *</i>
    + QReport_RaspWHEN_EDU_SPEC \t\t\t: <i>TSmallintField *</i>
    + QReport_RaspNOM_DELA \t\t\t\t\t: <i>TSmallintField *</i>
    + QResult_ExamN_PREDMET \t\t\t\t: <i>TSmallintField *</i>
    + QResult_ExamNOM_BALL \t\t\t\t\t: <i>TSmallintField *</i>
    + QResult_ExamSTATUS_BALL \t\t\t\t: <i>TSmallintField *</i>
    + QSelect_abWHEN_EDU_MIDDLE \t\t\t: <i>TSmallintField *</i>
    + QSelect_abWHEN_EDU_SPEC \t\t\t\t: <i>TSmallintField *</i>
    + QSelect_abN_VID_SPORT \t\t\t\t\t: <i>TSmallintField *</i>
    + QSelect_abN_SPORT_CATEGORY \t\t\t: <i>TSmallintField *</i>
    + QSelect_abEDUCATION \t\t\t\t\t: <i>TSmallintField *</i>
    + QSelect_abSTATUS \t\t\t\t\t\t: <i>TSmallintField *</i>
    --
    <b>FINISH PART 2</b> (For others, see: class_DMUnit_all_fields 1, 3 and 4)
    --

    + <b>{abstract} TDM (AOwner \t: <i>TComponent *</i>) virtual</b>

}


@enduml